### ISSUE TITLE
Help needed. redis: connection pool timeout

### ISSUE THREAD

**Issue by belek** [go-redis/redis#1002]
My application uses redis streams (XREAD, XADD) and does not have any high load. Sometimes getting error:
`redis: connection pool timeout`

go-redis client with default configuration and redis server image v.5 from docker hub.
```
redisClient := redis.NewClient(&redis.Options{
    Addr:               "docker-redis:6379",
    Password:           "", // no password set
    DB:                 0,  // use default DB
  })
```

How can I troubleshoot this problem?

**Comment by vmihailenco** [comment]
If you are using `XREAD BLOCK` with big timeout from multiple goroutines that could explain why all connections are busy.

**Comment by belek** [comment]
@vmihailenco thanks. We had 5 Seconds as BLOCK value. Reduced that to 100 Milliseconds and no more timeout errors.
