### ISSUE TITLE
Can't connect to Memorystore in Google App Engine 

### ISSUE THREAD

**Issue by ibrunotome** [go-redis/redis#1007]
Using 

```go
app.Ring = redis.NewRing(&redis.RingOptions{
	Addrs: map[string]string{
		"10.0.0.3": ":6379",
	},
})
```

I always got a `ring.go:263: ring shard state changed: Redis<:6379 db:0> is down`, even building with the `appengine` flag after see another issue here. I'm missing something?

There is no password, both the application and memorystore use the `default` network and I can connect to it using other languages (but I'm new to golang so maybe I'm missing something).

**Comment by ibrunotome** [comment]
Ok, I was thinking that the left side of the map is the `host` and the right side is the ` port` 😅, now is working fine!

```go
app.Ring = redis.NewRing(&redis.RingOptions{
	Addrs: map[string]string{
		"redis": os.Getenv("REDIS_HOST"),
	},
	DB: 1,
})
```

**Comment by palytoxin** [comment]
I made the same mistake, thx
