### ISSUE TITLE
How do I choose a different database?

### ISSUE THREAD

**Issue by lij2960** [go-redis/redis#1018]
How do I choose a different db in one connection?

**Comment by leesio** [comment]
You should just be able to specify a DB number when instantiating the client

e.g.

```
client := redis.NewClient(&redis.Options{
    Addr: "localhost:6379",
    DB: 8,
})
```

**Comment by HayTran94** [comment]
> How do I choose a different db in one connection?

You can do like the following code 
` client.Do("SELECT", dbnumber)`

where `dbnumber` is your db number which you want to working on it. After that, the other commands will do in this db number, if you want to working on a different one, please do it again.

**Comment by vmihailenco** [comment]
On master you can do:

```go
conn := client.Conn()
err := conn.SelectDB(1).Err()
// from now on conn is bind to Redis db #1
```

`Conn` is needed because default `Client` uses pool of multiple connections which may have different selected database by default.

**Comment by europelee** [comment]
@vmihailenco 
As your above comment, does it mean that 'client.Do("SELECT", dbnumber)' might be a bad idea, and it might cause your command writing into wrong db?

**Comment by vmihailenco** [comment]
@europelee generally yes, `SELECT` is bind to the connection and `Client` uses random connection from the pool.
