### ISSUE TITLE
TTL get error code

### ISSUE THREAD

**Issue by Laily123** [go-redis/redis#1026]
if I use `client.TTL("key_name").Result()` and get an error code -1 or -2. I think it should be it. but I get -1000000000. It is perplexing。

**Comment by vmihailenco** [comment]
What does `redis-cli` return?

**Comment by Laily123** [comment]
redis-cli returns -1

**Comment by vmihailenco** [comment]
Okay, please provide code that I can run and that reproduces the problem.

**Comment by vmihailenco** [comment]
This should be fixed in master branch.

**Comment by maralla** [comment]
I think the solution in #1039 is misleading as -1 and -2 are not duration actually. They are just an indicator or error code.

> Integer reply: TTL in seconds, or a negative value in order to signal an error (see the description above).

So I think it may be better to just return error for -1 and -2 which indicates no expire and key not exists respectively.

**Comment by bubunyo** [comment]
to add to what Marilla said, the fix that was implemented for this creates a misleading API that completely ignores the precession that was set with `DurationCmd`.
