### ISSUE TITLE
redis use too much memory

### ISSUE THREAD

**Issue by akzi** [go-redis/redis#1032]
Build ID: ff6d359927c53c41874240ee65a2e24531dec565
Type: inuse_space
Time: May 24, 2019 at 7:24pm (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 3.34GB, 98.90% of 3.37GB total
Dropped 36 nodes (cum <= 0.02GB)
      flat  flat%   sum%        cum   cum%
    3.32GB 98.33% 98.33%     3.32GB 98.38%  gopkg.in/redis.v5/internal/proto.(*Reader).ReadBytesReply
    0.02GB  0.57% 98.90%     0.02GB  0.57%  go-sync-collection/sync_collection.(*URICounter).startUpdateRoutine.func1
         0     0% 98.90%     3.32GB 98.51%  go-sync-collection/sync_collection.(*SyncCollection).StartFetchDataRoutine.func1
         0     0% 98.90%     3.32GB 98.38%  gopkg.in/redis%2ev5.(*ClusterClient).Process
         0     0% 98.90%     3.32GB 98.38%  gopkg.in/redis%2ev5.(*ClusterClient).Process-fm
         0     0% 98.90%     3.32GB 98.38%  gopkg.in/redis%2ev5.(*StringCmd).readReply
         0     0% 98.90%     3.32GB 98.38%  gopkg.in/redis%2ev5.(*baseClient).Process
         0     0% 98.90%     3.32GB 98.38%  gopkg.in/redis%2ev5.(*baseClient).defaultProcess
         0     0% 98.90%     3.32GB 98.38%  gopkg.in/redis%2ev5.(*cmdable).LPop

**Comment by vmihailenco** [comment]
Try to upgrade to latest v6.15.3
