### ISSUE TITLE
pubsub channel keep-alive problem

### ISSUE THREAD

**Issue by larrycinnabar** [go-redis/redis#1037]
I'm keep getting 
```
redis: 2019/05/30 05:51:06 pubsub.go:151: redis: discarding bad PubSub connection: redis: ping timeout
redis: 2019/05/30 05:51:11 pubsub.go:151: redis: discarding bad PubSub connection: redis: ping timeout
```

I think problem is in [initChannel function](https://github.com/go-redis/redis/blob/master/pubsub.go#L423-L509)

If pool is closed then it just completely close the channel and exits from go routine.
```golang
		for {
			msg, err := c.Receive()
			if err != nil {
				if err == pool.ErrClosed {
					close(c.ch)
					return
				}
```
And then the second go-routine (health) will always do `ping timeout`.
The `reconnect` idea doesn't work because first goroutine (the main read one) is not running anymore

**Comment by vmihailenco** [comment]
Please a program that reproduces the problem.

**Comment by larrycinnabar** [comment]
Very simple program that just resent items to other channel:
```golang
		redisChan := rc.PSubscribe(channels...).Channel()
		go func() {
			for redisMsg := range redisChan {
				m := models.RedisMessage{
					Channel: redisMsg.Channel,
					Pattern: redisMsg.Pattern,
					Payload: redisMsg.Payload,
				}

				ch <- m
			}
		}()
```

**Comment by larrycinnabar** [comment]
Any suggestions?

inside `initChannel` you have 2 goroutines: the main once - consumer, and the second one - health-checker.

So, when pool is closed and we get `pool.errClosed` on attempt to consume a message, we just exit the goroutine. It's a mode when reconnect want help because the only consuming goroutine will not be run again ever, until you restart the application

**Comment by vmihailenco** [comment]
I see that it should exit [here](https://github.com/go-redis/redis/blob/master/pubsub.go#L504-L505). You still did not provide the program that reproduces the problem.

**Comment by larrycinnabar** [comment]
@vmihailenco yeap, it should. But it returns [here](https://github.com/go-redis/redis/blob/master/pubsub.go#L438-L439)

I suppose you need more detailed way of my problem (that I posted above). With redis connection, etc.

Ok:

```golang
client := redis.NewClient(&redis.Options{
		Addr:               node,
		ReadTimeout:        250 * time.Millisecond,
		WriteTimeout:       250 * time.Millisecond,
		DialTimeout:        c.options.DialTimeout,
		PoolTimeout:        5 * time.Second,
		IdleTimeout:        3 * time.Minute,
		PoolSize:           30 * runtime.NumCPU(),
	})


var pingDone bool
if pingResult, pingErr := client.Ping().Result(); pingErr == nil {
	pingDone = pingResult == "PONG"
}

log.Println("Ping Done: %t", pingDone)



expired := make(ch models.RedisMessage)
go func() {
	redisChan := client.PSubscribe("__keyevent@0__:expired").Channel()
	for redisMsg := range redisChan {
		m := models.RedisMessage{
			Channel: redisMsg.Channel,
			Pattern: redisMsg.Pattern,
			Payload: redisMsg.Payload,
		}

		expired <- m
	}
}()

// somewhere in other part of application
go func(){
	for msg := range expired {
		log.Printf("debug: expired %v", msg)
	}
})()
```

It's working for 5-10 hours and then the message described in topic above appears

**Comment by larrycinnabar** [comment]
any ideas, suggestions, pieces of advices? @vmihailenco

**Comment by vmihailenco** [comment]
Make sure you are using latest version. If that does not help - try to isolate the problem. Most likely it is a problem with your code.

**Comment by larrycinnabar** [comment]
@vmihailenco 

Ok, I'll try to isolate problem, but can you please help me with these questions:

1) is pool.ErrClosed a crucial thing that should not be recovered from? If yes, then our problem is with getting ErrClosed but not with pubSub channels

2) if pool.ErrClosed is a possible thing, and pubSub channel should be recovered, then how?
[here](https://github.com/go-redis/redis/blob/master/pubsub.go#L438-L439) it just `returns` from the main go-routine, so it will never call `c.Receive()` anymore.

Main question is in the fact if `pool.ErrClosed` is an error that pub-sub can recover from (and handle keep-alived channel), or not?

**Comment by vmihailenco** [comment]
pool.ErrClosed means that client is closed via `Client.Close()`. All connections are closed and PubSub stops receving messages and closes the Go channel.

**Comment by larrycinnabar** [comment]
so, it means that our problem is not the pub-sub part, but just the fact that client is closed

**Comment by larrycinnabar** [comment]
@vmihailenco 

Is there a way to get some kind of notification (via channel or something) that redis library got `pool.ErrClosed`

So then, we can in our application just listen to it, and fully re-establish redis connection if needed

**Comment by vmihailenco** [comment]
Client is closed by your app and you have full control of this process. I don't see how go-redis can help you here.
