### ISSUE TITLE
Release v6.15.3 couses mistake path import

### ISSUE THREAD

**Issue by KacperPerschke** [go-redis/redis#1044]
`kacper@wirtualka-kacpra:~/Repo$ cat go.mod 
module main

go 1.11

require github.com/gorilla/mux v1.7.2

require github.com/spf13/viper v1.3.0

require gopkg.in/redis.v6 v6.15.3

// require gopkg.in/redis.v2 v2.3.2
kacper@wirtualka-kacpra:~/Repo$ go vet -v
go: gopkg.in/redis.v6@v6.15.3: parsing go.mod: unexpected module path "github.com/go-redis/redis"
go: error loading module requirements
`

**Comment by vmihailenco** [comment]
Try replacing gopkg.in/redis.v6 with github.com/go-redis/redis

**Comment by KacperPerschke** [comment]
> Try replacing gopkg.in/redis.v6 with github.com/go-redis/redis

I've just tried and had to revrite some calls but finaly it works well.

Thanks!
