### ISSUE TITLE
Master build is failing in travis

### ISSUE THREAD

**Issue by cep21** [go-redis/redis#1052]
https://travis-ci.org/go-redis/redis
https://travis-ci.org/go-redis/redis/jobs/545738089

**Comment by vmihailenco** [comment]
I've restarted and it passes now. It is flaky and needs to be improved, but I don't think we need this issue open. Thanks anyway.

**Comment by cep21** [comment]
Would it instead be worthwhile to make an issue to make CI stable for go-redis?
