### ISSUE TITLE
Backwards incompatible change on context.Deadline()

### ISSUE THREAD

**Issue by cep21** [go-redis/redis#1053]
Addressing https://github.com/go-redis/redis/commit/530e66a66efb9ad1bca4443a9863007f368d5d74

Previously, the context timeout was ignored. Now it overwrites the explicit read/write timeouts.

The expected behavior, for me, would be to use the soonest timeout of both the context and the explicit read/write timeout.  So if the context times out in 1 minute, and the ReadTimeout is set to 3 seconds, I would expect a timeout of 3 seconds.

**Comment by vmihailenco** [comment]
See https://github.com/go-redis/redis/pull/1051
