### ISSUE TITLE
MaxRedirects vs MaxRetries of ClusterOptions

### ISSUE THREAD

**Issue by gonejack** [go-redis/redis#1063]
I am testing the offline behaviours of go-redis by manually turn off the wifi network.

```go
opt := &redis.ClusterOptions{
	Addrs:        addrs,
	Password:     Password,
        ...
}

client := redis.NewClusterClient(opt)

for {
	time.Sleep(time.Second)

	get, err := client.Get("test").Result()

	fmt.Println("%s:%s", get, err)
}
```

After several tests it's seems like `MaxRedirects` is the only option that could affect the total execution time before returning error when the network was down, then what would be the use case of option `MaxRetries` author?

**Comment by vmihailenco** [comment]
Try to assign some value to MaxRetries. If there is still a question - re-open with a program that reproduces the problem.
