### ISSUE TITLE
Cluster client logs info for command not found

### ISSUE THREAD

**Issue by kollektiv** [go-redis/redis#1069]
Version: 4a3dbb325139

Using the cluster client, the internal logger is logging a lot of lines on commands. I believe [cmdsInfo](https://github.com/go-redis/redis/blob/4a3dbb32513924da74212c7653ced756169ee223/cluster.go#L1499) is being ran before cluster state has synced, which results in [cmdsInfoCache](https://github.com/go-redis/redis/blob/4a3dbb32513924da74212c7653ced756169ee223/cluster.go#L655) storing an empty result.

When this happens, a [random node](https://github.com/go-redis/redis/blob/4a3dbb32513924da74212c7653ced756169ee223/cluster.go#L514) is always chosen on the first attempt, which has a high chance of getting a `MOVED` response

Output
```
redis: 2019/06/26 10:14:07 cluster.go:1534: info for cmd=get not found
redis: 2019/06/26 10:14:07 cluster.go:1534: info for cmd=get not found
redis: 2019/06/26 10:14:07 cluster.go:1534: info for cmd=get not found
redis: 2019/06/26 10:14:07 cluster.go:1534: info for cmd=get not found
```

Example
```go
package main

import (
	"fmt"

	"github.com/go-redis/redis"
)

func main() {
	client := redis.NewClusterClient(&redis.ClusterOptions{
		Addrs: []string{"localhost:30001"},
	})

	for i := 0; i < 1000; i++ {
		cmd := client.Get("0")
		_, err := cmd.Result()
		if err != nil && err != redis.Nil {
			fmt.Printf("error getting result: %v\n", err)
		}
	}
}

```

**Comment by huija** [comment]
github.com/go-redis/redis/tree/v6.15.2
我换成上面的版本没问题了, 应该是有了改动, 文档还是旧的

**Comment by vmihailenco** [comment]
I guess that is possible if you say so. But why does it happen?

**Comment by lkramer** [comment]
Hey, I'm seeing this as well. Any idea what the reason is?

**Comment by kollektiv** [comment]
@vmihailenco This has started happening since https://github.com/go-redis/redis/pull/1056. Before #1056, `process` would always retrieve the cluster state before through `cmdSlotAndNode` that called `c.state.Get()`.

Now `process` is first calling `cmdInfo`, which calls `c.cmdsInfoCache.Get()` before cluster state is retrieved

**Comment by vmihailenco** [comment]
Okay, but we do we need a cluster state to retrieve commands info? ClusterClient is created with at least 1 healthy node which should be enough to retrieve commands info...

**Comment by kollektiv** [comment]
@vmihailenco Cluster state isn't necessary. Refreshing cluster state lazily creates the nodes (`c.nodes.GetOrCreate`).

`cmdsInfo` calls `c.nodes.Get`, so it relies on the nodes being created. What if `cmdsInfo` calls `c.nodes.GetOrCreate` instead?

**Comment by kollektiv** [comment]
Is it possible to compute the slot of the command without depending on [COMMAND](https://redis.io/commands/command)?

**Comment by vmihailenco** [comment]
>What if cmdsInfo calls c.nodes.GetOrCreate instead?

Good call - I've sent a fix.
