### ISSUE TITLE
Is it possible to run a callback after each resubscribe in pubsub?

### ISSUE THREAD

**Issue by huangjunwen** [go-redis/redis#1070]
I have a key (say `cnf`) containing some config that will be changed time by time, and a channel (say `cnf:changed`) to notify other clients that `cnf` has been changed. The producer side looks like

```
SET cnf newconfig_blablabla
PUBLISH cnf:changed ""
```

And the consumer side looks like:

```
SUBSCRIBE cnf:changed
// wait subscribed
GET cnf                 // get the newest config
```

The problem is that now the [PubSub](https://godoc.org/github.com/go-redis/redis#PubSub) type seems do the reconnection/resubscribe automatically, if there is an update during the gap, the notification will be lost and the consumer will not be able to get the newest config. If a callback can be run after each subscribe/resubscribe, then i can `GET cnf` again to make sure we can get the newest one.

**Comment by vmihailenco** [comment]
You are welcome to contribute something like that. Method like `PubSub.OnReconnect(fn func())` looks like a good fit...

**Comment by huangjunwen** [comment]
@vmihailenco I've created a PR https://github.com/go-redis/redis/pull/1074 to add `PubSub.OnSubscription`.

**Comment by vmihailenco** [comment]
Should be addressed with `PubSub.ChannelWIthSubscriptions`
