### ISSUE TITLE
Go module not compatible

### ISSUE THREAD

**Issue by CuBiC3D** [go-redis/redis#1081]
Mentioned before by another person in #1050 but was closed. 
The `6.15.3` release is not compatible with go modules, latest recognised version is `6.15.2` before adding go.mod file. See https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher for complete requirements.

Using `go get -u github.com/go-redis/redis` results in `github.com/go-redis/redis v6.15.2+incompatible`. 
By trying to pull the new version with `go get -u github.com/go-redis/redis@6.15.3` result in `github.com/go-redis/redis v0.0.0-20190503082931-75795aa4236d` not recognising the version any more for any future version.

**Comment by vmihailenco** [comment]
`go get -u github.com/go-redis/redis@6.15.3` should be `go get -u github.com/go-redis/redis`

**Comment by CuBiC3D** [comment]
@vmihailenco As I said, `go get -u github.com/go-redis/redis` pulls `6.15.2` with `incompatible` flag, as the repository does not implement correct modules definition.

**Comment by vmihailenco** [comment]
Sorry, try `go get -u github.com/go-redis/redis@master`. I am going to release v7 as fully compatible with go mod but that will take some time.

**Comment by CuBiC3D** [comment]
Thank you! ;)

**Comment by vmihailenco** [comment]
You should be able to use `github.com/go-redis/redis/v7` which is in beta but usable.
