### ISSUE TITLE
Cannot pipeline reads

### ISSUE THREAD

**Issue by lukepighetti** [go-redis/redis#1082]
Hi there, I don't see a way to pipeline read operations with `go-redis`. Is this a missing feature? My goal is to HGETALL on multiple keys.

The strange thing I if I print `[]redis.Cmdr` I can see the results in there, but there is no public property to access the result on `redis.Cmdr`

**Comment by vmihailenco** [comment]
See these 2 examples
- https://godoc.org/github.com/go-redis/redis#example-Client-Pipeline
- https://godoc.org/github.com/go-redis/redis#example-Client-Pipelined

You can also type cast `redis.Cmder` into concrete type which should give access to typed `Val` and `Result`:

````
cmder.(*redis.IntCmd).Val()
cmder.(*redis.IntCmd).Result()
````

**Comment by lukepighetti** [comment]
Thanks, for any others looking for this info, this is what I ended up doing.


```
	pipe := r.Client.Pipeline()

	results := []*redis.StringStringMapCmd{}

	for _, id := range ids {
		results = append(results, pipe.HGetAll(fmt.Sprintf("messages:payload:%v", id)))
	}

	_, err := pipe.Exec()

	for _, cmd := range results {
		result, err := cmd.Result()
                // do something with the result
        }
```





```

**Comment by larryzhu2018** [comment]
even get does not work with pipeline - it does not return the values correctly
```
	var values []string
	keys = []string{"test-key"}
	pipe = client.Pipeline()
	for _, key := range keys {
		val, err := pipe.Get(ctx, key).Result()
		if err != nil {
			panic(err)
		}
		values = append(values, val)
	}
	pipe.Exec(ctx)
```
