### ISSUE TITLE
pipeline error handle

### ISSUE THREAD

**Issue by xzf0587** [go-redis/redis#1095]
i used pipeline to exec  commands, some of them will return "$-1" response if such as "get","rpop" commands have no result. And go-redis will translate this response to 
  `  const Nil = RedisError("redis: nil")`
which will fail the pipeline.exec(), while all the commands have successfully executed.

**Comment by vmihailenco** [comment]
Yes, that is how it works. What is the question?

**Comment by xzf0587** [comment]
i read the code again,and found that i should not only check the returned error but also the error in each of the commands when using  pipeline.exec().

**Comment by vmihailenco** [comment]
Yes, you can also check `err != nil && err != redis.Nil` if you don't care about `redis.Nil`.
