### ISSUE TITLE
marshal time.Time save to redis , and the result is wrong

### ISSUE THREAD

**Issue by fengbenming** [go-redis/redis#1096]
when json.Marshal serialize the time.Time,  and then Unmarshal is ok.  but when marshal  and save to redis, then the result is wrong. why does redis add the " to it.  like:  "\"2019-07-24T10:20:31.987734+08:00\""

such code like :
key := "updateTime"
	t0 := time.Now()
	res, _ := json.Marshal(t0)
	fmt.Println(res)
	var t1 time.Time
	json.Unmarshal(res, &t1)
	fmt.Println(t1) //print is normal time

	redis.Set(key, res)
	redisdb.Do("set", key, res)
	result, _ := redisdb.Do("get", key).Result()
	fmt.Println(result)

**Comment by vmihailenco** [comment]
`""` are added by ` json.Marshal` - all seems to be working as expected.
