### ISSUE TITLE
context.Context can be nil

### ISSUE THREAD

**Issue by kollektiv** [go-redis/redis#1098]
Version: 6bc7daa5b1e86745a6976ac1c4dfe6c76ea6af1f

Certain methods, such as `func (c *Client) Process(cmd Cmder) error`, will default pass a nil context. https://github.com/go-redis/redis/blob/6bc7daa5b1e86745a6976ac1c4dfe6c76ea6af1f/redis.go#L511

What are your thoughts on passing `c.Context()` (defaults to `context.Background()`) instead of `c.ctx` so the context is never nil? It's strongly recommended on https://golang.org/pkg/context/ to not pass a nil context.

There are a few other places where `c.ctx` is passed where `c.Context()` could be passed instead: `ring.go`, `sentinel.go`, and `tx.go`

**Comment by vmihailenco** [comment]
`c.ctx` is supposed to never have a nil value - it is initialized with `context.Background()` when client is created. `c.Context()` just returns `c,ctx` so there will not be any difference.

Do I miss anything?

**Comment by kollektiv** [comment]
You're right, I was using a version prior to https://github.com/go-redis/redis/pull/1080. `c.ctx` is always initialized now
