### ISSUE TITLE
Read errors not set on Cmdable

### ISSUE THREAD

**Issue by kollektiv** [go-redis/redis#1099]
Version: 6bc7daa5b1e86745a6976ac1c4dfe6c76ea6af1f

If there is a read error that occurs here https://github.com/go-redis/redis/blob/6bc7daa5b1e86745a6976ac1c4dfe6c76ea6af1f/redis.go#L271 the error is not set on the Cmdable. Setting the read error on the Cmdable is useful to get the error in the AfterProcess hook. What are your thoughts on setting the read error on the Cmdable, like when write errors happen?

**Comment by kollektiv** [comment]
My mistake, `cmd.readReply` will set the error onto the cmdable

**Comment by vmihailenco** [comment]
Let's keep this open. I believe there is at least one case where `WithWriter` does not an error on the command and hopefully I can make code more obviously correct.

**Comment by kollektiv** [comment]
In what case will `WithWriter` not set an error on the cmdable?
