### ISSUE TITLE
Retry sleeps supporting context cancellation

### ISSUE THREAD

**Issue by kollektiv** [go-redis/redis#1100]
Version: 6bc7daa5b1e86745a6976ac1c4dfe6c76ea6af1f

v7 now has context support. There are calls to `time.Sleep` but they do not respect context cancellations
https://github.com/go-redis/redis/blob/6bc7daa5b1e86745a6976ac1c4dfe6c76ea6af1f/redis.go#L247

An option is to use a context-aware sleep https://github.com/aws/aws-sdk-go/blob/bd8be1f3a00996ada22da77e8bdd22cd6c740732/aws/context_sleep.go#L12

**Comment by vmihailenco** [comment]
Sounds good - could you send a PR?
