### ISSUE TITLE
Dial Connections with context

### ISSUE THREAD

**Issue by kollektiv** [go-redis/redis#1101]
Version: 6bc7daa5b1e86745a6976ac1c4dfe6c76ea6af1f

v7 now supports context. Could the default Dialer use `DialContext` instead of `Dial`?

https://github.com/go-redis/redis/blob/6bc7daa5b1e86745a6976ac1c4dfe6c76ea6af1f/options.go#L115

**Comment by vmihailenco** [comment]
Good idea - do you care to send a PR?

**Comment by kollektiv** [comment]
@vmihailenco Yes! I've created a PR
