### ISSUE TITLE
 Fix: max_retries should fail when the context deadline timeouts

### ISSUE THREAD

**Issue by 8treenet** [go-redis/redis#1107]
https://github.com/8treenet/redis/commit/3a11286f6894d096b03bf2028dde0c6e98e1d8ec

**Comment by vmihailenco** [comment]
I don't think this is needed - `false` is returned by default.

**Comment by 8treenet** [comment]
I've already tested that the context timeout is not valid, so I'm still retrying.

**Comment by vmihailenco** [comment]
I don't understand what that means...

**Comment by 8treenet** [comment]
It's time you learned Chinese.

**Comment by vmihailenco** [comment]
Nah, I am strill struggling with English :)
