### ISSUE TITLE
mget time complexity?

### ISSUE THREAD

**Issue by mjmanav4** [go-redis/redis#1109]
Lets say i want fetch values for 100 keys present in an array

APPROACH 1: loop though the array of keys and make get calls to redis (n network calls)

APPROACH 2: use mget (1 network call)

will mget() retrive data faster then get() ??

what is the time complexity for mget vs get ?

Does mget() uses go-routine internally ??

**Comment by vmihailenco** [comment]
mget should make 1 write/read operation and should be faster. But this is not specific for go-redis. It is a general Redis question. Please ask it somewhere else.

As for the go-redis I recommend you to use `Pipeline` instead of `MGet` since it is implemented in Cluster & Ring clients.
