### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by zhu463175790** [go-redis/redis#1128]
fail to list imports(github.com/go-redis/redis): fail to get imports(github.com/go-redis/redis/v7/internal): cannot find package "github.com/go-redis/redis/v7/internal"

**Comment by vmihailenco** [comment]
v7 requires [Go modules](https://github.com/golang/go/wiki/Modules) support. v6.15.4 is the last version that works without Go modules.

**Comment by vmihailenco** [comment]
Use version 6.15.4 - details depend on which dependency management tool you are using. If none - `git checkout v6.15.4`.
