### ISSUE TITLE
Redis instrumentation not safe for concurrent use

### ISSUE THREAD

**Issue by wspowell** [go-redis/redis#1139]
I have been working on some applications that utilize redis heavily. This week I attempted to instrument the redis commands in order to trace the time they take (for local use in order to not send developemnt profiling data to hosted profiling solutions). However, I ran in an issue that I traced back to `redis.Client`. 

We create one global `redis.UniversalClient` and pass that around to all goroutines. This works and is safe for concurrent use. The issue arises when you call `WrapProcess()`.  This function will change the internal state of the global `redis.UniversalClient` causing subsequent calls to keep wrapping over and over (and thus causing issues). When I noticed that `WrapProcess()` has been removed in favor of `redis.Hook`, I thought this issue would be solved. However, I found that the same issue exists, just in another form. I looked for examples of other projects using `go-redis` but all I found were simple examples where the client was only used once. I took a look at different dedicated logging solutions (ie New Relic, Datadog, etc) and since they all use `WrapProcess()` they all have this issue.

**Observed behavior:**
Using a global `redis.UniversalClient` is not safe for concurrent use due to the manipulation of internal state. In this case the (old) `process` function variable via `WrapProcess()` and (new) `hooks` array via `AddHook`.

**Desired behavior:**
One possible solution here could be to separate the responsibilities of the various tasks. Each client appears to create its own connection pool and there is no way set the pool or create a new  client from an existing pool. If the connection pools were pulled out into their own structure and no longer embedded inside each client, then there would be the ability to create a new client that would simply take the pool as a parameter (instead of an options struct). At this point, the connection pool, say `redis.UniversalPool`, would become set once globally and each goroutine could safely create its own client, say `redis.Client(ctx, pool)`,  and alter it all it wants.

**Example showing incorrect behavior:**
I am including a code example for both v6.15.4 and the current master branch (d19aba07b47683ef19378c4a4d43959672b7cec8) that shows how `redis.Client` is not safe for concurrent use. If `redis.UniversalClient` or the instrumentation is being use incorrectly in this example, please let me know, since in its current form getting profiling data for redis across multiple goroutines is not possible via the provided methods.

```
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/go-redis/redis"
)

const (
	handlerNameContextKey = "handlerName"
)

var (
	redisClient redis.UniversalClient
)

/*
// version = "6.15.4"
//
// What it prints:
//
// Setting WrapProcess from handler1
// [handler1] starting processing: <get handler1: >
// [handler1] finished processing: <get handler1: handler1>
// [handler1] value: handler1
// [handler1] starting processing: <set handler2 handler2: >
// [handler1] finished processing: <set handler2 handler2: OK>
// Setting WrapProcess from handler2
// [handler2] starting processing: <get handler2: >
// [handler1] starting processing: <get handler2: >
// [handler1] finished processing: <get handler2: handler2>
// [handler2] finished processing: <get handler2: handler2>
// [handler2] value: handler2
//
// What I expect (want to happen) instead:
//
// Setting WrapProcess from handler1
// [handler1] starting processing: <get handler1: >
// [handler1] finished processing: <get handler1: handler1>
// [handler1] value: handler1
// Setting WrapProcess from handler2
// [handler2] starting processing: <get handler2: >
// [handler2] finished processing: <get handler2: handler2>
// [handler2] value: handler2
//
func handler(handlerName string) {
	redisClient.Set(handlerName, handlerName, 0)

	// Instrument redis (using example code).
	// https://godoc.org/gopkg.in/go-redis/redis.v6
	redisClient.WrapProcess(func(old func(cmd redis.Cmder) error) func(cmd redis.Cmder) error {
		fmt.Println("Setting WrapProcess from " + handlerName)
		return func(cmd redis.Cmder) error {
			fmt.Printf("[%s] starting processing: <%s>\n", handlerName, cmd)
			err := old(cmd)
			fmt.Printf("[%s] finished processing: <%s>\n", handlerName, cmd)
			return err
		}
	})

	value, err := redisClient.Get(handlerName).Result()
	if err != nil {
		fmt.Printf("[%s] error: %s\n", handlerName, err)
	}
	fmt.Printf("[%s] value: %s\n", handlerName, value)
}

*/

func profile(name string) func() {
	start := time.Now().UTC()

	return func() {
		fmt.Printf("[%s] runtime: %v\n", name, time.Now().UTC().Sub(start))
	}
}

type profiler struct {
	context.Context

	timer func()
}

func (self *profiler) start() {
	self.timer = profile(self.Context.Value(handlerNameContextKey).(string))
}
func (self *profiler) stop() {
	self.timer()
}

func (self *profiler) BeforeProcess(ctx context.Context, cmd redis.Cmder) (context.Context, error) {
	self.start()
	return ctx, nil
}
func (self *profiler) AfterProcess(ctx context.Context, cmd redis.Cmder) error {
	self.stop()
	return nil
}
func (self *profiler) BeforeProcessPipeline(ctx context.Context, cmds []redis.Cmder) (context.Context, error) {
	self.start()
	return ctx, nil
}
func (self *profiler) AfterProcessPipeline(ctx context.Context, cmds []redis.Cmder) error {
	self.stop()
	return nil
}

// master@d19aba07b47683ef19378c4a4d43959672b7cec8
//
// What it prints:
//
// [handler1] starting
// [handler1] runtime: 0s
// [handler1] value: handler1
// [handler2] starting
// [handler1] runtime: 0s
// [handler1] runtime: 0s
// [handler2] runtime: 1.0263ms
// [handler2] value: handler2
//
// What I expect (want to happen) instead:
//
// [handler1] starting
// [handler1] runtime: 0s
// [handler1] value: handler1
// [handler2] starting
// [handler2] runtime: 1.0263ms
// [handler2] value: handler2
//
func handler(handlerName string) {
	fmt.Printf("[%s] starting\n", handlerName)

	ctx := context.WithValue(context.Background(), handlerNameContextKey, handlerName)

	redisClient.Set(handlerName, handlerName, 0)

	// Instrument redis (using example code).
	// https://godoc.org/github.com/go-redis/redis#ex-package--Instrumentation
	redisClient.AddHook(&profiler{
		Context: ctx,
	})

	value, err := redisClient.Get(handlerName).Result()
	if err != nil {
		fmt.Printf("[%s] error: %s\n", handlerName, err)
	}
	fmt.Printf("[%s] value: %s\n", handlerName, value)
}

func main() {
	// Create one client that has a connection pool and set as the global redis client.
	redisClient = redis.NewClient(&redis.Options{
		Addr:     "localhost:6379",
		Password: "", // no password set
		DB:       0,  // use default DB
	})

	// No goroutines used.
	// Demonstrates that the underlying client is indeed not safe for concurrent use.
	handler("handler1")
	handler("handler2")
}
```

**Comment by vmihailenco** [comment]
Well, that is how it works. Normally you should add exactly 1 hook and pass request/task specific data via context.

**Comment by wspowell** [comment]
I would really appreciate an example of instrumentation usage where there is a context passed during redis command invocation per request like you said. The only place I see to add a context is during creation of the hook. What other method is available to set a context outside of a hook? If the intention is that you are supposed to add a hook during each request (ie at the beginning in some middleware) then this that is exactly the issue I am seeing. Those hooks will be applied to all requests, not just the current one because the client is global and the hook alters the client's internal state.

Could you provide a working example that demonstrates how to properly use hooks across requests?

**Comment by vmihailenco** [comment]
Something like

```go
package main

import (
	"context"
	"fmt"

	"github.com/go-redis/redis/v7"
)

type redisHook struct{}

var _ redis.Hook = redisHook{}

func (redisHook) BeforeProcess(ctx context.Context, cmd redis.Cmder) (context.Context, error) {
	fmt.Printf("starting processing: <%s>\n", cmd)
	fmt.Println("context.foo is", ctx.Value("foo"))
	return ctx, nil
}

func (redisHook) AfterProcess(ctx context.Context, cmd redis.Cmder) error {
	fmt.Printf("finished processing: <%s>\n", cmd)
	return nil
}

func (redisHook) BeforeProcessPipeline(ctx context.Context, cmds []redis.Cmder) (context.Context, error) {
	fmt.Printf("pipeline starting processing: %v\n", cmds)
	return ctx, nil
}

func (redisHook) AfterProcessPipeline(ctx context.Context, cmds []redis.Cmder) error {
	fmt.Printf("pipeline finished processing: %v\n", cmds)
	return nil
}

func main() {
	rdb := redis.NewClient(&redis.Options{
		Addr: ":6379",
	})
	rdb.AddHook(redisHook{})

	ctx := context.Background()
	ctx1 := context.WithValue(ctx, "foo", "bar1")
	ctx2 := context.WithValue(ctx, "foo", "bar2")
	for _, ctx := range []context.Context{ctx1, ctx2} {
		err := rdb.WithContext(ctx).Ping().Err()
		if err != nil {
			panic(err)
		}
	}
}
```

The output is:

```
starting processing: <ping: >
context.foo is bar1
finished processing: <ping: PONG>
starting processing: <ping: >
context.foo is bar2
finished processing: <ping: PONG>
```

The only part I don't like is `rdb.WithContext` API to pass context, but it is not too bad and I hope that in v8 all commads will accept `context.Context` as first argument.

**Comment by wspowell** [comment]
Thank you! `WithContext()` appears to be the critical missing piece when using `Client` as a global across goroutines since it appears that it solves the thread safety issue. I think it would be a good idea to update `example_instrumentation_test.go` to include this call.

My personal opinion, it may also be prudent to point out somewhere that obtaining a `Client` instance without calling `WithContext` on it first is not thread safe. The comment on `Client` that says `It's safe for concurrent use by multiple goroutines.` is misleading. I believe it is referring mainly to the underlying connection pool (which is thread safe), but makes developers think it means the actual `Client` struct usage, which is not thread safe without being careful.

**Comment by Antonboom** [comment]
@wspowell, +1

**Comment by vmihailenco** [comment]
In v8 `context.Context` is accepted as first argument.
