### ISSUE TITLE
Consider merging opencensus integration

### ISSUE THREAD

**Issue by mickael-carl** [go-redis/redis#1146]
[This fork](https://github.com/opencensus-integrations/redis/pull/1) adds Opencensus integration. Would there be any interest in a PR adding this back here?

**Comment by vmihailenco** [comment]
I am very much interested in supporting tracing, but I prefer to wait until [OpenTelemetry](https://opentelemetry.io/) is ready. Meanwhile I am working on better context propagation support.

**Comment by mickael-carl** [comment]
Good to hear! From the OpenTelemetry website:
> _I want to start instrumenting production code today. What should I use?_
>We are still working on the first production-ready release of OpenTelemetry. For those who want to start instrumenting production code immediately, use either OpenCensus or OpenTracing. OpenTelemetry will provide compatibility bridges and there is no need to wait for production-ready OpenTelemetry APIs in your language.
So maybe doing the integration sooner rather than later would still work out?

**Comment by directionless** [comment]
There is now opentelemtry support in `go-redis`. This should probably be closed.

**Comment by vmihailenco** [comment]
Yes, there is also basic OpenCensus integration in https://github.com/go-redis/redisext/tree/master/rediscensus
