### ISSUE TITLE
Streams - Connection pool timeout

### ISSUE THREAD

**Issue by JamesMurkin** [go-redis/redis#1147]
I am using redis with a fairly standard setup, which uses streams (XREAD/XADD).

Under no real load at all (~30 connections reading streams) I am getting the occasional:

> redis: connection pool timeout

I am using a 5 second block in the XREAD

My issue looks exactly like:
https://github.com/go-redis/redis/issues/1002

I was hoping someone could explain what is happening a bit better, so I could decide which action to take.

Is what is happening is that that as I have a 5 second block (XREAD BLOCK), that occasionally there is no free connections to redis (all are blocked waiting) so requests for new connections to redis timeout?

If so, I could:
- Increase redis pool size 
 If they are all blocking, I imagine this will have minor performance impact and prevent "redis: connection pool timeout"
- Decrease the BLOCK timeout
 As I am not expecting new data on the stream all the time, I would expect most the time to be blocking. So wouldn't reducing the BLOCK timeout just cause me to spam redis with timeout -> XREAD BLOCK loop. Does this have any performance impact or is this recommended?

I also see in redis you can set timeout to 0, which means it never timeout. Is this advisable? 

I don't want to spam redis by constantly re-issuing XREAD commands, however I don't want to get redis: connection pool timeout's.

Ideally I want each connection to watch a stream indefinitely (long time) and process any data that is added to the stream. What is the most efficient way to do this?

What is the recommended approach?

**Comment by vmihailenco** [comment]
Usually the best way is to use block timeout you need but limit number of goroutines that perform XREAD BLOCK. Most likely 1 or 2 is enough but I don't know what you are doing.
