### ISSUE TITLE
can't build the project

### ISSUE THREAD

**Issue by wrick198** [go-redis/redis#1148]
error information:
cluster.go:16:2: cannot find package "github.com/go-redis/redis/v7/internal" in any of:

In this project, there is no v7, why?

**Comment by wrick198** [comment]
in cluster.go:
import (
	"context"
	"crypto/tls"
	"fmt"
	"math"
	"math/rand"
	"net"
	"runtime"
	"sort"
	"sync"
	"sync/atomic"
	"time"

	"github.com/go-redis/redis/v7/internal"
	"github.com/go-redis/redis/v7/internal/hashtag"
	"github.com/go-redis/redis/v7/internal/pool"
	"github.com/go-redis/redis/v7/internal/proto"
)
However, there is no project "github.com/go-redis/redis/v7/internal" in any of place.
why?

**Comment by vmihailenco** [comment]
You need to use Go and activate Go module support - https://github.com/golang/go/wiki/Modules#how-to-install-and-activate-module-support
