### ISSUE TITLE
version 6.15.3+ is not usable with Go modules

### ISSUE THREAD

**Issue by pierrre** [go-redis/redis#1149]
I'm opening a new issue, because the problem is slightly different.

Before v6.15.2, the repository didn't use Go module, but it was usable in a project using Go modules.
Since v6.15.3, the repository contains a `go.mod` file that doesn't respect the Go module rules.
Since Go 1.13, the Go module rules are stricter.
You can't install anymore v6.15.3 and v6.15.4 with Go 1.13 (FYI it will be released very soon)
I've opened an issue about this https://github.com/golang/go/issues/34005 and they confirmed that the issue is on go-redis side.

I see a simple solution: remove entirely the Go module support from v6, and release a new tag v6.15.5.

It seems that v7 is using the Go module correctly, but it's still in beta.

WDYT ?

**Comment by vmihailenco** [comment]
Works for me. Could you send a PR to the v6 branch?

**Comment by pierrre** [comment]
Or maybe it's caused by the new `go 1.13` line in `go.mod`, I don't know.
But anyway, `v6` is not compatible with Go module, so we should remove `go.mod`.
I'll send a PR.
