### ISSUE TITLE
Not able to go get gopkg.in/redis.v6

### ISSUE THREAD

**Issue by poojakar** [go-redis/redis#1154]
**I got following message when i try to get gopkg.in/redis.v6 **package****
$go get gopkg.in/redis.v6
package github.com/go-redis/redis/v7/internal/util: cannot find package "github.com/go-redis/redis/v7/internal/util" in any of:
	/usr/local/go/src/github.com/go-redis/redis/v7/internal/util (from $GOROOT)
	/home/pooja/work/redis_new_trial/src/github.com/go-redis/redis/v7/internal/util (from $GOPATH)
package github.com/go-redis/redis/v7/internal: cannot find package "github.com/go-redis/redis/v7/internal" in any of:
	/usr/local/go/src/github.com/go-redis/redis/v7/internal (from $GOROOT)
	/home/pooja/work/redis_new_trial/src/github.com/go-redis/redis/v7/internal (from $GOPATH)
package github.com/go-redis/redis/v7/internal/proto: cannot find package "github.com/go-redis/redis/v7/internal/proto" in any of:
	/usr/local/go/src/github.com/go-redis/redis/v7/internal/proto (from $GOROOT)
	/home/pooja/work/redis_new_trial/src/github.com/go-redis/redis/v7/internal/proto (from $GOPATH)

**And If I try with "github.com/go-redis/redis" as some people suggested, again I get following messages. I dont see v7 directory downloaded with this package**
$ go get github.com/go-redis/redis
package github.com/go-redis/redis/v7/internal: cannot find package "github.com/go-redis/redis/v7/internal" in any of:
	/usr/local/go/src/github.com/go-redis/redis/v7/internal (from $GOROOT)
	/home/pooja/work/redis_new_trial/src/github.com/go-redis/redis/v7/internal (from $GOPATH)
package github.com/go-redis/redis/v7/internal/consistenthash: cannot find package "github.com/go-redis/redis/v7/internal/consistenthash" in any of:
	/usr/local/go/src/github.com/go-redis/redis/v7/internal/consistenthash (from $GOROOT)
	/home/pooja/work/redis_new_trial/src/github.com/go-redis/redis/v7/internal/consistenthash (from $GOPATH)
package github.com/go-redis/redis/v7/internal/hashtag: cannot find package "github.com/go-redis/redis/v7/internal/hashtag" in any of:
	/usr/local/go/src/github.com/go-redis/redis/v7/internal/hashtag (from $GOROOT)
	/home/pooja/work/redis_new_trial/src/github.com/go-redis/redis/v7/internal/hashtag (from $GOPATH)
package github.com/go-redis/redis/v7/internal/pool: cannot find package "github.com/go-redis/redis/v7/internal/pool" in any of:
	/usr/local/go/src/github.com/go-redis/redis/v7/internal/pool (from $GOROOT)
	/home/pooja/work/redis_new_trial/src/github.com/go-redis/redis/v7/internal/pool (from $GOPATH)
package github.com/go-redis/redis/v7/internal/proto: cannot find package "github.com/go-redis/redis/v7/internal/proto" in any of:
	/usr/local/go/src/github.com/go-redis/redis/v7/internal/proto (from $GOROOT)
	/home/pooja/work/redis_new_trial/src/github.com/go-redis/redis/v7/internal/proto (from $GOPATH)
package github.com/go-redis/redis/v7/internal/util: cannot find package "github.com/go-redis/redis/v7/internal/util" in any of:
	/usr/local/go/src/github.com/go-redis/redis/v7/internal/util (from $GOROOT)
	/home/pooja/work/redis_new_trial/src/github.com/go-redis/redis/v7/internal/util (from $GOPATH)

**Comment by vmihailenco** [comment]
Use v6.15.5 or learn how to use [Go modules](https://github.com/golang/go/wiki/Modules) because v7 does not work without them.
