### ISSUE TITLE
Versioning of structs

### ISSUE THREAD

**Issue by suren4Kites** [go-redis/redis#1160]
Hi,

I am trying to cache a go struct, am setting the expiry as 1 day.
Lets say my struct is {a:"aa", b:"bb"} and the key is K1, its expiry is 1 day. But I changed the struct to have one field, let's say {a:"aa", b:"bb", c:"cc"}, if the Key is not expired, it will not get updated since the same key.
I want to have an option to identify the version of struct change, before get or set cache.
Please let me know if there is anyway.

**Comment by vmihailenco** [comment]
go-redis does not interact with structs in any way so it can't help you. I will try to give more detailed answer in https://github.com/go-redis/cache/issues/27
