### ISSUE TITLE
LPush does not push data in list

### ISSUE THREAD

**Issue by pratiktech9** [go-redis/redis#1167]
I am quite new to golang and facing this issue

When  I try to push multiple string values using LPush it does not insert it

```
client.LPush("fruit", "orange", "apple")
```

When I inspect return value of above, I get

```
WRONGTYPE Operation against a key holding the wrong kind of value
```

I there anything I am doing wrong?

**Comment by pratiktech9** [comment]
Seems like I was using wrong way (i.e `Get`) to fetch the key value

**Comment by bluemind777** [comment]
You Ok!
