### ISSUE TITLE
RouteRandomly does NOT in fact route randomly

### ISSUE THREAD

**Issue by Wintereise** [go-redis/redis#1175]
Hi folks,

We're going by your "cluster of servers without using cluster mode" example as described in https://godoc.org/github.com/go-redis/redis#example-NewClusterClient--ManualSetup

Here's our bootstrap process (all slots belong to one "shard," just multiple read replicas).

```  
         clusterSlots := func() ([]redis.ClusterSlot, error) {
            slots := []redis.ClusterSlot{
                // First node with 1 master and 1 slave.
                {
                    Start: 0,
                    End:   16383,
                    Nodes: []redis.ClusterNode{},
                },
            }

            addresses := config.Get("cache", "redis", "addresses").StringSlice([]string{})
            for _, address := range addresses {
                slots[0].Nodes = append(slots[0].Nodes, redis.ClusterNode{
                    Addr: address,
                })
            }

            return slots, nil
        }

        options := &redis.ClusterOptions{
            ClusterSlots:  clusterSlots,
            Password:      config.Get("cache", "redis", "password").String(""),
            PoolSize:      config.Get("cache", "redis", "pool-size").Int(100),
            MinIdleConns:  config.Get("cache", "redis", "max-idle-connections").Int(5),
            RouteRandomly: true,
        }

        codec.Redis = redis.NewClusterClient(options)
```

What we're seeing happen however is that the set queries do seem to take place for all the nodes, but the reading (GET in our case) always seem to only take place to the "master" (first node in the group). We verified this by running `MONITOR` on all the redis servers while running commands.
 
Is this intended? If yes, how can we achieve the "one master, multiple read replicas" setup?

Thank you.

**Comment by zhoulin1359** [comment]
```golang
	if c.opt.ReadOnly && cmdInfo != nil && cmdInfo.ReadOnly {
		if c.opt.RouteByLatency {
			return state.slotClosestNode(slot)
		}
		if c.opt.RouteRandomly {
			return state.slotRandomNode(slot)
		}
		return state.slotSlaveNode(slot)
	}
```
ReadOnly is false,

**Comment by felipsmartins** [comment]
btw what means `redis.ClusterSlot.Start` and `redis.ClusterSlot.end`?

**Comment by jhmartin** [comment]
https://github.com/go-redis/redis/blob/3e4ae80c124cf7e6e9d015f827cd2cc1c332088b/cluster.go#L213-L214 Is this a bug? It looks like both randomly / latency just configure latency.

**Comment by vmihailenco** [comment]
https://github.com/go-redis/redis/pull/2275
