### ISSUE TITLE
what is the differnence between NewFailoverClient and NewSentinelClient

### ISSUE THREAD

**Issue by uraphaelp** [go-redis/redis#1179]
I'm trying to create a new client connection to my local redis sentinel cluster, but quite confused which method should I apply 
Since the `NewFailoverClient` contains attributes like addresses of `sentinels` and `mastername`, but the `NewSentinelClient` has more methods like `GetMasterAddrByName`.
So I'm pretty confused which one to choose, cuz I jsut want to make a simple test and have some data feedback from my local sentinels via the client

**Comment by vmihailenco** [comment]
NewFailoverClient is for connecting to the Redis Server that uses Redis Sentinel for failover. NewSentinelClient is for connection to the Redis Sentinel.

**Comment by Queetinliu** [comment]
I have multi sentinels and redis and i want to test redis sentinel HA so i use NewFailoverClient,I hope this could help you
