### ISSUE TITLE
Access to raw bytes in StringSliceCmd

### ISSUE THREAD

**Issue by remko** [go-redis/redis#1180]
StringCmd has a `Bytes()` method, which I assume can be used to store and retrieve raw bytes. StringCmd only has methods that return strings. Would it be possible to add methods that return byte slices?

**Comment by vmihailenco** [comment]
I you care about effeciency I would recommend to iterate over `[]string` and use usual trick to covert string to bytes without allocation - https://github.com/golang/go/issues/25484
