### ISSUE TITLE
how to create unit test redis new client ?

### ISSUE THREAD

**Issue by myansenr** [go-redis/redis#1182]
hello .. here is my code.. please help .. how to create unit test for mock connection redis 
thank you

// START KONEKSI REDIS
		client := redis.NewClient(&redis.Options{
			Addr:         Cfg.RedisConnDefault.RedisConnDefaultHost,
			Password:     Cfg.RedisConnDefault.RedisConnDefaultPassword,
			DB:           db_redis,
			MaxRetries:   redis_max_entries,
			ReadTimeout:  3 * time.Second,
			WriteTimeout: 3 * time.Second,
		})

		// PING KONEKSI REDIS
		_, err = client.Ping().Result()

**Comment by wingyplus** [comment]
@myansenr redis client implements `redis.Cmdable`. So in production code, you must accept redis client as `redis.Cmdable` as well. For test code, you can create type that implements `redis.Cmdable` and create result in `Ping()` method like this: 

```
type MockCmdable struct {

}

func (cmd *MockCmdable) Ping() *StatusCmd {
	return redis.NewStatusResult("1", nil)
}

... // TODO: mock other methods.
```

If you're not comfortable to write mock manually. I recommended you to use `mockgen`, it'll generate mock for you automatically.

**Comment by myansenr** [comment]
okay thank youu

**Comment by JordyMoos** [comment]
redis.Cmdable does not have the `Close() error` function. Could this be added? Else I cant treat `redis.Client` as `redis.Cmdable`

**Comment by wingyplus** [comment]
Cmdable concerned about command that let you interact with redis not a connection management. So you can use io.Closer interface which responsible for close boundary or create your own interface that embeded Cmdable and io.Closer.

**Comment by JordyMoos** [comment]
You are right, thanks
