### ISSUE TITLE
any plan to support context as the first param?

### ISSUE THREAD

**Issue by FelixSeptem** [go-redis/redis#1185]
as title describe, add `ctx` as the first for method call, to use entire context control mechanism

**Comment by vmihailenco** [comment]
Yes, the plan is to release v7 with few pending fixes and then in v8 change all functions to accept `context.Context` as first param. Context-less variants will not be supported.

**Comment by FelixSeptem** [comment]
> Yes, the plan is to release v7 with few pending fixes and then in v8 change all functions to accept `context.Context` as first param. Context-less variants will not be supported.

glad to hear that, close this issue now

**Comment by iDevoid** [comment]
can't wait for this one! :+1:
