### ISSUE TITLE
Client.Ping not working in v7

### ISSUE THREAD

**Issue by matthieuberger** [go-redis/redis#1187]
The very basic example showed in the readme dosen't seem to work, I get an EOF error.
Step to reproduce:

1. Start a redis instance

`docker run -d -p 6379:6379 --name redis1 redis`

2. Run the example code:

```
func ExampleNewClient() {
	client := redis.NewClient(&redis.Options{
		Addr:     "localhost:6379",
		Password: "", // no password set
		DB:       0,  // use default DB
	})

	pong, err := client.Ping().Result()
	fmt.Println(pong, err)
}

func main () {
	ExampleNewClient()
}
```

Output: EOF

**Comment by vmihailenco** [comment]
I would check if you can connect to the Redis with `redis-cli`.
