### ISSUE TITLE
Context cancel not working on blocking operations

### ISSUE THREAD

**Issue by kernle32dll** [go-redis/redis#1196]
After eagerly testing out the newest v7 Beta, I stumbled across an odd issue, when using contexts in conjunction with blocking operations (such as BRPop).

Consider this simple example:

```go
client := redis.NewClient(&redis.Options{})

cancelCtx, cancelFn := context.WithCancel(context.Background())

wg := &sync.WaitGroup{}
wg.Add(1)

go func() {
	client.WithContext(cancelCtx).BRPop(0, "some-key")
	wg.Done()
}()

time.Sleep(2 * time.Second)

cancelFn()
wg.Wait()

// .... will never get here
```

So what happens is that the client establishes the connection, and waits indefinitely due to the `0` timeout (which is perfectly fine). However, this way it is impossible to cancel the connection, if it has been successfully established (hence, the exemplary `time.Sleep`).

Oddly tough, this might be an unexpected limitation of Go itself. To cite the documentation of the undelying [Dialer.DialContext](https://golang.org/pkg/net/#Dialer.DialContext) used, emphasis by me:

> The provided Context must be non-nil. If the context expires before the connection is complete, an error is returned. **Once successfully connected, any expiration of the context will not affect the connection.**

I have no idea how to even fix this, unfortunately. Probably some clever switch statement leveraging `ctx.Done()`, and a channel something something while waiting for the first bytes (Reader maybe?)

**Comment by calebdoxsey** [comment]
Supporting proper context cancellation requires the use of a goroutine. If the performance overhead of a goroutine is unacceptable perhaps this issue should be marked as wont-fix.

**Comment by vmihailenco** [comment]
@calebdoxsey the cost of a goroutine *is* acceptable especially since we can check for `ctx.Done() ==  nil` and don't spawn a goroutine. My main suggestion is to move code to hooks - https://github.com/go-redis/redis/blob/master/redis.go#L49-L66 and https://github.com/go-redis/redis/blob/master/redis.go#L90-L107. This way you can check for timeout once per a command -  not in reader *and* writer.

**Comment by zt9** [comment]
I am having a similar problem - the BRPOP is blocking, but when I cancel the context, nothing seems to happen. I see that @calebdoxsey has [a fix](https://github.com/go-redis/redis/pull/1248) for this, but I am not sure how to use it. Would you be able to provide an example? 

Here is what I understand:

- for whatever reason, the blocking command cannot be cancelled in this client
- to deal with this, there is a hack that you can use to kill the underlying connection. This is done using `cancelWithSetDeadline()`.
- let's say you have a redis client `rdb`,  you get a connection using a background context using `rdb.Conn(context.Background())` (`Conn` is needed to run `cancelWithSetDeadline()`) - How do you relate this to the `rdb` client to run the BRPOP command. I am in a knot, would be grateful for an example that unblocks a blocking command so I can untangle myself.

**Comment by vmihailenco** [comment]
Closed by https://github.com/go-redis/redis/pull/1493
