### ISSUE TITLE
Cluster client swallows pipeline errors

### ISSUE THREAD

**Issue by kollektiv** [go-redis/redis#1198]
Version: v7.0.0-beta.4

The cluster client can swallow errors when trying to execute pipelined commands. For example, if there is a write i/o timeout, the error is not set on any of the commands, and an error is only set on commands from `c.mapCmdsByNode`

https://github.com/go-redis/redis/blob/dab9d3f80286dfc493442e6f0b1c7809873ca602/cluster.go#L1083-L1087

This example program demonstrates timeouts occurring, and no error returned by `client.Pipelined`

```go
package main

import (
	"fmt"
	"log"
	"os"
	"time"

	"github.com/go-redis/redis/v7"
)

const host = "localhost:30001"

func main() {
	if err := debug(); err != nil {
		log.Printf("error: %v", err)
		os.Exit(1)
	}
}

func debug() error {
	client := redis.NewClusterClient(&redis.ClusterOptions{
		Addrs:        []string{host},
		MaxRedirects: 1,
		ReadTimeout:  1000 * time.Millisecond,
		WriteTimeout: 500 * time.Millisecond,
	})

	const numPairs = 5000000
	pairs := make([]string, numPairs*2)
	for i := 0; i < numPairs; i++ {
		pairs[i*2] = fmt.Sprintf("%d", i)
		pairs[i*2+1] = fmt.Sprintf("%d", i)
	}

	s := time.Now()
	_, err := client.Pipelined(func(p redis.Pipeliner) error {
		for i := 0; i < len(pairs); i += 2 {
			p.Set(pairs[i], pairs[i+1], 10*time.Second)
		}

		return nil
	})

	if err != nil {
		return fmt.Errorf("setting keys: %w", err)
	}

	log.Printf("set %d pairs dur=%v", numPairs, time.Since(s))

	return nil
}
```

The output of the program outputs a duration much longer than the read and write timeouts combined for two attempts (3 seconds). Adding logging after L1083 reveals i/o timeout errors.

```go
2019/11/23 13:01:20 set 5000000 pairs dur=5.56938607s
```

**Comment by vmihailenco** [comment]
Thanks for the report and reproducer - I think I've fixed this in https://github.com/go-redis/redis/pull/1252

**Comment by vmihailenco** [comment]
>The output of the program outputs a duration much longer than the read and write timeouts combined for two attempts (3 seconds)

`mapCmdsByNode` takes almost 1 second for `5000000` commands. You may want to look into optimizing the code if you really need to work with millions of commands...
