### ISSUE TITLE
Redis Keyspace Notifications

### ISSUE THREAD

**Issue by achu1612** [go-redis/redis#1200]
Does the library support Redis Keyspace Notifications ?
Can I get any kind of notification if one key expires ?

**Comment by jberry777** [comment]
Hello, what was the resolution for issue?
Does this library support the Redis notify-keyspace-events capablity?

I'd like to use this library and have a use case for refreshing a cache entry with updated data whenever its TTL expires. My intent is to use the notification to notify my service of a key name that just expired by listening to a channel that Redis should write the notification to.
