### ISSUE TITLE
how to get all keys for redis cluster

### ISSUE THREAD

**Issue by wxylinxi** [go-redis/redis#1201]
hi, 
  i want to get all keys for the redis cluster ,but i don't know how to get it .hope someone can help me ,thanks

**Comment by wziww** [comment]
https://redis.io/commands/scan
DO NOT USE KEYS [patten] unless your keys amount is not so much

**Comment by wxylinxi** [comment]
> https://redis.io/commands/scan
> DO NOT USE KEYS [patten] unless your keys amount is not so much

en ,thanks ,such as , 
func (c cmdable) Scan(cursor uint64, match string, count int64) *ScanCmd;
this can only get  the key of one node from redis cluster, but i want to get all key of the cluster.Can i use the  go-redis do it ?

**Comment by wziww** [comment]
> > https://redis.io/commands/scan
> > DO NOT USE KEYS [patten] unless your keys amount is not so much
> 
> en ,thanks ,such as ,
> func (c cmdable) Scan(cursor uint64, match string, count int64) *ScanCmd;
> this can only get the key of one node from redis cluster, but i want to get all key of the cluster.Can i use the go-redis do it ?


To create a temporarily client (set ip and port you want) to do your commands
Here's an example
https://github.com/simple-devops/octopus/blob/master/myredis/index.go#L244-L249

**Comment by wxylinxi** [comment]
> > > https://redis.io/commands/scan
> > > DO NOT USE KEYS [patten] unless your keys amount is not so much
> > 
> > 
> > en ,thanks ,such as ,
> > func (c cmdable) Scan(cursor uint64, match string, count int64) *ScanCmd;
> > this can only get the key of one node from redis cluster, but i want to get all key of the cluster.Can i use the go-redis do it ?
> 
> To create a temporarily client (set ip and port you want) to do your commands
> Here's an example
> https://github.com/simple-devops/octopus/blob/master/myredis/index.go#L244-L249

Great! thanks

**Comment by vmihailenco** [comment]
Also see https://godoc.org/github.com/go-redis/redis#example-ScanIterator
