### ISSUE TITLE
ZAdd not working V7

### ISSUE THREAD

**Issue by nkumar15** [go-redis/redis#1206]
Hi

I am using version v7 to add a sorted set in redis with below code. Ping is successful.
However I don't see score and member inserted in redis key.

Not sure I am doing it correctly or not. Can somebody confirm please?
Or which version of this library recommended currently as home page docs recommends v7?
```
package main


import (
	"fmt"
	"github.com/go-redis/redis/v7"
)

func main() {

	rdb := redis.NewClient(&redis.Options{
		Addr:     "localhost:6379",
		Password: "",
		DB:       0,
	})

	pong, err := rdb.Ping().Result()
	fmt.Println(pong, err)

	_, err = rdb.ZAdd("mykey", &redis.Z{1, "some string"}).Result()
	if err != nil {
		fmt.Errorf("%v", err)
	}
}
```
Expected: score and member to be present in redis
Result: score and member not present.

**Comment by vmihailenco** [comment]
It is working fine - I guess you are checking wrong Redis server...
