### ISSUE TITLE
Unable to pass a list of arguments to variadic functions 

### ISSUE THREAD

**Issue by jskelcy** [go-redis/redis#1207]
This was touched on in #739, but the ticket was for a different issue so I am opening up an issue for specifically this. 

Many functions take a list of variadic number of arguments, (`Rpush`, `SAdd`, etc), and ideally, callers would be able to pass in an exploded list of arguments. So:
```
myList := []string{"element1", "element2"} 
redis.Rpush("words", myList... )
```
However, when this runs I am seeing the error `ERR wrong number of arguments for 'rpush' command`.

**Comment by vmihailenco** [comment]
You should be using `[]interface{}{"element1", "element2"}`, but otherwise it should work fine. It it does not - please post a program that reproduces the problem.

**Comment by jskelcy** [comment]
I am realizing now that my the project I was looking at was using the miniredis project and not an actual redis node. That is likely the issue, I'll see if I can swap out miniredis for real redis and see if I get the same results.
