### ISSUE TITLE
XRead block

### ISSUE THREAD

**Issue by antaintan** [go-redis/redis#1210]
hello, how to use XRead, i want to block routing when call XRead

**Comment by antaintan** [comment]
i change XReadArgs struct, add field MessageID.  code as below
type XReadArgs struct {
	Streams []string
	Count   int64
	Block   time.Duration
	MessageID string
}

func (c *cmdable) XRead(a *XReadArgs) *XStreamSliceCmd {
	args := make([]interface{}, 0, 5+len(a.Streams))
	args = append(args, "xread")
	if a.Count > 0 {
		args = append(args, "count")
		args = append(args, a.Count)
	}
	if a.Block >= 0 {
		args = append(args, "block")
		args = append(args, int64(a.Block/time.Millisecond))
	}
	args = append(args, "streams")
	for _, s := range a.Streams {
		args = append(args, s)
	}

	// message id or $ special ID
	args = append(args, a.MessageID)

	cmd := NewXStreamSliceCmd(args...)
	if a.Block >= 0 {
		cmd.setReadTimeout(a.Block)
	}
	c.process(cmd)
	return cmd
}

it's work fine.

**Comment by vmihailenco** [comment]
Message id is specified along with streams, e.g.:

``` go
&XReadArgs{
    Streams: []string{stream1, stream2, id1, id2},
}
```
