### ISSUE TITLE
Multiple Watch 

### ISSUE THREAD

**Issue by clemabd** [go-redis/redis#1215]
Hi, this is not really an issue. It is more a request of help. 

I am trying to do this 4 redis calls in one transaction : 

```
        func getHost(key) host, score, error{
         numberOfHosts, err := rdb.ZCard(key).Result()
	if err != nil {
		return nil, 0, err
	}
	host, err := rdb.ZRangeByScoreWithScores(key, redis.ZRangeBy{
		Min:    "0",
		Max:    strconv.Itoa(maxScore),
		Offset: numberOfHosts - 1,
		Count:  1,
	}).Result()
	if err != nil {
		return nil, 0, err
	}
	score := host[0].Score
	member, err := json.Marshal(host[0].Member)
	if err != nil {
		return nil, 0, err
	}

	if int(score) < maxCapacity {
		rdb.ZIncrBy(key, score+1, string(member))
	}

	host, err := rdb.GetHost(string(member))
	if err != nil {
		return nil, 0, err
	}
	return host, int(score), nil
}
```
I found this https://godoc.org/github.com/go-redis/redis#Client.Watch in the doc and I am trying to do something with it but it is a bit difficult at the moment. 

Is anybody already done this and provide advice ?

**Comment by vmihailenco** [comment]
Sorry, but I don't understand what your code is doing and how `Watch` is supposed to be used there.
