### ISSUE TITLE
Solution of HMSET deprecated

### ISSUE THREAD

**Issue by amarjeetanandsingh** [go-redis/redis#1216]
Hi
As per [redis doc](https://redis.io/commands/hmset) HMSET is deprecated. It suggests to use HSET now.

But in [code](https://github.com/go-redis/redis/blob/master/commands.go#L970) i see, we are still using "hmset".

What could be a proper solution?

**Comment by vmihailenco** [comment]
My understanding is that HMSET is an alias for HSET so we can continue using it without any consequences. We can also replace HMSET with HSET in our code...

**Comment by NathanBaulch** [comment]
What about those of us stuck using Redis v3? `HMSet` returns the error "ERR wrong number of arguments for 'hset' command" as expected since `HSET` is not variadic in Redis pre-v4.
