### ISSUE TITLE
HMSet in master creates empty key/value pair

### ISSUE THREAD

**Issue by stevealx** [go-redis/redis#1218]
I did not submit a PR, since I do not know the code very well, but use of HMSet in the latest master creates a hash with an empty key and value in my use case.

It looks like the length of 'args' is being computed based on the length of 'values', but values
is an interface and always seems to have a length of 1.  Multiplying its length by 2 creates the extra nil/nil pair in 'args'.  This patch seems to fix it:

```diff --git a/commands.go b/commands.go
index 0a6d1ad..1beb881 100644
--- a/commands.go
+++ b/commands.go
@@ -988,7 +988,7 @@ func (c cmdable) HMGet(key string, fields ...string) *SliceCmd {
 //
 // Note that it uses HSET Redis command underneath because HMSET is deprecated.
 func (c cmdable) HMSet(key string, values ...interface{}) *IntCmd {
-   args := make([]interface{}, 2+2*len(values))
+ args := make([]interface{}, 2)
        args[0] = "hset"
        args[1] = key
        args = appendArgs(args, values)
```

**Comment by vmihailenco** [comment]
Thanks for the report!
