### ISSUE TITLE
Hooks/Wrappers ignored by Watch

### ISSUE THREAD

**Issue by NathanBaulch** [go-redis/redis#1223]
I'm using `WrapProcess` to add logging instrumentation in go-redis v6 and noticed that commands run within `Watch` aren't intercepted. This is because `Client.newTx` creates a new `baseClient` with default process functions. So I'm forced to use the following workaround whenever I create a watch transaction:

```go
err := rds.Watch(func(tx *redis.Tx) error {
	// workaround: process wrappers not automatically applied to watch transactions
	if log {
		tx.WrapProcess(...)
	}
	...
}
```

I'm not fluent with this library but I assume there's a good reason to create a new `baseClient` internally. So I guess the only way to support this would be to store the wrapper functions internally and re-apply them when watch transactions are created, something like (ignoring pipeline for brevity):

```go
type baseClient struct {
	...
	wrappers []func(unc(Cmder) error) func(Cmder) error
	...
}

func (c *baseClient) WrapProcess(
	fn func(oldProcess func(cmd Cmder) error) func(cmd Cmder) error,
) {
	c.process = fn(c.process)
	c.wrappers = append(c.wrappers, fn)
}

func (c *Client) newTx() *Tx {
	...
	tx.baseClient.init()
	tx.statefulCmdable.setProcessor(tx.Process)
	for _, fn := range c.wrappers {
		tx.WrapProcess(fn)
	}
	return &tx
}
```

Happy to send a PR.

This scenario looks even trickier in v7 with the switch to instrumentation hooks because not only are they not passed to watch transactions but they can't be added manually. What are my options for reliable command logging in v7?

Looks like `Tx` should inherit the hooks from the original `Client`. Again, happy to provide a simple PR that passes this unit test:

```go
func ExampleWatch_instrumentation() {
	rdb := redis.NewClient(&redis.Options{
		Addr: ":6379",
	})
	rdb.AddHook(redisHook{})

	rdb.Watch(func(tx *redis.Tx) error {
		tx.Ping()
		tx.Ping()
		return nil
	}, "foo")
	// Output:
	// starting processing: <watch foo: >
	// finished processing: <watch foo: OK>
	// starting processing: <ping: >
	// finished processing: <ping: PONG>
	// starting processing: <ping: >
	// finished processing: <ping: PONG>
	// starting processing: <unwatch: >
	// finished processing: <unwatch: OK>
}
```

**Comment by vmihailenco** [comment]
Thanks for the detailed explanation - I've tried to fix this in https://github.com/go-redis/redis/pull/1225. Let me know if there are any issues.

>I assume there's a good reason to create a new baseClient internally

For watch we need a special sticky connection pool that reuses the same connection. To achieve that we create new baseClient.

**Comment by NathanBaulch** [comment]
Looks good, I've upgraded to v7. On a related note, would it be possible to get some indication in the `(Before|After)ProcessPipeline` hooks of whether the pipeline is transactional or not?

**Comment by vmihailenco** [comment]
You could try to inspect commands - transactional pipeline should be wrapped with MULTI ... EXEC.

**Comment by NathanBaulch** [comment]
Unfortunately those commands are not included in the `cmds` slice passed to the pipeline hooks, so transactional and non-transactional pipelines look the same. They added deeper down just before sending them to `proto.Writer`.

**Comment by vmihailenco** [comment]
Indeed, and changing that is a non-trivial change for Cluster and Ring which may need to retry subset of commands... I think adding BeforeProcessTxPipeline/AfterProcessTxPipeline is the easiest fix...

**Comment by vmihailenco** [comment]
@NathanBaulch please try v7.1.0 - I've fixed (Before|After)ProcessPipeline to include multi & exec.

**Comment by NathanBaulch** [comment]
LGTM 👍 thanks
