### ISSUE TITLE
read/write tcp i/o timeout

### ISSUE THREAD

**Issue by HardLearning** [go-redis/redis#1227]
I need to calculate the total cost of time of **get requeset**, And I found that if I set the value bigger than 5MB, it will timeout. 
![image](https://user-images.githubusercontent.com/27262951/71650856-03a6fe80-2d54-11ea-9c0e-acaf03c78e9b.png)

![image](https://user-images.githubusercontent.com/27262951/71650877-2d602580-2d54-11ea-9c07-b59aa511910d.png)

**Comment by vmihailenco** [comment]
Sometimes requests timeout - it is not necessary a problem especially if payload is large (5MB is large).
