### ISSUE TITLE
redis.v7 HGetAll Incorrect result

### ISSUE THREAD

**Issue by enzhaojiao** [go-redis/redis#1231]
Hset value is interface{}
why HGetAll  value is map[string]string ?
it should be map[string]interface{}

**Comment by vmihailenco** [comment]
We don't know underlying type - all data comes as string and it is user responsibility to parse that string.

**Comment by enzhaojiao** [comment]
HMGet is  []interface{}
HGet  is string 
HGetAll is map[string]string
So should HMGet be consistent with them

**Comment by vmihailenco** [comment]
AFAIR HMGet is an []interface{} to disinguish between empty value "" and nil value (key does not exist).

**Comment by enzhaojiao** [comment]
Ok thank you for your answer.
