### ISSUE TITLE
redis get request timeout

### ISSUE THREAD

**Issue by HardLearning** [go-redis/redis#1232]
![image](https://user-images.githubusercontent.com/27262951/71861609-e72f0b80-3131-11ea-86a5-0caac4a82371.png)
I have set timeout parameter， however， redis get command will timeout anyway. 
![image](https://user-images.githubusercontent.com/27262951/71861910-f793b600-3132-11ea-8c0b-7c753dc3f2de.png)
I have set read timeout is 2ms, pool timeout is 2ms, the data size is 4MB, however, the total cost of time is 111ms.

**Comment by vmihailenco** [comment]
If read timeout is 2 ms and command takes 111 ms to complete - you get a read timeout. It is not clear what is the problem.
