### ISSUE TITLE
Advice for fixed-size ring

### ISSUE THREAD

**Issue by seizethedave** [go-redis/redis#1238]
Hi -

Is there a way to turn off the healthchecks that remove hosts from the ring? Each host in my ring has its own high-availability setup (GCP Memorystore) and I'm using them together as a consistent database so I don't want the key->host membership changing at all.

Alternatively, the readme hints that ClusterClient can use a bunch of non-Cluster Redis hosts. Is this true? It seems like the code depends on `MOVED` etc messages coming from cluster-mode hosts.

Thanks!

**Comment by vmihailenco** [comment]
There is no way to disable healthchecks, but you could send a PR that does that when `HeartbeatFrequency == -1`. Should be fairly straightforward - https://github.com/go-redis/redis/blob/master/ring.go#L385

>Is this true? It seems like the code depends on MOVED etc messages coming from cluster-mode hosts.

It does and I believe it is not working properly. I don't have enough time to work on it.

**Comment by seizethedave** [comment]
Thanks!
