### ISSUE TITLE
Possible to change the per-connection READONLY command?

### ISSUE THREAD

**Issue by beams0305** [go-redis/redis#1240]
Hi,

We've been seeing new connection spikes after applying the fix for handling Remove() for SingleConnPool: #1112 . Please correct me if I'm wrong: I think the client will issue one READONLY command per connection if ReadOnly option is set to true, but this command might become a bottleneck when server is under heavy load and many requests time out causing lots of new connections to be created. 

I'm not sure what would be the best way to fix this, but: 
1) Do we really need to issue READONLY command given that we always slot slave node if ReadOnly option is enabled and it's a ReadOnly command? https://github.com/go-redis/redis/blob/master/cluster.go#L1570
2) Is it possible to change the READONLY setting to just be set once instead of per connection? E.g., issue a CONFIG SET command when init the ClusterClient? 

Thank you and I look forward to your advice!

**Comment by vmihailenco** [comment]
Readonly is set once per connection because it works on a connection level

>>>Enables read queries for *a connection* to a Redis Cluster replica node

It is done once in a pipeline so it should not cause any measurable performance penalties.
