### ISSUE TITLE
Possible to make the setErr as public in baseCmd?

### ISSUE THREAD

**Issue by git-hulk** [go-redis/redis#1254]
We are going to implement the Redis read/write splits based on go-redis, and it may want to emit the error before sending the command to the Redis server(like "no slave was alive"). It would be convenient if `baseCmd` exports the setError.

any advice? thanks :)

**Comment by vmihailenco** [comment]
If making `setErr` public is the only requirement - just send a PR. It should be a small change.

**Comment by git-hulk** [comment]
@vmihailenco ok, thanks for the reply.
