### ISSUE TITLE
Clone() method exposes the internal type `hooks`

### ISSUE THREAD

**Issue by pierrre** [go-redis/redis#1258]
https://pkg.go.dev/github.com/go-redis/redis/v7@v7.0.0?tab=doc#Client.Clone

The returned value is the private type `hooks`.
Is that normal ? (that's very unusual from my point of view)

**Comment by vmihailenco** [comment]
No, that is a method from an embedded `hooks` struct. Thanks for the report.

**Comment by pierrre** [comment]
thank you
