### ISSUE TITLE
Help needed. redis: connection pool timeout

### ISSUE THREAD

**Issue by dongbiao830415** [go-redis/redis#1261]
redis version       : 3.2.12
go-redis version : e7f788704f5a5e72a697d716cc67694b523539f5(2019-05-26T05:49:28Z)
cluster nodes	   : 6, Deployed in two different data centers
go-client 		   : Deployed in one of the data centers
client NumCPU   : 4
steps	           :
	(1) create client
	client = redis.NewClusterClient(&redis.ClusterOptions{
		Addrs:         clusterAdds,
		Password:      password,
		ReadOnly:      true,
		RouteRandomly: true,
		ReadTimeout:   7 * time.Second,
		DialTimeout:   3 * time.Second,
	})

	codec := cache.Codec{
		Redis: client,
		Marshal: func(v interface{}) ([]byte, error) {
			return json.Marshal(v)
		},
		Unmarshal: func(bytes []byte, v interface{}) error {
			return json.Unmarshal(bytes, v)
		},
	}
	(2) get data from redis 
	codec.Get(key, data)
	(3) a large number of "redis: connection pool timeout" errors occur,how can I troubleshoot this problem?

**Comment by vmihailenco** [comment]
That likely means that Redis is too slow and can't serve all the requests.

**Comment by jackerlu** [comment]
Have you solved this problem?

**Comment by vmihailenco** [comment]
See [Debugging Go Redis](https://redis.uptrace.dev/guide/go-redis-debugging.html)
