### ISSUE TITLE
v7: HMSet now requires at least Redis 4.0

### ISSUE THREAD

**Issue by pierrre** [go-redis/redis#1262]
Hello,
My company is using an old version of Redis (3.2.1), and we can't upgrade right now.
We were using `go-redis` v6 without any issue.
When we called `HMSet()`, is was doing a `hmset` (deprecated in recent versions of Redis) command to our Redis, and it was working.
Since `go-redis` v7, the call to `HMSet()` is converted to `hset`, which support multiple key/value since Redis 4.0.
However, my company is not yet using Redis 4.0, so the `hset` with multiple key/value fails.
I don't see anything in the changelog of v7.
Do you have a minimum Redis version supported policy ?

**Comment by vmihailenco** [comment]
Well, I guess we could
- remove HSet
- rename HMSet to HSet
- restore old HMSet

Which is trivial to do and support but is backwards incompatible for HMSet func signature. It seems to be minor thing though and likely will help people to migrate to v7 so I am inclined to break the semver rules and release it as v7.2...

**Comment by pierrre** [comment]
Thank you for your quick answer.

Yes, that would work for me.
On my side, I will rewrite my function calls `HMSet()` to multiple `HSet()` (I'm using TxPipeline, so it shouldn't be very costly).
It's a temporary fix, if you release this in 7.2, I'll use `HMSet()` again.

Just a question: do you have similar changes between v6 and v7 that are not mentioned in the changelog ?
Reading the full Git diff would take a very long time :stuck_out_tongue:

**Comment by pierrre** [comment]
A suggestion, add a warning in the "new" `HSet()` function: multiple key/value is not supported before Redis 4.0

-------------------

> rename HMSet to HSet

> but is backwards incompatible for HMSet func signature

I know that some libraries https://github.com/bsm/redislock/blob/3d76f17a9f1e22d11521f78267ce1795641ae596/redislock.go#L31-L37 depends on the exact signature of the methods exposed by go-redis.
It could break such library.
But it's not an issue for me, personally.

**Comment by vmihailenco** [comment]
>Just a question: do you have similar changes between v6 and v7 that are not mentioned in the changelog ?

Honestly I don't remember. Most of the work was about context.Context and hooks system.

>It could break such library.

Ack. Hope it is not too bad.

>A suggestion, add a warning in the "new"

Done

**Comment by pierrre** [comment]
> Do you have a minimum Redis version supported policy ?

In the Go MongoDB driver, they say clearly that MongoDB 2.6+ is supported.

https://github.com/go-redis/redis/blob/726f6807ac6652fa683b8d98f2d984e4ee2cc8b9/.travis.yml#L5-L6
Travis always installs a recent version of Redis.
If we want to guarantee that `go-redis` is compatible with older versions, we must probably install them manually.
On my local computer, I can easily test old versions of Redis with Docker: `docker container run --rm --net=host --name=redis redis:3.2.1-alpine`

**Comment by pierrre** [comment]
The fix works for me.
Thank you !
