### ISSUE TITLE
TTL command reply with negative duration

### ISSUE THREAD

**Issue by dselyuzhitskiy** [go-redis/redis#1264]
Hi!

Thanks for great library. 
I found that TTL command reply has negative duration. It is because for absent keys or keys without ttl redis answer contain -1 or -2. I think it is probably good to handle such replies in DurationCmd and return errors like NoTTL or NotFound. Or i should handle all possible answers in my application ?

**Comment by vmihailenco** [comment]
Errors like NoTTL or NotFound could be an interesting idea if we have a fresh start, but at this stage it will break a lot of code for the relatively small benefit (cleaner API). I prefer to keep existing behavior as is.

**Comment by cpdyj** [comment]
Should we add some notes on the docs for those problems? 
Be honest, the docs is too "succinct". Some strange cases doesn't be described.

**Comment by vmihailenco** [comment]
You can contribute at https://github.com/go-redis/docs
