### ISSUE TITLE
Breaking change introduced in v7.1.0

### ISSUE THREAD

**Issue by dethi** [go-redis/redis#1265]
v7.1.0 introduced a breaking change that is not documented.

This [change](https://github.com/go-redis/redis/commit/49a0c8c3198bec92efef81a9a9e514920348e22e#diff-9c42b524cb14ca001c61267826cbefb1) renamed the `.String() (string, error)` method to `.Text() (string, error)` and introduced a new `.String() string` method, which doesn't work the same way if the command returned an error.

This should be added explicitly to the changelog.

**Comment by vmihailenco** [comment]
Update changelog - thanks.
