### ISSUE TITLE
does redis.Client.Ping() have same protocol as redis-cli?

### ISSUE THREAD

**Issue by rokrokss** [go-redis/redis#1274]
I'm deploying go services using this library on kubernetes cluster.
a weird thing is that redis.Client.Ping() fails with
```
dial tcp {{redis-server-ip}}: connect: connection refused
```
but using `redis-cli` on go service's pod works well.
I'm having a hard time debugging this issue, can anyone give me any advice? I will be really appreciated.

**Comment by vmihailenco** [comment]
Not a Redis issues - you should look into your network access setup.
