### ISSUE TITLE
RFC:  transforming the reported master port under Redis Sentinel behind TLS

### ISSUE THREAD

**Issue by ae6rt** [go-redis/redis#1275]
Until open source Redis and Sentinel support TLS, and those features are stable, I will run my sentinels and master behind an stunnel L4 proxy terminating TLS.  In the Java world, [Redisson](https://github.com/redisson/redisson) and [Lettuce](https://github.com/lettuce-io/lettuce-core) both support TLS to the sentinel and master.  Those libraries also support a user defined mapping function to map IP:port values, where the mapped values are what the ensuing client TCP connections are based on.

We build Redisson and Lettuce support into our Java frameworks where I work.  We have a local policy that says, e.g., if the port == 6380, then transform the port to 6381.  Granted, those Java libraries don't give me a way to know if the port belongs to the sentinel or master explicitly, but I know my infrastructure and if the port happens to be 6380, then I know that is a master port and the associated master can be reached through the L4 stunnel proxy on port 6381.

So, my question is, is there an interest in this sort of port mapping feature in `go-redis`?  I can imagine the FailoverOptions could have a field

```
type FailoverOptions struct {
...
    MasterPortMapper func(addr string) string
}
```
which is flowed into 

```
type sentinelFailover struct {
...
	masterPortMapper func(addr string) string
}
```

where `masterPortMapper` can be used to adjust the master port per local policy.  

Or some such.

Is there an interest in this sort of feature in this project?  

Thank you.

**Comment by vmihailenco** [comment]
Can't this be done with `FailoverOptions.Dialer`? It accepts `addr string` and you rewrite it with the logic you suggested.

**Comment by ae6rt** [comment]
Oh, my.  You are right.  My original analysis of the Dialer had a bug in it.  This shows the Dialer can be used for master port mapping:

```
func main() {
	tlsConfig := &tls.Config{
		InsecureSkipVerify: true,
	}
	dialer := func(ctx context.Context, network, addr string) (net.Conn, error) {
		parts := strings.Split(addr, ":")
		if parts[1] == "6380" {
			addr = parts[0] + ":1380"
			fmt.Printf("@@@ Dialer mapped addr: %s\n", addr)
		}
		netDialer := &net.Dialer{
			Timeout:   5 * time.Second,
			KeepAlive: 5 * time.Minute,
		}
		if tlsConfig == nil {
			return netDialer.DialContext(ctx, network, addr)
		}
		return tls.DialWithDialer(netDialer, network, addr, tlsConfig)
	}

	rdb := redis.NewFailoverClient(&redis.FailoverOptions{
		MasterName:    "mymaster",
		Password:      "changeit",
		SentinelAddrs: []string{"192.168.99.1:11380"},
		Dialer:        dialer,
	})

	rdb.Set("foo", "bar", time.Duration(0))
	get := rdb.Get("foo")
	fmt.Println(get.Result())
}
```

outputting

```
redis: 2020/03/19 06:00:17 sentinel.go:435: sentinel: new master="mymaster" addr="192.168.99.1:6380"
@@@ Dialer mapped addr: 192.168.99.1:1380
bar <nil>
```

Thank you for reading and sorry for the noise.
