### ISSUE TITLE
Reconnect after CLUSTERDOWN dials wrong host

### ISSUE THREAD

**Issue by ericrenard** [go-redis/redis#1276]
Hello,

We use go-redis on a number of services, towards a shared redis cluster. Yesterday we experienced a weird behavior ; I tried to find issues related to this but did not succeed.

Our redis client is initialized like this :
`rd := redis.NewClusterClient(&redis.ClusterOptions{ReadOnly: true, Addrs: nodesAddresses})`

nodesAddresses contain multiple remote redis nodes host + ports.

At one point, we needed to reconfigure our cluster. During this operation, we had first errors such as :
`dial tcp 10.128.41.117:6380: connect: connection refused`

Then errors such as :
`CLUSTERDOWN Hash slot not served`

Once the cluster was fully reconfigured, we then had some (not all) services stuck on these errors :
`dial tcp :6379: connect: connection refused`

This error did not go away until we restarted the concerned services.
It seems go-redis tried to reconnect on localhost and "forgot" our initial Addrs.

Have you ever experienced something like this ?

Thanks

**Comment by vmihailenco** [comment]
go-redis uses addresses supplied by Redis Cluster. You can use `CLUSTER SLOTS` command to debug it.

**Comment by tianyi-ge** [comment]
I encountered the same weird situation. I typed `redis-cli --cluster fix host:port` to fix the hash slots and found the connection refused error.

I solved this by `./redis-cli --cluster create host1:port1 host1:port1 ...` to recreate the cluster. This step also reshards the hash slots.
