### ISSUE TITLE
How to select db in cluster?

### ISSUE THREAD

**Issue by wolking** [go-redis/redis#1278]
I saw that both FailoverOptions and Options can set DB, why not ClusterOptions?
![image](https://user-images.githubusercontent.com/12195297/77278952-988a1a00-6cfb-11ea-998b-324f4962c87e.png)
![image](https://user-images.githubusercontent.com/12195297/77278989-ae97da80-6cfb-11ea-81b0-6dacfec1a8c1.png)

**Comment by vmihailenco** [comment]
AFAIK Redis Cluster does not support db option.

**Comment by wolking** [comment]
> AFAIK Redis Cluster does not support db option.
My mistake,haha.thank you
