### ISSUE TITLE
Support for redis:// urls

### ISSUE THREAD

**Issue by cousine** [go-redis/redis#128]
Hi,

I'm wondering if there is a way to connect using a redis url in the following format:

    redis://username:password@host:port/

**Comment by vmihailenco** [comment]
Hi,

No, but you can write a tiny wrapper that parses the URL and constructs `redis.Options` instance that can be passed to `redis.NewClient`.

**Comment by cousine** [comment]
Thanks, I did that and it works flawlessly :)

**Comment by saulshanabrook** [comment]
@cousine Could you post your code just to save the rest of us a bit of time? :)

**Comment by saulshanabrook** [comment]
@cousine Ah i see it here, nevermind: https://github.com/go-redis/redis/issues/129#issuecomment-118889469
