### ISSUE TITLE
Cannot connect to Elasticache

### ISSUE THREAD

**Issue by ThomasJannaud** [go-redis/redis#1283]
Hi,

We try to connect to Elasticache (Cluster mode):

```
client := redis.NewClusterClient(&redis.ClusterOptions{
    Addrs:   []string{ ""clustercfg.x.y.usw2.cache.amazonaws.com:6379""},
})
err := client.Set("key", "value", time.Minute)
```

This works fine on a local redis cluster `127.0.0.1:30001` but we get a `read tcp 172.24.x.x:46908->172.24.x.x:6379: i/o timeout` error on Elasticache

Note that we are trying to move away from another redis client (mna/redisc) which works ok with Elasticache, so it is not a permission issue.

Is there anything special we need to do in the Dialer maybe for Elasticache (cluster mode)?

Thanks

**Comment by ThomasJannaud** [comment]
There was an issue with the TLS config, fixed and seems to be working

**Comment by ThomasJannaud** [comment]
There was an issue in our TLS config, things work great now thanks!

**Comment by bruno-chavez** [comment]
Hey @ThomasJannaud what TLS issue did you had and how did you fix it? Having the same problem right now

**Comment by ThomasJannaud** [comment]
@bruno-chavez as a dialer, do you use a tls.DialWithDialer?

**Comment by subhankarc** [comment]
@ThomasJannaud Can you please provide the code snippet which worked for you ?

**Comment by advanderveer** [comment]
Although I can't really speak for the op, this is almost certainly fixed (it did so for me on ElastiCahce) by adding TLSConfig like so:
```
client := redis.NewClusterClient(&redis.ClusterOptions{
    Addrs:   []string{ "clustercfg.x.y.usw2.cache.amazonaws.com:6379"},
   TLSConfig: &tls.Config{},
})
```
