### ISSUE TITLE
v7 binary so fat compared to v5

### ISSUE THREAD

**Issue by kokizzu** [go-redis/redis#1284]
measurement by goweight:

v5 = 3.0 MB
```
goweight . | head -n 5
  3.9 MB net/http
  3.8 MB runtime
  3.0 MB gopkg.in/redis.v5
  2.9 MB github.com/wcharczuk/go-chart
  2.5 MB github.com/valyala/fasthttp
```

v7 = 8.7 MB
```
goweight . | head -n 8
  8.7 MB github.com/go-redis/redis/v7
  7.3 MB github.com/aws/aws-sdk-go/service/s3
  3.9 MB net/http
  3.8 MB runtime
  3.3 MB github.com/gocql/gocql
  2.8 MB github.com/aws/aws-sdk-go/aws/endpoints
  2.5 MB github.com/valyala/fasthttp
  1.9 MB go.mongodb.org/mongo-driver/mongo
```

**Comment by vmihailenco** [comment]
That is pretty bad and I am not sure I can do much. Even adding something like

``` go
type A struct {
	Cmdable // this is just a huge interface without implementation
}

type B struct {
	Cmdable
}

type C struct {
	Cmdable
}
```

adds another few megabytes. TBH this looks like some deficiency in Go but it is unclear whether compiler can handle it better.

The only thing I can do is to try to move Cluster and Ring implementation into separate packages. That should help if you don't use those clients.

**Comment by vmihailenco** [comment]
After some experimentation it looks like goweight does not provide accurate information, e.g. compiled binary is 7395300 bytes, but at the time goweight reports

```
   12 MB github.com/go-redis/redis/v8
  5.8 MB runtime
  2.4 MB net
  2.4 MB crypto/tls
  2.0 MB reflect
```

which does not seem to be accurate at all.

**Comment by vmihailenco** [comment]
And there is already issue for that - https://github.com/jondot/goweight/issues/16
