### ISSUE TITLE
Issue with master failover to slave in Manual Cluster

### ISSUE THREAD

**Issue by islanderman** [go-redis/redis#1291]
I am using `cluster` with my own `ClusterSlots` func to maintain cluster slots info.  My redis is not a cluster, but a set of redis master/slave nodes instead. My slave nodes are essentially replicas, so I do not want to send any write operations to them.

The application runs fine in high load environment for about two hours and it started to send write requests to slave nodes. I set **MaxRedirects** to -1, and **ReadOnly** to false, but the client doesn't seem to pick ONLY the master node and fail/timeout instead of failover to slave.

Here's my `redis.ClusterOptions`:

```go
redisConf := &redis.ClusterOptions{

        ReadOnly:      false,
        RouteRandomly: false,

        MinIdleConns: 150,
        MaxRetries: 16,
        MaxRedirects: -1,
        PoolSize: 2000,

        ReadTimeout: time.Millisecond * 5000,
        WriteTimeout: time.Millisecond * 5000,
        DialTimeout: time.Millisecond * 5000,
        PoolTimeout: time.Millisecond * 7000,

        IdleCheckFrequency: time.Minute * 1,
    }
```

Please advice how I can config my cluster config, so that it only talks to the master nodes. Thanks in advance.

**Comment by garima803** [comment]
@islanderman:  Did you find answer for your question as I am also trying to solve similar kind of issue.

**Comment by islanderman** [comment]
> @islanderman:  Did you find answer for your question as I am also trying to solve similar kind of issue.

I ended up upgrading the version number to v7 and rewrite some of the go-routine I had (as watchdog) and it worked fine.
