### ISSUE TITLE
连接池设计会导致连接在proxy的时候，出现某台proxy机器繁忙

### ISSUE THREAD

**Issue by leizihui** [go-redis/redis#1293]
我在使用集群版的云redis，云redis前置了proxy，在高并发的情况下，其中某台proxy会特别繁忙，cpu占用100%。其他proxy机器很空闲，我认为这是从coonPool中取出连接时导致的
idx := len(p.idleConns) - 1 ，在这个地方idx使用随机数应该会更好

**Comment by mazhan465** [comment]
显然这和连接池按什么顺序取没关系，是proxy的负载均衡算法不合适，比如用了原地址哈希，如果proxy负载均衡算法正常，连接池中的每条连接应该是随机对应一个后端的redis实例，顺序取和随机取连接没有任何区别

**Comment by gojuukaze** [comment]
应该就是上面说的那样-- 负载均衡算法选择的问题。  

不过上面的说法有点小错误，如果用ip哈希，你这个redis连接池的链接因为是同一个地址的，所以会连到同一台proxy。

**Comment by leizihui** [comment]
经过验证，是腾讯云的集群redis的proxy问题

**Comment by scroot** [comment]
腾讯云 好多技术细节问题，TCP高并发也有问题 , 现在不知道解决没有
