### ISSUE TITLE
Result() return redis: nil

### ISSUE THREAD

**Issue by yongjuntang** [go-redis/redis#1305]
RClient := redis.NewClient(&redis.Options{
		Addr:     host+":"+port, // use default Addr
		Password: "",               // no password set
		DB:       0,                // use default DB
	})        
pipe := RClient.Pipeline()
	pipe.ZRevRangeWithScores(cacheKey,0,2)
	pipe.ZRevRank(cacheKey,uidStr)
	pipe.ZScore(cacheKey,uidStr)
	cmders, err := pipe.Exec() //the err returned "redis:nil"
	if err != nil && err.Error() != "redis: nil" {
		return nil, nil, nil, err
	}

**Problem: pipe.Exec() returned "redis: nil"**

**Comment by ragnaros2046** [comment]
any progress?

**Comment by vmihailenco** [comment]
@ragnaros2046 see https://redis.uptrace.dev/#redisnil

**Comment by ragnaros2046** [comment]
> @ragnaros2046 see https://redis.uptrace.dev/#redisnil
Got it! But When I use HMGET to get a non-existing key,  it return err = nil not  redis: nil
