### ISSUE TITLE
NewClusterClient().Command()  return error:   redis: got 7 elements in COMMAND reply, wanted 6

### ISSUE THREAD

**Issue by dodo-luck** [go-redis/redis#1329]
/**********************env**********************/
go V1.14.2
redis V6.0.1
go-redis V7

/**********************code**********************/
package main

import (
	"fmt"
	"github.com/go-redis/redis/v7"
)

func main() {
	rdb := redis.NewClusterClient(&redis.ClusterOptions{
		Addrs: []string{":7000", ":7001", ":7002", ":7003", ":7004", ":7005"},
	})
	
	fmt.Println(rdb.Command())
}

/**********************************************/
 redis: got 7 elements in COMMAND reply, wanted 6

 why ?

**Comment by dodo-luck** [comment]
func call:    _process()  --> cmdInfo()  cmdSlot()  -->  cmdsInfo()  -->  Command()

func (c *ClusterClient) _process(ctx context.Context, cmd Cmder) error                                                 
func (c *ClusterClient) cmdInfo(name string) *CommandInfo          
func (c *ClusterClient) cmdsInfo() (map[string]*CommandInfo, error)
func (c cmdable) Command() *CommandsInfoCmd
func cmdSlot(cmd Cmder, pos int) int {
	if pos == 0 {
		return hashtag.RandomSlot()
	}
	firstKey := cmd.stringArg(pos)
	return hashtag.Slot(firstKey)
} 

This error causes the function(_process) to be slow . because  the return value of the function(cmdInfo) is nil ,  in that case, the function(func cmdSlot(cmd Cmder, pos int) int) arg (pos) will be 0.
不晓得咋回事0.0

**Comment by vmihailenco** [comment]
Should be fixed by https://github.com/go-redis/redis/pull/1357.
