### ISSUE TITLE
XReadGroup wrong command format

### ISSUE THREAD

**Issue by dselyuzhitskiy** [go-redis/redis#1330]
An error occurs when using XReadGroup command:

` ERR Unbalanced XREAD list of streams: for each stream key an ID or '$' must be specified`

It is because command should have ID or $ at the end: [https://redis.io/commands/xreadgroup](https://redis.io/commands/xreadgroup)

I think we can add IDs field of []string type for XReadGroupArgs struct, and if it is nil, add ">" to the end of command

**Comment by xuchenCN** [comment]
Take look the test code

`res, err := client.XReadGroup(&redis.XReadGroupArgs{
					Group:    "group",
					Consumer: "consumer",
					Streams:  []string{"stream", ">"},
				}).Result()`

**Comment by dselyuzhitskiy** [comment]
@xuchenCN  thanks a lot, i will do like this, but it is really implicit solution
