### ISSUE TITLE
`AUTH un pw` is attempted even on versions prior to 6.0

### ISSUE THREAD

**Issue by Bogdanp** [go-redis/redis#1338]
Cloud hosting providers like Heroku that offer hosted Redis tend to have bogus usernames in their `REDIS_URL` environment variables. Version 8 assumes that if a username is present in the options, it should issue an `AUTH username password` command instead of a plain `AUTH password`, but this breaks when run against versions of Redis prior to 6.0. Instead, I think the library should first determine the version of Redis it's connecting against and issue the appropriate `AUTH` command. Either that, or attempt to `AUTH` with the username and fall back to the password-only variant if it fails with the `ERR wrong number of arguments for 'auth' command` error.

In the mean time, the workaround is to explicitly set the `Username` to `""` after parsing the URLs from these providers:

```go
opt, err := redis.ParseURL(os.Getenv("REDIS_URL"))
opt.Username = ""
c := redis.NewClient(opt)
```

I can also understand if you chalk this up to just a breaking change from v7.

**Comment by gkorland** [comment]
@Bogdanp we are aware of this issue in Heroku Redis, but it's a bug in how the Redis URL is created on Heroku, I think it should've been fixed by now and new Redis 5 DBs don't have this issue anymore

**Comment by Bogdanp** [comment]
OK, that makes sense. Thanks!
