### ISSUE TITLE
v5 upgrade v7 ,HMSet  not support map[string]string

### ISSUE THREAD

**Issue by blackbeans** [go-redis/redis#1347]
Our project decide upgrade redis client from v5 to v7.But HMSet  not support map[string]string，
but in v5 it's running well. Redis.v7 hmset /hset only supports []string and map[string]interface{}，but HGetAll returns map[string]string，This bug has a big risk in codes.
So i suggest  hmset/hset  supports  map[string]string , so than avoid this risk .

```
func appendArgs(dst, src []interface{}) []interface{} {
	if len(src) == 1 {
		switch v := src[0].(type) {
		case []string:
			for _, s := range v {
				dst = append(dst, s)
			}
			return dst
		case map[string]interface{}:
			for k, v := range v {
				dst = append(dst, k, v)
			}
			return dst
		case map[string]string:
			for k, v := range v {
				dst = append(dst, k, v)
			}
			return dst
		}
	}

	dst = append(dst, src...)
	return dst


```

**Comment by monkey92t** [comment]
We have already supported map[string]string in v8, it seems we can close this issue.
