### ISSUE TITLE
Redundant requests for every command in ClusterClient

### ISSUE THREAD

**Issue by jonas0616** [go-redis/redis#1348]
After changing to ClusterClient, it could be observed that the request latency becomes much higher than before.

According to observation by tcpdump, every command triggers ClusterClient sends `AUTH`,  `CLUSTER SLOTS`, and `COMMAND`  requests to **ALL** redis servers before handling the real request. Furthermore, most of these redundant requests create new connections instead of reusing connections in the pools.

It could also find that the request is not sent to the server which is responsible for the key slot. There are a lot of `MOVED` responses, and the client needs to redirect the request to another redis server. If the request is randomly sent to the redis servers, it should not send `CLUSTER SLOTS` command before sending the real request.

**Comment by Neoysx** [comment]
I got the same problem, I see a lot of "COMMAND" requests when i run redis-cli in monitor mode.

**Comment by Neoysx** [comment]
> I got the same problem, I see a lot of "COMMAND" requests when i run redis-cli in monitor mode.

Problem solved, redis server renamed "command".

**Comment by vmihailenco** [comment]
This is a problem with Redis 6 which should be fixed by https://github.com/go-redis/redis/pull/1357. Only go-redis v7 and v8 were patched, v6 and earlier still have this problem with Redis 6.
