### ISSUE TITLE
How to get all keys or get all keys by pattern ?

### ISSUE THREAD

**Issue by solitarysp** [go-redis/redis#1350]
I want to get all key with one pattern ``` KeysGameOnline:*```
I using method Keys in commangds.go but result undefined.
![image](https://user-images.githubusercontent.com/20993683/83587074-5b060080-a578-11ea-83b6-99ea471673da.png)
How to get all keys or get all keys by pattern ?

**Comment by vmihailenco** [comment]
https://redis.uptrace.dev/get-all-keys/
