### ISSUE TITLE
govendor fetch github.com/go-redis/redis/v7 get empty folder

### ISSUE THREAD

**Issue by zhusihan-python** [go-redis/redis#1352]
hi, i'm trying to connect redis using go-redis, but I dont know where the ctx come from, most instructions to use go-redis didn't mention this parameter, when I'm trying to use a older version v7, with a command "govendor fetch github.com/go-redis/redis/v7", i just got an empty folder. I'm wondering do you still support v7 edition, or am I doing something wrong?any help would be appreciate.
![image](https://user-images.githubusercontent.com/23504604/83655030-7ad90b00-a5f0-11ea-856f-0f403afb241b.png)

**Comment by vmihailenco** [comment]
As govendor recommends - you have to use go modules - https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away
