### ISSUE TITLE
ClusterClient can't reconnect to clusters if all the cluster nodes IP changed

### ISSUE THREAD

**Issue by davidfu13** [go-redis/redis#1358]
Hi,

I wonder is there anyway to let ClusterClient reconnect to cluster nodes without restarting process if all the cluster nodes' IP change at the same time? Currently I have to restart my cluster client process to achieve that.

From the source code I believe it's because of that once the cluster client had resolved all the cluster nodes' IP successfully, the client will store the addresses and continue to use those IP to connect to the cluster.
The client might reload the cluster nodes' IP if at least one of the cluster nodes is connectable.
However, if all my cluster nodes' IP change at the same time, then the client can't no longer reach the cluster to reload the new cluster nodes IP. Therefore, it can't reconnect to cluster successfully until the process is restarted again and the server naming resolving procedure is re-run again.

Is there anyway to solve this kind of problem? Thanks for you help.

**Comment by xuchenCN** [comment]
LGTM +1

**Comment by vmihailenco** [comment]
I believe we did all we could in https://github.com/go-redis/redis/pull/1377. Closing since it is not clear what else can be done.
