### ISSUE TITLE
Error : /go/src/github.com/go-redis/redis/internal/proto/writer.go:16:2: undefined: io.StringWriter

### ISSUE THREAD

**Issue by yuvarajpalaniappan** [go-redis/redis#1369]
/go/src/github.com/go-redis/redis/internal/proto/writer.go:16:2: undefined: io.StringWriter

**Comment by vmihailenco** [comment]
Please upgrade your Go.

**Comment by JeevithaRamu** [comment]
@vmihailenco Is there any option to use old go-redis version instead of upgrading GO ?

**Comment by vmihailenco** [comment]
Sure, I don't have details though. I would use Go modules but they likely unavailable for you.

I've removed io.StringWriter from the master branch - if that is the only problem you should be fine.
