### ISSUE TITLE
'Ring' cannot authenticate passwords

### ISSUE THREAD

**Issue by devinsburke** [go-redis/redis#1370]
On v8-beta1, ring.go had 'depreciated features' removed. One of them was that password was transferred in the clientOptions() method from the RingOptions to the Options struct. As a result, when using a ring, an AUTH command is never sent even when a password was provided on the Ring declaration.

go-redis/cache seems to require the use of a Ring, but I can't use Cache at all now because I require a password on my redis server.

I can confirm that adding "Password: opt.Password," as line 124 in ring.go fixes the issue.

Why was this removed? What is the alternative?

**Comment by vmihailenco** [comment]
That is an overlook - thanks for fixing.
