### ISSUE TITLE
[v7.4.0] Redis EOF after 30 seconds of inactivity

### ISSUE THREAD

**Issue by ddouglas** [go-redis/redis#1373]
Hello

I was have this issue with v0.6.*. I did research the error with this package and found #846. I've followed the advice that you left in that thread but I am still having the issue.

My Setup:
Go Http Server hosting a GraphQL API. First request for a record that is not in Redis is always successful. I cache the record in Redis for 60 minutes. If the user reruns the GraphQL query after 30 seconds an EOF is returned from Redis. If the same query is run again, the record is returned, from redis

Current Timeout configuration in Redis
```
 redis-cli -p 42500 config get timeout
1) "timeout"
2) "10"
```

Current Version in Go.mod:
```
github.com/go-redis/redis/v7 v7.4.0
```

Current Client configuration
```
redisClient := redis.NewClient(&redis.Options{
	Addr:       cfg.RedisAddr,
	MaxRetries: 3,
})
```

My timeout is currently set to 10 seconds. I am not sure if this is to low or not, but I do know that this is higher than the default outlined in the comments for Read and WriteTimeout.

I finally figured out earlier tonight what this EOF error was  and that it was coming from Redis today. Now i am not sure what to do to fix it. I am open to any recommendations.

I will point out that this app runs inside of a docker container and the redis server is running on the host server. That is the only that that I was able to think of based on your comment in #846 

> But overall I would start with trying to isolate & reproduce this problem using small app. EOF every 30 seconds suggests you are doing something very wrong or network is very unreliable. I wonder what is the latency of PING command?

If you are interested in how it is being used
https://github.com/eveisesi/neo/blob/master/app/app.go#L93

Log Entries:

```
time="2020-06-12T03:11:05Z" level=info msg="request complete" << Document delivered successfully
time="2020-06-12T03:11:56Z" level=error msg="failed to fetch km from redis" error=EOF key="neo:killmail:84910181:86baad59a13548555a6a58de2d72d8862eb3e471" 
time="2020-06-12T03:11:56Z" level=info msg="request complete" << Document delivered successfully

```

**Comment by ddouglas** [comment]
If you are interested in how it is being used
https://github.com/eveisesi/neo/blob/master/app/app.go#L93

**Comment by vmihailenco** [comment]
```
 redis-cli -p 42500 config get timeout
1) "timeout"
2) "10"
```

This means that Redis closes connection after 10 seconds of inactivity. But go-redis will keep connection for `IdleTimeout = 5min`. I think you want to increase Redis timeout to 6 minutes or decrease go-redis IdleTimeout.

**Comment by ddouglas** [comment]
I increased redis timeout to `2 min` and set  `idletimeout` to `2 min` as well with a check every `10 seconds`. Thank you for your assistance sir. I was truely stumped.
