### ISSUE TITLE
[Doc] Where is `ctx` comes from??

### ISSUE THREAD

**Issue by mitnk** [go-redis/redis#1374]
There is the broken updates (from v5 to v7? I don't know). So I'm re-read the doc "get started" section of https://redis.uptrace.dev/. But it also show broken example, no way to get started :(

How do you use `ctx` without define it?
![image](https://user-images.githubusercontent.com/177049/84589666-ba122200-ae62-11ea-96a3-de04f7b4de2e.png)

**Comment by mitnk** [comment]
As another issue mentioned, does it really make sense to pass a context every time issuing a command? Not intuitive to me.

**Comment by mitnk** [comment]
Also it would be great to add the date time in changelogs, so that users can see *when* new changes are added.

**Comment by mitnk** [comment]
And seems the `ctx` var in current README also comes from no where. Did I miss a big part of any (Go) knowledge here?

**Comment by mcg-web** [comment]
Seem that [the solution is in example](https://github.com/go-redis/redis/blob/master/example_test.go#L13)
