### ISSUE TITLE
Implement LPOS command

### ISSUE THREAD

**Issue by nektro** [go-redis/redis#1378]
https://redis.io/commands/lpos

**Comment by nektro** [comment]
> Available since 6.0.6.

Just added.

**Comment by nektro** [comment]
https://stackoverflow.com/a/9324783 I'm surprised this didn't get added so much sooner.

**Comment by nektro** [comment]
I was going to implement this myself, but both https://github.com/antirez/redis/releases and https://hub.docker.com/_/redis show `6.0.5` as the most recent version.

**Comment by vmihailenco** [comment]
Closed by https://github.com/go-redis/redis/pull/1556
