### ISSUE TITLE
ClusterClient can not connect to single node runs with cluster-enabled = false

### ISSUE THREAD

**Issue by albertforweb** [go-redis/redis#1382]
**### what is the difference between ClusterClient and Client ?**

when redis instances run in cluster mode, below code works as expected.

	option := redis.ClusterOptions{
		Addrs:    []string{CACHE_SERVER},
		Password: CACHE_SERVER_PASSWORD,
	}

	redisClusterClient = redis.NewClusterClient(&option)
	pong, err := redisClusterClient.Ping().Result()

however, when run it against a single redis node with "cluster-enabled = false" in config file (which is default)

then the error shows:

Err :  ERR This instance has cluster support disabled

### how to make the same code work for both Redis setup (cluster mode and single node with cluster-enabled = false ) ?

Thanks

**Comment by swdee** [comment]
You can either create a wapper Interface for `NewClusterClient` and `NewClient` or use the [UniversalClient](https://pkg.go.dev/github.com/go-redis/redis/v8?tab=doc#NewUniversalClient)

**Comment by vmihailenco** [comment]
What @swdee said is the only option.

>ERR This instance has cluster support disabled

This comes from Redis itself, not from go-redis. Therefore it is not a go-redis problem.
