### ISSUE TITLE
XRead returns error if result set ie empty

### ISSUE THREAD

**Issue by DeepDiver1975** [go-redis/redis#1383]
When calling client.XReadStreams on an empty stream I do get an error with the string "redis: nil".

In cases where e.g. the redis server is not reachable the error holds "EOF" or "dial tcp 127.0.0.1:6379: connect: connection"

To me an empty stream is not really an error - the other case for sure is.

Is this a bug or am I miss taken?

THX

**Comment by DeepDiver1975** [comment]
:ping_pong:

**Comment by vmihailenco** [comment]
This error (redis.Nil) is returned by Redis Server - you can check that by using `redis-cli`. It may be inconvenient but we don't hide errors returned by Redis iteself.

**Comment by DeepDiver1975** [comment]
Tux
