### ISSUE TITLE
v7 transaction pipeline returns incorrect results sometimes

### ISSUE THREAD

**Issue by ambersmit** [go-redis/redis#1386]
Trying to upgrade to v7.4.0 from v6.15.2 but I am running into issues with the new transaction pipeline code. 

When executing the transaction pipeline, I am sometimes getting the MULTI StatusCmd back in our result set now. Before, I would always just get back the BoolCmds. Now it seems that in certain situations I lose one of the BoolCmds I should be getting back and instead get a StatusCmd back of the MULTI command.  

I am using the Client in redis.go and initializing the transactional pipeline by calling the func TxPipeline() on that client. 
Using that pipeline, I then add each item. See example code below. 

```
pipe := client.TxPipeline()

// for each item I issue the SetNX
pipe.SetNX(key, value, expiration)

response, err := pipe.Exec()
```

If no error is returned, I then loop through the response array of []redis.Cmder's. This array is where I am having the issue. Before it would always just return BoolCmd's where as now it seems to sometimes return the first item as the StatusCmd from the MULTI cmd. So, when I had 6 items to set in redis, I got back 6 items in the response array but the first would be StatusCmd and the remaining 5 would be BoolCmds. I'd be missing one BoolCmd and have an extra StatusCmd that I don't expect.

It doesn't seem to always happen though... another time when I had 7 items to set in redis, I correctly got back all 7 items and they were all BoolCmds. 

Additionally, from my testing I believe this might be the problem commit: 218b17f0fc567ce62f7d6d0607caff1d8100354f 
When I test with commit 709e543f16bf20d4f6df33bc7d24fb4b6a0991bc I don't see this issue.

**Comment by jshore1296** [comment]
Another developer in our org found the root cause here - we were attempting to cast the response before checking to see if we got an error.  It seems that when an error is returned, we get back a StatusCmd, but if there is no error, we get a BoolCmd.

**Comment by ambersmit** [comment]
Reopening. It does not look like our changes that @jshore1296 mentioned have fixed this. Those changes were related to a different part of the code.

**Comment by sgp** [comment]
@vmihailenco I think I have a test + fix that takes care of this issue. PR is up above.
