### ISSUE TITLE
No support set keepTTL?

### ISSUE THREAD

**Issue by 357711589** [go-redis/redis#1393]
How should  I do?

https://redis.io/commands/set
>= 6.0: Added the KEEPTTL option.

**Comment by x1nchen** [comment]
like this 

```
err := rdb.Do("set", key, value, "keepttl").Err()
if err != nil {}
```

more refer to this discussion on https://github.com/go-redis/redis/pull/1439

**Comment by 357711589** [comment]
> like this
> 
> ```
> err := rdb.Do("set", key, value, "keepttl").Err()
> if err != nil {}
> ```
> 
> more refer to this discussion on #1439

OK Thanks

**Comment by vmihailenco** [comment]
@x1nchen what about using `-1` expiration in `Set` command as indicator for `KEEPTTL`? E.g. `Set(ctx, "foo", "bar", -1)` means `SET foo bar KEEPTTL`.

Adding separate command for KEEPTTL is problematic since we need 3 of them:
- SetKeepTTL
- SetKeepTTLNx
- SetKeepTTLEx

**Comment by x1nchen** [comment]
@vmihailenco 

> Adding separate command for KEEPTTL is problematic since we need 3 of them:

> SetKeepTTL
> SetKeepTTLNx
> SetKeepTTLEx

Yes. You're right!

**Comment by x1nchen** [comment]
@vmihailenco 

> what about using -1 expiration in Set command as indicator for KEEPTTL? E.g. Set(ctx, "foo", "bar", -1) means SET foo bar KEEPTTL.

Oh, this mean is too implicit for users. I prefer to add new 3 apis just like you introduced above.

**Comment by vmihailenco** [comment]
It could be

```redis
const KeepTTL = -1
Set(ctx, "foo", "bar", KeepTTL)
SetNX(ctx, "foo", "bar", KeepTTL)
SetXX(ctx, "foo", "bar", KeepTTL)
```

What do you think?

**Comment by x1nchen** [comment]
> It could be
> 
> ```go
> const KeepTTL = -1
> Set(ctx, "foo", "bar", KeepTTL)
> SetNX(ctx, "foo", "bar", KeepTTL)
> SetXX(ctx, "foo", "bar", KeepTTL)
> ```
> 
> What do you think?

You mean you want to implement this feature as the code shows below?

```
func (c cmdable) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) *StatusCmd {
	args := make([]interface{}, 3, 5)
	args[0] = "set"
	args[1] = key
	args[2] = value
	if expiration > 0 {
		if usePrecise(expiration) {
			args = append(args, "px", formatMs(ctx, expiration))
		} else {
			args = append(args, "ex", formatSec(ctx, expiration))
		}
	}

        if expiration == -1 {
		args = append(args, "keepttl")
	}

	cmd := NewStatusCmd(ctx, args...)
	_ = c(ctx, cmd)
	return cmd
}
```

**Comment by vmihailenco** [comment]
Exactly except that we also add new constant

```
const KeepTTL = -1

....

        if expiration == KeepTTL {
		args = append(args, "keepttl")
	}
...


```

**Comment by x1nchen** [comment]
> Exactly except that we also add new constant
> 
> ```go
> const KeepTTL = -1
> 
>         if expiration == KeepTTL {
> 		args = append(args, "keepttl")
> 	}
> ...
> ```

OK  but we also need to update docs to publish this kind of usage.

**Comment by x1nchen** [comment]
@vmihailenco I created another PR for this issue. Please review if you have time.

**Comment by vmihailenco** [comment]
Fixed by https://github.com/go-redis/redis/pull/1499
