### ISSUE TITLE
go-redis v8.0.0-beta.5 panic on Redis Cluster 6.0.5

### ISSUE THREAD

**Issue by gferreux** [go-redis/redis#1401]
Hi, here is the panic:

`panic: runtime error: invalid memory address or nil pointer dereference
 -> github.com/go-redis/redis/v8.(*ClusterClient)._process
 ->   /go/pkg/mod/github.com/go-redis/redis/v8@v8.0.0-beta.5/cluster.go:776
    github.com/go-redis/redis/v8.(*ClusterClient).process
      /go/pkg/mod/github.com/go-redis/redis/v8@v8.0.0-beta.5/cluster.go:738
    github.com/go-redis/redis/v8.hooks.process
      /go/pkg/mod/github.com/go-redis/redis/v8@v8.0.0-beta.5/redis.go:57
    github.com/go-redis/redis/v8.(*ClusterClient).Process
      /go/pkg/mod/github.com/go-redis/redis/v8@v8.0.0-beta.5/cluster.go:734
    github.com/go-redis/redis/v8.cmdable.Get
      /go/pkg/mod/github.com/go-redis/redis/v8@v8.0.0-beta.5/commands.go:671`

- go-redis: v8.0.0-beta.5
- redis-server: 6.0.5
- client config: redis://redis-shard0-0.redis.redis:6379,redis-shard0-1.redis.redis:6379,redis-shard0-2.redis.redis:6379,redis-shard1-0.redis.redis:6379,redis-shard1-1.redis.redis:6379,redis-shard1-2.redis.redis:6379,redis-shard2-0.redis.redis:6379,redis-shard2-1.redis.redis:6379,redis-shard2-2.redis.redis:6379,redis-shard3-0.redis.redis:6379,redis-shard3-1.redis.redis:6379,redis-shard3-2.redis.redis:6379,redis-shard4-0.redis.redis:6379,redis-shard4-1.redis.redis:6379,redis-shard4-2.redis.redis:6379?idletimeout=300&poolsize=50&pooltimeout=30&routebylatency=true
- server config: redis-cluster with 5 shards and 2 replicas each
- context: when a node goes down

Note: client config with `routerandomly=true` do not panic

**Comment by vmihailenco** [comment]
Can you provide a minimal repro?
