### ISSUE TITLE
How to store JSON data in Redis 

### ISSUE THREAD

**Issue by gholami-mohammad** [go-redis/redis#1406]
Please take a look at this topic: [https://redislabs.com/redis-best-practices/data-storage-patterns/json-storage/](https://redislabs.com/redis-best-practices/data-storage-patterns/json-storage/)

As you can see, there is a way to store JSON data in Redis using ReJSON. How do we do it using go-redis?

**Comment by gkorland** [comment]
You should check https://github.com/nitishm/go-rejson/ which uses go-redis client.
