### ISSUE TITLE
redis: discarding bad PubSub connection: redis: ping timeout

### ISSUE THREAD

**Issue by ramfoodpanda** [go-redis/redis#1407]
We are getting this ping timeout message after couple of hours from the initial deployment. 

We initialize the client with following code:
 
`func NewClient(address string, readTimeout time.Duration, writeTimeout time.Duration) *redis.Client {
	return redis.NewClient(&redis.Options{
		Addr:         address,
		DB:           0, // use default DB
		ReadTimeout:  readTimeout,
		WriteTimeout: writeTimeout,
	})
}`

we traced this error to 
https://github.com/go-redis/redis/blob/3d03b1fa6a1ed0775d4b032861da0637b45437da/pubsub.go#L475.

**Comment by ramfoodpanda** [comment]
`case <-timer.C:
				pingErr := c.Ping(ctx)
				if healthy {
					healthy = false
				} else {
					if pingErr == nil {
						pingErr = errPingTimeout
					}
					c.mu.Lock()
					c.reconnect(ctx, pingErr)
					healthy = true
					c.mu.Unlock()
				}`

i would like to understand why we are not checking `pingErr := c.Ping(ctx)` pingErr here ? , instead of getting actual error we are getting ping timeout error , if we can get to know underlying error that caused ping timeout, it would be easier for us to check ?

**Comment by vmihailenco** [comment]
The read [the code](https://github.com/go-redis/redis/blob/3d03b1fa6a1ed0775d4b032861da0637b45437da/pubsub.go#L475) as use `pingErr` if it is not nil.

**Comment by ramfoodpanda** [comment]
@vmihailenco  Thanks for your response.
do you have any insights on how we can troubleshoot such configuration that would help us

**Comment by vmihailenco** [comment]
`redis: ping timeout` means that there were no messages from Redis for 30 seconds. That may happen if there are problems with network and/or Redis.

If there are no `channel is full` logs - I don't know what can be done.
