### ISSUE TITLE
Need an example on how you can cancel a blocking read

### ISSUE THREAD

**Issue by zt9** [go-redis/redis#1408]
Creating a new question so as to not hijack another thread - I am having a similar problem [mentioned here](https://github.com/go-redis/redis/issues/1196)- the BRPOP is blocking, but when I cancel the context, nothing seems to happen. I see that @calebdoxsey has a fix for this, but I am not sure how to use it. Would you be able to provide an example?

Here is what I understand:

- for whatever reason, the blocking command cannot be cancelled in this client
- to deal with this, there is a hack that you can use to kill the underlying connection. This is done using cancelWithSetDeadline().
- let's say you have a redis client `rdb`, you get a connection using a background context using `rdb.Conn(context.Background())` (`Conn` is needed to run `cancelWithSetDeadline()`) - How do you relate this to the `rdb` client to run the `BRPOP` command? I am in a knot, would be grateful for an example that unblocks a blocking command so I can untangle myself.

**Comment by zt9** [comment]
I tried this go get command 

`go get github.com/go-redis/redis/v8@84229f069e58a2919cee7992654f6ef59c489758`

and got the following error:
`go get github.com/go-redis/redis/v8@84229f069e58a2919cee7992654f6ef59c489758: github.com/go-redis/redis/v8@84229f069e58a2919cee7992654f6ef59c489758: invalid version: unknown revision 84229f069e58a2919cee7992654f6ef59c489758`

**Comment by vmihailenco** [comment]
`context.WithCancel` currently is not supported.

>I am trying to pull in this fix I tried this go get command

That revision is not in this repo - you need to use @calebdoxsey clone if it is still available.

Closing since this is tracked by https://github.com/go-redis/redis/issues/1196
