### ISSUE TITLE
v8: Heavy-weight dependencies

### ISSUE THREAD

**Issue by kyleconroy** [go-redis/redis#1409]
I've been trying to integrate go-redis into my application, but am running into dependency problems. After initializing a fresh Go module and installing v8, I was surprised by the breadth and scope of the required dependencies.

```
go mod init github.com/kyleconroy/redis-mod
go get github.com/go-redis/redis/v8
```

Here's the resulting [go.sum](https://gist.github.com/kyleconroy/9268906c2ddb4bc669bb3eb4cc6d85c4), which list 60 packages:

```
cloud.google.com/go
dmitri.shuralyov.com/gpu/mtl
github.com/BurntSushi/toml
github.com/BurntSushi/xgb
github.com/DataDog/sketches-go
github.com/OneOfOne/xxhash
github.com/benbjohnson/clock
github.com/census-instrumentation/opencensus-proto
github.com/cespare/xxhash
github.com/client9/misspell
github.com/cncf/udpa/go
github.com/davecgh/go-spew
github.com/dgryski/go-rendezvous
github.com/envoyproxy/go-control-plane
github.com/envoyproxy/protoc-gen-validate
github.com/fsnotify/fsnotify
github.com/go-gl/glfw/v3.3/glfw
github.com/go-redis/redis
github.com/go-redis/redis/v8
github.com/golang/glog
github.com/golang/mock
github.com/golang/protobuf
github.com/google/go-cmp
github.com/google/gofuzz
github.com/hpcloud/tail
github.com/kr/pretty
github.com/kr/pty
github.com/kr/text
github.com/onsi/ginkgo
github.com/onsi/gomega
github.com/opentracing/opentracing-go
github.com/pmezard/go-difflib
github.com/prometheus/client_model
github.com/spaolacci/murmur3
github.com/stretchr/objx
github.com/stretchr/testify
go.opentelemetry.io/otel
golang.org/x/crypto
golang.org/x/exp
golang.org/x/image
golang.org/x/lint
golang.org/x/mobile
golang.org/x/mod
golang.org/x/net
golang.org/x/oauth2
golang.org/x/sync
golang.org/x/sys
golang.org/x/text
golang.org/x/tools
golang.org/x/xerrors
google.golang.org/appengine
google.golang.org/genproto
google.golang.org/grpc
google.golang.org/protobuf
gopkg.in/check.v1
gopkg.in/fsnotify.v1
gopkg.in/tomb.v1
gopkg.in/yaml.v2
gopkg.in/yaml.v3
honnef.co/go/tools
```

Many of these aren't surprising, but a quite a few stood out to me:

- cloud.google.com/go
- dmitri.shuralyov.com/gpu/mtl
- github.com/BurntSushi/xgb
- google.golang.org/appengine
- google.golang.org/grpc
- gopkg.in/fsnotify.v1
- golang.org/x/mobile
- github.com/go-gl/glfw/v3.3/glfw
- github.com/envoyproxy/go-control-plane

Why does this package need access to graphics packages (OpenGL, Metal, and X)?

## Environment

This was tested on MacOS 10.14.6 and Go 1.14.3

```
$ go version
go version go1.14.3 darwin/amd64
```

**Comment by kyleconroy** [comment]
Alright, after doing a little more digging, the problem seems to stem from entries in go.sum. v8 doesn't depend on most of the entries in go.sum, but I believe their presence causes issues.

**Comment by kyleconroy** [comment]
The output of [go mod graph](https://gist.github.com/kyleconroy/6c86769d349af8712a696a6a48d92b8e) explains the origins of each dependency. Using that output, it becomes clear how some of the stranger packages show up. The two worst offenders are `golang.org/x/exp` and `go.opentelemetry.io/otel`

```
golang.org/x/exp@v0.0.0-20200513190911-00229845015e dmitri.shuralyov.com/gpu/mtl@v0.0.0-20190408044501-666a987793e9
golang.org/x/exp@v0.0.0-20200513190911-00229845015e github.com/BurntSushi/xgb@v0.0.0-20160522181843-27f122750802
golang.org/x/exp@v0.0.0-20200513190911-00229845015e github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200222043503-6f7a984d4dc4
golang.org/x/exp@v0.0.0-20200513190911-00229845015e golang.org/x/image@v0.0.0-20190802002840-cff245a6509b
golang.org/x/exp@v0.0.0-20200513190911-00229845015e golang.org/x/mobile@v0.0.0-20190719004257-d2bd2a29d028
golang.org/x/exp@v0.0.0-20200513190911-00229845015e golang.org/x/mod@v0.1.1-0.20191107180719-034126e5016b
golang.org/x/exp@v0.0.0-20200513190911-00229845015e golang.org/x/sync@v0.0.0-20190423024810-112230192c58
golang.org/x/exp@v0.0.0-20200513190911-00229845015e golang.org/x/sys@v0.0.0-20191001151750-bb3f8db39f24
golang.org/x/exp@v0.0.0-20200513190911-00229845015e golang.org/x/tools@v0.0.0-20200207183749-b753a1ba74fa
golang.org/x/exp@v0.0.0-20200513190911-00229845015e golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898
```

```
go.opentelemetry.io/otel@v0.7.0 github.com/DataDog/sketches-go@v0.0.0-20190923095040-43f19ad77ff7
go.opentelemetry.io/otel@v0.7.0 github.com/benbjohnson/clock@v1.0.3
go.opentelemetry.io/otel@v0.7.0 github.com/davecgh/go-spew@v1.1.1
go.opentelemetry.io/otel@v0.7.0 github.com/golang/protobuf@v1.4.2
go.opentelemetry.io/otel@v0.7.0 github.com/google/go-cmp@v0.5.0
go.opentelemetry.io/otel@v0.7.0 github.com/google/gofuzz@v1.0.0
go.opentelemetry.io/otel@v0.7.0 github.com/kr/pretty@v0.1.0
go.opentelemetry.io/otel@v0.7.0 github.com/opentracing/opentracing-go@v1.1.1-0.20190913142402-a7454ce5950e
go.opentelemetry.io/otel@v0.7.0 github.com/stretchr/testify@v1.6.1
go.opentelemetry.io/otel@v0.7.0 google.golang.org/genproto@v0.0.0-20191009194640-548a555dbc03
go.opentelemetry.io/otel@v0.7.0 google.golang.org/grpc@v1.30.0
go.opentelemetry.io/otel@v0.7.0 gopkg.in/check.v1@v1.0.0-20190902080502-41f04d3bba15
```

I'm not sure what to do about the `go.opentelemetry.io/otel` package, but it looks like the only package used from `golang.org/x/exp` is `rand`. Any reason that's used instead of the stdlib rand package?

**Comment by vmihailenco** [comment]
I am not 100% sure, but I believe Go just records all dependencies it downloads - even if they are NOT used to build a binary / production build. It is done so to have version info to resolve version conflicts that may happen later Therefore it does not look productive to worry about extra entries in go.mod. They should not cause any problems.

**Comment by cemremengu** [comment]
Can we opt out of telemetry? Is this a temporary thing for the beta?

**Comment by kyleconroy** [comment]
> Therefore it does not look productive to worry about extra entries in go.mod. They should not cause any problems.

The reason I opened this issue is because the extra entries do cause issues. In my case, I depended on a very old version of `cloud.google.com/go`. I couldn't use v8 of go-redis without changing other parts of applications that have nothing to do with the go-redis package.

**Comment by kyleconroy** [comment]
> Can we opt out of telemetry? Is this a temporary thing for the beta?

@cemremengu a maintainer can correct me, but I believe the `go.opentelemetry.io/otel` package is used to instrument go-redis so that it can emit tracing information. A end-user would configure an OpenTelemetry exporter to forward traces to their tracing system of choice.

The go-redis package is not collecting nor sending telemetry data to a third-party

**Comment by vmihailenco** [comment]
>The go-redis package is not collecting nor sending telemetry data to a third-party

Yes, it is opt-in and only active after adding OpenTelemetry hook and configuring exporter - see https://redis.uptrace.dev/tracing/

>I depended on a very old version of cloud.google.com/go

Understood. In ideal world cloud.google.com/go should provide 2 different major versions via Go modules - but we are not there yet :)

**Comment by kyleconroy** [comment]
> In ideal world cloud.google.com/go should provide 2 different major versions via Go modules

I guess I have a different perspective. In my ideal world, go-redis wouldn't depend on cloud.google.com/go in the first place. I've opened an issue on the otel package to solve the issue.
