### ISSUE TITLE
Log with context to associate all log by traceID

### ISSUE THREAD

**Issue by liuximu** [go-redis/redis#1411]
when we want trace request, we find we can't associate the request access log to redis log:
- all redis client use one Logging
- the log info without context(we want solve it)

in our team, we pass context.Context which carry traceID to logger, then we can get log content like:
```
access.log
trace_id=123 client_ip=127.0.0.1 more info

mysql.log
trace_id=123 sql="udpate a..." more info
```

how about redis log just like mysql log ?

```
type Logging interface {
	Printf(format string, v ...interface{})

        // vs

	Printf(ctx context.Context, format string, v ...interface{})
}
```

**Comment by vmihailenco** [comment]
Agreed. Can you send a PR?
