### ISSUE TITLE
redis: connection pool timeout

### ISSUE THREAD

**Issue by unidbaas** [go-redis/redis#1421]
this problem occurs when multiple goroutines are started in a concurrent scenario

**Comment by vmihailenco** [comment]
That describes almost every Go program.

**Comment by unidbaas** [comment]
so only can execute a pipeline synchronously, but not asynchronously？？？

**Comment by chjiyun** [comment]
i also have this problem, i need to insert 100 million data to redis bloom filter, and start 10000 goroutines  synchronously
