### ISSUE TITLE
Set without expiration

### ISSUE THREAD

**Issue by Annonomus-Penguin** [go-redis/redis#143]
For this function:

    func (c *Client) Set(key string, value interface{}, expiration time.Duration) *StatusCmd

Is there a way to set without having an expiration time as a really far time from now? Will nil work?

**Comment by vmihailenco** [comment]
`expiration=0` means no expiration. So if you don't want key to expire use:

```
cl.Set("key", "value", 0)
```

**Comment by Annonomus-Penguin** [comment]
Thank you. I couldn't find that anywhere in the docs.

**Comment by vmihailenco** [comment]
Fair point. Tried to address with https://github.com/go-redis/redis/pull/144
