### ISSUE TITLE
redis.SetLogger

### ISSUE THREAD

**Issue by kamly** [go-redis/redis#1433]
can i use redis.SetLogger show debug mesage? 

like `gorm.LogMode(true)`

**Comment by vmihailenco** [comment]
I don't think so. Perhaps you are looking for https://redis.io/commands/monitor

**Comment by kamly** [comment]
i want is that it can show debug message when i developing .  

eg. when i set `gorm.LogMode(true)` ,  i can see debug messsage ( redis >  set xx xx ) in cli
