### ISSUE TITLE
What will happen if configure an wrong redis cluster ip address?

### ISSUE THREAD

**Issue by canhe890** [go-redis/redis#1435]
Hi all!
I wonder what will happen if the cluster ip address configured
like this:
10.10.0.10:6379(a correct redis node ip addr),192.168.0.10:6379(an ip addr from another redis cluster)
or
10.10.0.10:6379(a correct redis node ip addr),172.16.0.10:6379(a wrong ip addr)

It seems that the client only uses the first ip address?
thanks!

**Comment by vmihailenco** [comment]
go-redis uses supplied adresses to call https://redis.io/commands/cluster-nodes. Then it uses addresses returned by cluster nodes.
