### ISSUE TITLE
Failed import with go 1.13+

### ISSUE THREAD

**Issue by Elojah** [go-redis/redis#1450]
Hello,

I'm trying to upgrade a project to redis v8 with context, i use go 1.13 on my machine and go 1.13 is specified in `go.mod`

`> go mod tidy`

```	github.com/go-redis/redis/v8 imports
	github.com/dgryski/go-rendezvous tested by
	github.com/dgryski/go-rendezvous.test imports
	hash/maphash: malformed module path "hash/maphash": missing dot in first path element
```
related to https://github.com/golang/go/issues/40067

Does this mean go-redis v8 can't be imported with go 1.13+ ?

Thanks

**Comment by vmihailenco** [comment]
Please try v8.0.0-beta.8. This should be already fixed by https://github.com/dgryski/go-rendezvous/commit/9f7001d12a5f0021fd3283525f888b5814ccee27
