### ISSUE TITLE
Redis (3.199) GEO functions

### ISSUE THREAD

**Issue by alexander-vasilenko** [go-redis/redis#146]
Hello!
Here http://redis.io/commands/geoadd we've several new geoxxx commands.
It would be cool to support them by go-redis...
Opinions?

**Comment by dim** [comment]
Sure, can you please submit a PR with tests? There is plenty of examples in
commands.go you can probably 'recycle'. Let us know if you get stuck.

**Comment by vmihailenco** [comment]
As @dim said we will accept PR. Otherwise I will add GEO commands myself when they are available in stable Redis version.

**Comment by icha024** [comment]
Got a PR in for GEOADD and GEORADIUS: https://github.com/icha024/redis

The other GEO commands seem to be a derivative of GEORADIUS, will add those soon.

**Comment by vmihailenco** [comment]
AFAIK @icha024 added all geo commands. Closing.
