### ISSUE TITLE
BRPop、BLPop、RPushX …… Only execute the first one when operating multiple keys

### ISSUE THREAD

**Issue by lisiyu88** [go-redis/redis#1465]
example：

    fmt.Println(client.BRPop(time.Duration(3)*time.Second, "TestList", "TestList1").Val())
    ==>
    []string{"TestList", "world"}

Only execute the first one，But，BRPop allows multiple keys，Why is this happening?

**Comment by git-hulk** [comment]
maybe you should have a look at these command behaviors at https://redis.io/command

**Comment by rbg** [comment]
Specifically : https://redis.io/commands/blpop#what-key-is-served-first-what-client-what-element-priority-ordering-details

HTH!

**Comment by lisiyu88** [comment]
![image](https://user-images.githubusercontent.com/26218057/100405873-77a27180-309f-11eb-8d76-ae1945aa33da.png)

This paragraph solved my doubts, thank you very much！
