### ISSUE TITLE
Setting timeout does not seem to have an effect

### ISSUE THREAD

**Issue by jameskyle** [go-redis/redis#147]
When setting timeout options, it doesn't seem to effect the actual dial timeout. For example:

        glog.Infoln("Setting timeout to ", time.Duration(60*5)*time.Second

	client = redis.NewClient(&redis.Options{
		Addr:        "localhost:31600",
		Password:     "",
		DB:           0,
		DialTimeout:  time.Duration(60*5)*time.Second,
		ReadTimeout:  time.Duration(60*5)*time.Second,
		WriteTimeout: time.Duration(60*5)*time.Second,
	})
        _, _ := client.Pong().Result()

Assuming no Redis server is running at all, this should take 5m to timeout if I'm interpreting the docs right. But when I execute:

    % time go run main.go 

I get

    I0810 15:17:09.897471 43124 main.go:22] Setting timeouts to:  5m0s
     dial tcp 172.31.2.11:31600: operation timed out
    go runmain.go -logtostderr 0.33s user 0.08s system 0% cpu 1:15.75 total

So only 1m15s.

**Comment by jameskyle** [comment]
Answering my own ticket: This is likely the result of a kernel tcp timeout which overrides this value which behaves like a maximum. From the net/#Dialer docs

        // With or without a timeout, the operating system may impose
        // its own earlier timeout. For instance, TCP timeouts are
        // often around 3 minutes.

**Comment by vmihailenco** [comment]
:thumbsup:
