### ISSUE TITLE
No MaxRetries field in FailoverOptions struct

### ISSUE THREAD

**Issue by arnaudbriche** [go-redis/redis#148]
HI,

I noticed that there is a MaxRetries field in the Options struct, but not in the FailoverOptions.
Is this deliberate ? And if so, could you explain why you choose to not implement auto-retry with
a failover client ?

**Comment by vmihailenco** [comment]
Hi,

Sorry, I missed this issue.

`MaxRetries` was added after `FailoverClient`, so this is simply an overlook. Also you probably have to use new `ClusterClient` with Redis Cluster, which supports `MaxRedirects` option.
