### ISSUE TITLE
Memory Usage keeps on increasing

### ISSUE THREAD

**Issue by akshayvijapur** [go-redis/redis#1482]
Hi Team,

I am using redis-client to connect to redis and do some operations. I am seeing that memory size of the program keeps on increasing. i tried to do pprof.
1.  go tool pprof --alloc_space heap.out

Showing nodes accounting for 1.90GB, 91.70% of 2.07GB total
Dropped 87 nodes (cum <= 0.01GB)
Showing top 10 nodes out of 61
      flat  flat%   sum%        cum   cum%
    0.92GB 44.47% 44.47%     1.31GB 63.31%  github.com/go-redis/redis/v8.stringInterfaceMapParser
    0.44GB 21.32% 65.79%     0.44GB 21.32%  github.com/go-redis/redis/v8/internal/proto.(*Reader).readStringReply
    0.15GB  7.12% 72.90%     0.15GB  7.12%  github.com/godror/godror/dsn.newParamsArray (inline)
    0.09GB  4.24% 77.15%     1.58GB 76.54%  github.com/go-redis/redis/v8.cmdable.XRange
    0.08GB  3.75% 80.90%     0.08GB  3.75%  github.com/go-redis/redis/v8.NewXMessageSliceCmd (inline)
    0.07GB  3.47% 84.36%     0.12GB  5.92%  github.com/godror/godror/dsn.paramsArray.WriteTo
    0.06GB  2.83% 87.19%     1.40GB 67.67%  github.com/go-redis/redis/v8.xMessageSliceParser
    0.04GB  1.96% 89.15%     0.04GB  1.96%  strings.(*Builder).Write
    0.03GB  1.60% 90.76%     0.04GB  2.08%  github.com/godror/godror.(*statement).bindVars
    0.02GB  0.94% 91.70%     0.33GB 15.91%  github.com/godror/godror.(*conn).initTZ

2.  go tool pprof heap.out

Showing nodes accounting for 2052.21kB, 100% of 2052.21kB total
Showing top 10 nodes out of 37
      flat  flat%   sum%        cum   cum%
    1028kB 50.09% 50.09%     1028kB 50.09%  bufio.NewReaderSize (inline)
  512.19kB 24.96% 75.05%   512.19kB 24.96%  runtime.malg
  512.02kB 24.95%   100%   512.02kB 24.95%  github.com/go-redis/redis/v8/internal/proto.(*Reader).readStringReply
         0     0%   100%     1028kB 50.09%  bufio.NewReader (inline)
         0     0%   100%  1540.02kB 75.04%  github.com/go-redis/redis/v8.(*Client).Process
         0     0%   100%   512.02kB 24.95%  github.com/go-redis/redis/v8.(*StringSliceCmd).readReply
         0     0%   100%   512.02kB 24.95%  github.com/go-redis/redis/v8.(*StringSliceCmd).readReply.func1
         0     0%   100%     1028kB 50.09%  github.com/go-redis/redis/v8.(*baseClient)._getConn
         0     0%   100%  1540.02kB 75.04%  github.com/go-redis/redis/v8.(*baseClient)._process
         0     0%   100%  1540.02kB 75.04%  github.com/go-redis/redis/v8.(*baseClient)._process.func1

Can Some one help me to identify the issue?

**Comment by vmihailenco** [comment]
That is `--alloc_space` - memory allocated during the all time program was running. You need `--inuse_space` to find out what is actually there atm.

**Comment by Liaowei** [comment]
I also met.

Build ID: 3f5bebeb50952c5ec6f8de3ee4e0c829c6d8e04e
Type: inuse_space
Time: Mar 18, 2021 at 1:03pm (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 270.16MB, 99.26% of 272.17MB total
Dropped 15 nodes (cum <= 1.36MB)
Showing top 10 nodes out of 49
      flat  flat%   sum%        cum   cum%
  247.34MB 90.88% 90.88%   247.34MB 90.88%  github.com/go-redis/redis/v8/internal/proto.(*Reader).readStringReply
    6.50MB  2.39% 93.27%     6.50MB  2.39%  github.com/vmihailenco/go-tinylfu.(*lruCache).add
       6MB  2.20% 95.47%        6MB  2.20%  container/list.(*List).insertValue
    4.82MB  1.77% 97.24%     4.82MB  1.77%  github.com/vmihailenco/go-tinylfu.New
    4.50MB  1.65% 98.90%    12.50MB  4.59%  github.com/go-redis/cache/v8.(*TinyLFU).Set

**Comment by itcuihao** [comment]
The same problem, how to modify
