### ISSUE TITLE
Init ClusterClient with unavailable nodes will block any command execution for a long time

### ISSUE THREAD

**Issue by GreenHedgehog** [go-redis/redis#1489]
For example, i've inited with 6 nodes and default all other settings, and in took something about 2 minutes to perform ping call. That is totally unintuitive, because i've expected something like context cancelation error or connection error, but not blocking execution for such sufficient time.  How i figured out, its happens because of commands info cache initialization, that not bounds by time by anything. Even context, that we could pass with method `WithContext` of `ClusterClient`, would not replace it for `cmdsInfo` method, so we always calls commands with `context.Background` (I've already mentioned it in #1480). 

So, i'm proposing add new configuration option, that would explicitly bounds commands cache initialization by time. And still fix `WithContext` method to apply changed context value to all calls. I could write it by myself if you will okay with it issue.

**Comment by vmihailenco** [comment]
The best solution is using `ReadTimeout` and `WriteTimeout`. Context cancellation is not fully working - see https://github.com/go-redis/redis/issues/1196

**Comment by GreenHedgehog** [comment]
Yeah, reducing `ReadTimeout` and `WriteTimeout` seems like the only way now, but it's still not the best solution. I repeat, with default config it's takes like 2 minutes to perform any request, not only first (cause cache initialization failed, and it wiil be retry on the next call). We could reduce thats timeouts to much less values(300ms and without retries), but it still would be +~10s to method call. I think that its just necessary to add a way to fail faster without any affection on a regular timeouts.

**Comment by vmihailenco** [comment]
I believe that with ReadTimeout=1s and MaxRedirects=3 it should take up to 3 seconds or so. Default config does not have ReadTimeout...

Ideally this should be addressed by supporting context cancelation. https://github.com/go-redis/redis/issues/1196 has a linked unfinished PR - if you are super interested you may give it a try :)

**Comment by GreenHedgehog** [comment]
>I believe that with ReadTimeout=1s and MaxRedirects=3 it should take up to 3 seconds or so. Default config does not have ReadTimeout...

Yeah, but its for one node, and if you have 6 in cluster, its became 18s al least). And, actually, there is a default timeout https://github.com/go-redis/redis/blob/4b9d6dfd4033eb723aa68cadfcc6284e2251fc97/cluster.go#L96-L102

>Ideally this should be addressed by supporting context cancelation. #1196 has a linked unfinished PR - if you are super interested you may give it a try :)

Yeah, thx, i'll see, im very interested to find some proper solution :)

**Comment by vmihailenco** [comment]
Should be closed by https://github.com/go-redis/redis/pull/1493
