### ISSUE TITLE
Scan

### ISSUE THREAD

**Issue by no1youknowz** [go-redis/redis#149]
Here is a simple example:

	package main

	import (
		"fmt"
		"gopkg.in/redis.v3"
	)

	func Connect() *redis.Client {
		client := redis.NewClient(&redis.Options{
			Addr:     "127.0.0.1:6379",
		})

		return client
	}

	func main() {
		client := Connect()

		// Generate objects
		cursor, _, _ := client.Scan(0, "tracking_insert_click_*", 0).Result()

		if cursor > 0 {
			_, keys, _ := client.Scan(0, "tracking_insert_click_*", cursor).Result()
			fmt.Println(keys)

		}

	}

Is this really the right way of using scan?

I tried initially the code from : https://github.com/go-redis/redis/blob/master/commands_test.go#L552

But I had no results.

Please clarify.

**Comment by dim** [comment]
How about:

```go
package main

import (
	"fmt"

	"gopkg.in/redis.v3"
)

func Connect() *redis.Client {
	client := redis.NewClient(&redis.Options{
		Addr: "127.0.0.1:6379",
	})

	return client
}

func scanKeys(c *redis.Client, eachSlice func([]string)) (err error) {
	var cursor int64
	for {
		var keys []string
		if cursor, keys, err = c.Scan(cursor, "", 50).Result(); err != nil {
			return
		}

		if len(keys) > 0 {
			eachSlice(keys)
		}

		if cursor == 0 {
			break
		}
	}
	return
}

func main() {
	client := Connect()

	// Seed some keys
	for i := 0; i < 240; i++ {
		client.Set(fmt.Sprintf("k%04d", i), "value", 0)
	}

	// Scan all keys
	err := scanKeys(client, func(keys []string) {
		fmt.Printf("found %d keys\n", len(keys))
	})
	if err != nil {
		fmt.Println("ERROR: %s", err)
	}
}

/*
$ go run main.go
found 50 keys
found 50 keys
found 51 keys
found 51 keys
found 38 keys
*/
```

**Comment by no1youknowz** [comment]
Thanks, the for loop was the missing piece for me!
