### ISSUE TITLE
v8.1.2 cluster pipeline data race problem

### ISSUE THREAD

**Issue by xujunhai** [go-redis/redis#1500]
WARNING: DATA RACE
Read at 0x00c00062c148 by goroutine 105:
  github.com/go-redis/redis/v8.(*SliceCmd).Result()
      /var/go/pkg/mod/github.com/go-redis/redis/v8@v8.1.2/command.go:352 +0x7f0
 ..........

Previous write at 0x00c00062c148 by goroutine 7:
  github.com/go-redis/redis/v8.(*baseCmd).SetErr()
      /var/go/pkg/mod/github.com/go-redis/redis/v8@v8.1.2/command.go:151 +0x3e
  github.com/go-redis/redis/v8.(*SliceCmd).SetErr()
      <autogenerated>:1 +0x57
  github.com/go-redis/redis/v8.setCmdsErr()
      /var/go/pkg/mod/github.com/go-redis/redis/v8@v8.1.2/command.go:32 +0xd4
  github.com/go-redis/redis/v8.(*ClusterClient)._processPipeline()
      /var/go/pkg/mod/github.com/go-redis/redis/v8@v8.1.2/cluster.go:1087 +0x78b
  github.com/go-redis/redis/v8.(*ClusterClient)._processPipeline-fm()
      /var/go/pkg/mod/github.com/go-redis/redis/v8@v8.1.2/cluster.go:1076 +0x7a
  github.com/go-redis/redis/v8.hooks.processPipeline.func1()
      /var/go/pkg/mod/github.com/go-redis/redis/v8@v8.1.2/redis.go:91 +0x92
  github.com/go-redis/redis/v8.hooks.withContext.func1()
      /var/go/pkg/mod/github.com/go-redis/redis/v8@v8.1.2/redis.go:136 +0x34

....
Goroutine 7 (finished) created at:
  github.com/go-redis/redis/v8.hooks.withContext()
      /var/go/pkg/mod/github.com/go-redis/redis/v8@v8.1.2/redis.go:136 +0xb4
  github.com/go-redis/redis/v8.hooks.processPipeline()
      /var/go/pkg/mod/github.com/go-redis/redis/v8@v8.1.2/redis.go:90 +0x760
  github.com/go-redis/redis/v8.(*ClusterClient).processPipeline()
      /var/go/pkg/mod/github.com/go-redis/redis/v8@v8.1.2/cluster.go:1073 +0x114
  github.com/go-redis/redis/v8.(*ClusterClient).processPipeline-fm()
      /var/go/pkg/mod/github.com/go-redis/redis/v8@v8.1.2/cluster.go:1072 +0x7a
  github.com/go-redis/redis/v8.(*Pipeline).Exec()
      /var/go/pkg/mod/github.com/go-redis/redis/v8@v8.1.2/pipeline.go:115 +0x1ca
  ........
==================

**Comment by vmihailenco** [comment]
Please show full stack for goroutine 105.
