### ISSUE TITLE
Wrong cmd slot of xread in cluster

### ISSUE THREAD

**Issue by chengjing1181122598** [go-redis/redis#1501]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior

Xread should not occur MOVED error in cluster.
## Current Behavior

Xread always occur MOVED error in cluster.
## Steps to Reproduce

1. github.com/go-redis/redis/v7 v7.4.0
2. In cluster mode
3. XRead(&redis.XReadArgs{Streams: []string{"test_stream_pub_sub", "$"}, Count:   100, Block:   0})
![image](https://user-images.githubusercontent.com/23028470/93732289-3dca7000-fc03-11ea-83ad-4653e236b499.png)
4. Wrong cmd args position used to slot, should be "test_stream_pub_sub" instead of "count".
5. Incidentally please check other cmd about stream.

**Comment by vmihailenco** [comment]
go-redis uses command information from Redis

```
command info xread
1) 1) "xread"
   2) (integer) -4
   3) 1) readonly
      2) movablekeys
   4) (integer) 1
   5) (integer) 1
   6) (integer) 1
   7) 1) @read
      2) @stream
      3) @slow
      4) @blocking
```

Here `4) (integer) 1` is the position (`1`) of the key argument. So it uses `args[1]` which is `count`. So everything works as expected (but incorrectly).

**Comment by chengjing1181122598** [comment]
> go-redis uses [command information](https://redis.io/commands/command#nested-result-array) from Redis
> 
> ```
> command info xread
> 1) 1) "xread"
>    2) (integer) -4
>    3) 1) readonly
>       2) movablekeys
>    4) (integer) 1
>    5) (integer) 1
>    6) (integer) 1
>    7) 1) @read
>       2) @stream
>       3) @slow
>       4) @blocking
> ```
> 
> Here `4) (integer) 1` is the position (`1`) of the key argument. So it uses `args[1]` which is `count`. So everything works as expected (but incorrectly).

**Comment by chengjing1181122598** [comment]
> go-redis uses [command information](https://redis.io/commands/command#nested-result-array) from Redis
> 
> ```
> command info xread
> 1) 1) "xread"
>    2) (integer) -4
>    3) 1) readonly
>       2) movablekeys
>    4) (integer) 1
>    5) (integer) 1
>    6) (integer) 1
>    7) 1) @read
>       2) @stream
>       3) @slow
>       4) @blocking
> ```
> 
> Here `4) (integer) 1` is the position (`1`) of the key argument. So it uses `args[1]` which is `count`. So everything works as expected (but incorrectly).

**Comment by chengjing1181122598** [comment]
> go-redis uses [command information](https://redis.io/commands/command#nested-result-array) from Redis
> 
> ```
> command info xread
> 1) 1) "xread"
>    2) (integer) -4
>    3) 1) readonly
>       2) movablekeys
>    4) (integer) 1
>    5) (integer) 1
>    6) (integer) 1
>    7) 1) @read
>       2) @stream
>       3) @slow
>       4) @blocking
> ```
> 
> Here `4) (integer) 1` is the position (`1`) of the key argument. So it uses `args[1]` which is `count`. So everything works as expected (but incorrectly).

There is movablekeys in command flags.It is the note from https://redis.io/commands/command.
```
"movablekeys - keys have no pre-determined position. You must discover keys yourself."
```
So the client should do more to discover keys, right?

**Comment by vmihailenco** [comment]
Should be fixed by https://github.com/go-redis/redis/pull/1502
