### ISSUE TITLE
can't SET with slices data

### ISSUE THREAD

**Issue by ahan** [go-redis/redis#1504]
In a function, I filtered a list with some featured products, then I want to save the products in redis for cache.
But it end with error "can't marshal []xxx"

With `MarshalBinary()` help, I can successfully SET key saved with single product.

But with multi products, it just errored, I googled around, can't find too much tips.

Is there any way to save with slices?

Example Code:
```
type Test struct {
	ID int `json:"id"`
}
func (s Test) MarshalBinary() ([]byte, error) {
	return json.Marshal(s)
}
items := []Test{
	Test{
		ID: 1,
	},
	Test{
		ID: 2,
	},
}
err := rdb.Set(ctx, "test_key", items, 0).Err()
```

`panic: redis: can't marshal []Test (implement encoding.BinaryMarshaler)`

**Comment by vmihailenco** [comment]
This is not a go-redis issue. It is best to find some thin wrapper around go-redis that will do that for you, e.g. https://github.com/go-redis/cache

As a quick tip

```
type Tests []Test

func (Tests) MarshalBinary() ([]byte, error) {}

items := Tests{}
rdb.Set(ctx, "key", items)
```

**Comment by ahan** [comment]
Thanks for response.

I checked the `go-redis/cache` out, it seems a pretty good stuff, but it didn't provide much info in README.
Can you say more about what's its features, or pros, something more detailed?
