### ISSUE TITLE
Unsafe breaks appengine compatibility

### ISSUE THREAD

**Issue by davidtai** [go-redis/redis#151]
Please revert use of the unsafe package, it prevents use of this lib with google appengine.

**Comment by vmihailenco** [comment]
I did not know that it is possible to use Redis on Appengine these days... Should be fixed.

**Comment by davidtai** [comment]
Thanks for the quick response!

Actually upon further testing, it doesn't work with appengine due to the connection sandboxing (the unsafe just prevented the code from being deployed).  I will probably just fork your project and add a customizable tcp dialing/command interface so I can inject appengine/socket instead.

**Comment by vmihailenco** [comment]
What about:

```
cl := redis.NewClient(&redis.Options{
    Dialer: func() (net.Conn, error) {
        return socket.Dial(c, "tcp", ":6379")
    },
})
```

Though you will also need access to `conn.SetContext` (I guess we can add `client.SetContext`).

**Comment by davidtai** [comment]
Yes, that would actually work out pretty well I think.

**Comment by vmihailenco** [comment]
Cool, let me know if you are interested in `client.SetContext`. I don't want to add it without knowing for sure that is useful.
