### ISSUE TITLE
Sentinel, discarding bad PubSub connection: redis: ping timeout

### ISSUE THREAD

**Issue by pierrre** [go-redis/redis#1518]
This issue is not really a duplicate of https://github.com/go-redis/redis/issues/1407 , because I've got new informations.

I'm using v8.2.3.
I'm creating a failover/sentinel client.

My logs shows
```
discarding bad PubSub connection: redis: ping timeout
```
approximately every minute.

If I understand correctly, the sentinel/failover client is using pubsub in order to receive status change from the server. (I'm not really an expert here).

So I looked at this code
https://github.com/go-redis/redis/blob/7125bf611e5d7d9bb4487dd6cb80d888bad92d23/pubsub.go#L478-L512

If I understand correctly:
- if we receive pubsub messages frequently enough, we will receive a message from the channel `c.ping`, so it will be considered healty
- the `pingTimeout` is now 1 second (when the previous issue was opened, it was 30 seconds)
- if we don't receive a pubsub message, then the code sends a "ping" command
- if the pubsub was previously healthy, it is changed to not healthy, which will trigger again a ping later
- if the pubsub was previously not healty, it is ALWAYS disconnected/reconnected, and an error is logged (even if the ping command didn't fail)
- even if `pingErr` is nil, it will be defined with `errPingTimeout`

From my point of view, as a Go developer and user of this library, this code looks really suspicious.
If I understand correctly, if we don't receive any pubsub message after 1 or 2 seconds, it will disconnect/reconnect the pubsub, and log an error message.

## Expected Behavior

I should not see this error log.

## Current Behavior

I can see this error log.

## Possible Solution

The code inside `case <-timer.C` should be rewritten:
- check the `pingErr`. If it's nil, don't try to reconnect
- IMO the `healthy` variable is not useful. If we receive a pubsub message, simply reset the time. Otherwise send a "ping" command, and if it fails, disconnect/reconnect.

**Comment by vmihailenco** [comment]
Looks like you are right that we can better use the result of `Ping` command. In Postgres from which I ported this code `Ping` is sent on a separate connection - so the result does not mean much. Still we can't be 100% sure that successful write to a connection means that the connection is healthy.

>when the previous issue was opened, it was 30 seconds

30 seconds can be too much in some cases...

**Comment by git-hulk** [comment]
We are suffering this issue in production as well. It seems enough to only make sure the local socket is OK or not since if the connection was closed by the Redis server, the connection would be got an error. if the Redis server machine was suddenly crash without sending the TCP fin, write the `ping` command would receive the TCP rst. So writes the ping command error was nil should mean that the connection was OK?

**Comment by monkey92t** [comment]
Fixed by #1764
