### ISSUE TITLE
moved dep go.opentelemetry.io/otel/api/trace 

### ISSUE THREAD

**Issue by onyxg** [go-redis/redis#1525]
This package is broken!

go.opentelemetry.io/otel/api/trace is not resolving

See here: https://github.com/open-telemetry/opentelemetry-go/pull/1229

**Comment by vmihailenco** [comment]
I will update Otel dependency when it is ready. Meanwhile please stay on the Otel version specified in the go.mod file (v0.12). `go get -u ./...` is not always a great idea.

**Comment by onyxg** [comment]
We are still using GOPATH and I am there are others are too!
Ideally master should always build... from scratch...
But, NVM we replaced your package, especially after clustering Redis was a failure

**Comment by eriken** [comment]
@onyxg 
May I ask what package you moved to?

**Comment by onyxg** [comment]
Golang made it easy to write our own basic KV store

**Comment by eriken** [comment]
Not the answer I hoped for but thanks anyway.
