### ISSUE TITLE
cannot find package "go.opentelemetry.io/otel/api/trace"

### ISSUE THREAD

**Issue by settys** [go-redis/redis#1526]
As per the issue detailed in the link pasted below, it seems the open-telemetry are refactoring their code.

https://github.com/open-telemetry/opentelemetry-go/pull/1229

Pls update go-redis with the refactored code.

**Comment by Muved** [comment]
I'm having the same issue.

**Comment by vmihailenco** [comment]
Master branch was updated.

**Comment by hakluke** [comment]
I'm still getting this error when running `go get -u github.com/go-redis/redis`

**Comment by vmihailenco** [comment]
It is `github.com/go-redis/redis/v8`.
