### ISSUE TITLE
Can not get module

### ISSUE THREAD

**Issue by nicolasopt** [go-redis/redis#1537]
Thanks for your helpful library!

Today, when I run go get github.com/go-redis/redis
It stopped with this error:

package go.opentelemetry.io/otel/api/trace: cannot find package "go.opentelemetry.io/otel/api/trace" in any of:
        /usr/local/go/src/go.opentelemetry.io/otel/api/trace (from $GOROOT)
        /go/src/go.opentelemetry.io/otel/api/trace (from $GOPATH)

Seems go.opentelemetry.io/otel/api/trace updated new version, please help us solved it.

**Comment by vmihailenco** [comment]
https://github.com/go-redis/redis/issues/1534

**Comment by vinifr** [comment]
What about this?

go get github.com/go-redis/redis/v8
cannot find package "github.com/go-redis/redis/v8" in any of:
	/usr/local/go/src/github.com/go-redis/redis/v8 (from $GOROOT)
	/home/vini/go/src/github.com/go-redis/redis/v8 (from $GOPATH)
