### ISSUE TITLE
panic on large number of retries

### ISSUE THREAD

**Issue by ocallaco** [go-redis/redis#1548]
https://github.com/go-redis/redis/blob/38caa12762e776c4637ad9697805c2e9a2e3dbb4/internal/internal.go#L17

this shift will make d a negative duration when the number of retries is high (around 35 for min backoff of 100ms), which will cause a panic when passed to Int63n

**Comment by vmihailenco** [comment]
Do you run go-redis with high number of retries `MaxRetries=40`? Or there is something else?

**Comment by ocallaco** [comment]
yeah in our use case, we can retry thousands of times.  we use the retries in the redis client to essentially wait indefinitely if there's any issue and only surfacing an error when the error is truly fatal (eg WRONGTYPE).
