### ISSUE TITLE
 SRandMember doesn't support "count" parameter

### ISSUE THREAD

**Issue by hyt-hz** [go-redis/redis#155]
Hi, looks like we don't have support for "count" parameter in SRandMember command, is there any plan for this. Thanks.

http://redis.io/commands/srandmember

**Comment by vmihailenco** [comment]
I will try to fix it tomorrow. I did not decide yet if it should be `SRandMember(key, count)` or `SRandMemberNum(key, count)`...

**Comment by hyt-hz** [comment]
@vmihailenco thanks for your quick response. IMHO SRandMemberNum would be better since it wouldn't break existing API.
