### ISSUE TITLE
discarding bad PubSub connection

### ISSUE THREAD

**Issue by hzhijun** [go-redis/redis#1550]
redis: 2020/10/28 14:23:13 pubsub.go:151: redis: discarding bad PubSub connection: read tcp 172.16.0.199:46492->10.0.1.109:6110: read: connection reset by peer
请问这种情况是什么原因导致的呢？

**Comment by hzhijun** [comment]
我们有两个服务端项目都在使用 redis 发布订阅功能，几乎同一时间，两个系统都出现了类似的报错日志。

**Comment by vmihailenco** [comment]
That is a pretty general error. Bad networking could cause it.

**Comment by hzhijun** [comment]
这种情况持续了将近 6 个小时，我应该怎么规避这种问题呢？我们的网络不会持续六个小时不稳定的。

**Comment by hzhijun** [comment]
遇到这种情况需要重新走订阅逻辑吗？需要重新调用 redisClient.Subscribe(channels...) 吗？

**Comment by hzhijun** [comment]
我亲自测试过了，应该不是网络波动所导致的。
1. 如果是网络波动的话，会打印 redis: discarding bad PubSub connection: redis: ping timeout ，但是我追查日志时并没有找到相关的日志，
2. 如果是网络波动引起的话，等网络恢复了之后，发布消息时是可以正常接收到的，我遇到的情况是，将近6个小时没有恢复，直到我重新启动服务后订阅通知功能才恢复正常。

**Comment by hzhijun** [comment]
redis: 2020/10/28 14:23:13 pubsub.go:151: redis: discarding bad PubSub connection: read tcp 172.16.0.199:46492->10.0.1.109:6110: read: connection reset by peer
我本地浮现了该条日志；
当我主动调用 redisClient.Close() 后，在调用 redisClient.Publish() 方法就会打印上边的日志；
我们线上服务并没有调用过 Close() 方法。

**Comment by akkuman** [comment]
me too

**Comment by unidbaas** [comment]
me too
