### ISSUE TITLE
HGetAll returns incorrect results for non existing key

### ISSUE THREAD

**Issue by omritapingo** [go-redis/redis#1587]
Calling 
```go 
res, err := redis.Client().HGetAll("unkown-key").Result()
```
should return a nil pointer with a `redis.Nil` error, but instead returns an empty map with a nil error

## Possible Solution

`isNilReply` function should check for `HGetAll` empty response ( `*0`)

https://github.com/go-redis/redis/blob/72e5988b6eea5da1466ce6e5375dcb18bf654a10/internal/proto/reader.go#L316-L320

Redis protocol response:
```
❯ nc 127.0.0.1 6379
hgetall foo
*0
```

**Comment by vmihailenco** [comment]
>should return a nil pointer with a redis.Nil error

Why? Your example demonstrates that Redis Server returns empty response and so does go-redis.

**Comment by omritapingo** [comment]
got it, thank you :)
