### ISSUE TITLE
redis.HGet returns redis.Nil when the key contains spaces

### ISSUE THREAD

**Issue by kbirk** [go-redis/redis#1592]
Hey there.

I've run into an issue using this lib when I attempt to read values under a key that contains a space. 

I attempted wrapping it in double quotes (which works on the CLI), but that also does not seem to work with this lib.

Any suggestions?

**Comment by vmihailenco** [comment]
Hey,

This works for me just fine

```go
package main

import (
	"context"
	"log"

	"github.com/go-redis/redis/v8"
)

func main() {
	ctx := context.Background()

	rdb := redis.NewClient(&redis.Options{
		Addr: ":6379",
	})

	if err := rdb.Set(ctx, "foo bar", "hello world", 0).Err(); err != nil {
		panic(err)
	}

	log.Println(rdb.Get(ctx, "foo bar"))
}
```

Please reopen if this is still a problem.
