### ISSUE TITLE
redis.Nil error string "redis: nil" is confusing

### ISSUE THREAD

**Issue by WGH-** [go-redis/redis#1593]
On the protocol level, many Redis commands return special `nil` value when the key doesn't exist and in several other conditions.

The problem is that in this library it's treated as an error with rather confusing `Error()` string `"redis: nil"`.

When I first saw it, I thought that it was the result of some kind of botched `fmt.Errorf("redis: %v", something)`, where something turned out to be `nil`, rather than special Redis value.

I think it would be nice to replace that "redis: nil" with something more descriptive, like "key not found". Although for e.g. BLPOP appropriate description would be "no element could be popped and the timeout expired".

**Comment by sushruthg-aka** [comment]
Or can we get an exported type ErrRedisNil so that caller can do an errors.Is check at call site

**Comment by WGH-** [comment]
> Or can we get an exported type ErrRedisNil so that caller can do an errors.Is check at call site instead of string matching

You can already compare the error to `redis.Nil` directly without string matching.

**Comment by vmihailenco** [comment]
I believe this issue should be addressed with some note in documentation and/or better example.

>I think it would be nice to replace that "redis: nil" with something more descriptive, like "key not found". Although for e.g. BLPOP appropriate description would be "no element could be popped and the timeout expired".

This is the reason we don't use more specific values. In practice it is more convenient to have single `redis.Nil` than 10 different errors for every situation.

**Comment by vmihailenco** [comment]
I've added some docs https://redis.uptrace.dev/#redisnil . I don't see what else can be done.

**Comment by WGH-** [comment]
What do you think about changing the error string to "redis: nil value returned" or something similar?

**Comment by vmihailenco** [comment]
@WGH- that would be a minor improvement that would break some programs that do `cmd.Err() == "redis: nil"`.

**Comment by revolter** [comment]
> I've added some docs [redis.uptrace.dev/#redisnil](https://redis.uptrace.dev/#redisnil) . I don't see what else can be done.

One year later, and the link is already dead.

**Comment by oAnubis** [comment]
Also depending on your specific application uses you can write a ParseResult function to override the results similar to overriding MarshalJson to fit your applications needs.
