### ISSUE TITLE
If the context parameter is used?

### ISSUE THREAD

**Issue by seth-shi** [go-redis/redis#1594]
### I'm sorry I' m confused because it's not a bug

* As I read the document, I saw how context came from, but the instances were in small applications
* When I http the application, I should have a lot of users with questions context, if I pass it correctly.
* my code
```
package main

import (
	"context"
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/go-redis/redis/v8"
	"net/http"
)

var ctx = context.Background()

func main()  {

	host := ""
	port := 0
	password := ""

	client := redis.NewClient(&redis.Options{
		Addr:     fmt.Sprintf("%s:%d", host, port),
		Password: password, // no password set
		DB:       0,        // use default DB
	})
	
	g := gin.Default()
	g.GET("/ping", func(c *gin.Context) {
		
		var msg string
		
		// 1
		msg = client.Get(ctx, "ping").String()
		
		// 2
		msg = client.Get(context.Background(), "ping").String()
		
		// 3
		msg = client.Get(c, "ping").String()
		
		// 4
		msg = client.Get(c.Request.Context(), "ping").String()

		c.String(http.StatusOK, msg)
	})
}

```

## I am using 4 in my program, I want to know if my use is correct? thx ##

**Comment by vmihailenco** [comment]
4 is the right choice.

- 1 is is kinda wrong because it uses one global context. Usually you want a separate context for each request.
- 2 creates empty context which kinda pointless.
- 3 uses Gin context which can't be used as a full replacement for `context.Context`.

**Comment by sleepreading** [comment]
Usually, We don't care about the context. I think it's helpful to provide some methods that doesn't need context!
