### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by sado0823** [go-redis/redis#1600]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

when i use this package to conn redis, it can normally use `in first few times`, and then it would be this error `context deadline exceeded `

here is my init code
```golang
RedisPool := redis.NewClient(&redis.Options{
			Addr:         redisCfg.DSN,
			Username:     redisCfg.Username,
			Password:     redisCfg.Password,
			PoolSize:     redisCfg.MaxActive,
			MinIdleConns: redisCfg.MinIdle,
			MaxConnAge:   cast.ToDuration(redisCfg.MaxLifeTime) * time.Millisecond,
			IdleTimeout:  cast.ToDuration(redisCfg.IdleTimeout) * time.Millisecond,
		})

manager.Engines[redisCfg.Usage] = RedisPool

		if index == 0 {
			manager.DefaultEngine = RedisPool
		}
```

and each time i use, i will get a new conn

```golang

        dbConn = m.DefaultEngine.Conn(ctx)

	if res := dbConn.Select(ctx, dbIndex); res.Err() != nil {
		panic(res.Err())
	}

	dbConn.AddHook(TracingHook{})
	return dbConn
```

and i request my api, backend is grpc server, several times after, it comes error fo me, `context deadline exceeded`

and then, i use this just through http request
```golang
RedisManager.MustUse(x.BuildInCtx, 0).Get(x.BuildInCtx, "kkk")
```

and it has the same problem, it can use successful in few times, and then i got a panic in this line`dbConn.Select(ctx, dbIndex)`

i try to init this use below codes
```golang
RedisPool := redis.NewClient(&redis.Options{
			Addr:         redisCfg.DSN,
			Username:     redisCfg.Username,
			Password:     redisCfg.Password
}
```

i also get the same wrong...

how can i fix it ?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by sado0823** [comment]
my version is v8.4.0, and  i try 8.4.8, it doesn't help

**Comment by vmihailenco** [comment]
It looks like you have a deadline set on `x.BuildInCtx`. You probably want a different context without a deadline.

**Comment by giannimassive** [comment]
FYI https://github.com/redis/go-redis/issues/3497
