### ISSUE TITLE
How does txpipeline guarantee transactions?

### ISSUE THREAD

**Issue by TXYH1** [go-redis/redis#1602]
Hello, I have a question. I can't find the answer anywhere else. Can you help me？

Is txpipeline transactional? In the defaultprocesstxpipeline, cmds is divided into different slices and requests to the service concurrently. Although the commands to be executed for different services are wrapped by multi / exec, how to ensure that all commands are transactional for multiple services? For example, a request to a service failed.

```
for node, cmds := range cmdsMap {
    ......
    go func(node *clusterNode, cmds []Cmder) {
           ......
	    cn, err := node.Client.getConn()
	    ......
   
	    err = c.txPipelineProcessCmds(node, cn, cmds, failedCmds)
	    node.Client.releaseConnStrict(cn, err)
    }(node, cmds)
    }
```

**Comment by vmihailenco** [comment]
@TXYH1 Redis Cluster does not support distributed transactions. Divided commands are run in different/separate transactions on different Redis Servers.

**Comment by TXYH1** [comment]
@vmihailenco Thank you for your reply. At present, transactions can only be guaranteed on a single node, right
