### ISSUE TITLE
Normal behaviour when ReadOnly is set but no Route* option set ?

### ISSUE THREAD

**Issue by ericrenard** [go-redis/redis#1614]
Hello,
We recently upgraded go-redis in our microservices from v5 to v8. We use go-redis against a redis cluster. We noticed a huge change between the 2 versions : our slaves received pretty much no traffic.
After investigation, we believe this is due to the fact that we did not set RouteRandomy or RouteByLatency to true when initializing the Client. In v5, this caused all reads to go to slave nodes. In v8, this causes all reads to go to master node, probably because of the following code :

cluster.go:1642
```
if (c.opt.RouteByLatency || c.opt.RouteRandomly) && cmdInfo != nil && cmdInfo.ReadOnly {
		return c.slotReadOnlyNode(state, slot)
	}
```

We changed RouteByLatency to true, this improved the situation (now slaves receive around half of reads) but it seems there's no way in the current version of the lib to set options to redirect all reads to slave nodes such as we did before.

Is this an intended change ? 

Thanks

**Comment by vmihailenco** [comment]
This was not intentional. Please try v8.4.10 with `ReadOnly=true`.

**Comment by ericrenard** [comment]
Works fine now, thanks :)

**Comment by vmihailenco** [comment]
Thanks for reporting.
