### ISSUE TITLE
parse redis bytes value inefficient

### ISSUE THREAD

**Issue by smartnews-weitao** [go-redis/redis#1618]
So my use case is i store []bytes inside redis, and i saw the go-redis client will parse from []byte to string inside StringCmd, and my program (a grpc server) will parse it from string back to []byte, it seems rather inefficient.

So i am wondering is there an efficient workaround or can you guys implement a BytesCmd or something like that?

**Comment by vmihailenco** [comment]
You can use `rdb.Get(ctx, "foo").Bytes()` to get bytes instead of string.

**Comment by smartnews-weitao** [comment]
@vmihailenco I checked the implementation, the rdb.Get(ctx, "foo").Bytes() just parsed bytes from string, so basically the go-redis parse raw bytes to string, then after i call rdb.Get(ctx, "foo").Bytes(), it parsed from string back to bytes, that's why i said it's inefficient.

**Comment by vmihailenco** [comment]
That is what I mean - https://github.com/go-redis/redis/blob/master/command.go#L688-L690. It uses unsafe to avoid copying the string.

**Comment by smartnews-weitao** [comment]
yes, i know the implementation avoid copying the string, but i looked into where StringCmd get the val in the first place, it's parsed from []byte to string inside the readReply() function.

**Comment by vmihailenco** [comment]
And you suggest?

**Comment by smartnews-weitao** [comment]
I am not sure, maybe implement a byteCmd which will treat string response as pure bytes, or implement it in a way that users can implement their own codecs. If this requirement is too specific, i guess the best way for me is fork my own version and do it on my version.

**Comment by vmihailenco** [comment]
Please try, but I don't think there is a problem to be solved.

>it's parsed from []byte to string inside the readReply() function.

It is read from a socket. You can't avoid that.

**Comment by smartnews-weitao** [comment]
i am not sure, but i post the code here:

`func (r *Reader) readStringReply(line []byte) (string, error) {
	if isNilReply(line) {
		return "", Nil
	}

	replyLen, err := util.Atoi(line[1:])
	if err != nil {
		return "", err
	}

	b := make([]byte, replyLen+2)
	_, err = io.ReadFull(r.rd, b)
	if err != nil {
		return "", err
	}

	return util.BytesToString(b[:replyLen]), nil
}`

how about remove the last line and return simply b[:replyLen],nil

**Comment by vmihailenco** [comment]
That won't change anything. `util.BytesToString` uses unsafe and does not not allocate.

**Comment by smartnews-weitao** [comment]
ok, i get the point, so both BytesToString & StringToBytes doesn't actually parsing, it's just change the pointer type?

**Comment by vmihailenco** [comment]
Yes, the convert []byte <-> string without re-allocating memory.

**Comment by smartnews-weitao** [comment]
thx, i thought there was 2 actual result parsing. With mere 2 pointer type conversion i can live with it. Thank you again for the enlightenment.
