### ISSUE TITLE
Error MOVED 9362

### ISSUE THREAD

**Issue by brainlabs** [go-redis/redis#1633]
i use AWS elastic cache cluster (cluster mode enable ) with single endpoint cluster config and always got error **MOVED 9362**

My setting like this:
`r := redis.NewUniversalClient(&redis.UniversalOptions{
    Addrs:          strings.Split(conf.Redis.Hosts, ","),
    ReadTimeout:    time.Duration(conf.Redis.ReadTimeoutSecond) * time.Second,
    WriteTimeout:   time.Duration(conf.Redis.WriteTimeoutSecond) * time.Second,
    DB:             conf.Redis.DB,
    PoolSize:       conf.Redis.PoolSize,
    PoolTimeout:    time.Duration(conf.Redis.PoolTimeoutSecond) * time.Second,
    MinIdleConns:   conf.Redis.MinIdleConn,
    IdleTimeout:    time.Duration(conf.Redis.IdleTimeoutSecond) * time.Second,
    RouteByLatency: conf.Redis.RouteByLatency,
    Password:       conf.Redis.Password,
})`

**Comment by goku321** [comment]
I'm facing a somewhat similar issue. I've a Redis cluster with six nodes. I get `MOVED` error sometimes. The default value for `MaxRedirects` is 3. That means, when there are more than 3 redirections, the client would give a `MOVED` error. Would having a higher value for `MaxRedirects` help?

**Comment by vmihailenco** [comment]
In theory there should not be more than 1 redirect. But in practice you should figure out why you have redirects and act based on that information.

Closing since I can't debug this based on the config.
