### ISSUE TITLE
GETSET deprecated in redis 6.2

### ISSUE THREAD

**Issue by kelvie** [go-redis/redis#1653]
## Expected Behavior

`GetSet` will use `SET` with the `GET` parameter in redis 6.2 or above

Or alternatively a new function that allows me to call `SET` with the `GET parameter

## Current Behavior

We can only do a getset using the redis `GETSET` command

## Possible Solution

Detect the version in `GetSet` and use `SET` instead, or create a new library function.

## Steps to Reproduce

Create a `RedisClient`, and call `GetSet` on it.

## Context (Environment)

We want to not have to worry about code changes if we upgrade redis and GETSET gets removed.

## Detailed Description

See  https://redis.io/commands/getset 

## Possible Implementation

See above

**Comment by vmihailenco** [comment]
Hello,

It looks like we need to add some general `Client.SetArgs(string, string, redis.SetArgs)` function that supports all the args that SET supports

```
SET key value [EX seconds|PX milliseconds|EXAT timestamp|PXAT milliseconds-timestamp|KEEPTTL] [NX|XX] [GET]
```

Contributions are welcome. For now you can use

```
rdb.Do(ctx, "set", key, value, "GET").Result()
```

**Comment by ynden** [comment]
Hello,
I would like to give it a try.

Thanks

**Comment by ashwinrrao** [comment]
Hi,
Is it fine if i give it a try as well?

**Comment by vmihailenco** [comment]
Hi,

I believe we already have a PR for this - https://github.com/go-redis/redis/pull/1662
