### ISSUE TITLE
V8 Package refuses to install properly

### ISSUE THREAD

**Issue by chippyash** [go-redis/redis#1656]
## Expected Behavior

Application should build

## Current Behavior

```
src/presignedurl/fs-presigned-url.go:19:2: cannot find package "github.com/go-redis/redis/v8" in any of:
        /snap/go/6921/src/github.com/go-redis/redis/v8 (from $GOROOT)
        /home/akitson/Projects/Golang/src/github.com/go-redis/redis/v8 (from $GOPATH)
```
directory `/home/akitson/Projects/Golang/src/github.com/go-redis/redis/v8` does not exist. `/home/akitson/Projects/Golang/src/github.com/go-redis/redis` does exist after the `go get`

## Possible Solution

N/A

## Steps to Reproduce

Following instructions on readme:
- `go get github.com/go-redis/redis/v8`
- add "github.com/go-redis/redis/v8" to import

Run a build
`env GOOS=linux go build -ldflags="-s -w" -o bin/fs-presigned-url src/presignedurl/fs-presigned-url.go`

## Context 

Completely stopped dev, as cannot load the module. I first encountered this running Go V1.13, so reading the notice that package is valid only last 2 versions, I upgraded to Go V1.15. No change

## Environment
go1.15.7 linux/amd64
Ubuntu 20.04.1 LTS
go installation: `sudo snap install --classic --channel=1.15/stable go `

**Comment by vmihailenco** [comment]
You have not initialized a Go module:

```bash
mkdir /tmp/redis-test
cd /tmp/redis-test
go mod init redis-test
go get github.com/go-redis/redis/v8
```

**Comment by chippyash** [comment]
ah sorry, forgot that step in my report. I did.  contents of go.mod are
```
package main

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"github.com/aws/aws-sdk-go/aws"
	"os"
	"time"
	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
	"github.com/bshuster-repo/logrus-logstash-hook"
	"github.com/go-redis/redis/v8"
	"github.com/google/uuid"
	"github.com/mitchellh/mapstructure"
	log "github.com/sirupsen/logrus"
	"gopkg.in/square/go-jose.v2/jwt"
	"net/http"
	"strconv"
)
```

**Comment by vmihailenco** [comment]
That is not go.mod . When all is done right you should not see $GOPATH in the error message.

**Comment by chippyash** [comment]
again my bad. for some reason I copy-pasta'd the wrong file. Tired I guess, trying to get round this problem
So here's my go.mod
```
module files-service

go 1.15

require (
	github.com/aws/aws-lambda-go v1.22.0
	github.com/aws/aws-sdk-go v1.37.6
	github.com/bshuster-repo/logrus-logstash-hook v1.0.0
	github.com/go-redis/redis/v8 v8.5.0
	github.com/google/uuid v1.2.0
	github.com/mitchellh/mapstructure v1.4.1
	github.com/sirupsen/logrus v1.7.0
	gopkg.in/square/go-jose.v2 v2.5.1
)
```
excerpt from go.sum
```
github.com/go-redis/redis/v8 v8.5.0 h1:L3r1Q3I5WOUdXZGCP6g44EruKh0u3n6co5Hl5xWkdGA=
github.com/go-redis/redis/v8 v8.5.0/go.mod h1:YmEcgBDttjnkbMzDAhDtQxY9yVA7jMN6PCR5HeMvqFE=
```

settings
```
GOPATH="/home/akitson/Projects/Golang"
GOROOT="/snap/go/7013"
```

So GOPATH is outside of project directory. Everything I've read says it should be for go modules.  Your mod is different?

I tried running your incantation
```
mkdir /tmp/redis-test
cd /tmp/redis-test
go mod init redis-test
go get github.com/go-redis/redis/v8
```
But as I expected, that was just creating a brand new go module. Nothing changed in my module afterwards. It had a go.mod and a go.sum, just like my app.

I guess the thing that irks me the most is that no other go module is giving me this problem. So I am in a bit at a quandry as to why the redis module is being such a pain.  And actually, it is a blocker. Not being able to use Redis in AWS is a major problem and without a solution, we'll be going back to writing lambdas in PHP (which does work)

**Comment by vmihailenco** [comment]
>But as I expected, that was just creating a brand new go module. Nothing changed in my module afterwards. It had a go.mod and a go.sum, just like my app.

But it worked without any errors.

>Your mod is different?

The problem is not with go.mod, but with the fact that Go does not use your module at all and instead uses GOPATH (see your error message). Try `GO111MODULE=on` and check that `src/presignedurl/` is inside your Go module.

**Comment by chippyash** [comment]
@vmihailenco Thanks for your perseverance. I think I have sorted this.

I changed the build command to cd into the module directory and then run the build, e.g.

`cd src/presignedurl; env GOOS=linux go build -ldflags="-s -w" -o ../../bin/fs-presigned-url fs-presigned-url.go; cd ../..`

and that now works (build command is part of a Makefile).  I confess, I do not understand why this is so, nor why the inclusion of go-redis requires it as the module built just fine before its inclusion.  If you have any ideas on that, please share as it might help others.

Many thanks.
