### ISSUE TITLE
dial tcp x.x.x.x:6380: i/o timeout 

### ISSUE THREAD

**Issue by vasundhara785** [go-redis/redis#1659]
Iam  facing the same problem with the error dial tcp x.x.x.x:6380: i/o timeout .
Does the operations (GET,SET ) made on redis would also create a client connection internally?

More insights:
redis version :  v6.15.8
one connection is opened and redis operations are made on the same connection.
![image](https://user-images.githubusercontent.com/59416677/107744826-629dbc00-6d39-11eb-8e8f-cb9567dc273f.png)
Its showing more than thousands of client connections.
What could be the problem any help urgently needed?

**Comment by jonyhy96** [comment]
This may due to wrong redis cluster network configuration.
You can add a breakpoint at [here](https://github.com/go-redis/redis/blob/master/cluster.go#L1019) to see if the node info of slots is match with your given Addrs in clusterOptions.

**Comment by vmihailenco** [comment]
This does not look like a go-redis problem. Besides v6 is quiet old.

**Comment by kunalpahwa9** [comment]
Hey @vasundhara785 we ran into the same problem recently, CPU was ok but getting the same error `dial tcp x.x.x.x:6380: i/o timeout` were you able to solve this issue?
Can we replicate the same to test/verify if there is some issue with the library?
FYI we are also using a similar version of the library.
