### ISSUE TITLE
is Client safe for concurrent use?

### ISSUE THREAD

**Issue by ginkoob** [go-redis/redis#166]
is Client safe for concurrent use? I'm using redis in a web app and I'm wondering if I should keep the client in a global variable or if I should Close / create a new one on each handler request.

**Comment by dim** [comment]
The client is thread safe, but pipelines, multi blocks, etc are not.

**Comment by vmihailenco** [comment]
What @dim said. Multi, pipelines and PubSub are not thread-safe, because using them from multiple goroutines does not make much sense to me. But we can make them thread-safe if you find such use case.

Hopefully https://github.com/go-redis/redis/pull/167 will make situation clearer.

**Comment by sammy007** [comment]
I have an app where .multi should be called from hundreds of goroutines in order to persist some work done by each worker. Is it good use-case to make .multi thread safe?

**Comment by dim** [comment]
Not really, in my opinion. For me, the same rule applies here as for native
Go maps. The Go team could have made them thread safe but decided not to
add it would benefit only a small fraction of use cases.

I don't know the exact scenario, but I would suggest you should
batch/collect the results from your goroutines and then build a multi
statement from a single goroutine. Take e.g. a look at
https://github.com/facebookgo/muster for that purpose.

**Comment by sammy007** [comment]
Well, maybe I am missing something. I don't wanna share multi tx between goroutines, each goroutine will create separate client.Multi().
I guess this code is ok then: https://github.com/sammy007/go-cryptonote-pool/blob/master/go-pool/storage/redis.go#L73
Please tell me if I am wrong.

**Comment by vmihailenco** [comment]
From what I see it is okay, but you use Redis transactions (MULTI) without WATCH, which AFAIK is somewhat pointless (but I can be wrong :). When you don't need WATCH you can just use pipelines - https://godoc.org/gopkg.in/redis.v3#ex-Client-Pipelined. It will not be much faster though.

>I don't wanna share multi tx between goroutines, each goroutine will create separate client.Multi().

Then you don't have to worry about thread-safety since each goroutine will have its own copy of Multi.

**Comment by lcosmin** [comment]
How about the following scenario:  create a pipeline, pass it to multiple goroutines (which do some operations) and call Exec() a single time (after the goroutines have finished) from the function that created the pipeline. Is this still unsafe ?

**Comment by vmihailenco** [comment]
Yes, currently it is unsafe. But I see a point and I am inclined to make pipeline/multi threadsafe just to avoid confusion it causes :)

**Comment by lwjli** [comment]
Under high concurrency with single client, some request may fail.
After filter out the failed request, the response is OK.

**Comment by drachs** [comment]
I think it is really important to document the read safety of the library.  In particular, I came here wonder if I should do a global redis client or needed to do one redis client per go routine.   I am assuming from the discussion that a global redis client is preferable.   I didn't see this addressed in the docs.

But I'd like to leave the feedback that if some parts of the library are thread safe and others are not then it's very important to make that clear in the documentation, especially in a language like Go with a very aggressive multithreaded model.

**Comment by DachuanZhao** [comment]
> I think it is really important to document the read safety of the library. In particular, I came here wonder if I should do a global redis client or needed to do one redis client per go routine. I am assuming from the discussion that a global redis client is preferable. I didn't see this addressed in the docs.
> 
> But I'd like to leave the feedback that if some parts of the library are thread safe and others are not then it's very important to make that clear in the documentation, especially in a language like Go with a very aggressive multithreaded model.

+1 . Is the client safe for concurrent use now ?

**Comment by bgokden** [comment]
After a couple of days of testing. I can confirm that Redis client operations that use streams are not thread-safe.
I am developing an async chat system. I have a web socket backend where a goroutine reads the messages and sends them to a stream and another goroutine that reads from a stream and sends them to the web socket. It was breaking for no apparent reason and I came here because some operations are not thread-safe. As I see any blocking operation is not thread-safe.
