### ISSUE TITLE
 undefined: otel.Meter

### ISSUE THREAD

**Issue by antichown** [go-redis/redis#1660]
go get github.com/go-redis/redis

 github.com/go-redis/redis/internal
/home/linux/go/src/github.com/go-redis/redis/internal/instruments.go:24:23: undefined: otel.Meter

go version
go version go1.15.8 linux/amd64

**Comment by staropram** [comment]
seems like otel.Meter has moved to "go.opentelemetry.io/otel/metric/global" and then has to be called as global.Meter

**Comment by vmihailenco** [comment]
@staropram no, it is not - https://pkg.go.dev/go.opentelemetry.io/otel/

This is a varation of https://github.com/go-redis/redis/issues/1534
