### ISSUE TITLE
Error github.com/go-redis/redis/internal/instruments.go:24:23: undefined: otel.Meter

### ISSUE THREAD

**Issue by omides248** [go-redis/redis#1661]
Hello, I use **go1.12.7** after using `go get github.com/go-redis/redis` or  `go get github.com/go-redis/redis/v8` error:

Error github.com/go-redis/redis/internal/instruments.go:24:23: undefined: otel.Meter

How to fix it, thanks.

**Comment by vmihailenco** [comment]
https://github.com/go-redis/redis/issues/1534
