### ISSUE TITLE
undefined: otel.Meter

### ISSUE THREAD

**Issue by qiqisteve** [go-redis/redis#1667]
# github.com/go-redis/redis/v8/internal
C:\Users\Administrator\go\pkg\mod\github.com\go-redis\redis\v8@v8.5.0\internal\instruments.go:24:23: undefined: otel.Meter

**Comment by tobidalhof** [comment]
Same here after upgrading go mod dependencies with `go get -u ./...` 

![image](https://user-images.githubusercontent.com/10046578/108309844-a4ec5080-71b2-11eb-8c16-206e3fd173a1.png)

**Comment by zhajming** [comment]
I got this problem too. It seems has been resolved by [commit](https://github.com/go-redis/redis/commit/1f32092a3b04c21b6e8e51e2c94c03448d14a2c9) 
@vmihailenco Could you make a new tag (v8.5.1) for it?

**Comment by vmihailenco** [comment]
Done
