### ISSUE TITLE
HGetAll not returning redis.Nil when key doesn't exist

### ISSUE THREAD

**Issue by thatsarunb4u** [go-redis/redis#1668]
When key doesn't exist in REDIS, HGetAll is expected to return "redis.Nil" for the error field. However, error is <nil> and map is [] (empty).

## Expected Behavior

When key doesn't exist in REDIS, HGetAll is expected to return "redis.Nil" for the error field.

## Current Behavior

error is <nil> and map is [] (empty).

## Possible Solution

error should be returned as redis.Nil when key is not available.

## Steps to Reproduce

1. Call HGetAll like this.. 
       valMap, getErr := redisCli.HGetAll(ctx, derivedDoc.CorrId).Result()
2. if getErr == redisgo.Nil { //Key  doesn't exist block, which never gets executed. }
3. Output of log.println(getErr, valMap) is <nil> and []

**Comment by wziww** [comment]
That's what redis-server reply. go-redis just parse it.

```shell
# telnet example
hgetall test
*0
get test
$-1
```

**Comment by thatsarunb4u** [comment]
Thanks for the response.

According to spec, go redis is supposed to return redis.Nil right? Pasting a snippet from the docs for reference.

**redis.Nil**
go-redis exports the redis.Nil error and returns it whenever Redis Server responds with (nil). We have to use an error to distinguish between an empty string reply and a nil reply:

```
val, err := rdb.Get(ctx, "key").Result()
switch {
case err == redis.Nil:
    fmt.Println("key does not exist")
case err != nil:
    fmt.Println("Get failed", err)
case val == "":
    fmt.Println("value is empty")
}
```

**Comment by thatsarunb4u** [comment]
Any reason why its closed?

**Comment by thatsarunb4u** [comment]
@vmihailenco ?

**Comment by vmihailenco** [comment]
@wziww explained that this is how Redis Server works. We don't change Redis Server behavior in go-redis client.

**Comment by thatsarunb4u** [comment]
What about the documentation I've quoted above? It says go-redis returns redis.Nil whenever redis returns nil..

https://github.com/go-redis/redis/issues/1668#issuecomment-781098586

**Comment by thatsarunb4u** [comment]
@vmihailenco  @wziww

**Comment by vmihailenco** [comment]
It is working as intended - it was explained why. If you think docs wording can be improved - please send a PR.

**Comment by kumari-jyoti** [comment]
@vmihailenco It works for GET, not for HGETALL as explained by @thatsarunb4u 
@thatsarunb4u I am also stuck with the same, were you able to find solution for identifying missing key in HGETALL scenario

**Comment by gregvend** [comment]
I came for the same issue but go-redis behaves correctly.

This is how redis behaves:

```
[db16] > GET "nothing"
(nil)

[db16] > HGET "nope" "nope"
(nil)

[db16] > HGETALL "nope"
(empty list or set)
```

for `HGETALL`, as redis does not return `(nil)`, `go-redis` does not return `redis.Nil`.
