### ISSUE TITLE
when using HSet, HGetAll almost simultaneously, HSet is ignored in certain case 

### ISSUE THREAD

**Issue by leejh903** [go-redis/redis#1669]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior

- `Hset` should worked eventually

## Current Behavior

- `Hset` is ignored

## Steps to Reproduce

1. create cluster redis instance 
2. create certain data in redis
3. `Hset` to already created data from goroutine
4. `HGetAll` to already created data

```
func Test(t *testing.T) {
	ctx := rest.NewContext()
	r := GetRedisInstance(ctx)

	doc := map[string]interface{}{
		"a": "A",
		"b": "B",
	}

	go func() {
		e := r.client.HSet(ctx, "testKey", doc).Err()
		assert.NoError(t, e)
	}()

	//time.Sleep(1 * time.Second)

	data, e := r.client.HGetAll(ctx, "testKey").Result()
	assert.NoError(t, e)
	fmt.Println(data)
}
```

If I do not use goroutine when using `HSet`, it works well.
But using `Hset` in goroutine, it reproduces.

## Context (Environment)

- poolsize: 10
- pooltimeout: 3s
- minIdleConnn: 200
- cacheexpiration: 1h

**Comment by vmihailenco** [comment]
You have to add some synchronization to your program so go-routines are executed in some order.

**Comment by leejh903** [comment]
Thanks for answer @vmihailenco! But I do not understand why redis value are not changed. After these two cases(`HSet` -> `HGetAll`, `HGetAll` -> `HSet`), I think `Hset` should be worked and value should be changed eventually.
