### ISSUE TITLE
cannot find package "go.opentelemetry.io/otel/label"  while downloading go redis client

### ISSUE THREAD

**Issue by loukikbhandari** [go-redis/redis#1670]
While downloading/importing go redis client using the following command  it complains for package "go.opentelemetry.io/otel/label" not found 

go get -u github.com/go-redis/redis

## Expected Behavior
This command **go get -u github.com/go-redis/redis**
should download the package successfully 

## Current Behavior

go get -u github.com/go-redis/redis

package go.opentelemetry.io/otel/label: cannot find package "go.opentelemetry.io/otel/label" in any of:
        /Users/test/sdk/go1.14.15/src/go.opentelemetry.io/otel/label (from $GOROOT)
        /Users/test/go/src/go.opentelemetry.io/otel/label (from $GOPATH)

## Possible Solution

https://github.com/open-telemetry/opentelemetry-go/commit/ecf65d7968225482a4d50e4955d6bc826119b49c
open-telemetry updated the names from labe -> attribute and this should be fixed in go redis client

## Steps to Reproduce
1. Open terminal (go is already installed and in path)
2. go get -u github.com/go-redis/redis

## Context (Environment)
My go env is as follows. I am using  MacOS Catalina 10.15.4

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/test/Library/Caches/go-build"
GOENV="/Users/test/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/test/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/test/sdk/go1.14.15"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/test/sdk/go1.14.15/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

## Detailed Description

Downloading go client with below command should work smoothly
go get -u github.com/go-redis/redis

**Comment by vmihailenco** [comment]
It should be `go get -u github.com/go-redis/redis/v8`

**Comment by ManuelWeiss** [comment]
+1
```
go get -u github.com/go-redis/redis/v8
```
doesn't work

**Comment by zeewell** [comment]
#1679
