### ISSUE TITLE
Ping too much in PubSub

### ISSUE THREAD

**Issue by PeerXu** [go-redis/redis#1673]
Hi, everyone.

I wrote a program with redis over 4G network.

So, traffic is limited.

When I am using `PSubscribe` command to subscribe message,

there are many ping packets over the network.

## Expected Behavior

`PSubscribe` succeed and ping channel for 1 minutes once.

## Current Behavior

Ping every seconds!

## Steps to Reproduce

```go
package main

import (
	"context"
	"fmt"

	"github.com/go-redis/redis/v8"
)

func main() {
	var opts redis.Options
	opts.Addr = "127.0.0.1:6379"
	client := redis.NewClient(&opts)
	ps := client.PSubscribe(context.Background(), "hello")
	ch := ps.Channel()
	for {
		select {
		case _, ok := <-ch:
			if !ok {
				return
			}
			fmt.Println("receive message")
		}
	}
}

```
```bash
$ sudo tcpdump -i lo
# catch ping pong packets every seconds
```

**Comment by vmihailenco** [comment]
Redis Server is supposed to serve thousands of commands per second. It is hard to believe that a ping once a second causes any problems.

**Comment by PeerXu** [comment]
@vmihailenco Yes, Redis Server is good enough to handle thousands of commands per second.
But ping once need to cost about 250~ Bytes(Ping packet, Pong packet, TCP ACK packet),
then 648 MBytes per month.
In some IoT situation, data traffic is very limited.

I read the code and found ping period is 1 minutes in old version,
but change to ping every second for faster renew the subscription.
Could we ping faster when disconnected, and ping slower when connected?

**Comment by vmihailenco** [comment]
>Could we ping faster when disconnected, and ping slower when connected?

Yes, this sounds much better. But it still should not be smaller than 5 seconds...

**Comment by rbg** [comment]
sounds like it should be externalized with sensible defaults for the normal use-case. That could allow IOT'ers the option to alter to accommodate Cell/LoRa

**Comment by PeerXu** [comment]
@rbg, I change #1674 to expose the ping strategy interface if set.
Default ping frequency is 1 second as normal use-case.

**Comment by monkey92t** [comment]
redis-server does not resend data on dropped connections, so we need to know that the connection is dropped and reconnect faster. 

I agree with @vmihailenco . you may consider increasing the time, but it should not be too long. If the ping cycle is controlled externally, there will be more unreliability.

**Comment by PeerXu** [comment]
redis-server does not resend data on dropped connections, but redis-cli(or hiredis) does not ping redis-server on subscribe.

I think ping cycle handled by developer is a common situation. 

When I use go-redis to subscribe message first, ping cycle is controlled by library not manually, what an awesome experience.

But more and more difference situations, I need to control ping cycle manually, but not exposed interface.

So we should expose ping cycle handler for developer to control ping cycle with difference strategies in difference situation.

**Comment by monkey92t** [comment]
What I mean is that the ping cycle time can be controlled by parameters, such as the https://github.com/go-redis/redis/issues/1700 scheme.
But do not control the ping scheduling strategy externally, such as the https://github.com/go-redis/redis/pull/1674 scheme. If pubsub is reliable, we can use it more flexibly, but it is not reliable, so we need to detect the offline status and reconnect it as soon as possible.
If the interval between each ping is too long, we can easily lose a lot of data.

I think we can increase the frequency of ping after disconnection on the https://github.com/go-redis/redis/issues/1700 scheme, so that it can recover as quickly as possible.
