### ISSUE TITLE
PubSub isn't closing after context done

### ISSUE THREAD

**Issue by leoleoasd** [go-redis/redis#1677]
My code is someting like this:
```go
sub := redis.Subscribe(request.Context(), "runs")
go func() {
        <- request.Context().Done()
        log.Errorf("CONTEXT END!")
}()
// defer sub.Close()

// Use sub
// ...
```
If I comment out the `sub.Close()`, the sub won't close after my HTTP request's context done. So the Redis connection is never returned to the pool.
## Expected Behavior

Subscription closes after context done.

## Steps to Reproduce

```go
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/go-redis/redis/v8"
)

func main() {
	var opts redis.Options
	opts.Addr = "127.0.0.1:6379"
	client := redis.NewClient(&opts)

	for {
		ctx, _ := context.WithTimeout(context.Background(), time.Second)
		ps := client.PSubscribe(ctx, "hello")
		ch := ps.Channel()
		go func() {
			for {
				select {
				case _, ok := <-ch:
					if !ok {
						return
					}
					fmt.Println("receive message")
				}
			}
		}()
	}
}
```

Then, use `CLIENT LIST` and you can see clients continually growing.

**Comment by wangfengfly** [comment]
i do not think that is a problem, you must close the sub manually when request is done, as go-redis does not know when the request context is done, you can not depend on it to do this work.  The issue can be closed now.

**Comment by vmihailenco** [comment]
Agreed, context only affects the `PSubscribe` command, not the whole `PubSub` or an individual subscription.
