### ISSUE TITLE
Context cancelled in cluster slots lazy reload

### ISSUE THREAD

**Issue by gjacquet** [go-redis/redis#1682]
I have noticed a high error rate in the `cluster slots` command.
Traces show the error as `context canceled`

It seems the `cluster slots` is running past the execution of the get command as shown in this trace:
![image](https://user-images.githubusercontent.com/5912456/110052526-b5113d80-7d25-11eb-89b3-da889beb056a.png)

I believe `func (c *clusterStateHolder) LazyReload(ctx context.Context)` is being called sometimes with the same context as the main command (a simple get in this example). By the time the reload completes the context used for the main command may have been cancelled.

## Expected Behavior

`cluster slots` in the lazy reload should complete successfully even if the context from the command that triggered is has been cancelled.

## Current Behavior

There is some kind of race condition were the lazy reload may fail if the context used for the main command has been cancelled. 

## Possible Solution

I think the lazy reload should use the context from the cluster client rather than the one used in the command, or any context not bound to the execution of the command.

## Steps to Reproduce

It is hard to reproduce reliably but here is the idea:
1. Create a ClusterClient
2. Run a fast command like a get with a cancellable context
3. Immediately cancel the command's context as the command function returns
4. Check the lazy reload failed.

## Context (Environment)

This happens in a web application where the request is a simple lookup in redis and then returns immediately.
I am passing the http.Request.Context() to the redis command. I believe this context gets cancelled at the end of the http request.

## Possible Implementation

It would be possible to add a context to the `clusterStateHolder` which could be initialized from (or the same as) the clusterClient's context.

Using this context instead of the context used for the command would allow for the reload to run safely in the background.
I drafted something real quick there: #1683

**Comment by vmihailenco** [comment]
Thanks for reporting this and for the PR. I've fixed this by not accepting ctx in `LazyReload`.

**Comment by gjacquet** [comment]
Thanks for the quick fix!
When are you planning the next release?

**Comment by gjacquet** [comment]
I have been some test and it seems to be working fine.
I do see the `cluster slots` running with another context in another trace and I no longer see any error related to the `cluster slots` / reload.

**Comment by vmihailenco** [comment]
I've tagged v8.7.1
