### ISSUE TITLE
Redis Cluster connection on minikube times out

### ISSUE THREAD

**Issue by gopherine** [go-redis/redis#1691]
## Expected Behavior

Connect to redis cluster(running on minikube) on local machine

## Current Behavior

connection times out when using `NewClusterClient`
get error https://serverfault.com/questions/812156/redis-cluster-error-moved redis cluster moved when using `NewClient`

## Steps to Reproduce
- Installed redis cluster using helm charts
- expose using nodeport ot port forward on minikube
```go
	redisClient := redis.NewClusterClient(&redis.ClusterOptions{
		Addrs:    []string{"127.0.0.1:6379"},
		Password: "M2eVOyDXqd",
	})

	result, err := redisClient.Ping(context.TODO()).Result()
	if err != nil {
		log.Panic(err)
	}
	fmt.Println("connected", result)
```
the above code times out, I am running this one macos bigsur

**Comment by monkey92t** [comment]
the information you provided is too little. I think it might be a problem with the minikube network settings?
I have not used minikube, but I have not found any problems when using k8s redis cluster
you can try to use redis-cli to test, or use tools to track network packets

**Comment by gopherine** [comment]
> the information you provided is too little. I think it might be a problem with the minikube network settings?
> I have not used minikube, but I have not found any problems when using k8s redis cluster
> you can try to use redis-cli to test, or use tools to track network packets

If minikube settings had problem, it would also not help with a single instance connection but the problem happens only for cluster

I can successfully connect using redis-cli problem occurs only with the go program

Can you guide me through what extra info you need, Because all i did is launch redis cluster and basically try to run the above code. I am not using load balancer but nodeport to expose the endpoints.

**Comment by monkey92t** [comment]
can you provide the redis and minikube versions used? And the configuration items of minikube used (if any, such as yaml file)  and go、go-redis version

I try to copy your environment tomorrow (it's now night in my country) to track the work of go-redis.

**Comment by monkey92t** [comment]
same #1698

**Comment by lily-lee** [comment]
> ## Expected Behavior
> Connect to redis cluster(running on minikube) on local machine
> 
> ## Current Behavior
> connection times out when using `NewClusterClient` get error https://serverfault.com/questions/812156/redis-cluster-error-moved redis cluster moved when using `NewClient`
> 
> ## Steps to Reproduce
> * Installed redis cluster using helm charts
> * expose using nodeport ot port forward on minikube
> 
> ```go
> 	redisClient := redis.NewClusterClient(&redis.ClusterOptions{
> 		Addrs:    []string{"127.0.0.1:6379"},
> 		Password: "M2eVOyDXqd",
> 	})
> 
> 	result, err := redisClient.Ping(context.TODO()).Result()
> 	if err != nil {
> 		log.Panic(err)
> 	}
> 	fmt.Println("connected", result)
> ```
> 
> the above code times out, I am running this one macos bigsur

i met the same problem
