### ISSUE TITLE
Why does the go redis/v8 version function input must have a context type?

### ISSUE THREAD

**Issue by MrGlp** [go-redis/redis#1694]
Why does the go redis/v8 version function input must have a context type?
example: go redis/v8
func (c cmdable) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) *StatusCmd {...}

but go redis does not
example: go redis
func (c cmdable) Set(key string, value interface{}, expiration time.Duration) *StatusCmd {...}

What is the difference and impact on use?

**Comment by vmihailenco** [comment]
context.Context is mainly used for canceling operations and tracing. It is a general Go feature so you should be able to google more info if needed.
