### ISSUE TITLE
V8 performance degradation ~20%

### ISSUE THREAD

**Issue by jfjm2018** [go-redis/redis#1695]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior
Similar performance comparing to V7.

## Current Behavior
~20 degradation.

## Context (Environment)
Simple app that reads from Redis Cluster and returns result via REST. Original version with V7.4.0, and new version with V8.6.0, everything else are the same except changes to accommodate the new API. context.Background is used. The test was done on Linux, Redis 5.0.7.

**Comment by vmihailenco** [comment]
Please provide some program that reproduces the problem.

**Comment by jfjm2018** [comment]
Here is a sample app. The only difference is one uses V7 (7.4.0) and the other uses V8 (8.6.0).
[redis7.go.gz](https://github.com/go-redis/redis/files/6135428/redis7.go.gz)
[redis8.go.gz](https://github.com/go-redis/redis/files/6135429/redis8.go.gz)

**Comment by jfjm2018** [comment]
Further testing shows V8 (8.0.0) is almost on par with V7 (7.4.0). However, 8.1.0 and 8.6.0 shows ~20 degradation.

**Comment by monkey92t** [comment]
@jfjm2018  

HI~, based on the information you provided, I did a simple test.

redis version: Redis server v=6.1.242 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=572ba9acdb92d890

redis-server: 127.0.0.1: 6379

redis-cluster:
master: 127.0.0.1:1001, 127.0.0.1:1002, 127.0.0.1:1003
slave: 127.0.0.1:2001, 127.0.0.1:2002, 127.0.0.1:2003

```go
127.0.0.1:1001> cluster nodes
4baf31a244dd8cb0fdeccebc5bf65875228787cf 127.0.0.1:1003@11003 master - 0 1615710812485 3 connected 10000-16383
04401cd0e1ab632825bbb29ecdf41856b2320650 127.0.0.1:1001@11001 myself,master - 0 1615710810000 1 connected 0-4999
886c44065fc2862889b803ae3f3b64b27a2e9f4f 127.0.0.1:2003@12003 slave 4baf31a244dd8cb0fdeccebc5bf65875228787cf 0 1615710809000 3 connected
56dee0d5a57b3e77fdc417b8b3b927f82a078a87 127.0.0.1:2001@12001 slave 04401cd0e1ab632825bbb29ecdf41856b2320650 0 1615710810458 1 connected
4888357cec2b19de4ce8be45409bcd31f8b35339 127.0.0.1:1002@11002 master - 0 1615710811468 2 connected 5000-9999
88978ac9fb8441e225f51d5639aa5bf91b909a10 127.0.0.1:2002@12002 slave 4888357cec2b19de4ce8be45409bcd31f8b35339 0 1615710809435 2 connected
```

This is the Redis.Client test result: https://github.com/monkey92t/tool/blob/master/Redis-Client-V7-V8.pdf
This is the RedisCluster test result: https://github.com/monkey92t/tool/blob/master/RedisCluster-Client%20V7-V8.pdf
This is the test program: https://github.com/monkey92t/tool/blob/master/main.go

according to the results of this test, I found that there is not much evidence to prove that there is a problem with v8 efficiency, and the network request itself is unstable.

If you have a better test, you can reopen an issue.
