### ISSUE TITLE
Set with KeppTTL is working?

### ISSUE THREAD

**Issue by danielalvarenga** [go-redis/redis#1707]
## Expected Behavior

Set passing `redis.KeepTTL` as expiration should work.

## Current Behavior

When I send `redis.KeepTTL`, I receive the error `ERR syntax error`, but works when I pass a time.

## Steps to Reproduce

```
package databases

import (
	"context"
	"encoding/json"

	"github.com/go-redis/redis/v8"
)

var ctx = context.Background()

// RedisCli represents redis wrapper struct
type RedisCli struct {
	client *redis.Client
	prefix string
}

// NewRedis try to connect with redis
func NewRedis(url, app, sufix string) (RedisCli, error) {
	client := redis.NewClient(&redis.Options{
		Addr:     url + ":6379",
		Password: "", // No password set
		DB:       0,  // Use default DB
	})

	_, err := client.Ping(ctx).Result()
	if err != nil {
		return RedisCli{}, err
	}
	return RedisCli{client: client, prefix: app + ":" + sufix + ":"}, nil
}

// SetDataKeepingExpiration update existing key keeping the ttl (expiration)
func (c RedisCli) SetDataKeepingExpiration(key string, value interface{}) error {
	_, err := c.client.Get(ctx, c.prefix+key).Result()
	if err == redis.Nil {
		return nil
	}

	bt, err := json.Marshal(value)
	if err != nil {
		return err
	}

	return c.client.Set(ctx, c.prefix+key, string(bt), redis.KeepTTL).Err()
}
```

## Context (Environment)

I'm trying to update a cache value keeping the ttl.
I tried the solution in https://github.com/go-redis/redis/issues/1393 , but it did not work.

## Detailed Description

How that is a recent update, I did not find use cases and I did not find mistakes in the implementation, but maybe there is some bug?

**Comment by vmihailenco** [comment]
My guess is that you are using old Redis version that does not have keepttl

**Comment by vmihailenco** [comment]
My guess is that you are using old Redis version that does not have keepttl

**Comment by danielalvarenga** [comment]
> My guess is that you are using old Redis version that does not have keepttl

I got this error before the current error. When I was using the wrong version I received the error saying that keepttl is undefined.
After fix, now I receive the error described in that issue.

**Comment by vmihailenco** [comment]
The following program is working

```go
package main

import (
	"context"

	"github.com/go-redis/redis/v8"
)

func main() {
	ctx := context.Background()

	rdb := redis.NewClient(&redis.Options{
		Addr: ":6379",
	})
	if err := rdb.Set(ctx, "foo", "bar", redis.KeepTTL).Err(); err != nil {
		panic(err)
	}
}
```

You need to figure out what is different on your side.
