### ISSUE TITLE
Upgrade ZRANGE Command

### ISSUE THREAD

**Issue by ragnaros2046** [go-redis/redis#1709]
It would be nice to upgrade [ZRANGE](https://redis.io/commands/zrange) command to reduce the calls. 

Starting with Redis 6.2.0, this command can replace the following commands: ZREVRANGE, ZRANGEBYSCORE, ZREVRANGEBYSCORE, ZRANGEBYLEX and ZREVRANGEBYLEX.

**Comment by monkey92t** [comment]
Yes, the `ZRange` command does support more parameters, but it breaks the compatibility to lower versions.

I don't think that changes can be made at this time.

```go
//old:  ZRANGE key start stop [WITHSCORES]
//new: ZRANGE key min max [BYSCORE|BYLEX] [REV] [LIMIT offset count] [WITHSCORES]
```
