### ISSUE TITLE
Error building project with redis lib : duplicate method private

### ISSUE THREAD

**Issue by avikagg** [go-redis/redis#1715]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

Trying to build sample project with redis library included.
Error:
```
# go.opentelemetry.io/otel/trace
../go.opentelemetry.io/otel/trace/config.go:117:2: duplicate method private
```

Code: 
```
var client = redis.NewClient(&redis.Options{
        Addr:     "host:6379",
        Password: "",
        DB:       0,
})

err := client.Set(ctx, "name", redisValue, 0).Err()
```
## Expected Behavior
Should build the executable file.

## Current Behavior
Facing Error 
```
# go.opentelemetry.io/otel/trace
../go.opentelemetry.io/otel/trace/config.go:117:2: duplicate method private
```

What could be wrong here?

**Comment by vmihailenco** [comment]
Should be variation of https://github.com/go-redis/redis/issues/1534

**Comment by avikagg** [comment]
hi @vmihailenco thanks for your response. 
Actually, I am able to build the package if I exclude redis functionality from the project, only when I include redis functionality it fails with the above error.

**Comment by corlinp** [comment]
Any solution to this @avikagg ? I'm having the same problem, but it was only introduced after I vendored opentelemetry after successfully using the redis package

**Comment by corlinp** [comment]
Turns out the opentelemetry library is not compatible with Go 1.13 or earlier. You are probably trying to build on an older Go version.

**Comment by ravikanthdba** [comment]
I had this issue with go version 1.13.

I installed the following go version 1.16, modified my go.mod file to the following:

`module github.com/example

go 1.16

require (
	github.com/go-redis/redis/v8 v8.8.1
	github.com/gomodule/redigo v1.8.3
	github.com/nitishm/go-rejson/v4 v4.0.0
)
`

my code in main.go:
`
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"

	goredis "github.com/go-redis/redis/v8"
	"github.com/gomodule/redigo/redis"
	rejson "github.com/nitishm/go-rejson/v4"
)

// Name - student name
type Name struct {
	First  string `json:"first,omitempty"`
	Middle string `json:"middle,omitempty"`
	Last   string `json:"last,omitempty"`
}

// Student - student object
type Student struct {
	Name Name `json:"name,omitempty"`
	Rank int  `json:"rank,omitempty"`
}

func Example_JSONSet(rh *rejson.Handler) {

	student := Student{
		Name: Name{
			"Mark",
			"S",
			"Pronto",
		},
		Rank: 1,
	}
	res, err := rh.JSONSet("student", ".", student)
	if err != nil {
		log.Fatalf("Failed to JSONSet")
		return
	}

	if res.(string) == "OK" {
		fmt.Printf("Success: %s\n", res)
	} else {
		fmt.Println("Failed to Set: ")
	}

	studentJSON, err := redis.Bytes(rh.JSONGet("student", "."))
	if err != nil {
		log.Fatalf("Failed to JSONGet")
		return
	}

	readStudent := Student{}
	err = json.Unmarshal(studentJSON, &readStudent)
	if err != nil {
		log.Fatalf("Failed to JSON Unmarshal")
		return
	}

	fmt.Printf("Student read from redis : %#v\n", readStudent)
}

func main() {
	var addr = flag.String("Server", "localhost:6379", "Redis server address")

	rh := rejson.NewReJSONHandler()
	flag.Parse()

	// Redigo Client
	conn, err := redis.Dial("tcp", *addr)
	if err != nil {
		log.Fatalf("Failed to connect to redis-server @ %s", *addr)
	}
	defer func() {
		_, err = conn.Do("FLUSHALL")
		err = conn.Close()
		if err != nil {
			log.Fatalf("Failed to communicate to redis-server @ %v", err)
		}
	}()
	rh.SetRedigoClient(conn)
	fmt.Println("Executing Example_JSONSET for Redigo Client")
	Example_JSONSet(rh)

	// GoRedis Client
	cli := goredis.NewClient(&goredis.Options{Addr: *addr})
	defer func() {
		if err := cli.FlushAll(context.Background()).Err(); err != nil {
			log.Fatalf("goredis - failed to flush: %v", err)
		}
		if err := cli.Close(); err != nil {
			log.Fatalf("goredis - failed to communicate to redis-server: %v", err)
		}
	}()
	rh.SetGoRedisClient(cli)
	fmt.Println("\nExecuting Example_JSONSET for Redigo Client")
	Example_JSONSet(rh)
}

`

This worked and the output is below:
`
rgarimel-mn3:example rgarimel$ go run main.go
Executing Example_JSONSET for Redigo Client
Success: OK
Student read from redis : main.Student{Name:main.Name{First:"Mark", Middle:"S", Last:"Pronto"}, Rank:1}

Executing Example_JSONSET for Redigo Client
Success: OK
Student read from redis : main.Student{Name:main.Name{First:"Mark", Middle:"S", Last:"Pronto"}, Rank:1}
rgarimel-mn3:example rgarimel$
`

I this is needs to be explicitly mentioned

**Comment by SUN-XIN** [comment]
I got the same problem today. The I solved it by updating the version de the lib /go-redis.
I use also go1.13, you can use the version `v8.6.0` of this lib if you don't want to update to go1.14
And update your go.mod like `github.com/go-redis/redis/v8 v8.6.0`

**Comment by vmihailenco** [comment]
Seems to be fixed - closing.
