### ISSUE TITLE
tcp connection closed

### ISSUE THREAD

**Issue by closetool** [go-redis/redis#1727]
When I use this library in concurrent condition, there's always an error: `redis: 2021/04/15 19:27:51 pubsub.go:168: redis: discarding bad PubSub connection: read tcp 127.0.0.1:41902->127.0.0.1:6379: use of closed network connection`
How could I fix it?

**Comment by vmihailenco** [comment]
That is probably because you close your Redis client without closing PubSub connections. It is hard to tell more without details.

**Comment by closetool** [comment]
@vmihailenco It works! Thinks!
