### ISSUE TITLE
dial tcp i/o timeout

### ISSUE THREAD

**Issue by linsijia1002** [go-redis/redis#1740]
Here is my code:
func NewRedisCluster(ip, port, password string) (ICache, error) {
	var ipList, portList, svrList []string

	ipList = strings.Split(ip, ",")
	portList = strings.Split(port, ",")

	for i, v := range ipList {
		svrList = append(svrList, v + ":" + portList[i])
	}

	fmt.Println(svrList)

	cluster := r.NewClusterClient(&r.ClusterOptions{
		Addrs:  svrList,
		Password: password,
		OnConnect: func(ctx context.Context, cn *r.Conn) error {
			cp_log.Info("cluster connect! %s", cn.String())
			return nil
		},
	})
	fmt.Println("create cluster success")

	cmd := cluster.Do(context.Background(), "set", "test02", "value02")
	if cmd.Err() != nil {
		panic("redis test fail: " + cmd.Err().Error())
	}
	fmt.Println("success cluster")
}

Here is my print:
[1.14.145.17:7001 1.14.145.17:7002 1.14.145.17:7003 1.14.145.17:7004 1.14.145.17:7005 1.14.145.17:7006]
create cluster success
2021/04/27 17:03:30.398 [I] [redisCluster.go:34]  cluster connect! Redis<1.14.145.17:7005 db:0>
2021/04/27 17:03:30.492 [I] [redisCluster.go:34]  cluster connect! Redis<1.14.145.17:7003 db:0>
2021/04/27 17:03:40.605 [I] [redisCluster.go:34]  cluster connect! Redis<1.14.145.17:7006 db:0>
2021/04/27 17:03:50.645 [M] [instance.go:61]  redis test fail: dial tcp 172.16.0.12:7003: i/o timeout

Here is my config file:
port 7001
requirepass 1234
masterauth 1234
protected-mode yes
daemonize no
appendonly yes
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 15000
cluster-announce-ip 1.14.145.17
cluster-announce-port 7001                  (7001..7006)
cluster-announce-bus-port 17001         (17001..17006)

Here is my create cluster cmd:
redis-cli -a 1234 --cluster create 172.16.0.12:7001 172.16.0.12:7002 172.16.0.12:7003 172.16.0.12:7004 172.16.0.12:7005 172.16.0.12:7006 --cluster-replicas 1

Q: Is connect to 172.16.0.12:7003 is right?  The IP 172.16.0.12 is my server's lan ip,  local can't access. 
How should i do or config?

**Comment by monkey92t** [comment]
`ClusterClient` uses the address returned by https://redis.io/commands/cluster-slots

**Comment by linsijia1002** [comment]
> `ClusterClient` uses the address returned by https://redis.io/commands/cluster-slots,
> You can refer to the detailed redis-cluster documentation: https://redis.io/topics/cluster-tutorial/

First,  tks for your answer.
The _CLUSTER SLOTS_ cmd return the instances addr list, but is the remote server lan ip addr :( , local pc can't access!

**Comment by monkey92t** [comment]
Yes, I understand what you mean. But we can only get the node address of the cluster in this way, you need to ensure that the client can access all the cluster nodes.

**Comment by wziww** [comment]
you can change slots' address in redis-server config file manually in development so that your local pc can access to it, but not suggested in production.

**Comment by linsijia1002** [comment]
> you can change slots' address in redis-server config file manually in development so that your local pc can access to it, but not suggested in production.

ok, thank u guys.
I guess I'll just have to build the vmware at local
