### ISSUE TITLE
Compatibility with go modules

### ISSUE THREAD

**Issue by mkaiser323** [go-redis/redis#1741]
For compatibility with go modules, major versions higher than v2 need to follow the convention defined in https://blog.golang.org/v2-go-modules

## Expected Behavior

1. When I run the command `go get github.com/go-redis/redis` it should get the latest version
2. When I run the command `go get github.com/go-redis/redis@v8.8.2` it should get `v8.8.2`

## Current Behavior

1. While opted into go modules, when I run the command `go get github.com/go-redis/redis` it gets `v6.15.9`. This is because that is the last version that is not opted into go modules. If opted into go modules, it expects it to follow the convention explained above, which is not followed by `v7.0.0` and above. Thus it considers `v6.15.9` the last valid version.

2. While opted into go modules, when I run the command `go get github.com/go-redis/redis@v8.8.2` it shows the following error:

``` 
require github.com/go-redis/redis: version "v8.8.2" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v8
```

## Possible Solution

Implement the convention described in https://blog.golang.org/v2-go-modules
I.e, for the latest major version `v8` use a subfolder named `v8` 

## Steps to Reproduce

1. Create a go project that uses go modules
2. Create a basic hello-world example that uses `https://github.com/go-redis/redis`
3. run `go get github.com/go-redis/redis` to demonstrate that it does not get the latest version
4. run `go get github.com/go-redis/redis@v8.8.2` to see error message about incompatible major version

## Context (Environment)

As more projects move to go modules, this will be needed in order to allow users to use the latest version of the code. As of right now, only `v6.15.9` and under are usable by projects using go modules.

## Detailed Description

Implement the convention described in https://blog.golang.org/v2-go-modules:

> a new major version of a module must have a different module path than the previous version. Starting with v2, the major version must appear at the end of the module path

> For example, when the authors of the module github.com/googleapis/gax-go developed v2, they used the new module path github.com/googleapis/gax-go/v2. Users who wanted to use v2 had to change their package imports and module requirements to github.com/googleapis/gax-go/v2

For example, for the latest major version `v8` you would use a subfolder named `v8`

**Comment by vmihailenco** [comment]
It should be `go get github.com/go-redis/redis/v8@v8.8.2`

**Comment by monkey92t** [comment]
Doc:

```go
If an old package and a new package have the same import path,
the new package must be backwards compatible with the old package.
```

And

```go
For example, when the authors of the module github.com/googleapis/gax-go developed v2, they used the new module path github.com/googleapis/gax-go/v2. Users who wanted to use v2 had to change their package imports and module requirements to github.com/googleapis/gax-go/v2.
```

so...`go get github.com/go-redis/redis` is not allowed to obtain v8 version.
