### ISSUE TITLE
Option to limit number of connections when using a connection pool

### ISSUE THREAD

**Issue by sidprak** [go-redis/redis#1763]
Currently, the pooling behavior is just to open non-pooled connections if we have gone beyond the pool size (https://github.com/go-redis/redis/blob/master/internal/pool/pool.go#L161-L164). It would be nice to support a mode where we just return errors if the pool is empty. Silently opening extra connections is good to not error on extra commands, but it makes connection pool issues difficult to debug.

## Expected Behavior

Create a new pooling mode so that an error is returned instead of opening extra connections, when we reach the pool size.

## Current Behavior

See above.

## Possible Solution

See above. 

## Steps to Reproduce

See above.

## Context (Environment)

We started to see severe performance issues due to extra connections constantly being opened to Redis. It was very difficult to see why this was happening since the pool size was set to a low number. We then discovered that the go-redis library opens extra connections when necessary.

## Detailed Description

* Add a new boolean option, `LimitPoolSize` for example.
* If this option is set, throw an error in this condition: https://github.com/go-redis/redis/blob/master/internal/pool/pool.go#L162.
* If the option is not set, the behavior is unchanged from today.

**Comment by sidprak** [comment]
I can make a pull request for this if accepted.

**Comment by vmihailenco** [comment]
@sidprak that [code](https://github.com/go-redis/redis/blob/master/internal/pool/pool.go#L162) should not trigger unless you are using `MinIdleConns > 0`. If so, setting `MinIdleConns = 0` should help.

go-redis can only open extra connections if you are using `PubSub` a lot and do not close it properly. In all other cases, go-redis pool should stay within the limits.

If that info does not help, please provide a reproducer.

**Comment by sidprak** [comment]
Thanks @vmihailenco. I see that now.

We are using the connection pool with pool size = 15 and min idle conns = 5, because opening connections is very expensive in our environment. However, when we inspected one of our production workloads, we saw that it had 90 connections open to the Redis server. I'll try to get this down to a minimal case and add some stats.

**Comment by sidprak** [comment]
@vmihailenco on second thought, I'm not sure I understand. This is what I see:
* I see https://github.com/go-redis/redis/blob/master/internal/pool/pool.go#L162 is triggering if `pooled` is true
* We call newConn with pooled set to true from https://github.com/go-redis/redis/blob/master/internal/pool/pool.go#L258
* And that is called from https://github.com/go-redis/redis/blob/master/redis.go#L207

Would that still trigger the code to go over the pool size? We are not using PubSub here, only get, set and hash operations.

**Comment by vmihailenco** [comment]
>Would that still trigger the code to go over the pool size?

It should not. With MinIdleConn=0 the sequence is:
- wait for our turn which effectively limits the number of connections (see waitTurn)
- get the idle conn or create a new one
- do some work with with the conn
- put the conn to the pool
- free turn

With `MinIdleConns > 0` it is more complicated because there is a separate thread that tries to add a conn async from the main code path.

**Comment by sidprak** [comment]
I see, thanks for explaining. We do have `MinIdleConns > 0`. Is there a way to limit the maximum number of connections when `MinIdleConns > 0`? Basically, in our application, we want to pre-open some number of connections at startup, but we also don't want the connection pool to grow unbounded.

**Comment by sidprak** [comment]
I guess that also shouldn't happen under normal operations. I'll keep testing and let you know if I find anything. Thanks again for explaining how things work!

**Comment by sidprak** [comment]
We've gotten to the bottom of this. There was a configuration issue in our code which resulted in a pool size of 0 being passed in and defaulting to 10 connections per CPU. This is the reason we were seeing so many connections.
