### ISSUE TITLE
[BUG] XReadGroup method hashes incorrect key. Leads to NOGROUP error.

### ISSUE THREAD

**Issue by dhh93** [go-redis/redis#1766]
Hello,

There seems to be a bug in the slice indexing logic in the `XReadGroup` method that results in the incorrect key being hashed. When used with `Ring`, this causes the client to search through an incorrect shard, which throws a `NOGROUP` / key not found error.

I think the initial `keyPos` in [commands.go/Line 1774](https://github.com/go-redis/redis/blob/8f0fbd2fe81b4af1a394a0109820362df011c0ae/commands.go#L1774) should start at `3` instead of `1`. Because `GROUP group consumer` are three required parameters in the [XREADGROUP](https://redis.io/commands/xreadgroup) command, the current iteration logic stops about 3 indices too short.

## Expected Behavior

Consider the following command:

`XREADGROUP GROUP foo bar COUNT 10 BLOCK 0 STREAMS hello >`
- `keyPos` should be `9`, but the current value is `6`. Code hashes `block` instead of `hello`.

If `COUNT` is omitted (pulling in every message):

`XREADGROUP GROUP foo bar BLOCK 0 STREAMS hello >`
- `keyPos` should be `7`, but the current value is `4`. 

## Current Behavior

See above.

## Possible Solution

1. Change starting index position to 3 in [Line 1774](https://github.com/go-redis/redis/blob/8f0fbd2fe81b4af1a394a0109820362df011c0ae/commands.go#L1774)
2. Increment `keyPos` by 2 instead of 1 in [Line 1785](https://github.com/go-redis/redis/blob/8f0fbd2fe81b4af1a394a0109820362df011c0ae/commands.go#L1785) to start at first key instead of the `STREAMS` parameter

### Current code

```go
	keyPos := int8(1) 
	if a.Count > 0 {
		args = append(args, "count", a.Count)
		keyPos += 2
	}
	if a.Block >= 0 {
		args = append(args, "block", int64(a.Block/time.Millisecond))
		keyPos += 2
	}
	if a.NoAck {
		args = append(args, "noack")
		keyPos++
	}
	args = append(args, "streams")
	keyPos++
	for _, s := range a.Streams {
		args = append(args, s)
	}
```

### Proposed Change

```go
	keyPos := int8(3) // XREADGROUP GROUP group consumer are required parameters, start at index 3
	if a.Count > 0 {
		args = append(args, "count", a.Count)
		keyPos += 2
	}
	if a.Block >= 0 {
		args = append(args, "block", int64(a.Block/time.Millisecond))
		keyPos += 2
	}
	if a.NoAck {
		args = append(args, "noack")
		keyPos++
	}
	args = append(args, "streams")
	keyPos += 2 // increment by 2 instead of 1 so the cursor starts at first key
	for _, s := range a.Streams {
		args = append(args, s)
	}
```

## Steps to Reproduce

1. `*Ring` client with >1 shard
2. Stream `hello` with consumer group `foo`

Sample code below:

```go
package main

import (
	"context"

	"github.com/go-redis/redis/v8"
)

func main() {
	rdb := redis.NewRing(&redis.RingOptions{
		Addrs: map[string]string{
			"shard1": ":7000",
			"shard2": ":7001",
			"shard3": ":7002",
		},
	})

	// create stream "hello" with consumer group "foo" and ID "0" (fetch entire msg history)

	_, _ = rdb.XGroupCreateMkStream(context.Background(), "hello", "foo", "0")

	// add test message

	xArgs := &redis.XAddArgs{
		Stream: "hello",
		Values: map[string]interface{}{
			"hello": "world",
		},
	}

	_, _ = rdb.XAdd(context.Background(), xArgs).Result()

	// read message from stream as consumer "Bob" and group "foo"

	readArgs := &redis.XReadGroupArgs{
		Group:    "foo",
		Consumer: "Bob",
		Streams:  []string{"hello", ">"},
		Count:    10,
		// Block and NoAck zero values
	}

	_, _ = rdb.XReadGroup(context.Background(), readArgs).Result()

	// Should throw the following error:
	// NOGROUP No such key 'hello' or consumer group 'foo' in XREADGROUP with GROUP option

}
```

**Comment by dhh93** [comment]
We may also have to account for cases in which there are reads from multiple streams that may potentially be residing on different shards. The current logic only hashes the first key.

**Comment by monkey92t** [comment]
Yes, it has errors
