### ISSUE TITLE
Too many connections

### ISSUE THREAD

**Issue by DaveBlooman** [go-redis/redis#177]
I have a project that I recently deployed to AWS using elasticache.  When load testing to 500 requests per second, we found that the host was maintaining the connections to redis, which we believe is causing redis connection pool timeouts.  Could you give some advice on how to debug this, here is the connection setup

```go
package caching

import (
	"os"
	"time"

	"gopkg.in/redis.v3"
)

type RedisCache struct {
	client *redis.Client
}

func (c *RedisCache) getClient() *redis.Client {
	if c.client == nil {
		c.client = redis.NewClient(&redis.Options{
			Addr:        os.Getenv("REDIS_HOST"),
			Password:    "", // no password set
			DB:          0,  // use default DB
			DialTimeout: 3 * time.Second,
			PoolSize:    300,
		})
	}

	return c.client
}

func (c *RedisCache) Get(key string) (string, error) {
	return c.getClient().Get(key).Result()
}

func (c *RedisCache) Set(key string, data string, expiration time.Duration) (string, error) {
	return c.getClient().Set(key, data, expiration).Result()
}
```

**Comment by vmihailenco** [comment]
From what I know 500 SET/GET req/s is nothing for Redis and go-redis client. But still did you check Redis http://redis.io/commands/slowlog? Can it be that Redis is busy processing some slow command?

Also check https://github.com/go-redis/cache that have some in-process cache for super-hot items.

**Comment by vmihailenco** [comment]
You can also run your tests with `PoolSize = 1` or `PoolSize = 2` to make sure that you properly close `redis.Multi` or `redis.PubSub`. You can also grep for `redis.Multi` and `redis.PubSub` to check that you `Close` them when work is done.

**Comment by vmihailenco** [comment]
Hopefully my advices were helpful :)
