### ISSUE TITLE
How to implement periodic refresh topology

### ISSUE THREAD

**Issue by smartnews-weitao** [go-redis/redis#1772]
My redis cluster is on top of kubernetes, so sometimes i may move the entire cluster to another set of nodes and they all change ip address. So my go-redis client needs to refresh the topology from time to time. I am wondering is there a config to do that? Or do i need to send some cluster-nodes command from time to time?

**Comment by smartnews-weitao** [comment]
> After the migration, it seems to be a new cluster, not an extension of the original cluster.

Yes, but if i periodically call 'cluster nodes' command from go-redis client, it will be able to catch the new cluster's address. Wondering why is that?

**Comment by monkey92t** [comment]
I don't know the network structure of kubernetes and your redis-cluster migration process. If it is a gradual migration of a single node, go-redis can know the new node

**Comment by smartnews-weitao** [comment]
Yes, i am gradually migrated every redis instance to new node. So they are restarted with new ip one by one.

**Comment by smartnews-weitao** [comment]
> I don't know the network structure of kubernetes and your redis-cluster migration process. If it is a gradual migration of a single node, go-redis can know the new node

The problem is, my client might don't have any traffic to redis-cluster sometimes. So do i need to send 'cluster nodes' periodically from client if i want to catch such migration?

**Comment by monkey92t** [comment]
You can try `clusterClient.ReloadState(ctx)`, it will reload the cluster state.

**Comment by smartnews-weitao** [comment]
> You can try `clusterClient.ReloadState(ctx)`, it will reload the cluster state.

So it will randomly chose a instance and send cluster slots to it to refresh the topology? Will this lazy reload also be triggered if client received a 'moved' or 'ask' or timeout from redis?

**Comment by monkey92t** [comment]
> > You can try `clusterClient.ReloadState(ctx)`, it will reload the cluster state.
> 
> So it will randomly chose a instance and send cluster slots to it to refresh the topology? Will this lazy reload also be triggered if client received a 'moved' or 'ask' or timeout from redis?

Yes, ReloadState(ctx) will try to trigger using one node. If it fails, it will continue to try other nodes. If all nodes (loaded) fail, it will generate an error.

This behavior is triggered in many situations, but not including move and ask.

**Comment by monkey92t** [comment]
If you customize the ClusterOptions.ClusterSlots configuration item, it will use the node information you defined and will not obtain it from redis-cluster.

**Comment by smartnews-weitao** [comment]
> > > You can try `clusterClient.ReloadState(ctx)`, it will reload the cluster state.
> > 
> > 
> > So it will randomly chose a instance and send cluster slots to it to refresh the topology? Will this lazy reload also be triggered if client received a 'moved' or 'ask' or timeout from redis?
> 
> Yes, ReloadState(ctx) will try to trigger using one node. If it fails, it will continue to try other nodes. If all nodes (loaded) fail, it will generate an error.
> 
> This behavior is triggered in many situations, but not including move and ask.

Can you give me some triggered situations? Really appreciate it.

**Comment by monkey92t** [comment]
> Can you give me some triggered situations? Really appreciate it.

Places that may be triggered (when executing commands)
1. The cluster information is saved for up to 10 seconds, and it will be judged whether it needs to be refreshed when the command is executed (it will not be refreshed if the command is not executed).
2. When the node becomes read-only, send a write command.
3. Pipeline.

**Comment by monkey92t** [comment]
@smartnews-weitao  If you have no more questions, can we close the issue?

**Comment by smartnews-weitao** [comment]
Yes, i think i call the clusterClient.ReloadState(ctx) every 30 seconds, i can find the migration of entire cluster and refresh my topology.

**Comment by monkey92t** [comment]
OK, If there are more findings, you can reopen the issue.
