### ISSUE TITLE
In sentinel mode, How do I dispatch any query request to the slave node?

### ISSUE THREAD

**Issue by tianshr123** [go-redis/redis#1779]
I have a cluster environment and the current data access traffic is extremely high, the master node processes all requests, as a result, the redis CPU usage of the master node reaches 100%.
In sentinel mode, all the connections are created using the master info. is there any method for dispatching some query requests to the standby node? 
![image](https://user-images.githubusercontent.com/69893838/120298062-4fb8f280-c2fc-11eb-9029-2324c234bc60.png)

**Comment by monkey92t** [comment]
@tianshr123 You can try `redis.NewFailoverClusterClient(opt)`
Please pay attention to `RouteByLatency` and `RouteRandomly` options.

**Comment by tianshr123** [comment]
@monkey92t 
Thank you. That's exactly what I need.

**Comment by nsmosi** [comment]
I have tried the both option but still does not work:
```go
RouteByLatency:   true,
RouteRandomly:    true,
```
