### ISSUE TITLE
I have an issue when get cache

### ISSUE THREAD

**Issue by hoangan1903** [go-redis/redis#1783]
when Redis cannot get the cache, I have received this error

runtime error: invalid memory address or nil pointer dereference
C:/Program Files (x86)/Go/src/runtime/panic.go:212 (0x3432c3)
        panicmem: panic(memoryError)
C:/Program Files (x86)/Go/src/runtime/signal_windows.go:246 (0x34318f)
        sigpanic: panicmem()
C:/Program Files (x86)/Go/src/runtime/internal/atomic/asm_386.s:105 (0x30204c)
        Xadd64: MOVL    0, AX // crash when unaligned
C:/Users/ADMIN/Projects/go/src/dom/vendor/github.com/go-redis/cache/cache.go:199 (0xafbb43)
        (*Codec).getBytes: atomic.AddUint64(&cd.misses, 1)
C:/Users/ADMIN/Projects/go/src/dom/vendor/github.com/go-redis/cache/cache.go:159 (0xafb86d)
        (*Codec)._get: b, err := cd.getBytes(key, onlyLocalCache)
C:/Users/ADMIN/Projects/go/src/dom/vendor/github.com/go-redis/cache/cache.go:149 (0xafb795)
        (*Codec).get: err = cd._get(key, object, false)
C:/Users/ADMIN/Projects/go/src/dom/vendor/github.com/go-redis/cache/cache.go:136 (0xafd402)
        (*Codec).Get: return cd.get(nil, key, object)

**Comment by vmihailenco** [comment]
Should be in https://github.com/go-redis/cache, but it is not clear which version you are using.
