### ISSUE TITLE
Add support for GT and LT in ZADD

### ISSUE THREAD

**Issue by chorin1** [go-redis/redis#1789]
## Expected Behavior
Since Redis 6.2 [ZADD](https://redis.io/commands/ZADD) has additional useful options - `LT` (less than) and `GT` (greater than). 
There should be corresponding functions in go-redis -> `ZAddLT` & `ZAddGT`.

## Possible Implementation

Since GT, LT and NX options are mutually exclusive there are two ways to go from here:
1. Add ZAddLT/GT + ZIncrGT/LT + ZAddXXGT/LT (total of 6 functions)
2. Have a single ZAdd function and introduce a Zadd options struct => breaking change.

**Comment by chorin1** [comment]
If there's interest, I can cook up a PR

**Comment by monkey92t** [comment]
We can keep the more commonly used API, such as:
`zadd key score member...`
`zaddNX..`

In addition, we can add an API that supports all parameters, such as `ZAddArgs(ctx, key, *ZAddArgs)`
What do you think?

**Comment by vmihailenco** [comment]
+1 to `ZAddArgs(ctx, key, ZAddArgs)` (not a `*ZAddArgs` since it is a small struct)

**Comment by monkey92t** [comment]
@chorin1 HI~
I am currently upgrading the `sorted set` series of commands. If you have no plans at this time, I will modify the `ZADD` command

**Comment by chorin1** [comment]
@monkey92t go ahead.
I saw that you already transitioned the item to "in-progress" so I didn't start any work on my end.
LMK if you need help.
