### ISSUE TITLE
How to check if current client is closed

### ISSUE THREAD

**Issue by y2mao** [go-redis/redis#179]
Hi,

I'd like to know if I can detect current client is closed or not, just like following commented line

```go
var (
	currentRedis  *redis.Client
	redisLock     sync.Mutex
)

func Redis() *redis.Client {
	// if currentRedis == nil || currentRedis.IsClosed() {
	if currentRedis == nil {
		redisLock.Lock()
		defer redisLock.Unlock()

		if currentRedis == nil {
			opt := config.Current().Redis.ToRedisOptions()
			client := redis.NewClient(opt)
			if _, err := client.Ping().Result(); err != nil {
				panic(fmt.Errorf("[redis] %#v", err))
			} else {
				currentRedis = client
			}
		}
	}

	return currentRedis
}
```

**Comment by dim** [comment]
It's normally not something you would need, as clients are intentionally
closed by developers. Your code sample is a little confusing, but you could
call `currentRedis = nil` after closing the client.

**Comment by y2mao** [comment]
Hi @dim. Actually I was going to maintain a global variable  of `redis.Client`.  So it could be reused by each request to redis. But once it get error, the connection will be closed and following request will receive a error `client is closed.` That's why I'm looking for a property or function to detect if connection is closed. 

But I just found that go-redis supports connection pool. So could you please give me some advice about the best practice of such scenario? Should I  `redis.NewClient` and close it for every request?

Thank you

**Comment by dim** [comment]
Hmm, why would you close and re-initialise the client? Redis clients
maintain their own pools and will close and restart connections
automatically on errors.

**Comment by ferhatelmas** [comment]
For example, in tests, if a client is wrapped and used in multiple places and we always lint err check, simple deferring wouldn't be possible because the client can be closed once. It would be nice if `ErrClosed` was exported to conditionally close instead of error message.
