### ISSUE TITLE
 ClientID() return error 

### ISSUE THREAD

**Issue by gepengscu** [go-redis/redis#1790]
r := redis.NewClient(
  &redis.Options{
     Addr:     "localhost:6379",
    Password: "", // no password set
    DB:       0,  // use default DB
  })
  log.Println(r.ClientID(ctx).Result())
  //  output: 0 ERR Syntax error, try CLIENT (LIST | KILL ip:port | GETNAME | SETNAME connection-name)

**Comment by wziww** [comment]
https://redis.io/commands/client-id

**Comment by monkey92t** [comment]
Available since 5.0.0.
