### ISSUE TITLE
git tag v6.15.9 redis aws redis cluster mode. sdk also send request to slave node after slave stop server

### ISSUE THREAD

**Issue by CUIZIHANG-cmyk** [go-redis/redis#1794]
The client does not seem to know that the slave has stopped serving. The client continues to send requests to the slave, and then a connection refused error occurs

Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior

After the slave node is stopped, no request is sent to it. The SDK can respond in time

## Steps to Reproduce

1.
2.
3.
4.

**Comment by monkey92t** [comment]
6.15.9 is a long time ago version, it may have some problems, have you tried the latest version?

**Comment by monkey92t** [comment]
The redis cluster depends on the result of the cluster slots command (returned nodes). In v6.15.9, the refresh interval is 1 minute (10 seconds in v8).

**Comment by monkey92t** [comment]
If you have no more questions, I will close this issue.
