### ISSUE TITLE
Redis Pool links go up but not down

### ISSUE THREAD

**Issue by boteman0206** [go-redis/redis#1796]
this is my setting

redisHandle = redis.NewClient(&redis.Options{
		Addr:         addr,
		Password:     pwd,
		DB:           db,
		MinIdleConns: 28,
		IdleTimeout:  30,
		PoolSize:     512,
		MaxConnAge:   30 * time.Second,
	})
	_, err := redisHandle.Ping().Result()
	if err != nil {
		panic(err)
	}

**Comment by monkey92t** [comment]
You can consider reducing the value of poolsize.

**Comment by monkey92t** [comment]
In addition, the IdleTimeout option is time.Duration, you set 30 (nanoseconds), a connection is only idle for 30 nanoseconds, the correct setting example: 2 * time.Second

**Comment by monkey92t** [comment]
If you have a new discovery, you can reopen the issue.

**Comment by boteman0206** [comment]
ok,thinks
