### ISSUE TITLE
aliyun redis set  error 

### ISSUE THREAD

**Issue by dafa168** [go-redis/redis#1797]
## Detailed Description

code： 
![image](https://user-images.githubusercontent.com/2015166/123364418-f2385e80-d5a6-11eb-9ecf-a739656dc79c.png)

![image](https://user-images.githubusercontent.com/2015166/123364438-fb293000-d5a6-11eb-9ae1-d696a0563435.png)

阿里云redis 
set  zxc "test" keepttl
(error) ERR syntax error

**Comment by monkey92t** [comment]
Need redis-server >= 6.0 (#1774)
Please confirm the version of aliyun redis service.

**Comment by monkey92t** [comment]
If you have a new discovery, you can reopen the issue.

**Comment by dafa168** [comment]
yes got ! aliyun redis version is 5.x

**Comment by monkey92t** [comment]
It is a limitation of redis-server, not go-redis (https://redis.io/commands/set).
I will add a comment to Get() later to mark the usage instructions for KeepTTL.
