### ISSUE TITLE
Possible bug: ConnPool.Get return "redis: connection pool timeout" with BLPop

### ISSUE THREAD

**Issue by sesky4** [go-redis/redis#1798]
## Version I'm using
github.com/go-redis/redis/v8 v8.10.0

## What happened
1. create a client
```
       runtime.NumCPU() == 8
       redis.NewClient(&redis.Options{
		Addr:         s.conf.Redis.Addr,
		Username:     s.conf.Redis.Username,
		Password:     s.conf.Redis.Password,
		MinIdleConns: 10, 
	})
```
2. create a lot of goroutine each calling `client.BLPop(context.Background(), ...)` with no timeout
3. some client.BLPop calls return error: "redis: connection pool timeout", when all other connections are blocked.

## Expected behavior
client.BLPop created a new temp connection to do the request

## My thoughts
I looked into ConnPool.Get
```
1. it calls ConnPool.waitTurn, which want to put an object into p.queue
2. since all other connection are blocked in the BLPop call, no one will release the object from p.queue
3. this goroutine got timeout from timer.C
```

Is that intended or a bug?

**Comment by monkey92t** [comment]
BLPOP is a blocking command and is limited by the connection pool size (PoolSize). I think it is not a good idea to use a new connection every time. If you have a large number of BLPOP or similar blocking commands, you can adjust the size of PoolSize.

**Comment by vmihailenco** [comment]
I agree with @monkey92t that the best solution is probably to increase `PoolSize` and somehow limit the number of `BLPop` goroutines in your program.

>client.BLPop created a new temp connection to do the request

Always creating a new connection is (very) expensive. And creating a separate pool just for BLPop looks like an overkill.

**Comment by sesky4** [comment]
Yes, sir. Thanks XD
