### ISSUE TITLE
Question regarding cluster pipeline

### ISSUE THREAD

**Issue by smartnews-weitao** [go-redis/redis#1804]
I read the doc that pipeline is thread-safe. However, i have multiple goroutines, and each one of them will handle request in parallel. So in each request, goroutine will create a pipeline and do some batch operation (no need to be transaction, just normal batch read). I am wondering will multiple pipeline in parallel be handled correctly and the result in each pipeline is correct?

**Comment by monkey92t** [comment]
Yes, the difference between pipes and ordinary commands is that multiple commands are sent at once.

**Comment by smartnews-weitao** [comment]
I see, let me give an example:
thread 1:
pipe1(get k1, k2, k3)

thread 2:
pipe2(get k4, k5, k6)

thread 1 & 2 are running in parallel. I am wondering pipe1 will correctly get v1,v2,v3 and pipe2 will correctly get v4,v5,v6 right?

Thank you in advance.

**Comment by monkey92t** [comment]
Yes
