### ISSUE TITLE
Scan not working on nested structure

### ISSUE THREAD

**Issue by csdenboer** [go-redis/redis#1806]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior

Scan should also work on nested structure

## Current Behavior

Nested field set to nil. It also doesn't even seem to call UnmarshalBinary.

## Steps to Reproduce
```
type CIDRBlocks []*net.IPNet

func (c CIDRBlocks) MarshalBinary() (data []byte, err error) {
	bytes, err := json.Marshal(c)
	return bytes, err
}

func (c *CIDRBlocks) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, c)
}

type Test struct {
	CIDRBlocks CIDRBlocks `redis:"cidr_blocks"`
}
client.HMSet(ctx, "test", "cidr_blocks", t.CIDRBlocks)
res := r.client.HGetAll(ctx, "test")
if err := res.Err(); err != nil {
        return nil, err
}

var t Test
if err := res.Scan(&t); err != nil {
        return nil, err
}
```

result HGETALL: map[cidr_blocks:[{"IP":"192.0.2.0","Mask":"////AA=="}]] 
result t: &t.Test{CIDRBlocks:t.CIDRBlocks(nil)}

**Comment by monkey92t** [comment]
Scan is only an auxiliary method, it does not call the external Unmarshal, are you interested? Can provide PR

**Comment by csdenboer** [comment]
Thanks for your comment. I checked the PR, but it doesn’t seem to implement a solution for this case.

**Comment by knadh** [comment]
Redis responses aren't nested. The `Scan()` method is for scanning Redis results as is. If some of those values have arbitrary serialization (JSON, msgpack etc.), you should unmarshal them separately.
