### ISSUE TITLE
Redis Publish Subscribe stop working when connect to external server, unstable network after a while

### ISSUE THREAD

**Issue by nguyenxuantuong** [go-redis/redis#181]
Hi,

I have recently moved the redis-server into another cloud instance and having go redis subscribe to it from another server. But after running for a while (about hour or so), the subscriber didn't receive the newly published message anymore. It might be due to the unstable network between 2 servers which cause lost redis connection or some unknown reasons. I am wondering if there is anyway to overcome that problem?

Below is the code which I used:

	client := goRedis.NewClient(&goRedis.Options{
		Addr:     Address,
		Password: Password, // no password set
		DB:       DB,  // use default DB
		MaxRetries: 5,
	})

	if _, err := client.Ping().Result(); err != nil {
		log.Fatal("unable to ping redis");
	}

	ticker := time.NewTicker(time.Duration(1) * time.Second)

	//this is to send "ping" request each second for health-check
	go func() {
		for {
			select {
			case <- ticker.C:
				//send heart-beat signal to check if everything is ok
				if _, err := client.Ping().Result(); err != nil {
					log.Error("unable to ping redis");
				}
			}
		}
	}()

	//create a client to pub/sub redis
	pubsub := client.PubSub()

	if err := pubsub.Subscribe("REDIS_CHANNEL"); err != nil {
		log.Fatal("unable to subscribe redis");
	}

	//run in another go-routines
	go func(){
		for {
			msgi, err := pubsub.ReceiveTimeout(0 * time.Millisecond)
			if err != nil {
				if neterr, ok := err.(net.Error); ok && neterr.Timeout() {
					// There are no more messages to process. Stop.
					break
				}
				panic(err)
			}

			switch msg := msgi.(type) {
				case *goRedis.Subscription:
					log.Info("subscribe to redis", msg.Kind, msg.Channel)
					//TODO: check if channel in the list; if not; push it into the list
				case *goRedis.Message:
					//ACTUAL EVENT HANDLER (NO MESSAGE "RECEIVED" after a while)
				default:
					log.Warning(fmt.Sprintf("unknown message: %#v", msgi))
			}
		}
	}()

The same code works perfectly if redis-server is on a single server with go-redis client code.

Thanks.

**Comment by vmihailenco** [comment]
Recently I added `ReceiveMessage` that handles reconnection automatically: https://godoc.org/gopkg.in/redis.v3#PubSub (look at example). Can you try it?
