### ISSUE TITLE
NewIntSlice causing "redis: can't parse int reply: "$1"" with MGET

### ISSUE THREAD

**Issue by ahmetb** [go-redis/redis#1810]
## Expected Behavior

I should be able to do a client.MGet and pass its args to `redis.NewIntSlice` and directly read integers from there.

## Current Behavior

```
	mget := client.MGet(ctx, keys...)
	cmd := redis.NewIntSliceCmd(ctx, mget.Args()...)
	if err := client.Process(ctx, cmd); err != nil {
		return 0, err
	}
```

This snippet is returning error:

    redis: can't parse int reply: "$1"

If I use `NewStringSliceCmd` instead of Int, I get properly parsed strings, indicating all keys that had values were proper integers.

![image](https://user-images.githubusercontent.com/159209/124324460-d5b49d00-db37-11eb-81ad-414238fe34d7.png)

So it's unclear to me why this is happening with `NewIntSliceCmd` is not parsing things correctly.

**Comment by monkey92t** [comment]
The MGET command responds to an array of strings. It is not an Int array.

It appears in RESP as: *2\r\n$1\r\na\r\n$1\r\nb\r\n

Just like the get command, it responds to the string type, even if your value is a number, redis still responds to a string.

If you need []int, you can convert []string to []int, or use client.Mget(..).Scan(dest)

**Comment by ahmetb** [comment]
And in .Scan(&dst) case, &dst has to be a []string?

I wish there was a bit of a better error message here.

**Comment by monkey92t** [comment]
Example:
```go
127.0.0.1:6379> set key1 100
OK
127.0.0.1:6379> set key2 200
OK
127.0.0.1:6379> set key3 300
OK
127.0.0.1:6379> 


type Temp struct {
	Key1 int `redis:"key1"`
	Key2 int `redis:"key2"`
	Key3 int `redis:"key3"`
}

temp := &Temp{}
rdb.MGet(ctx, "key1", "key2", "key3").Scan(temp)

// temp.Key1   100
// temp.Key2   200
// temp.Key3   300
```

**Comment by ahmetb** [comment]
Ack, I thought we could export into a map[string]int or just []int.
