### ISSUE TITLE
How to batch set key ttl

### ISSUE THREAD

**Issue by zsr228** [go-redis/redis#1812]
as title

**Comment by monkey92t** [comment]
Redis does not have commands to set the expiration time in batches, you can use the pipeline to set the ttl of multiple keys

**Comment by zsr228** [comment]
yes, I think should use the pipeline to set the ttl of multi keys.
but about batch set ttl, some ways I search, such as
"redis-cli -h 127.0.0.1 keys "pre:key_*" | xargs -i redis-cli -h 127.0.0.1 expire {} 86400"

**Comment by monkey92t** [comment]
This method is just a trick, and it needs to be used very carefully under normal circumstances. There are the following warnings in the redis document:

Warning: consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases. This command is intended for debugging and special operations, such as changing your keyspace layout. Don' t use KEYS in your regular application code.

**Comment by zsr228** [comment]
got it. we should use keys command extreme care especially in prod env, thanks a lot.
I will close this issue.
