### ISSUE TITLE
updateLatency can't detect failure

### ISSUE THREAD

**Issue by smartnews-weitao** [go-redis/redis#1839]
I am using go-redis's redis cluster client. And this is my client configuration:

rdb = redis.NewClusterClient(&redis.ClusterOptions{
		Addrs: redisAddresses,
		ReadOnly: true,
		RouteByLatency: true,
		ReadTimeout: time.Duration(readTimeout) * time.Millisecond,
		WriteTimeout: time.Duration(writeTimeout) * time.Millisecond,
	})

So i enabled RouteByLatency, i expect this feature will route my request to the redis node with best network environment. Also if the master/slave failed, i expect it will route my request to the healthy node in the same shard immediately. But during the test, if i killed my redis master node, it will take around 15-30 sec for the go redis client to recover. So my question is, what actually happen if one of redis node failed, and RouteByLatency can't detect that? So i looked into the code:

func (n *clusterNode) updateLatency() {
	const numProbe = 10
	var dur uint64

	for i := 0; i < numProbe; i++ {
		time.Sleep(time.Duration(10+rand.Intn(10)) * time.Millisecond)

		start := time.Now()
		n.Client.Ping(context.TODO())
		dur += uint64(time.Since(start) / time.Microsecond)
	}

	latency := float64(dur) / float64(numProbe)
	atomic.StoreUint32(&n.latency, uint32(latency+0.5))
}

Seems like n.Client.Ping(context.TODO()) it's waiting forever without a timeout? So if the redis node is failed, this function call will block until it recover?

**Comment by vmihailenco** [comment]
`updateLatency` relies on `ReadTimeout` to not block forever. And it just measures latency without trying to detect unavailable nodes. That is Redis Cluster responsibility, not go-redis.

**Comment by smartnews-weitao** [comment]
But i do want to achieve this fast detection and switch to a healthy node feature. And i have already set my ReadTimeout as 100 millisecond. So i guess if one of the node failed, this n.Client.Ping() will return in 100 millisecond, and record a 100 millisecond as latency for current node, which is very bad. Then it will automatically switch to another node in the same shard? But in reality, we didn't find such pattern.

**Comment by vmihailenco** [comment]
As I said it is not go-redis responsibility to detect bad nodes. go-redis can only retry the command on other node which AFAIK it already does.

**Comment by smartnews-weitao** [comment]
So you mean if go-redis failed to fetch result from current node, it will automatically retry the command on other node? I am wondering where is the logic? We didn't find it.

**Comment by vmihailenco** [comment]
See https://github.com/go-redis/redis/blob/master/cluster.go#L771-L850

**Comment by smartnews-weitao** [comment]
Thanks!
