### ISSUE TITLE
Recover from broken pipe

### ISSUE THREAD

**Issue by sammy007** [go-redis/redis#185]
After scheduled disconnects I see endless broken pipe errors. How I can configure client to get rid of this worst behaviour? It can't reconnect for hours until application restarted.

**Comment by vmihailenco** [comment]
Is there any way to reproduce behaviour you described?

Bad connections are automatically removed from the pool and client opens new connection instead of the bad one - https://github.com/go-redis/redis/blob/master/redis.go#L23-L37. The only exception to that rule is `PubSub`, which does automatic reconnection only if you use [ReceiveMessage](https://godoc.org/gopkg.in/redis.v3#PubSub.ReceiveMessage).

**Comment by sammy007** [comment]
I don't use pubsub, I just created client:

    func NewRedisClient(cfg *Config) *RedisClient {
    	client := redis.NewClient(&redis.Options{
	    	Addr:     cfg.Endpoint,
	   	    Password: cfg.Password,
    		DB:       cfg.Database,
	    	PoolSize: cfg.PoolSize,
    	})
	    return &RedisClient{client: client}
    }

and using it for multi and regular commands. Just try to create client, stop redis instance and run it again.

2015/11/13 02:03:52 write tcp [::1]:51737->[::1]:6379: write: broken pipe
2015/11/13 02:03:52 redis: Unwatch failed: write tcp [::1]:51737->[::1]:6379: write: broken pipe
2015/11/13 02:03:57 write tcp [::1]:51737->[::1]:6379: write: broken pipe
2015/11/13 02:03:57 redis: Unwatch failed: write tcp [::1]:51737->[::1]:6379: write: broken pipe

**Comment by sammy007** [comment]
This is how you can reproduce it on your side:

```go
package main

import (
	"gopkg.in/redis.v3"
	"time"
	"log"
)

var client *redis.Client

func main() {
	client = redis.NewClient(&redis.Options{
		Addr: "localhost:6379",
	})
	for {
		go func() {
			tx := client.Multi()
			defer tx.Close()

			res, err := tx.Exec(func() error {
				tx.HGet("foo", "bar")
				return nil
			})
			log.Println(res, err)
		}()

		time.Sleep(3000000000)
	}
}
```

It works as expected if there is no goroutine, but if i use goroutine, it ill never recover from lost connection. Also, it seems problem is only with multi.

**Comment by sammy007** [comment]
Tested this code on v2 and it works ok.

**Comment by vmihailenco** [comment]
`Multi` is special because it has to restore watches after reconnection. And since we don't have that functionality yet reconnection is disabled for multi...

**Comment by sammy007** [comment]
Did you run my example in this ticket? There is infinite loop with multi, next calls should perform successfully, but there is endless broken pipe errors even if redis instance is available again. You wanna say that this is expected behaviour?

**Comment by vmihailenco** [comment]
I wanted to say that it is expected behaviour, not desired.

**Comment by sammy007** [comment]
Thanks, I was confused because it works in v2.
