### ISSUE TITLE
v6.15.9   pubsub.go:159: redis: discarding bad PubSub connection: redis: ping timeout

### ISSUE THREAD

**Issue by 467892746** [go-redis/redis#1854]
version: v6.15.9
redis conn pool config:
 redis.NewClient(&redis.Options{
		Addr:     config.CoreConf.Server.Redis.Addr,
		Password: config.CoreConf.Server.Redis.PassWord,
	})

redis subcribe:
sub := client.Subscribe(pubsubChannel)
	for msg := range sub.Channel() {
				go func() {}()
	}

More and more ping timeouts occur as time increases
redis: 2021/08/13 10:02:19 pubsub.go:159: redis: discarding bad PubSub connection: redis: ping timeout
redis: 2021/08/13 10:03:19 pubsub.go:159: redis: discarding bad PubSub connection: redis: ping timeout
redis: 2021/08/13 10:04:19 pubsub.go:159: redis: discarding bad PubSub connection: redis: ping timeout

**Comment by vmihailenco** [comment]
Please upgrade to v8. v6 is not supported any more.
