### ISSUE TITLE
redis: discarding bad PubSub connection: redis: invalid reply

### ISSUE THREAD

**Issue by 467892746** [go-redis/redis#1858]
version: v8.11.3
redis version: 5.0 community

redis conn pool config:
redis.NewClient(&redis.Options{
Addr: config.CoreConf.Server.Redis.Addr,
Password: config.CoreConf.Server.Redis.PassWord,
})

redis subcribe:
sub := client.Subscribe(pubsubChannel)
for msg := range sub.Channel() {
go func() {}()
}

More and more invalid replys time increases
redis: 2021/08/13 14:30:00 pubsub.go:159: redis: discarding bad PubSub connection: redis: invalid reply: "\r\n"
redis: 2021/08/13 14:30:06 pubsub.go:159: redis: discarding bad PubSub connection: redis: invalid reply: "\r\n"
redis: 2021/08/13 14:30:12 pubsub.go:159: redis: discarding bad PubSub connection: redis: invalid reply: "\r\n"
redis: 2021/08/13 14:30:18 pubsub.go:159: redis: discarding bad PubSub connection: redis: invalid reply: "\r\n"
redis: 2021/08/13 14:30:24 pubsub.go:159: redis: discarding bad PubSub connection: redis: invalid reply: "\r\n"
redis: 2021/08/13 14:30:30 pubsub.go:159: redis: discarding bad PubSub connection: redis: invalid reply: "\r\n"
redis: 2021/08/13 14:30:36 pubsub.go:159: redis: discarding bad PubSub connection: redis: invalid reply: "\r\n"

**Comment by monkey92t** [comment]
It seems that redis response error (resp), it is not a problem of go-redis.

The redis-server should respond with a valid resp protocol under any circumstances.

You should check if there is a problem with the redis-server you are using.
