### ISSUE TITLE
Can ClusterClient point to a single node in the cluster?

### ISSUE THREAD

**Issue by mindscratch** [go-redis/redis#186]
In the [example](https://godoc.org/gopkg.in/redis.v3#ex-NewClusterClient) for the ClusterClient, it shows multiple redis hosts. Would the ClusterClient work if just one host was given? If so, does it matter if the host is a master or slave?

For example, I have 6 redis nodes running (3 master, with 1 slave each). I have a DNS server which round-robins between any of them. Meaning, if you connect to "redis.myserver.com" you'll get to any one of the 6 nodes.

**Comment by vmihailenco** [comment]
AFAIK it is safe to connect to only one random node in the cluster (master or slave). So you should be fine.
