### ISSUE TITLE
When redis client is closed before all goroutine is completed,p.poolSize and p.idleConnsLen will overflow maybe

### ISSUE THREAD

**Issue by mstmdev** [go-redis/redis#1861]
https://github.com/go-redis/redis/blob/bc9d5c8d3af4780baecc5b76e3f37a9c3d18ab42/internal/pool/pool.go#L117-L134

https://github.com/go-redis/redis/blob/bc9d5c8d3af4780baecc5b76e3f37a9c3d18ab42/internal/pool/pool.go#L412

When redis client is closed before all goroutine is completed,p.poolSize and p.idleConnsLen will overflow maybe.

**Comment by monkey92t** [comment]
Yes, but it seems to have a bigger problem, I need to do some experiments.

**Comment by monkey92t** [comment]
fixed by #1863
