### ISSUE TITLE
How can I set the pool OnClose when I create a redis client?

### ISSUE THREAD

**Issue by mstmdev** [go-redis/redis#1864]
https://github.com/go-redis/redis/blob/bc9d5c8d3af4780baecc5b76e3f37a9c3d18ab42/internal/pool/pool.go#L58

How can I set the pool `OnClose` when I create a redis `Client`?  I can't find the`OnClose`in the options.go.
https://github.com/go-redis/redis/blob/bc9d5c8d3af4780baecc5b76e3f37a9c3d18ab42/options.go#L29-L39

**Comment by monkey92t** [comment]
It doesn't seem to be used (for testing only), @vmihailenco  do you know? 

https://github.com/go-redis/redis/commit/f47fb47df0504eef87892242127de452af13769b#diff-e4a6f710d6c51e7dc7ceeb1495acc696b362cf4dcbfdf9587b4d22547d682cfaR51

**Comment by vmihailenco** [comment]
It is not a public API and can't be since `*Conn` is a private struct. If you need to customize `Conn.Close`, you can wrap `net.Conn` interface.
