### ISSUE TITLE
Judgment where in setCmdsErr is reversed

### ISSUE THREAD

**Issue by MaxwellZY** [go-redis/redis#1866]
#### As stated in the title, err judegement in the function setCmdsErr should be 
```go
if cmd.Err() != nil {
  cmd.setErr(e)
}
```

**Comment by vmihailenco** [comment]
Maybe, but it is hard to judge without an example. Do you have an example where such change makes a difference?

**Comment by MaxwellZY** [comment]
> Maybe, but it is hard to judge without an example. Do you have an example where such change makes a difference?

If not, what is the meaning of this function, just initialization error status?
```go
func setCmdsErr(cmds []Cmder, e error) {
	for _, cmd := range cmds {
		if cmd.Err() == nil {
			cmd.setErr(e)
		}
	}
}
```

**Comment by MaxwellZY** [comment]
Sorry i got it wrong, misunderstood of what this function does
