### ISSUE TITLE
Low performance in Redis HSet and HGetAll

### ISSUE THREAD

**Issue by PasinduTennage** [go-redis/redis#1873]
## Expected Behavior

A high throughput that is close to 20, 000 requests per second

## Current Behavior

A throughput of only 5500 requests per second

## Possible Solution

Are there any bottlenecks such as the number of connection pool threads? 

## Steps to Reproduce

Ubuntu version: `Ubuntu 20.04.2 LTS`
go-lang version:  `go1.15.2 linux/amd64`
Redis Version: `Redis server v=5.0.7 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=636cde3b5c7a3923`

In the performance test I implement the YCSB workloadA, using the parameters available in the YCSB core workload `A` [file](https://github.com/brianfrankcooper/YCSB/blob/master/workloads/workloada). 

The `key` length is `23 bytes` and the `value` length is `100` bytes. 

The Redis server is initialized with 1000 keys using the `Init()` method mentioned below. I use `HSET`  and `HGetAll` methods (because they are the ones used in the YCSB original workload generator). 

During the test the `executeRedisApp(request string)` method is called continuously, with `READ` and `UPDATE` requests. The `executeRedisApp(request string)` method calls  `HGetAll` for `READ` and `HSet` for `UPDATE` requests.  The `key` length is `23 bytes` and the `value` length is `100` bytes.  The `field` in the `HSet` is always constant `(field0)` 

```
package main

import (
	"context"
	"github.com/go-redis/redis/v8"
	"math/rand"
	"strconv"
	"strings"
)

type RedisApplication struct {
	numKeys int
	client  *redis.Client
	ctx     context.Context
}

func (redisApp *RedisApplication) Init(numKeys int) {
	redisApp.numKeys = numKeys
	redisApp.ctx = context.Background()
	redisApp.client = redis.NewClient(&redis.Options{
		Addr:     "127.0.0.1:6379",
		Password: "", // no password set
		DB:       0,  // use default DB
	})
	redisApp.client.FlushAll(redisApp.ctx)

	for i := 0; i < redisApp.numKeys; i++ {
		redisApp.client.HSet(redisApp.ctx, Get23LengthRecord(i),
			"field0", Get100LengthValue(),
			"field1", Get100LengthValue(),
			"field2", Get100LengthValue(),
			"field3", Get100LengthValue(),
			"field4", Get100LengthValue(),
			"field5", Get100LengthValue(),
			"field6", Get100LengthValue(),
			"field7", Get100LengthValue(),
			"field8", Get100LengthValue(),
			"field9", Get100LengthValue())
	}

}

func (redisApp *RedisApplication) executeRedisApp(request string) string {
	// request pattern: UPDATE/READ:key:field:value
	op := strings.Split(request, ":")[0]
	key := strings.Split(request, ":")[1]
	field := strings.Split(request, ":")[2]
	value := strings.Split(request, ":")[3]
	if op == "READ" {
		redisApp.get(key)
	} else if op == "UPDATE" {
		redisApp.update(key, field, value)
	}
	return request
}

func (redisApp *RedisApplication) get(key string) map[string]string {
	rslt, _ := redisApp.client.HGetAll(redisApp.ctx, key).Result()
	return rslt
}

func (redisApp *RedisApplication) update(key string, field string, value string) {
	redisApp.client.HSet(redisApp.ctx, key, field, value)
}

func Get100LengthValue() string {
	str := strconv.Itoa(rand.Intn(10))
	size := len(str)
	for size <= 100 {
		str = strconv.Itoa(rand.Intn(10)) + str
		size = len(str)
	}
	return str
}

func Get23LengthRecord(i int) string {
	str := strconv.Itoa(i)
	size := len(str)
	for size <= 19 {
		str = "0" + str
		size = len(str)
	}
	return "user" + str
}

```
## Context (Environment)

The code runs without any error, and achieves a throughput of 5500 ops/second. However, this is significantly lower than the go-redis benchmarks.

To find the bottleneck (and to make sure that redis-server is not the bottleneck) I ran the `redis-benchmark`

Command: `redis-benchmark`

Output

```
===== HSET ======
  100000 requests completed in 1.68 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

99.78% <= 1 milliseconds
100.00% <= 2 milliseconds
100.00% <= 2 milliseconds
59453.03 requests per second

```
As you can see, the Redis throughput is extremely high.

Any thoughts about why this is happening?

Thanks

**Comment by vmihailenco** [comment]
From what I see you are using a single thread/goroutine with many large keys, but redis-benchmark uses `50 parallel clients` and `3 bytes payload`.

**Comment by PasinduTennage** [comment]
@vmihailenco 

Thanks for the reply
Yes you are correct, I am using a single thread
Is `5050 Ops/second` the maximum throughput `go-redis` can handle?
Regards

**Comment by PasinduTennage** [comment]
Using a single thread, a higher throughput can be achieved by using `Pipeline`

```
pipe := redisApp.client.TxPipeline()
		for i := 0; i < len(requests); i++ {
			request := requests[i]
			// request pattern: UPDATE/READ:key:field:value
			op := strings.Split(request, ":")[0]
			key := strings.Split(request, ":")[1]
			field := strings.Split(request, ":")[2]
			value := strings.Split(request, ":")[3]
			if op == "READ" {
				pipe.HGetAll(redisApp.ctx, key)
			} else if op == "UPDATE" {
				pipe.HSet(redisApp.ctx, key, field, value)
			}
		}
              _, _ = pipe.Exec(redisApp.ctx)
```
