### ISSUE TITLE
Default pool wait time is documented as 5s but is actually 1s

### ISSUE THREAD

**Issue by justonia** [go-redis/redis#191]
Not sure which one is intended as the default setting, but right now the two do not match. I personally found 1s to be a bit low during a brief period of spikey load.

**Comment by vmihailenco** [comment]
1s is a lot for Redis which has average processing ~ 1ms. I will fix doc comment.

**Comment by justonia** [comment]
Yea normal processing time is super fast like you mention. However if you have an idle timeout set, your connections go idle and get pruned, and then you experience a burst of activity the client will have to spin up a bunch of new connections. If your pool size is significantly less than the number of new concurrent requests it is very easy to hit that 1s limit initially until all the connections are warmed up. I have bumped our idle pool timeout so it's not a big deal besides the inconsistency in docs, 1s default may be plenty for most people.
