### ISSUE TITLE
PubSub.ChannelWithSubscriptions is unable to preserve default channel size

### ISSUE THREAD

**Issue by pabigot** [go-redis/redis#1920]
PubSub provides [ChannelWithSubscriptions](https://pkg.go.dev/github.com/go-redis/redis/v8#PubSub.ChannelWithSubscriptions) which allows applications to detect reconnections.  This method takes an integer `size` parameter that translates into passing the [WithChannelSize](https://pkg.go.dev/github.com/go-redis/redis/v8#PubSub.ChannelWithSubscriptions) option to [newChannel()](https://github.com/go-redis/redis/blob/fa515240d4a060c0fe72e7c41f1416627ca3e29f/pubsub.go#L515-L530).  But `newChannel()` sets defaults before applying options, and the option closures don't support out-of-band values to signal that the default value should be preserved.

So the current API forces applications that want to use `ChannelWithSubscriptions()` to hard-code a size, risking inconsistency if the default size changes in the future.

Potential mitigations include:
* Providing the default size of channels as an exported constant that applications could use in this API;
* Defining the behavior of `WithChannelSize(-1)` to be to use the default size

I'd be happy to provide a patch if one of these, or some other solution, would be acceptable.

**Comment by vmihailenco** [comment]
We plan to address this in v9 by changing `ChannelWithSubscriptions` to accept `...ChannelOption` and removing mandatory size arg.

>Defining the behavior of WithChannelSize(-1) to be to use the default size

I would prefer this one because it does not introduce new public API.

>I'd be happy to provide a patch if one of these, or some other solution, would be acceptable.

Sure, please send a PR.

**Comment by vmihailenco** [comment]
Closing in favor https://github.com/go-redis/redis/issues/1921
