### ISSUE TITLE
Pool errClosed and errPoolTimeout are private errors

### ISSUE THREAD

**Issue by justonia** [go-redis/redis#193]
Part question, part suggestion. Why are those two errors package scoped? As is I am forced to search for "connection pool timeout" in the err.Error() string if I want my application to respond correctly by retrying later or notifying the client that we are temporarily unavailable. Seems like a dangerous way to do it on my end since that string could theoretically change and my code would silently break.

**Comment by vmihailenco** [comment]
When you encounter errPoolTimeout you should either:
- upgrade your Redis server to respond faster
- don't use slow commands that block other clients (e.g. http://redis.io/commands/SORT)
- use higher errPoolTimeout, which effectively is the same as retrying (PoolTimeout * NumberOfRetries)

So I just don't know a use case for exported errPoolTimeout.

>retrying later or notifying the client that we are temporarily unavailable

Why `err != nil` does not work here?

**Comment by justonia** [comment]
I understand all the reasons behind why this error might happen and how one might respond to it, but you aren't really answering my question -- why not expose it so clients of your library can make intelligent and type-safe decisions when handling errors?

For example, let's say I have an enormous spike of load and there is a lag time before my load balancer can spin up new instances. My existing instances, despite having a larger connection pool and larger timeout, might still cause that error to happen even with simple and quick operations. In that event I would send my game client a TemporarilyUnavailableError and let it retry later after a backoff period -- to the user this would be invisible. If another error happens that is unexpected by me and may indicate serious issues with my infrastructure or code,  I would end up returning an InternalServerError and my client would not retry and would instead alert the user that their game must be terminated.

**Comment by vmihailenco** [comment]
Another reason to not export `errPoolTimeout` is that it is specific to current pool implementation, e.g. v1/v2 did not have it at all.

>why not expose it so users of your library can make intelligent and type-safe decisions when handling errors?

My answer is that users should not handle `errPoolTimeout` in a special way. Surely I can be wrong, but I still did not hear a practical argument ("I want to do it" does not count :). Anyway you can use `err.Error() == "redis: connection pool timeout"` and I promise that I will not change that string.

**Comment by justonia** [comment]
Well I guess we can agree to disagree on this one :)

If the string won't change that's good enough for my use case.

**Comment by dim** [comment]
How about an `IsTimeout(error) bool` function as a compromise? Similar to
os.IsNotFound?

**Comment by justonia** [comment]
That'd be great, in general I prefer methods like that over direct error comparisons since they let you mutate the API under the hood and remain backwards compatible.

**Comment by vmihailenco** [comment]
I think `Temporary` is a better example - https://golang.org/src/net/net.go?s=11566:11687#L349

```
err := client.Ping().Err()
if err, ok := err.(net.Error); ok && err.Temporary() {
    // retry
}
```

But overall I am not sure that this is right thing and that many users will use it. But at least it looks idiomatic :)

**Comment by vmihailenco** [comment]
This does not look very popular/useful - closing for now.
