### ISSUE TITLE
It cost an increasing number of time when I use lots of concurrency and ClusterClient to connect redis cluster.

### ISSUE THREAD

**Issue by youzhixiaomutou** [go-redis/redis#1946]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior

It cost few time.

## Current Behavior

It cost an increasing number of time when I use lots of concurrency and `ClusterClient` to connect redis cluster.

## Steps to Reproduce

``` go
func main() {
	wg := sync.WaitGroup{}
	wg.Add(n)
	c := redis.NewClusterClient(&redis.ClusterOptions{
		Addrs:    []string{"xxx", "xxx", "xxx"},
		PoolSize:     5 * runtime.GOMAXPROCS(0),
		MinIdleConns: 5 * runtime.GOMAXPROCS(0),
	})
	n := 800
	for i := 0; i < n; i++ {
		go func() {
			wg.Wait()
			start := time.Now()
			_ = c.Get(context.Background(), "key")
			fmt.Printf("span=%dms\n", time.Since(start).Milliseconds())
		}()
		wg.Done()
	}
}
```

## Detailed Description

From the above, it logs dozens to several hundred milliseconds.
It seems that goroutines blocks on getting connections.
I use other driver like redigo, it return 0ms to 10 ms.

**Comment by tsingheng** [comment]
Me too!

**Comment by BuryMe** [comment]
me too!

**Comment by wenlincheng** [comment]
Me too!

**Comment by fmyxyz** [comment]
俺也一样，有好多的200ms

**Comment by vmihailenco** [comment]
Seems to be working as expected. You can make it 2 things to "improve" your program:
- Insert `time.Sleep(time.Second)` after calling `NewClusterClient` to give go-redis some time to open connections
- Increase `PoolSize` to `n := 800`. Otherwise, goroutines are waiting for a free connection from the pool.

**Comment by tsingheng** [comment]
我原来是用v6.15.7，redis3没有问题，redis6会出现并发情况下非常慢的情况，go-redis升级到8.3.0没有问题了。

**Comment by jademnp** [comment]
> 

it works for me. upgrade to the latest version solve it.
