### ISSUE TITLE
Set command with negative expire time，except err,  but with Set key that no associated expire.

### ISSUE THREAD

**Issue by buddyyu** [go-redis/redis#1948]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

Set command  implement not comply with  https://redis.io/commands/set
## Expected Behavior
when set with negative expire time, need return err.

## Current Behavior
set key that no associated expire, mean permanent.

## Possible Solution
when set with negative expire time, need return err.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by vmihailenco** [comment]
In Redis v8, `Set(ctx, "foo", "bar", -1)` means `SET foo bar KEEPTTL`. See the comment on `Set` function.

**Comment by buddyyu** [comment]
> In Redis v8, `Set(ctx, "foo", "bar", -1)` means `SET foo bar KEEPTTL`. See the comment on `Set` function.
`Set(ctx, "foo", "bar", -2)`
will clear exist ttl,   this case we expect return err.
