### ISSUE TITLE
Make test error: use of internal package not allowed

### ISSUE THREAD

**Issue by gdm85** [go-redis/redis#196]
```
go test ./... -test.v=1
package ./.
	imports gopkg.in/redis.v3/internal/consistenthash: use of internal package not allowed
Makefile:6: recipe for target 'test' failed
make: *** [test] Error 1
```

My `go env`:
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gdm85/projects"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

Is this a known issue?

**Comment by gdm85** [comment]
Nevermind, I figured out it's because it needs to be under a correct GOPATH directory structure.

By the way, I could contribute a patch to add glide support (for vendoring etc) if you like.

**Comment by vmihailenco** [comment]
I know nothing about glide, but I will be happy to review your pull request :)

**Comment by sithembiso** [comment]
I know this is a very old thread, but I'm stuck with the same issue:
```
imports github.com/go-macaron/cache/redis
imports gopkg.in/redis.v2
imports gopkg.in/redis.v5/internal/pool: use of internal package not allowed
```
@gdm85 how did you solve it? All my dependancies are in a `glide` managed `vendor` directory.

```
go version go1.6.2 linux/amd64
```

**Comment by vmihailenco** [comment]
Try to replace redis.v2 with redis.v5

**Comment by vmihailenco** [comment]
Actually it looks like go-macaron/cache depends on redis.v2. Where `gopkg.in/redis.v5/internal/pool` import comes from?

**Comment by sithembiso** [comment]
Yes, this package `github.com/go-macaron/cache/redis` depends on `redis.v2`.
I'm going to make a temporary change to the import statement in that package to see if it works. If it does I guess I'd have to take this up with the `github.com/go-macaron/cache` maintainers.

**Comment by sithembiso** [comment]
The good news now is, everything is working! The bad news is that I don't know that I did, but I didn't make the change above. 
I'll keep investigating and revert.

**Comment by jackzampolin** [comment]
Still running into a similar issue with glide.

**Comment by gdlxSong** [comment]
internal package:

Go's package system makes it easy to structure programs into components with clean boundaries, but there are only two forms of access: local (unexported) and global (exported). Sometimes one wishes to have components that are not exported, for instance to avoid acquiring clients of interfaces to code that is part of a public repository but not intended for use outside the program to which it belongs.

The Go language does not have the power to enforce this distinction, but as of Go 1.4 the go command introduces a mechanism to define "internal" packages that may not be imported by packages outside the source subtree in which they reside.

To create such a package, place it in a directory named internal or in a subdirectory of a directory named internal. When the go command sees an import of a package with internal in its path, it verifies that the package doing the import is within the tree rooted at the parent of the internal directory. For example, a package .../a/b/c/internal/d/e/f can be imported only by code in the directory tree rooted at .../a/b/c. It cannot be imported by code in .../a/b/g or in any other repository.

For Go 1.4, the internal package mechanism is enforced for the main Go repository; from 1.5 and onward it will be enforced for any repository.

Full details of the mechanism are in the design documen.
