### ISSUE TITLE
ReceiveMessage panics when pubsub closed

### ISSUE THREAD

**Issue by shagabutdinov** [go-redis/redis#198]
I've discovered panic on following situation:

1. First go routine reads message from pubsub
2. Second go routine closes that pubsub

Could you please give me a starting point on how this should be handled (maybe it is possible that you planned to catch such panic?); I suppose correct behaviour will be returning something like `PubsubClosedError` from `ReceiveMessage` when pubsub is closed.

Following example demonstrates how panic could be reproduced:

	package main

	import (
		"time"

		"gopkg.in/redis.v3"
	)

	func main() {
		connection := redis.NewClient(&redis.Options{Addr: "127.0.0.1:6379"})
		subscribe, err := connection.Subscribe("test")
		if err != nil {
			return
		}

		go func() {
			time.Sleep(time.Second)
			subscribe.Close()
		}()

		for {
			_, err := subscribe.ReceiveMessage()
			if err != nil {
				return
			}
		}
	}

Panic message:

	panic: p.cn == nil

	goroutine 1 [running]:
	gopkg.in/redis%2ev3.(*stickyConnPool).Remove(0xc82000aff0, 0xc8200a4000, 0x0, 0x0)
		.../redis.v3/pool.go:437 +0xe5
	gopkg.in/redis%2ev3.(*baseClient).putConn(0xc820012760, 0xc8200a4000, 0x7f4d48f3c6c8, 0xc8200704b0)
		.../redis.v3/redis.go:26 +0xa7
	gopkg.in/redis%2ev3.(*PubSub).ReceiveTimeout(0xc8200104c0, 0x12a05f200, 0x0, 0x0, 0x0, 0x0)
		.../redis.v3/pubsub.go:219 +0x10e
	gopkg.in/redis%2ev3.(*PubSub).ReceiveMessage(0xc8200104c0, 0x834598, 0x0, 0x0)
		.../redis.v3/pubsub.go:252 +0x56
	main.main()
		.../main.go:45 +0x108

	goroutine 17 [syscall, locked to thread]:
	runtime.goexit()
		/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

**Comment by vmihailenco** [comment]
Fixed by https://github.com/go-redis/redis/pull/200
