### ISSUE TITLE
dial tcp: i/o timeout after ElasticCache cluster upgraded

### ISSUE THREAD

**Issue by zhiyonghuang977** [go-redis/redis#2015]
I am using go-redis version v6.15.7. I have my application running in an AWS cluster behind loadbalancer, 

I have 5 servers running docker containers, redis cluster nodes IP changed after AWS cluster upgraded , 3 containers still connect to the old ip and often get i/o timeout errors, while 2 containers run fine. Application started working properly after a restart.

Can you please help me with identifying the issue ??
If it is previously known issue and is solved in latest version, can you point me to that link ??

The error was "dial tcp 10.31.187.223:6379: i/o timeout".

Below is my code snippet

```
DefaultRedisClusterClient = redis.NewClusterClient(&redis.ClusterOptions{
	Addrs:    conf.RedisURLs,
	Password: conf.PassWord,
})
if err := DefaultRedisClusterClient.Ping().Err(); err != nil {
	panic(err)
}

cmd := DefaultRedisClusterClient.HGetAll(key)
if cmd == nil {
	err = ErrorUnknown
	return
}
if cmd.Err() != nil {
	err = cmd.Err()
	return
}
```

**Comment by vmihailenco** [comment]
Please upgrade to latest version.

**Comment by zhiyonghuang977** [comment]
> Please upgrade to latest version.

So is this a known issue?

**Comment by zhiyonghuang977** [comment]
Thank you! So is this a known issue? What is the cause of the issue?

**Comment by vmihailenco** [comment]
It's been 3 years - some issues were definitely fixed during that time. I can't say for sure.

**Comment by duzhipeng** [comment]
> 
@zhiyonghuang977 
Hi,you try this：
大兄弟，你试试这个操作：

In the connection configuration, that is, under your code Addrs and Password, add a configuration: TLSConfig: &tls.Config{},
在连接配置里，也就是你代码Addrs、Password下面，加一个配置：TLSConfig: &tls.Config{},

**Comment by congzhegao** [comment]
Adding a minimum TLS config would work.
