### ISSUE TITLE
How To Properly setup TLS connection through Go-Redis

### ISSUE THREAD

**Issue by KrunchyKernel** [go-redis/redis#2020]
I cannot find any proper documentation on properly setting up the TLS config to be used when creating a new Go-Redis client. 
After the cert is added to the cert pool and added to the config, a connection is not made. 

This is for an enterprise purpose, so I know the cert is good, but the understanding of how to configure TLS from the client side (after it's set up on the Redis host) in Go using the go-redis driver is still very vague.

**Comment by calvinbui** [comment]
https://redis.uptrace.dev/guide/server.html#using-tls
