### ISSUE TITLE
PubSub ReceiveMessage: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context

### ISSUE THREAD

**Issue by lancehit** [go-redis/redis#205]
```
if badConn {
    c.reconnect()
    badConn = false
    continue
}

err := c.Ping("")
if err != nil {
    c.reconnect()
} else {
    badConn = true
}
continue
```

this call to Ping("") is unsupported on Redis versions below 3.2 (https://github.com/antirez/redis/issues/420) when operating in subscription mode

So when calling ReceiveMessage() the implicit timeout results in a Ping message being sent, which immediately results in an error:

**ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context**

repro steps:
 - create connection
 - subscribe to channel
 - ReceiveMessage() in a loop
 - wait ~5 seconds

**Comment by vmihailenco** [comment]
Any suggestions how to fix this? :) Probably `ReceiveMessage` should treat `ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context` as a reply from healthy connection...

**Comment by lancehit** [comment]
I'm not sure that assuming the connection is bad on a subscribed connection when a read timeout occurs is the best approach. For my use case, this would mean reconnecting every 5 seconds a message isn't sent, which is far more likely than a message being sent. Since timeout is an alternate success path for RecieveMessage it should assume that a net.Error with Timeout() == true means the connection is still valid.

if timeout was false though (ie: connection reset error), then you'd know a legitimate error occured, and should try to reconnect, which seems to be handled in the isNetworkError if block.

**Comment by vmihailenco** [comment]
I just tried and it turns out that Ping is supported at least from 2.8.17 which is considered to be old Redis version. So I am inclined to say that you need to upgrade your Redis version :)

**Comment by lancehit** [comment]
That's fair, I am still on 2.6. I'll migrate to 2.8 to resolve this. Thanks.
