### ISSUE TITLE
Use redis over SSH channel error

### ISSUE THREAD

**Issue by slowrookie** [go-redis/redis#2057]
- Use Redis over SSH channels

```golang
sshConfig := &ssh.ClientConfig{
		User:            "root",
		Auth:            []ssh.AuthMethod{ssh.Password("password")},
		HostKeyCallback: ssh.InsecureIgnoreHostKey(),
		Timeout:         15 * time.Second,
}

client, err := ssh.Dial("tcp", "remoteIp:22", sshConfig)
if err != nil {
log.Println(fmt.Errorf("%v", err))
}

cli := redis.NewClient(&redis.Options{
		Addr: net.JoinHostPort("127.0.0.1", "6379"),
  Dialer: func(ctx context.Context, network, addr string) (net.Conn, error) {
	  log.Println(fmt.Sprintf("%s %s", network, addr))
	  return client.Dial(network, addr)
  },
  })

_, err = cli.Ping(context.Background()).Result()
if nil != err {
log.Println(fmt.Errorf("%v", err))
}
```

-  Error:
ssh: tcpChan: deadline not supported

- Reason:
in the redis/interal/pool/conn.og  use ``` cn.netConn.SetReadDeadline  ``` and ``` cn.netConn.SetWriteDeadline ```

**Comment by vmihailenco** [comment]
I guess we could ignore errors returned from `SetReadDeadline`. Send a PR if you are interested.

**Comment by slowrookie** [comment]
when set `ReadTimeout` & `WriteTimeout` to -1 and disable `SetReadDeadline`
```golang
        cli := redis.NewClient(&redis.Options{
		ReadTimeout:  -1,
		WriteTimeout: -1,
	})
```

**Comment by monkey92t** [comment]
fixed: #2060

**Comment by GetcharZp** [comment]
> when set `ReadTimeout` & `WriteTimeout` to -1 and disable `SetReadDeadline`
> 
> ```go
>         cli := redis.NewClient(&redis.Options{
> 		ReadTimeout:  -1,
> 		WriteTimeout: -1,
> 	})
> ```

请问咋禁用 SetReadDeadline 呀？单独设置 ReadTimeout、WriteTimeout 没效果呢

**Comment by slowrookie** [comment]
如果使用最新的版本。https://github.com/go-redis/redis/pull/2176 已修复该问题。解决办法： https://github.com/go-redis/redis/pull/2176#discussion_r942220704 
commit： https://github.com/go-redis/redis/pull/2176/commits/bac50ce2e953769cb93f1a4e044253c744afa3cc

**Comment by awanganddong** [comment]
如果配置项如上图所示，则client.BLPop(ctx, 0, q.conf.queueName).Result() 报如标题错误，大家有兼容方案吗
