### ISSUE TITLE
Golang 1.18 on macOS connecting to AWS Elasticache: certificate is not standards compliant

### ISSUE THREAD

**Issue by calvinbui** [go-redis/redis#2058]
Starting with Golang 1.18, changes have been made to the crypto library that has caused issues with connections to Elasticache Redis clusters.

We get the following error when connecting on macOS: error: x509: "*.redis-locking.abc123.apse2.cache.amazonaws.com" certificate is not standards compliant

We believe this could be related to SCT requirements which are not being enforced on Elasticache certificates: https://cs.opensource.google/go/go/+/master:src/crypto/x509/root_darwin.go;l=52

## Expected Behavior

Redis server connection established

## Current Behavior

Error message:

```
x509: "*.redis-locking.abc123.apse2.cache.amazonaws.com" certificate is not standards compliant
```

## Possible Solution

Skip SCT check?

## Steps to Reproduce

N/A

## Context (Environment)

- macOS 12.2
- Golang 1.18
- go-redis 8.11.5

**Comment by vmihailenco** [comment]
Hm, I guess there should be some way to do that using `tls.Config`. go-redis itself does not have TLS-specific code.

**Comment by monkey92t** [comment]
It should be that the certificate has no SCTs information, you can contact AWS to ask for a solution, 
or try: `tls.Certificate.SignedCertificateTimestamps`

golang 1.18 macOS x509 commit: https://github.com/golang/go/commit/feb024f4153395e5bbb2a51bb3d1ddc4f5b0d2dc

go-redis can't do more work

**Comment by monkey92t** [comment]
we should close this issue :)

**Comment by vmihailenco** [comment]
Let me know if there is anything we can add to the docs to help others, i.e. example how to set up `SignedCertificateTimestamps` would be helpful...

**Comment by monkey92t** [comment]
@vmihailenco @calvinbui 

We have the following solutions to solve this issue.

1. To use `SignedCertificateTimestamps`, it is necessary to obtain SCTs information from the `Certificate Logs` server correctly, and we need a certificate file to do this.
2. AWS applies for SCTs information from Certificate Logs and re-issues certificates.
3. Skip certificate authentication, for example: 
`I don't have an AWS Elasticache Redis server for me to experiment with this, but in my experience it seems to work :).`
```go
db := redis.NewClient(&redis.Options{
	TLSConfig: &tls.Config{
		InsecureSkipVerify: true,
	},
})
```

**Comment by monkey92t** [comment]
I recommend using (2) to solve this problem. If AWS cannot provide a valid certificate in a short time, you can temporarily use (3).

(1) Although the problem can be solved, it is very complicated and not a solution that we should consider.

**Comment by emmaLP** [comment]
Can this issue be re-opened please?

I'm getting this issue and even when I set InsecureSkipVerify to true. I'm getting io timeout issues. 

I have ruled out network issues since I can connect via the redis cli by just adding the `--tls` flag.

**Comment by iwpnd** [comment]
Issue persists in v9.7.3. 

Connecting to the instance with the redis-cli works fine on macOS (15.3.2 (24D81) Sequoia). Any connections via go-redis require to skip verification or otherwise raise OPs error. As these AWS instances rely on public certificates I'm inclined to believe this is a mac thing. I'm just caught by surprise that redis-cli works just fine. 🤔
