### ISSUE TITLE
Cant use float64 in ZUnionStore weights

### ISSUE THREAD

**Issue by jareks** [go-redis/redis#206]
ZStore type is hardcoded to force using int64 in ZUnionStore operation:

```
type ZStore struct {
    Weights []int64
// ...
}
```
( https://github.com/go-redis/redis/blob/d1e774fa21682d9dc5dafec400d13a6f5eb8827d/commands.go#L1001 )

However redis allows to use both integers and floats as _weights_ in ZunionStore command:
```
192.168.233.2:6379> ZADD zset1 1 "one"
192.168.233.2:6379> ZADD zset2 2 "two"
192.168.233.2:6379> ZUNIONSTORE out 2 zset1 zset2 WEIGHTS 0.5 0.5
192.168.233.2:6379> ZRANGE out 0 2 WITHSCORES
1) "one"
2) "0.5"
3) "two"
4) "1"
```

**Comment by vmihailenco** [comment]
Should be fixed, thanks!
