### ISSUE TITLE
can't marshal net.IP (implement encoding.BinaryMarshaler)

### ISSUE THREAD

**Issue by zuoshuwen** [go-redis/redis#2061]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior

```go
func main() {
	ctx := context.Background()

	rdb := redis.NewClient(&redis.Options{
		Addr: ":6379",
	})

	ip := net.ParseIP("192.168.1.1")
	cmd := rdb.Do(ctx, "HSET", "user001", "ip", ip)
	fmt.Println(cmd.Err())

	var userInfo UserInfo

	if err := rdb.HGetAll(ctx, "user001").Scan(&userInfo); err != nil {
		panic(err)
	}
	spew.Dump(userInfo)
}
```

## Current Behavior
rdb.Do() cannot be executed successfully and returns an error message
`redis: can't marshal net.IP (implement encoding.BinaryMarshaler)`

## Possible Solution

`func WriteArg` add `case net.IP`

## Steps to Reproduce

N/A

## Context (Environment)

N/A

## Detailed Description

N/A

## Possible Implementation

N/A

**Comment by monkey92t** [comment]
fixed #2062
