### ISSUE TITLE
v8 Ring no longer supports different passwords per shard

### ISSUE THREAD

**Issue by shuz** [go-redis/redis#2067]
v8 Ring no longer supports different passwords per shard. In v7 there is a `Passwords` [field](https://github.com/go-redis/redis/blob/v7.4.1/ring.go#L32) that allows user to set password per shard. In v8 this is no longer available somehow.

**Comment by vmihailenco** [comment]
See the last example in https://redis.uptrace.dev/guide/ring.html#quickstart
