### ISSUE TITLE
redisBloom commands don't work

### ISSUE THREAD

**Issue by chjiyun** [go-redis/redis#2081]
```
rdb= redis.NewClient(&options)
status, err := rdb.Do(ctx, "BF.EXISTS", "bf_key", 123).Bool()
```
run the code and terminal export "ERR unknown command 'BF.EXISTS'"，Is this not supported？

**Comment by capric8416** [comment]
Your redis-server must install the [bloom module](https://github.com/RedisBloom/RedisBloom) first, or you can play RedisBloom with Docker
```bash
docker run -p 6379:6379 --name redis-redisbloom redislabs/rebloom:latest
```

**Comment by vmihailenco** [comment]
https://redis.uptrace.dev/guide/bloom-cuckoo-count-min-top-k.html
