### ISSUE TITLE
Support Redis 7.0.0

### ISSUE THREAD

**Issue by aarongable** [go-redis/redis#2082]
Version 7.0.0 of Redis was [recently released](https://raw.githubusercontent.com/redis/redis/7.0/00-RELEASENOTES), and contains a variety of backwards-incompatible changes.

One such example is that version 7.0.0 has extended the number of fields in the "CLUSTER SLOTS" command response, by [adding a new "hostname" field](https://github.com/redis/redis/pull/9530). The current code in this library returns an error when it encounters such a response, since it [expects only 2 or 3 elements](https://github.com/go-redis/redis/blob/60d62a8a40821552e86f9e99946585d266d9bda8/command.go#L2704) (the IP, Port, and optionally the ID).

Please work towards support for Version 7.0.0 by resolving this and other incompatibilities.

**Comment by khasanovbi** [comment]
Also redis now return errors like `ERR <message>`, previously redis return just `<message>`.

**Comment by tomasgareau** [comment]
Thought I'd pop in here and leave a quick breadcrumb trail to https://github.com/redis/redis-py/issues/1813 -- it's an issue tracking the Redis 7.0 features that the Python client needed to get in place and it has a great checklist of changes/new commands that might need to be supported.
