### ISSUE TITLE
"ClusterClient.Ping().Result() error: got 4 elements in cluster info address, expected 2 or 3" when used for accessing redis cluster

### ISSUE THREAD

**Issue by yuantingzhong** [go-redis/redis#2085]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

**go-redis reports error when it is used to access redis-cluster**
## Expected Behavior

go-redis/redis should works well with redis cluster
## Current Behavior
go-redis/redis ClusterClient.Ping().Result() reports error "got 4 elements in cluster info address, expected 2 or 3" (my redis cluster has six nodes)

## Steps to Reproduce

1.  I build my redis cluster with docker and the redis's version is 
```
"GOSU_VERSION=1.14",
"REDIS_VERSION=7.0.0",
"REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-7.0.0.tar.gz",
```
and my go version is 
```
# go version
go version go1.18.1 linux/amd64
```
2.  I am sure **my redis cluster works well**, for example, I make a test with redis-cli as follows
```
root@hecs-18053-0002:/home/root/code/redis-cluster/cmd# docker run -it --rm redis redis-cli -c -h 192.168.0.28 -p 6700 -a 123456
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
192.168.0.28:6700> cluster nodes
27bfce46e99d870f7ca4ae5c51df30737581e0cf 192.168.0.180:6901@16901 master - 0 1651637749193 7 connected 0-5460
d93f9f77dc49e7177f6cadf6f32cd27e1ed4ead0 192.168.0.28:6900@16900 slave 27139ca982574acfb125a9d0421d99c47789f7c4 0 1651637750196 3 connected
c3c553a61c78fcdfd07ba6c72402f1d0a23bc006 192.168.0.141:6902@16902 slave f366d818f6c5cdf4ab7843ca8a14f39d58e0fa9d 0 1651637748189 2 connected
27139ca982574acfb125a9d0421d99c47789f7c4 192.168.0.141:6702@16702 master - 0 1651637748000 3 connected 10923-16383
fab30d84431b0e7cebdf0ed257b99e3192ba2d8d 192.168.0.28:6700@16700 myself,slave 27bfce46e99d870f7ca4ae5c51df30737581e0cf 0 1651637749000 7 connected
f366d818f6c5cdf4ab7843ca8a14f39d58e0fa9d 192.168.0.180:6701@16701 master - 0 1651637751199 2 connected 5461-10922
192.168.0.28:6700> cluster info
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:7
cluster_my_epoch:7
cluster_stats_messages_ping_sent:45321
cluster_stats_messages_pong_sent:45740
cluster_stats_messages_sent:91061
cluster_stats_messages_ping_received:45740
cluster_stats_messages_pong_received:45321
cluster_stats_messages_update_received:5
cluster_stats_messages_received:91066
total_cluster_links_buffer_limit_exceeded:0
192.168.0.28:6700>
192.168.0.28:6700> keys *
1) "add"
2) "abb"
3) "bbb"
4) "kkkkkk"
5) "age"
6) "aac"
192.168.0.28:6700>
```
When I set or get key with redis-cli, it works well.
3. Then I test with a simple go program, as follows
```go
package main

import (
        "context"
        "encoding/json"
        "fmt"
        "github.com/go-redis/redis/v8"
        "time"
)

func main() {
        rdb := redis.NewClusterClient(&redis.ClusterOptions{
                Password: "123456",
                Addrs: []string{"192.168.0.28:6700", "192.168.0.180:6701", "192.168.0.141:6702", "192.168.0.28:6900", "192.168.0.180:6901", "192.168.0.141:6902"},
        })

        _, err := rdb.Ping(context.Background()).Result()
        if err != nil {
                panic(err)
        }

        err = testString(rdb)
        if err != nil {
                panic(err)
        }
}

func testString(client *redis.ClusterClient) error {
        key := "mykey"
        err := client.Set(context.Background(), key, "myvalue", time.Minute).Err()
        if err != nil {
                fmt.Println("set err", err)
                return err
        }

        fmt.Println("--------------------------------------")
        for i := 0; i < 6; i++ {
                keyCnt, err := client.Exists(context.Background(), key).Result()
                if err != nil {
                        fmt.Println("client.Exists error: ", err)
                }
                fmt.Println("client.Exists val: ", keyCnt)

                val, err := client.Get(context.Background(), key).Result()
                if err != nil {
                        if err == redis.Nil { // key does not exist
                                fmt.Println("key not exist")
                        } else {
                                fmt.Println("Get err", err)
                                return err
                        }
                } else {
                        fmt.Printf("key: %v, value：%v\n", key, val)
                }

                time.Sleep(15 * time.Second)
        }

        return nil
}
```
build and run this program, it report error, as follows
```
# ./main
panic: got 4 elements in cluster info address, expected 2 or 3

goroutine 1 [running]:
main.main()
        /home/root/code/redis-cluster/cmd/main.go:19 +0x171
```
I think this is a bug, please check and fix it. Thank you very much！

**Comment by UpwardGrowth** [comment]
Did you solve it, I have this problem too

**Comment by UpwardGrowth** [comment]
Did you solve it, I have this problem too

**Comment by UpwardGrowth** [comment]
I guess you are using the latest redis version(7.x), I downgrade back to 6.x version solved the problem.

**Comment by md185331** [comment]
Hi what is the solution to this issue? What specific version tag works?

**Comment by lintanghui** [comment]
`cluster slots` cmd is not backwards-incompatible  in redis-7.0, see detail at [Clusterbus extensions and hostname support](https://github.com/redis/redis/pull/9530) . the same issue #2082

**Comment by yuantingzhong** [comment]
> Did you solve it, I have this problem too
Please downgrade back to redis 6.x version, I have tested with 6.2.7 and it works well.

**Comment by yuantingzhong** [comment]
> I guess you are using the latest redis version(7.x), I downgrade back to 6.x version solved the problem.

Yes, you are right. Thank you.

**Comment by yuantingzhong** [comment]
> Hi what is the solution to this issue? What specific version tag works?

I replaced redis 7.x with redis 6.x ，and it worked well.

**Comment by xs0910** [comment]
我也遇到了，降回6.2.5就OK了

**Comment by highsea** [comment]
我从  redis:7.0.2-alpine  回退到 6.2 ，确实不报错了，谢谢
`docker pull redis:6.2-alpine3.16`
> PS: 
> redis7集群有报错： Unable to connect to redis cluster got 4 elements in cluster info address, expected 2 or 3

**Comment by vmihailenco** [comment]
Please use github.com/go-redis/redis/v9 with Redis 7

**Comment by mikhail-khalizev** [comment]
> Please use github.com/go-redis/redis/v9 with Redis 7

An error occurs:
`redis: 2022/07/18 15:54:24 pubsub.go:159: redis: discarding bad PubSub connection: read tcp 10.53.0.4:57004->10.53.0.3:17305: i/o timeout`

Redis server: 7.0.3
Package: github.com/go-redis/redis/v9 v9.0.0-beta.1

**Comment by mikhail-khalizev** [comment]
But PubSub works well with package `github.com/go-redis/redis/v8`

**Comment by SunGeolSong** [comment]
hello 
in source 

parse.go

info := ClusterSlotInfo{
			Start: int(start),
			End:   int(end),
			Addrs: make([]string, addrsn),
		}

		fmt.Printf("clusterSlotInfoSliceParser info.Addrs %v \n", info.Addrs)

		for i := int64(0); i < addrsn; i++ {

			fmt.Printf("clusterSlotInfoSliceParser loop i: %d \n", i)

			n, err := readArrayHeader(cn)
			if err != nil {
				return nil, err
			}

			fmt.Printf("clusterSlotInfoSliceParser loop i: %d, n: %d \n", i, n)

			if n != 2 && n != 3 && n != 4 {
				err := fmt.Errorf("clusterSlotInfoSliceParser got222 %d elements in cluster info address, expected 2 or 3 o 4", n)
				return nil, err
			}

			ip, err := readStringReply(cn)
			if err != nil {
				return nil, err
			}

			fmt.Printf("clusterSlotInfoSliceParser loop i: %d, ip: %s \n", i, ip)

			port, err := readIntReply(cn)
			if err != nil {
				return nil, err
			}

			fmt.Printf("clusterSlotInfoSliceParser loop i: %d, port: %d \n", i, port)

			if n >= 3 {
				// TODO: expose id in ClusterSlotInfo
				_, err := readStringReply(cn)
				if err != nil {
					return nil, err
				}
			}

			if n == 4 {

				s2, err := readArrayHeader(cn)
				if err != nil {
					fmt.Printf("clusterSlotInfoSliceParser loop i: %d, err: %v \n", i, err)

					return nil, err
				}

				fmt.Printf("clusterSlotInfoSliceParser loop i: %d, s2: %d \n", i, s2) // *0 mean 7.2 maybe end of array
			}

			info.Addrs[i] = net.JoinHostPort(ip, strconv.FormatInt(port, 10))
		}

**Comment by SunGeolSong** [comment]
info := ClusterSlotInfo{
			Start: int(start),
			End:   int(end),
			Addrs: make([]string, addrsn),
		}

		for i := int64(0); i < addrsn; i++ {
			n, err := readArrayHeader(cn)
			if err != nil {
				return nil, err
			}
			//if n != 2 && n != 3 {
			if n != 2 && n != 3 && n != 4 {
				err := fmt.Errorf("got %d elements in cluster info address, expected 2 or 3 or 4", n)
				return nil, err
			}

			ip, err := readStringReply(cn)
			if err != nil {
				return nil, err
			}

			port, err := readIntReply(cn)
			if err != nil {
				return nil, err
			}

			//if n == 3 {
			if n >= 3 {
				// TODO: expose id in ClusterSlotInfo
				_, err := readStringReply(cn)
				if err != nil {
					return nil, err
				}
			}

			if n == 4 {
				// TODO: expose id in ClusterSlotInfo
				_, err := readArrayHeader(cn) // *0 end
				if err != nil {
					return nil, err
				}
			}

			info.Addrs[i] = net.JoinHostPort(ip, strconv.FormatInt(port, 10))
		}

**Comment by liudonghua123** [comment]
I also got `panic: got 4 elements in cluster info address, expected 2 or 3` when I tried to use `go-redis` with the latest redis 7.2.3.
Since this is a known issues, why not update it or it has bean fixed?

**Comment by yangbodong22011** [comment]
The real fix PR for this issue is: https://github.com/redis/go-redis/pull/2108
