### ISSUE TITLE
cluster.go:1222 invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Justin910** [go-redis/redis#2099]
In the middle of running our program, the problem of null pointer appeared in Redis library
We can't find this problem online, please help

![image](https://user-images.githubusercontent.com/25916027/170906720-93ea3dfa-94d0-4fbb-8b83-b6a994d97bb6.png)
![image](https://user-images.githubusercontent.com/25916027/170906924-7eb84624-db40-4670-98f9-5e90bbaf767f.png)

**Comment by vmihailenco** [comment]
You are using v6, but the latest version is v8. Try to upgrade.
