### ISSUE TITLE
xreadgroup cant consume messages

### ISSUE THREAD

**Issue by yfanswer** [go-redis/redis#2104]
version: github.com/go-redis/redis v6.15.9+incompatible

Phenomenon: we found that we did not consume online and did not report an error. Then we changed the name of the consumer and began to consume normally.

We just found this phenomenon. We don't know the specific problem yet, so we sent an issue to see if you have encountered similar problems.

**Comment by vmihailenco** [comment]
v6 is not supporter any more.
