### ISSUE TITLE
No results but also no error!

### ISSUE THREAD

**Issue by SamiAlsubhi** [go-redis/redis#2121]
go-redis v8
go version go1.17.1 darwin/amd64

## Expected Behavior

if a command does not find a key/member than it should return `redis.Nil` in the error part of the result

## Current Behavior

command does not find a match and returns nil value and nil error.

## Steps to Reproduce

When I print val and err i get `[<nil>] <nil>` which does not make sense. Since there are no results, the error should be redis.Nil.

```go
func (r *RedisClient) GetOne(ctx context.Context, item *Identifier) (*SearchResponse, error) {
	pos, err := r.GeoPos(ctx, item.key(), item.Id).Result()

	if err == redis.Nil {
		return &SearchResponse{0, nil}, nil
	} else if err != nil {
		return nil, errors.New("failed to get point")
	}
	fmt.Println(pos, err) // [<nil>] <nil>
	point := pos[0]
	var objects []Object
	objects = append(objects, Object{
		Identifier: item,
		Location: &Location{
			Lat: point.Latitude,
			Lng: point.Longitude,
		},
	})

	return &SearchResponse{1, &objects}, nil

}
```

**Comment by vmihailenco** [comment]
>if a command does not find a key/member than it should return redis.Nil in the error part of the result

go-redis returns redis.Nil only when Redis Server returns `(nil)` response.

**Comment by SamiAlsubhi** [comment]
if you use the same command in `redis-cli` on a key that does not exist:

```
127.0.0.1:6379> GEOPOS DOESNT EXIST
1) (nil)
```
you get `nil` but in this library I am getting no `redis.Nil` and I am getting a list of one nil item in the results `[<nil>]`.

**Comment by vmihailenco** [comment]
Sorry, I've skipped that part. Yes, this is a bug.

**Comment by SamiAlsubhi** [comment]
I am using v8

**Comment by git-hulk** [comment]
@vmihailenco seems GeoPosCommand have to break the SetVal/Val/Result API to fix this issue since need to change from `[]*GeoPos` to `[]interface{}`. If this makes sense, I can submit a PR.

**Comment by VladimirStepanov** [comment]
@vmihailenco @SamiAlsubhi Which result we expect for this?
```bash
127.0.0.1:6379> GEOPOS Sicily Palermo NonExisting Catania
1) 1) "13.36138933897018433"
   2) "38.11555639549629859"
2) (nil)
3) 1) "15.08726745843887329"
   2) "37.50266842333162032"
```

**Comment by VladimirStepanov** [comment]
@vmihailenco @SamiAlsubhi i can add the following behavior:

**For:**
```bash
127.0.0.1:6379> GEOPOS Sicily not exists
1) (nil)
2) (nil)
```
**Result will be:** `[]*GeoPos{}, redis.Nil`

**For:**
```bash
127.0.0.1:6379> GEOPOS Sicily Palermo NonExisting
1) 1) "13.36138933897018433"
   2) "38.11555639549629859"
2) (nil)
```

**Result will be:** `[]*GeoPos{obj1, nil}, nil`

**Comment by vmihailenco** [comment]
After looking at this again, it seems to be working as expected. When I spoke before, I did not realize `GeoPos` returns multiple results in a slice.
