### ISSUE TITLE
Implement CLUSTER RESET

### ISSUE THREAD

**Issue by mindscratch** [go-redis/redis#213]
It appears support for [CLUSTER RESET](http://redis.io/commands/cluster-reset) is missing.

**Comment by dim** [comment]
Do you think you can submit at pull request, based on my commit for cluster
forget?

**Comment by mindscratch** [comment]
Yes, I'll do that.

**Comment by mindscratch** [comment]
I forked the repo and run make, on mac os x (el capitan) using go 1.5.1 and all tests fail, it seems perhaps it's not starting redis. Attached is the output from running `make`.
[output.txt](https://github.com/go-redis/redis/files/59807/output.txt)

**Comment by vmihailenco** [comment]
@mindscratch looks like Redis process can't start

```
      <*exec.ExitError | 0xc8204fc320>: {
          ProcessState: {
              pid: 35861,
              status: 256,
              rusage: {
                  Utime: {
                      Sec: 0,
                      Usec: 629,
                      Pad_cgo_0: [0, 0, 0, 0],
                  },
                  Stime: {
                      Sec: 0,
                      Usec: 1404,
                      Pad_cgo_0: [0, 0, 0, 0],
                  },
                  Maxrss: 688128,
                  Ixrss: 0,
                  Idrss: 0,
                  Isrss: 0,
                  Minflt: 199,
                  Majflt: 0,
                  Nswap: 0,
                  Inblock: 0,
                  Oublock: 0,
                  Msgsnd: 0,
                  Msgrcv: 0,
                  Nsignals: 0,
                  Nvcsw: 0,
                  Nivcsw: 1,
              },
          },
      }
      exit status 1
```

Most likely because you did not install test dependencies https://github.com/go-redis/redis/blob/master/Makefile#L5

**Comment by mindscratch** [comment]
@vmihailenco I do have the test dependencies. I've tried explicitly starting the redis server using `.test/redis/src/redis-server`, and then running `make`. Same problem with all of the tests failing.

**Comment by vmihailenco** [comment]
If you start tests with verbose `-v` flag you will see output from redis-server. That can help you to resolve the issue if you are still interested :)

BTW `CLUSTER RESET` was added in https://github.com/go-redis/redis/pull/223
