### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by Netherdrake** [go-redis/redis#215]
https://github.com/go-redis/redis/commit/401979b5976cbe8dfd45e727f7bd186db26f31a3

This change is a breaking change.

For instance, it is no longer possible to use `redis.RPush('key', []string{'a', 'b', 'c'}...)`

This should either be redis.v4 or have backwards compatibility with string values.

**Comment by vmihailenco** [comment]
Unfortunately I don't see any way to support []string{}... So reverting...
