### ISSUE TITLE
suggestion: consistent info if something doesn't exist

### ISSUE THREAD

**Issue by rand99** [go-redis/redis#220]
hello,
at the moment we have two behaviours when a key doesn't exist in this example

```
	map_cmd := fme.Redis_client.HGetAllMap("missing_key")
	t.Log(map_cmd.Err(), map_cmd.String(), map_cmd.Val())

	ss_cmd := fme.Redis_client.Get("missing_key")
	t.Log(ss_cmd.Err(), ss_cmd.String(), ss_cmd.Val())
```
results in 

```
	a_test.go:256: <nil> HGETALL missing_key: map[] map[]
	a_test.go:259: redis: nil GET missing_key: redis: nil 
```

So we have .Err() which is "redis: nil" one time and nil the other time.
redis-cli gives us this

```
127.0.0.1:6379> HGETALL missing_key
(empty list or set)
127.0.0.1:6379> GET missing_key
(nil)
127.0.0.1:6379> SMEMBERS missing_key
(empty list or set)
127.0.0.1:6379> 
```
so we explicitly know: ok this doesn't exist

It would be nice to have another cmd.Func (bool) called KeyNotFound() (like in sql-queries) additional to the Err(), Val() , ...

So, this wouldn't break anything (current api) and would be nice for all get methods.
Instead of checking if len(map) == 0 {} , etc.. for the types we could just do: if cmd.KeyNotFound() {}
What do you think?

best
m

**Comment by dim** [comment]
In my opinion, the current behaviour is correct and intended, as it follows
redis' own response logic.

For example, http://redis.io/commands/get may return nil, while
http://redis.io/commands/hgetall never do.

Returning redis.Nil as an error on some commands - I agree - sometimes
feels a little clumsy, but it's also a sensible compromise. I don't think
it would be right to return Nil on all commands, that would be
counterintuitive and a layer of logic on top of redis itself. A client
should not make such decisions.

**Comment by vmihailenco** [comment]
Speaking about `HGETALL` empty response can mean that:
- hash does not exist
- hash is empty

and we don't know answer for sure, because Redis Server does not tell us.

>for the types we could just do: if cmd.KeyNotFound() {}

We could add `cmd.IsEmpty()`, but it does not look important/popular enough (even now I don't see a convincing use case for it).

**Comment by dim** [comment]
Redis does not keep empty hash keys, empty keys are deleted:

```
$ redis-cli hset hash key value
(integer) 1
$ redis-cli exists hash
(integer) 1
$ redis-cli hdel hash key
(integer) 1
$ redis-cli exists hash
(integer) 0
```
