### ISSUE TITLE
pipeline set and client.Eval doesnt respect argument type and store data as string

### ISSUE THREAD

**Issue by cocodrino** [go-redis/redis#221]
Hello, sorry but I'm still a bit newbie with go and maybe I'm doing a mistake, the issue is than when I use pipeline set the value is stored as string even when I use an integer

```go
//p is p *redis.Pipeline
c = p.Set("USER::LIMIT:DISK::"+user.Name, 2000, 0)

in redis 
GET USER::LIMIT:DISK::tom
"2000"

the same happens with lua scripts, here I'm not sure if it's a mistake in go-redis but for instance if I use "2" as argument and inside my lua script I try to convert this value in 2 using number(v) seems not works 
```

**Comment by vmihailenco** [comment]
In redis numbers are stored as strings. So `p.Set` automatically converts int to string for you. You can find a list of supported types [here](http://redis.io/topics/data-types).

Also go-redis provides `Int64` shortcut that internally calls `strconv.ParseInt` to parse string into int64:

```
n, err := client.Get("USER::LIMIT:DISK::vmihailenco").Int64()
fmt.Println(n, err)
```

**Comment by cocodrino** [comment]
thanks for the resp @vmihailenco , I'm receiving a weird response when I try get values in a pipe...

```go
			_, err := client.Pipelined(func(p *redis.Pipeline) error {
				//....other code here

				clav := "USER::LIMIT:DISK::" + name
				fmt.Println("key is ", clav)
				limit, er := p.Get(clav).Int64()

				fmt.Println("values are ", limit, er)

				
			  //........
				return nil
			})


```
this print

```go

key is  USER::LIMIT:DISK::tomas
values are  0 strconv.ParseInt: parsing "": invalid syntax

```

but if I get this key with redis-cli
```bash

127.0.0.1:6379> get USER::LIMIT:DISK::tomas
"5"


```

the client is correctly configured: I can enter new values in my redis...am I doing something wrong???..thank you!!!...

**Comment by vmihailenco** [comment]
You don't have access to the value inside `Pipelined` function, because Pipeline queues commands to be executed in batch later. See (this example)[https://godoc.org/gopkg.in/redis.v3#example-Client-Pipelined] how to use `Pipelined`.

**Comment by cocodrino** [comment]
thanks @vmihailenco , sorry for don't answer before, this works as expected...
