### ISSUE TITLE
Test and update import path to github.com/redis/go-redis/v9

### ISSUE THREAD

**Issue by vmihailenco** [go-redis/redis#2217]
It probably will look like this:

```go
import redis "github.com/redis/go-redis/v9"
```

Checking if https://pkg.go.dev/golang.org/x/tools/cmd/goimports is still working would be nice.

- [ ] Should we add a canonical import path?

```shell
package redis // import "github.com/redis/go-redis/v9"
```

Another possibility will be using an import path like `go.redis.io/redis`, but not sure if that is worth it.

/cc @chayim

**Comment by chayim** [comment]
I really like the trend to go.redis.io/redis to be honest. I'll poke the internal folks and see what we can do here.

**Comment by vmihailenco** [comment]
@chayim yeah, its kinda nice when done right, for example, `go.opentelemetry.io/otel` works as an import path, but redirects to https://pkg.go.dev/go.opentelemetry.io/otel when accessed from a browser so it is more user friendly then the default.

**Comment by vmihailenco** [comment]
@chayim I am assigning this to you to check whether supporting `go.redis.io/redis/v9` is a feasible option. If not, we will go with `github.com/redis/go-redis/v9`.

https://sagikazarmark.hu/blog/vanity-import-paths-in-go/ should have some details.

**Comment by vmihailenco** [comment]
Closing since we decided to not use vanity import path. The import path will be

```
import redis "github.com/redis/go-redis/v9"
```
