### ISSUE TITLE
Support EVAL_RO and EVALSHA_RO

### ISSUE THREAD

**Issue by tisonkun** [go-redis/redis#2218]
Notice when porting [EVAL_RO tests for Kvrocks](https://github.com/apache/incubator-kvrocks/commit/87644ab5672fdcb8fe7d27e811ab115a88eb897f#diff-fd72f2293b0f304ba6ff9c6e65c2af3587b7cae4053cf3509d17424fde733f21).

This may be implemented almost as EVAL and EVALSHA.

**Comment by vmihailenco** [comment]
:+1: Something for v9

**Comment by tisonkun** [comment]
@vmihailenco thanks for confirming the value. If we're not in hurry, you can give me one week to try to implement it :)
