### ISSUE TITLE
v9 support lower Redis versions?

### ISSUE THREAD

**Issue by pjebs** [go-redis/redis#2222]
I did a quick test with v9 of this package.

It works with v7 of Redis as mentioned in docs.
When I tried it with v6 of Redis, it did not connect.

Do I have to use v8 of this package to use with v6?

Is there a chance that v9 of this package can support v6 and v7 of Redis?

**Comment by natenho** [comment]
Adding to the question, I'd like to understand the differences between major versions (regular, v8, v9), because I couldn't find in docs.

It would be great to have a migration description from one to another aswell.

**Comment by vmihailenco** [comment]
If you are using **Redis 6**, install go-redis/**v8**:

```shell
go get github.com/go-redis/redis/v8
```

If you are using **Redis 7**, install go-redis/**v9**:

```shell
go get github.com/go-redis/redis/v9
```

But `github.com/go-redis/redis/v9` should also work with Redis 6.
