### ISSUE TITLE
Retry error - READONLY You can't write against a read only replica

### ISSUE THREAD

**Issue by Harry-027** [go-redis/redis#2229]
I get an error while executing LUA script using evalsha command.

`ERR Error running script (call to f_f74233f556d3f99c50b61169cf8aa8d5deb63fb2): @user_script:5: @user_script: 5: -READONLY You can't write against a read only replica.`

I'm using ElastiCache for redis (cluster mode disabled & MultiAZ enabled). This happens during an upgrade/maintenance for cluster when a read-only replica is promoted to master.
As per my findings there is no issue from AWS side as the downtime was less than 20 secs but on retry mechanism the client kept throwing the same error for around 15 mins. Seems like the cluster state is not getting reloaded properly when there is ReadOnly error.

Probably, instead of `Lazyreload` we should allow a direct reload in such scenarios - [here](https://github.com/go-redis/redis/blob/master/cluster.go#L797)

Expected Behaviour -
Client shouldn't throw an error once the master node is again up & running.

**Comment by vmihailenco** [comment]
LazyReload should reload the cluster state in few seconds, not 15 mins.

>Probably, instead of Lazyreload we should allow a direct reload in such scenarios - [here](https://github.com/go-redis/redis/blob/master/cluster.go#L797)

Making it synchronous is not option if you thousands of commands per second.

Closing since this issue is non-actionable as it is.

**Comment by Harry-027** [comment]
@vmihailenco, according to you if `LazyReload` doesn't take 15 mins then for sure there must be something else causing the issue. Did you tried race condition checks on state reload use-case ? To be honest this is causing serious issues in our prod environment and I was expecting some root cause analysis from your end rather than closing it without any action.
