### ISSUE TITLE
Why not NewScript Run   retry use EvalSHA instead of Eval?

### ISSUE THREAD

**Issue by Lynton-Zhang** [go-redis/redis#2246]
https://github.com/go-redis/redis/blob/3e4ae80c124cf7e6e9d015f827cd2cc1c332088b/script.go#L72

If use Eval, this redis server instance seems to fail every time when `Run`?

**Comment by vmihailenco** [comment]
`EvalSha` uses less bandwidth compared to `Eval`, which helps with large scripts.

As for the fail, you would need to provide a reproducer https://stackoverflow.com/help/minimal-reproducible-example
