### ISSUE TITLE
RouteRandomly maps to RouteByLatency

### ISSUE THREAD

**Issue by jhmartin** [go-redis/redis#2274]
At https://github.com/go-redis/redis/blame/master/cluster.go#L213-L214 it looks like a specification to use `route_randomly` will instead trigger `RouteByLatency`.

```
	o.RouteByLatency = q.bool("route_by_latency")
	o.RouteByLatency = q.bool("route_randomly")
```

## Possible Solution

Switch 
`	o.RouteByLatency = q.bool("route_randomly")`
to
`	o.RouteRandomly = q.bool("route_randomly")`

**Comment by jhmartin** [comment]
@stephaniehingtgen Was this intentional?

**Comment by stephaniehingtgen** [comment]
@jhmartin sorry about that, it was not intentional. Thanks for bringing it up :) Opened a PR to fix it.
