### ISSUE TITLE
Ungraceful error handling

### ISSUE THREAD

**Issue by MuhammadTalhaRao** [go-redis/redis#2302]
When I set the TTL of the Set method which is not a duration constant from a time package like time.Duration(time.Now().UTC().Unix()) instead of time.Minute or something similar, the library neither gives compile time nor runtime error. It does not save the value in Redis which is very hard to debug.

func usePrecise(dur time.Duration) bool {
    return dur < time.Second || dur%time.Second != 0
}

Apparently, the error is because the duration must be multiple of a second which we found after debugging for a while. This error should be handled gracefully.

**Comment by vmihailenco** [comment]
>the library neither gives compile time nor runtime error.

You should either ask Go developers to add compile time errors or Redis developers to forbid small durations. It is not go-redis responsibility.
