### ISSUE TITLE
*"github.com/go-redis/redis/v8".Client does not implement redislock.RedisClient (wrong type for Eval method)

### ISSUE THREAD

**Issue by jackzhangsir** [go-redis/redis#2306]
module.go:34:33: cannot use r.redisClient (variable of type *"github.com/go-redis/redis/v8".Client) as type redislock.RedisClient in argument to redislock.New:
        *"github.com/go-redis/redis/v8".Client does not implement redislock.RedisClient (wrong type for Eval method)
                have Eval(ctx "context".Context, script string, keys []string, args ...interface{}) *"github.com/go-redis/redis/v8".Cmd
                want Eval(ctx "context".Context, script string, keys []string, args ...interface{}) *"github.com/go-redis/redis/v9".Cmd

**Comment by vmihailenco** [comment]
Replace redis/v8 with redis/v9.
