### ISSUE TITLE
Allow setting client name with paramater in connection string

### ISSUE THREAD

**Issue by sylr** [go-redis/redis#2312]
## Expected Behavior

Connection string should allow setting the client name as the [C# client does](https://stackexchange.github.io/StackExchange.Redis/Configuration#configuration-options) (see ClientName).

## Current Behavior

go-redis does not allow client name in connection string.

## Possible Solution

```
rediss://<user>:<password>@<host>:<port>/[<db>]?[name=<client_name>]
```

**Comment by monkey92t** [comment]
```go
func ExampleParseURL() {
	opt, err := redis.ParseURL("redis://:qwerty@localhost:6379/1?dial_timeout=5s")
	if err != nil {
		panic(err)
	}
	fmt.Println("addr is", opt.Addr)
	fmt.Println("db is", opt.DB)
	fmt.Println("password is", opt.Password)
	fmt.Println("dial timeout is", opt.DialTimeout)

	// Create client as usually.
	_ = redis.NewClient(opt)

	// Output: addr is localhost:6379
	// db is 1
	// password is qwerty
	// dial timeout is 5s
}


func ParseURL(redisURL string) (*Options, error) {
	u, err := url.Parse(redisURL)
	if err != nil {
		return nil, err
	}

	switch u.Scheme {
	case "redis", "rediss":
		return setupTCPConn(u)
	case "unix":
		return setupUnixConn(u)
	default:
		return nil, fmt.Errorf("redis: invalid URL scheme: %s", u.Scheme)
	}
}
```

**Comment by sylr** [comment]
@monkey92t could you elaborate what you mean with this example ?

**Comment by monkey92t** [comment]
Oh, sorry, I misread your issue... please forgive me😁...

`Redis ClientName` (`https://redis.io/commands/client-setname/`) is the name of the network connection, so it doesn't make sense for go-redis...

**Comment by ash2k** [comment]
Why does it not make sense? I'd like to be able to see the list of clients, connected to redis using [`CLIENT LIST`](https://redis.io/commands/client-list). My application needs to set the client name for that. There is `ClientSetName()` method on some connection types but it's impractical and wasteful to call it before each transaction/operation.

An ideal solution would be to allow to specify client name in `Options`/`FailoverOptions`/etc and let the library execute the `CLIENT SETNAME` command **once** right after a connection is established.

**Comment by monkey92t** [comment]
> Why does it not make sense? I'd like to be able to see the list of clients, connected to redis using [`CLIENT LIST`](https://redis.io/commands/client-list). My application needs to set the client name for that. There is `ClientSetName()` method on some connection types but it's impractical and wasteful to call it before each transaction/operation.

looks great
