### ISSUE TITLE
v9.0.0-rc.2 requires github.com/onsi/gomega v1.24.1 which works with go 1.18+ 

### ISSUE THREAD

**Issue by philchia** [go-redis/redis#2323]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

when import redis v9, my code can not compile at go 1.17

## Expected Behavior

need to be able to compile code at go 1.17, as the go.mod specified

## Current Behavior

go build report err says that module 

## Possible Solution

use github.com/onsi/gomega v1.24.1 requires go 1.18

**Comment by monkey92t** [comment]
go-redis supports 2 last Go versions and requires a Go version with [modules](https://github.com/golang/go/wiki/Modules) support.

supports 1.18,1.19
