### ISSUE TITLE
ExpireNX command should not exist in v8

### ISSUE THREAD

**Issue by itzik-solomon** [go-redis/redis#2332]
The Cmdable's ExpireNX command exists in branch v8 even though it depends on functionality that were added only in Redis 7.

## Expected Behavior

Cmdable should not define ExpireNX(), ExpireXX(), ExpireGT(), ExpireLT()

## Current Behavior

using these functions results in "(error) ERR wrong number of arguments for 'expire' command"

## Possible Solution

remove ExpireNX(), ExpireXX(), ExpireGT(), ExpireLT() from v8 branch

## Steps to Reproduce

1. call ExpireNX with any "valid" arguments
2. get error

**Comment by monkey92t** [comment]
I don't quite understand what it means...?

If your redis-server < 7.0, you should not use `ExpireNX()`

**Comment by itzik-solomon** [comment]
If I should not use it (because it is not supported), why does it exist in branches that don't support redis-server 7.0 in the first place?
what I'm trying to say is that it's misleading.

**Comment by monkey92t** [comment]
fixed #2340
