### ISSUE TITLE
ERR unknown command '--cluster'

### ISSUE THREAD

**Issue by Shaad7** [go-redis/redis#2336]
I have created a RedisClient using go-redis
```
rdClient := rd.NewClusterClient(rdClusterOpts)
```
I can do other database operation using the client
```
out,err := rdClient.Ping(context.TODO()).Result()
PONG
```
I can also do get set operation using the client.
When I try to rebalance the slots, it shows an error.
```
out, err := rdClient.Do(context.TODO(), "--cluster", "rebalance", "10.244.0.98", "--cluster-use-empty-masters").Result()
```
It shows the Error
```
ERR unknown command '--cluster', with args beginning with: 'rebalance' '10.244.0.96:6379' '--cluster-use-empty-masters
```

Is there any way to perform the Redis Cluster Manager commands using go-redis ?

**Comment by monkey92t** [comment]
The `rebalance` operation does not belong to the redis command (https://redis.io/commands/), it is an option of the redis-cli tool, you should use redis-cli to operate the cluster

**Comment by Shaad7** [comment]
Is it possible to operate the cluster using go-redis client ?

**Comment by monkey92t** [comment]
> Is it possible to operate the cluster using go-redis client ?

You can refer to the redis-cluster command(these commands are supported by go-redis):
[CLUSTER ADDSLOTS](https://redis.io/commands/cluster-addslots/)
[CLUSTER ADDSLOTSRANGE](https://redis.io/commands/cluster-addslotsrange/)
[CLUSTER BUMPEPOCH](https://redis.io/commands/cluster-bumpepoch/)
[CLUSTER COUNT-FAILURE-REPORTS](https://redis.io/commands/cluster-count-failure-reports/)
[CLUSTER COUNTKEYSINSLOT](https://redis.io/commands/cluster-countkeysinslot/)
[CLUSTER DELSLOTS](https://redis.io/commands/cluster-delslots/)
[CLUSTER DELSLOTSRANGE](https://redis.io/commands/cluster-delslotsrange/)
[CLUSTER FAILOVER](https://redis.io/commands/cluster-failover/)
[CLUSTER FLUSHSLOTS](https://redis.io/commands/cluster-flushslots/)
[CLUSTER FORGET](https://redis.io/commands/cluster-forget/)
[CLUSTER GETKEYSINSLOT](https://redis.io/commands/cluster-getkeysinslot/)
[CLUSTER INFO](https://redis.io/commands/cluster-info/)
[CLUSTER KEYSLOT](https://redis.io/commands/cluster-keyslot/)
[CLUSTER LINKS](https://redis.io/commands/cluster-links/)
[CLUSTER MEET](https://redis.io/commands/cluster-meet/)
[CLUSTER MYID](https://redis.io/commands/cluster-myid/)
[CLUSTER NODES](https://redis.io/commands/cluster-nodes/)
[CLUSTER REPLICAS](https://redis.io/commands/cluster-replicas/)
[CLUSTER REPLICATE](https://redis.io/commands/cluster-replicate/)
[CLUSTER RESET](https://redis.io/commands/cluster-reset/)
[CLUSTER SAVECONFIG](https://redis.io/commands/cluster-saveconfig/)
[CLUSTER SET-CONFIG-EPOCH](https://redis.io/commands/cluster-set-config-epoch/)
[CLUSTER SETSLOT](https://redis.io/commands/cluster-setslot/)
[CLUSTER SHARDS](https://redis.io/commands/cluster-shards/)
[CLUSTER SLAVES](https://redis.io/commands/cluster-slaves/)
[CLUSTER SLOTS](https://redis.io/commands/cluster-slots/)
[READONLY](https://redis.io/commands/readonly/)
[READWRITE](https://redis.io/commands/readwrite/)

go-redis supports redis-cluster (redis-server) commands (https://redis.io/commands), and does not support other functions (such as redis-cli)
