### ISSUE TITLE
Doubts about the retry mechanism

### ISSUE THREAD

**Issue by lingfengChen03** [go-redis/redis#2339]
Hi, I would like to know how the retry mechanism ensures that the command is not executed on the server side? In particular, why do io.EOF and io.ErrUnexpectedEOF allow retries?

Also the v8 version of _process has the variable retryTimeout always equal to 1, which should be a bug. v9 version has no problem.

**Comment by lingfengChen03** [comment]
Isn't there a case where the client sends a request, the server executes it, and then the tcp connection is broken when the data is returned?

**Comment by monkey92t** [comment]
First of all, io.EOF and io.EOF2 retries are meaningful. For redis-server restart, or switch redis-server, the established network connection will have io.EOF error. We try our best to retry the command in this case. When the redis-server is running normally, there will be no io.EOF error (RESP protocol).

retryTimeout is optimized in v9, and the commands with custom settings of readTimeout() are no longer retried.

 -------

> Isn't there a case where the client sends a request, the server executes it, and then the tcp connection is broken when the data is returned?

For this case, io.Read() will return an error and we will retry the command

**Comment by lingfengChen03** [comment]
Thank you very much for your reply.

> First of all, io.EOF and io.EOF2 retries are meaningful. For redis-server restart, or switch redis-server, the established network connection will have io.EOF error. We try our best to retry the command in this case. When the redis-server is running normally, there will be no io.EOF error (RESP protocol).

Now I know that io.EOF and io.EOF2 retries make sense.

> retryTimeout is optimized in v9, and the commands with custom settings of readTimeout() are no longer retried.

In v8 version _process variable retryTimeout is always equal to 1 means that read timeout needs to be retried as well?

> > Isn't there a case where the client sends a request, the server executes it, and then the tcp connection is broken when the data is returned?
> 
> For this case, io.Read() will return an error and we will retry the command

Lastly my understanding of this case the server side has already executed the command? Why do I need to retry in this case? And I don't see any error in the code.

Looking forward to your reply!

**Comment by lingfengChen03** [comment]
Thank you very much for your reply.

> First of all, io.EOF and io.EOF2 retries are meaningful. For redis-server restart, or switch redis-server, the established network connection will have io.EOF error. We try our best to retry the command in this case. When the redis-server is running normally, there will be no io.EOF error (RESP protocol).

Now I know that io.EOF and io.EOF2 retries make sense.

> retryTimeout is optimized in v9, and the commands with custom settings of readTimeout() are no longer retried.

In v8 version _process variable retryTimeout is always equal to 1 means that read timeout needs to be retried as well?

> > Isn't there a case where the client sends a request, the server executes it, and then the tcp connection is broken when the data is returned?
> 
> For this case, io.Read() will return an error and we will retry the command

Lastly my understanding of this case the server side has already executed the command? Why do I need to retry in this case? And I don't see any error in the code.

Looking forward to your reply!

**Comment by monkey92t** [comment]
> In v8 version _process variable retryTimeout is always equal to 1 means that read timeout needs to be retried as well?
> 
> > >
v8:  write error(retry YES), read timeout(retry YES), cmd.readTimeout (retry YES)
v9: write error(retry YES), read timeout(retry YES), cmd.readTimeout (retry NO) 



> Lastly my understanding of this case the server side has already executed the command? Why do I need to retry in this case? And I don't see any error in the code.

Yes, there are indeed cases where commands are repeated, which can have side effects on commands such as Incr,XAddd.
But in most cases, we still hope that when there is an error in the network, we can retry to execute the command to get the result. It depends on your own judgment. If you don't want go-redis to retry, you can set opt.MaxRetries=- 1

**Comment by lingfengChen03** [comment]
> > Lastly my understanding of this case the server side has already executed the command? Why do I need to retry in this case? And I don't see any error in the code.
> 
> If it is a mysql or oracle database, an error should be returned. But for redis, retries are a good option(default = 3) .

My understanding is that the client will receive a  ( connection reset) error on a read time exception, at which point looking at the code doesn't retry.

**Comment by monkey92t** [comment]
> My understanding is that the client will receive a ( connection reset) error on a read time exception, at which point looking at the code doesn't retry.

This is to use different strategies for different services.

**Comment by LeGamerDc** [comment]
i have encountered a similar problem, which we use a redis eval to do a CAS operation to implement a redis lock, it successed and met a peer reset, and retry, got failure. pretty hard to debug
