### ISSUE TITLE
func (c *Client) Info() should accept a section parameter

### ISSUE THREAD

**Issue by Shamanoid** [go-redis/redis#235]
func (c *Client) Info() *StringCmd should become :
func (c *Client) Info(section string) *StringCmd, in order to respect the INFO command reference such as defined in http://redis.io/commands/info

It would also permit to avoid requesting all default sections each time and would ease the creation of monitoring tools.

**Comment by vmihailenco** [comment]
Done https://godoc.org/gopkg.in/redis.v3#Client.Info

**Comment by Shamanoid** [comment]
Thanks a lot !
