### ISSUE TITLE
Should hooks be considered to use FIFO mode?

### ISSUE THREAD

**Issue by monkey92t** [go-redis/redis#2350]
In the v9 version, the hook uses the FILO mode (first in, last out). The hook added first is executed last.

It is a common practice for hooks to use FIFO mode in many services (such as gin). 

Should we consider using FIFO?

@vmihailenco ?

**Comment by vmihailenco** [comment]
The new hooks work by wrapping the previous hook function, e.g.:

```go
var hook hookFunc
hook = hook1(hook)
hook = hook2(hook)
hook = hook3(hook)
```

It looks like we can't control the execution order with such scheme, because there is only a single func to call...

**Comment by monkey92t** [comment]
We can calculate `hs.processHook` every time AddHook, like `setProcess`.

In addition, we also need to record the setProcess function(cmd exec func),
The hooks structure might look like this(systemHook is cmd exec func):

```go
type hooks struct {
	slice      []Hook
	systemHook Hook

	mu sync.Mutex

	dialHook              DialHook
	processHook           ProcessHook
	processPipelineHook   ProcessPipelineHook
	processTxPipelineHook ProcessPipelineHook
}
```

addhook could look like this (example):

```go

func (hs *hooks) addHook(hook Hook, systemHook bool) {
	hs.mu.Lock()
	defer hs.mu.Unlock()

	// The old cmdProcess will be overwritten by the new cmdProcess.
	if systemHook {
		hs.systemHook = hook
	} else {
		hs.slice = append(hs.slice, hook)
	}

	slice := make([]Hook, len(hs.slice), len(hs.slice)+1)
	copy(slice[0:], hs.slice)
	if hs.systemHook != nil {
		slice = append(slice, hs.systemHook)
	}

	last := slice[len(slice)-1]

	// The last one is generally a command execution function, it does not need next,
	// But in order to prevent panic, should we set a default function?
	// For example: NonDialHook(...){ return nil }
	hs.dialHook = last.DialHook(nil)
	hs.processHook = last.ProcessHook(nil)
	hs.processPipelineHook = last.ProcessPipelineHook(nil)
	hs.processTxPipelineHook = last.ProcessPipelineHook(nil)

	for i := len(slice) - 2; i >= 0; i-- {
		if wrapped := slice[i].DialHook(hs.dialHook); wrapped != nil {
			hs.dialHook = wrapped
		}
		if wrapped := slice[i].ProcessHook(hs.processHook); wrapped != nil {
			hs.processHook = wrapped
		}
		if wrapped := slice[i].ProcessPipelineHook(hs.processPipelineHook); wrapped != nil {
			hs.processPipelineHook = wrapped
		}
		if wrapped := slice[i].ProcessPipelineHook(hs.processTxPipelineHook); wrapped != nil {
			hs.processTxPipelineHook = wrapped
		}
	}
}
```

If we consider redesigning hooks, it may break the existing api.

**Comment by monkey92t** [comment]
We need to manually operate the call hook to the next chain. I think that for `hook`, we can provide the function of `next`, but the call of `next` should not be the user's task.

Example explanation:

```go
// Example-1:
func (H1) ProcessHook(next ProcessHook) ProcessHook {
	return func(ctx context.Context, cmd string) error {
		start := time.Now()
		err := next(ctx, cmd)
		log.Write("cmd_time", time.Since(start))
		return err
	}
}

// Example-2:
func (H1) ProcessHook(next ProcessHook) ProcessHook {
	return func(ctx context.Context, cmd string) error {
		// code....
		return nil
	}
}

```

Example-1 manually called `next`, because we need cmd_time, Example-2 did not call `next`, some other code was executed, but finally both Example-1 and Example-2 should call the redis command. If the user wants to terminate the redis command execution, we can provide API, such as (Abort, Exit, Return).


Maybe we should set up an independent hook instead of implementing the Hook interface every time.
```go
type Hook interface {
	DialHook(next DialHook) DialHook
	ProcessHook(next ProcessHook) ProcessHook
	ProcessPipelineHook(next ProcessPipelineHook) ProcessPipelineHook
}
```

If we do this, it will greatly break the existing API, but v9 is still the rc version, right? 😁😁😁

**Comment by monkey92t** [comment]
> we still have time to replace hooks implementation if that helps with redismock or something. Do you have a use for FIFO hooks?

NO, this is just my opinion on v9-hook based on my experience, FILO is not a problem if we do enough explanation.


> I believe that would require an allocation and should be considerably slower. But we could try.
> 
> >
I believe the performance problem is not big, we only need to call AddHook M times (M is the number of hooks)

I think for most users: the hook I added first should be executed first...(this is just my thought)

**Comment by vmihailenco** [comment]
@monkey92t just heads up that @chayim and I are planning to move the repo to the Redis org on github and tag v9. The new repo path will be github.com/redis/go-redis.

We can tag another release candidate like v9.0.0-rc3 or a final v9.0.0 version depending on what we decide here regarding the hooks.

**Comment by monkey92t** [comment]
@vmihailenco I agree to use FIFO mode, modified as described above:

> > We can calculate hs.processHook every time AddHook, like setProcess.

FIFO is more in line with most users' habit of `hook`...What do you think?

**Comment by vmihailenco** [comment]
>FIFO is more in line with most users' habit of hook...What do you think?

Agreed. Could you prepare a PR or do you want me to do it?

**Comment by monkey92t** [comment]
> > FIFO is more in line with most users' habit of hook...What do you think?
> 
> Agreed. Could you prepare a PR or do you want me to do it?

OK, let me add a PR...

**Comment by monkey92t** [comment]
#2358
