### ISSUE TITLE
SCAN fails to parse cursor value out of int64 range

### ISSUE THREAD

**Issue by mdogan** [go-redis/redis#2355]
SCAN cursor is an `unsigned 64 bit number` in Redis protocol. It's defined at https://redis.io/commands/scan as:

```
SCAN, SSCAN, HSCAN and ZSCAN return a two elements multi-bulk reply, 
where the first element is a string representing an unsigned 64 bit number (the cursor)...
```
But the cursor is read as an `int64` at https://github.com/go-redis/redis/blob/31f6ce03990aac1d06f366bb998ffef9713969e5/command.go#L2697

which fails to parse result if the cursor value is out of `int64` range, like;

```
strconv.ParseInt: parsing "14430143861864273311": value out of range
```

In v8, it was being read as `uint`: https://github.com/go-redis/redis/blob/6c688c7e9f6276867db4d09b1c48babb45cf2a93/internal/proto/reader.go#L216-L225

**Comment by vmihailenco** [comment]
Good catch! Thanks for reporting.
