### ISSUE TITLE
Redis Cluster

### ISSUE THREAD

**Issue by arnaudbriche** [go-redis/redis#24]
Are you planning on implementing Redis Cluster anytime soon ? Are you waiting for it to be production ready ? Or are you simply not interested ?

**Comment by bsm** [comment]
Cluster functionality is quite limited, compared to 'normal' redis, so I went down the route of wrapping this library to create a cluster client: https://github.com/bsm/redis-cluster/

**Comment by vmihailenco** [comment]
Redis Cluster support was merged into master some time ago. Closing.
