### ISSUE TITLE
Cluster commands like FlushAll and Keys only contact one node.

### ISSUE THREAD

**Issue by jaffee** [go-redis/redis#240]
```
cli := redis.NewClusterClient(&redis.ClusterOptions{
	Addrs: []string{"localhost:55400", "localhost:55401", "localhost:55402"},
})
// add data to a variety of keys
// ...
// now try flushing
cli.FlushAll().Result()
// only some keys will have been deleted because hashSlot just picks a random slot
```

I have a bit of code that fixes this (for FLUSHALL at least), but I wanted to make sure I'm not missing the right way to do this before I invest any more time in that.

**Comment by dim** [comment]
Yes, I was wondering if it makes more sense to remove these from
ClusterClient in the next release and expose them on the single Client only.

**Comment by jaffee** [comment]
Well, they're definitely useful commands to have IMO. Maybe a separate process method on ClusterClient for commands that need to talk to every node in the cluster? It looks like there are other clients (https://github.com/Grokzen/redis-py-cluster at least) that do this.

I'd be happy to take a stab at it if y'all are interested in having this functionality.

**Comment by dim** [comment]
I think you are getting into really dangerous territory, far beyond what a
client library should be capable of.

What guarantees would a FlushAll provide? What if one node is unresponsive
or fails, how would you deal with such a scenario? What if a node has just
been added to the cluster and is unknown to the client?

Instead, I would rather implement something like an iterator that allows
you to run through individual client connections and execute custom
commands, handle individual errors, etc

**Comment by vmihailenco** [comment]
>I would rather implement something like an iterator

This sounds right, but I afraid that in practise you just pass the problem to users :) I.e. I doubt that users can better answer questions you raised. Or that those questions can have more than one right answer...

**Comment by vmihailenco** [comment]
>I'd be happy to take a stab at it if y'all are interested in having this functionality.

I am interested to take a look at such pull request - thanks in advance.

**Comment by jaffee** [comment]
The iterator would solve the problem of what to return in the case that some nodes but not all encountered an error, but perhaps that could also be aggregated into a more sophisticated error from a single call.

The problem of ensuring that all nodes have been contacted/all slots have been covered is a bit trickier in the event that slots are being moved around - I think this problem remains in either case.

I'll see what I can come up with.

**Comment by Adrien-P** [comment]
I'm interested in such feature. For the moment I'll do the cluster "keys" command manually (iterating over nodes)

**Comment by vmihailenco** [comment]
Everyone who is interested in this please take a look at https://github.com/go-redis/redis/pull/331
