### ISSUE TITLE
run "go get", but report an error

### ISSUE THREAD

**Issue by JingchengLi** [go-redis/redis#242]
ljc@ljc-HP-Z220-SFF-Workstation:~/project/r2m_manager/src$ go get github.com/go-redis/redis
github.com/go-redis/redis/pool.go:133: undefined: atomic.Value

**Comment by vmihailenco** [comment]
Please upgrade to Go 1.4+

**Comment by JingchengLi** [comment]
I use Go 1.5.2 already.

**Comment by JingchengLi** [comment]
sorry, I found my go version is 1.2, I upgrade and it works now

**Comment by vmihailenco** [comment]
:ok_hand:
