### ISSUE TITLE
Nil reply parsing - handling missing keys

### ISSUE THREAD

**Issue by tbasnett** [go-redis/redis#246]
I think my question may be related to the recent update #226...

I have a scenario where I am using a Sort command and using the GET option to retrieve multiple hash fields. In my case one of the corresponding hashes is missing one of the fields which causes an error to be thrown (specifically from the isNilReply method which was moved to the readLine in the referenced ticket above)

I'm looking to be able to still return the results with missing fields having an empty string since the redis result will do the same. 

ie: SORT things1 GET things2:\*->somefield GET things2:\*->missingfield    

(An empty row is still returned for the missing field)

Is this something that could be addressed? (or since I am new to redis, is there another way to do this?)

**Comment by vmihailenco** [comment]
Thanks for the detailed report. Should be fixed by https://github.com/go-redis/redis/blob/fix/sort-nil-reply/commands_test.go#L540-L554. Since I can't change API I also added `SortInterfaces` which returns `[]interface{}` slice which helps when you want to differentiate `nil` and empty string.
