### ISSUE TITLE
some command line set, del aways print redis: nil in command line

### ISSUE THREAD

**Issue by goldalworming** [go-redis/redis#258]
hi, why my terminal always print redis: nil while execute set, del or another?

I think it will flooding my log file
it came from this code => err = red.Set(key, txtexp, texp).Err()
and this err = red.Del(key).Err()

how to prevent this?

**Comment by vmihailenco** [comment]
Can you show code that reproduces this issue?

**Comment by goldalworming** [comment]
the code is shown in my question
err = red.Set(key, txtexp, texp).Err()
and
err = red.Del(key).Err()

**Comment by goldalworming** [comment]
result := struct{ 	
		Success bool
		Message string
	}{}	
    if err == nil && token.Valid {
	    red := models.GetRedisClient()
	    username := token.Claims["username"].(string)

	    key := "scraper:"+username
	    texp := time.Minute*10
	    txtexp := time.Now().Add(texp).Unix()

        valget, err := red.Get(key).Result()
        if err != nil {
            fmt.Println(err)
        }
        if(valget==""){
			result.Success = false
			result.Message="User Not Login"
    	}else{
            err = red.Set(key, txtexp, texp).Err()
            if err != nil {
				result.Success = false
				result.Message = err.Error()
            }else{
				result.Success = true
				result.Message = key
            }
    	}

    }else{
	    fmt.Println(err)
		result.Success = false
		result.Message = err.Error()
    }

**Comment by vmihailenco** [comment]
redis.Nil error is returned when key does not exist - https://github.com/go-redis/redis/blob/v3.3.2/error.go#L11. I hopes that helps...
