### ISSUE TITLE
connPool.reaper disturb conn's usedAt

### ISSUE THREAD

**Issue by dunixd** [go-redis/redis#263]
Hi: `connPool.reaper` will get a `conn` and call `connPool.Put` every minite
```
func (p *connPool) reaper() {
    ticker := time.NewTicker(time.Minute)
    defer ticker.Stop()

    for _ = range ticker.C {
        if p.closed() {
            break
        }

        // pool.First removes idle connections from the pool and
        // returns first non-idle connection. So just put returned
        // connection back.
        if cn := p.First(); cn != nil {
            p.Put(cn)
        }
    }
}
```
Then `connPool`.Put will reset `cn.usedAt`
```
func (p *connPool) Put(cn *conn) error {
    if cn.rd.Buffered() != 0 {
        b, _ := cn.rd.Peek(cn.rd.Buffered())
        err := fmt.Errorf("connection has unread data: %q", b)
        Logger.Print(err)
        return p.Remove(cn, err)
    }
    if p.opt.getIdleTimeout() > 0 {
        cn.usedAt = time.Now()
    }
    p.freeConns <- cn
    return nil
}
```
But this action didn't call any redis cmd to redis-server.
So after a Idle time redis-server will close the connection but we will not.

**Comment by vmihailenco** [comment]
Thanks for debugging this. I just released v3.3.1 with a fix.

**Comment by dunixd** [comment]
Maybe [https://github.com/go-redis/redis/blob/master/pool.go#L214:L231](https://github.com/go-redis/redis/blob/master/pool.go#L214:L231) should also set `cn.UsedAt`.
Think about when `connPool.reaper` found a timeout `conn` a new `conn` will be replaced into `connPool` whose `UsedAt` is zero. That means it is an timeout `conn`

**Comment by vmihailenco** [comment]
Thanks fixed with https://github.com/go-redis/redis/pull/265
