### ISSUE TITLE
Tons of "connection has unread data" log messages with v3.3.2

### ISSUE THREAD

**Issue by dim** [go-redis/redis#267]
Not sure what happened, had no time to debug, but I get tons of `connection has unread data` messages since updating to 3.3.2:

```
redis: 2016/03/08 14:33:14 connection has unread data: "+OK\r\n"
redis: 2016/03/08 14:33:14 connection has unread data: "+OK\r\n"
redis: 2016/03/08 14:34:21 connection has unread data: "$-1\r\n"
redis: 2016/03/08 14:34:21 connection has unread data: "$-1\r\n"
redis: 2016/03/08 14:34:32 connection has unread data: "$-1\r\n"
```

**Comment by vmihailenco** [comment]
Can you share `redis.Options` you are using?

It can be that v3.3.2 just made the problem more obvious, because now go-redis always prints something to the log when closing connection that has unread data.

**Comment by vmihailenco** [comment]
My guess is that you have:
- MaxRetries > 0
- low ReadTimeout/WriteTimeout
- timeouts on reads/writes

That combination can lead to unread data in connection buffer. I have an idea how to improve situation, but it requires non-trivial refactoring.

**Comment by dim** [comment]
So yes, my `ReadTimeout` and `WriteTimeout` are quite low, which makes sense then. Thanks
