### ISSUE TITLE
the RateLimiter in Pool.  ratelimit.New(3*opt.getPoolSize(), time.Second)?

### ISSUE THREAD

**Issue by bairongdong1** [go-redis/redis#270]
I have a high concurrent application. 
May query redis-cluster 30,000 times per second.
How to set the poolSize?

Also, why set ratelimit 3 times of opt.getPoolSize()?
line 140 of file pool.go.
`rl:        ratelimit.New(3*opt.getPoolSize(), time.Second),`

**Comment by vmihailenco** [comment]
There is PoolSize option in https://godoc.org/gopkg.in/redis.v3#ClusterOptions. Note that by default pool size is 10 connections to each server in the cluster. So if you have 10 servers in the cluster go-redis will open 10*10=100 connections. That should be enough in most cases.

>Also, why set ratelimit 3 times of opt.getPoolSize()?

TLDR - it should not affect you as long as Redis Server/network is healthy.

When your app is healthy go-redis reuses open connections and everything is good. But when Redis Server is down your app starts to open/close connections with very high rate (30,000 times per second in your case). Very soon it will use all available connections in the system, which can affect other applications (such as database connections) if you don't configure your system limits right. To prevent this go-redis limits number of new connections you can open. By default it allows to open 30 new connections per second.
