### ISSUE TITLE
readN slice bounds out of range

### ISSUE THREAD

**Issue by mc0** [go-redis/redis#278]
I compiled recently after updating versions and got the following:
panic: runtime error: slice bounds out of range

goroutine 9 [running]:
gopkg.in/redis%2ev3.parseBytesReply(0xc82000e540, 0xc8200b3000, 0x5, 0x1000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/gopkg.in/redis.v3/parser.go:306 +0x304
gopkg.in/redis%2ev3.readBytesReply(0xc82000e540, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/gopkg.in/redis.v3/parser.go:318 +0xff
gopkg.in/redis%2ev3.(*StringCmd).readReply(0xc82006c6e0, 0xc82000e540, 0x0, 0x0)
	/go/src/gopkg.in/redis.v3/command.go:450 +0x42
gopkg.in/redis%2ev3.(*baseClient).process(0xc8200111e0, 0x7f1c325f0b58, 0xc82006c6e0)
	/go/src/gopkg.in/redis.v3/redis.go:114 +0x327
gopkg.in/redis%2ev3.(*baseClient).(gopkg.in/redis%2ev3.process)-fm(0x7f1c325f0b58, 0xc82006c6e0)
	/go/src/gopkg.in/redis.v3/redis.go:156 +0x34
gopkg.in/redis%2ev3.(*commandable).Process(0xc82000b7f0, 0x7f1c325f0b58, 0xc82006c6e0)
	/go/src/gopkg.in/redis.v3/commands.go:57 +0x34
gopkg.in/redis%2ev3.(*commandable).BRPopLPush(0xc82000b7f0, 0x84e190, 0x10, 0x84e170, 0x16, 0x2540be400, 0xc8200135c0)
	/go/src/gopkg.in/redis.v3/commands.go:751 +0x2fd

It looks like this introduced the issue @ `readN` (@vmihailenco):
ad0739be9976594d3ab71a4e61c5e8501fe11d66

The data it's getting out of redis is 7571 bytes via BRPopLPush.

This seems like a pretty large update for v3 - why didn't that make it into a v4?

**Comment by vmihailenco** [comment]
Thanks for the report.

>This seems like a pretty large update for v3 - why didn't that make it into a v4?

Well, API did not change and really that PR just moved some code to internal subpackage. And I was confident about that change because there are tests and benchmarks for setting/getting big keys...
