### ISSUE TITLE
connect unread data with ClusterInfo

### ISSUE THREAD

**Issue by mc0** [go-redis/redis#286]
I assume that this error is coming from `randomClient` as I'm not directly calling ClusterInfo.

connection has unread data: "$279\r\ncluster_state:ok\r\ncluster_slots_assigned:16384\r\ncluster_slots_ok:16384\r\ncluster_slots_pfail:0\r\ncluster_slots_fail:0\r\ncluster_known_nodes:6\r\ncluster_size:3\r\ncluster_current_epoch:16\r\ncluster_my_epoch:16\r\ncluster_stats_messages_sent:527928\r\ncluster_stats_messages_received:527928\r\n\r\n"

**Comment by vmihailenco** [comment]
Such log message can appear if there are network timeouts. Please try to upgrade to latest version since I made few improvement to connection management, e.g. https://github.com/go-redis/redis/pull/268
