### ISSUE TITLE
ClusterClient MGet fails ?

### ISSUE THREAD

**Issue by maxzerbini** [go-redis/redis#291]
Hi,
first of all thanks for your work, it' very useful.

Testing the ClusterClient and the MGet method, I got this error message "Error CROSSSLOT Keys in request don't hash to the same slot". I made the MGet call passing a list of keys that may belong to different slots.
Can I only invoke MGet with a lists of uniform keys all belong to the same slot?
How do I determine the slot of a key? Do I need to call the method ClusterKeySlot for every keys?

Regards,
Massimo

**Comment by dim** [comment]
Why don't you use a pipeline with multiple GETs?

**Comment by maxzerbini** [comment]
I tried to use ClusterPipeline according to your suggestion, I'm not sure that the performance of the pipeline will be identical to MGET, but can fit.

I found another problem executing a pipeline of Get operations, if all keys are stored in the cluster all is fine, but if a key is missing I got the error "redis: nil" .

It seems that the pipeline does not handle correctly the answers of the multiple GETs, can you make a fix?

**Comment by dim** [comment]
This is actually the correct and expected behaviour.

**Comment by maxzerbini** [comment]
How is it possible? In this way the GETs pipeline are unusable.

**Comment by vmihailenco** [comment]
Pipeline returns first error (if there are any), but it processes all commands nevertheless. So you can:
- ignore `redis.Nil` error if you don't care about it
- inspect each command separately

See https://github.com/go-redis/redis/blob/master/cluster_test.go#L447-L469 for an example.

**Comment by maxzerbini** [comment]
Ok, thank you.

2016-04-06 13:08 GMT+02:00 Vladimir Mihailenco <notifications@github.com>:
