### ISSUE TITLE
Write: Broken Pipe using ClusterClient

### ISSUE THREAD

**Issue by tpiron** [go-redis/redis#292]
Hi,

I'm having an issue with ClusterClient and the way it removes bad connections from the pool.

After a few seconds (almost a minute), if I query redis with a query that used to work, I'll get a "write: broken pipe", and then the query after that will be ok.

I can see that Option{} has a MaxRetries value, but ClusterOptions doesn't, any idea why Options has one and not ClusterOptions ? (https://github.com/go-redis/redis/issues/84#issuecomment-125043773)

Or is there another way to avoid getting broken pipe ? (I guess having a lower timeout in go-redis than in redis-server should probably fix that as well)

**Comment by vmihailenco** [comment]
Hi,

ClusterClient has `MaxRedirects` option instead of `MaxRetries`, because ClusterClient retries on:
- network errors (net.Error and io.EOF)
- redis ASK and MOVED response

But looks like `write: broken pipe` is not considered to a network error...

>Or is there another way to avoid getting broken pipe

Did you see `IdleTimeout` option?

```
    // Specifies amount of time after which client closes idle
    // connections. Should be less than server's timeout.
    // Default is to not close idle connections.
    IdleTimeout time.Duration
```

**Comment by tpiron** [comment]
I started using `IdleTimeout` (less than server's timeout) and it seems to be working.

I also had to disable the redis logger, as reaper was logging when releasing connections. 

`redis.Logger.SetOutput(ioutil.Discard)`

**Comment by vmihailenco** [comment]
Logger is disable by default in latest version. Also it is better to use `redis.SetLogger(log.New(ioutil.Discard, "redis: ", log.LstdFlags))` to set logger, because `redis.Logger` is deprecated.

**Comment by tpiron** [comment]
Indeed, it is disabled by default. (I had an old version of go-redis in my docker image.)
