### ISSUE TITLE
Are hashslots cached?

### ISSUE THREAD

**Issue by ak2344** [go-redis/redis#311]
Thanks for all your work, the client is pretty extensive. Happy to help flesh out documentation if that would help. 

I believe this is the case, but wanted to confirm -- are hashslots cached? If so, does anything need to be done if hashslots are reassigned?

**Comment by vmihailenco** [comment]
Hashslots are automatically discovered and cached. When client uses outdated slot info Redis Cluster replies with ASK/REDIRECT response and client automatically retrieves updated hashslots information. So you don't have to worry about this.

>Happy to help flesh out documentation if that would help.

Sure, that would be awesome - waiting for pull requests :)

**Comment by ak2344** [comment]
Thanks for the quick response! That's helpful.

Re: docs, I had a few of questions:

- Were there any sections / examples you'd like to see?
- What's the best way to structure the docs? Like if I add more examples, where should those live? In a new Readme maybe?
- If I wanted to communicate with you for questions, what's the best way to do that? Email?

**Comment by dim** [comment]
I think godoc is the best approach, the README should really just reference
the godoc page.

We need a more verbose package documentation as well as better struct
descriptions, especially for Client and ClusterClient. The details are
outlined here: https://blog.golang.org/godoc-documenting-go-code.

Finally, more examples could be provided via
https://blog.golang.org/examples.

**Comment by vmihailenco** [comment]
I can only add that README should include only brief/important information for users that have 30 seconds to decide if this package suits their needs or not. The rest should be in package comments and examples.

>If I wanted to communicate with you for questions, what's the best way to do that? Email?

I think the best way is to open PR or issue (like this one :).

**Comment by ak2344** [comment]
Hello,

What's the best way to contribute to the godoc? Sorry, new to go.

Also, I had another question. When I connect to a cluster via NewClusterClient(opt *ClusterOptions), is there a way to check if the connection was successful using the response from the connection attempt, or should I issue a ping right after connecting to confirm it was successful (two round trips)?

**Comment by vmihailenco** [comment]
>What's the best way to contribute to the godoc?

Godoc is automatically built from source code comments. See https://blog.golang.org/godoc-documenting-go-code

>should I issue a ping right after connecting to confirm it was successful (two round trips)

You should use `Ping` and it will take 1 roundtrip, because `NewClusterClient` does not open any connections.

**Comment by ak2344** [comment]
OK great. Thanks @vmihailenco!
