### ISSUE TITLE
Multi.Exec() doesn't preserve current database selection

### ISSUE THREAD

**Issue by KtorZ** [go-redis/redis#312]
Hey, I've just ran into an issue while using the client.
It seems that, if a database is selected "manually" (not within the client's options), executing a transaction will place the client in its original state with the default database selected. Not the actual one.

Here's how to reproduce:
```go
	c := redis.NewClient(&redis.Options{
		Addr: "localhost:6379",
	})
	/* Set two different values for the same key on redis #0 and redis #14 */
	_ = c.Set("example-key", "redis-client-#0", 0)
	_ = c.Select(14)
	_ = c.Set("example-key", "redis-client-#14", 0)

	/* Check the stored value */
	log.Println(c.Get("example-key").String())
	// GET example-key: redis-client-#14

	/* Process a transaction */
	multi, _ := c.Watch("example-key")
	_, _ = multi.Exec(func() error {
		/* Whatever */
		return nil
	})

	log.Println(c.Get("example-key").String())
	// GET example-key: redis-client-#0
```

whereas in Redis, we've the following behavior:

```redis
127.0.0.1:6379> SET "example-key" "redis-client-#0"
OK
127.0.0.1:6379> SELECT 14
OK
127.0.0.1:6379[14]> SET "example-key" "redis-client-#14"
OK
127.0.0.1:6379[14]> GET "example-key"
"redis-client-#14"
127.0.0.1:6379[14]> MULTI
OK
127.0.0.1:6379[14]> EXEC
(empty list or set)
127.0.0.1:6379[14]> GET "example-key"
"redis-client-#14"
```

**Comment by vmihailenco** [comment]
This is interesting! I think that behaviour of the program you provided is not defined, i.e. command may be executed against redis #0 or redis #14 depending on how connection pool is implemented.

Corrected program should be:

```
tx := c.Multi()
err := tx.Select(14).Err()
if err != nil { panic(err) }
err := tx.Watch(keys...)
if err != nil { panic(err) }
cmds, err := tx.Exec(func() error {
    tx.Set(...)
})
```
Probably better API should look like this:

```
cmds, err := c.Select(14).Watch("key1", "key2").MultiExec(func(tx *redis.Tx) error {
    tx.Set(...)
})
```

**Comment by KtorZ** [comment]
Hmm... So, if I get you right, we can't / shouldn't presume about the selected database during a transaction, because there's no way to know the state of the connection grabbed from the pool?

Fine. 

However, wouldn't it be nice to preserve consistency for within the same object ? I mean, the first client associated with a given connection `c` should still be connected to the previously selected database (in this case, `#14`). However, after a transaction, the state of `c` is reset to the default database `#0`. 

Since everything in the lib is made around pointers, clients are likely to be passed by reference, and doing so, a transaction will eventually mutate the original client for any other subsequent function calls (<- not cool).

**Comment by vmihailenco** [comment]
>because there's no way to know the state of the connection grabbed from the pool?

Yes, though you should not use `Select` manually so state is know and predictable :)

>However, after a transaction, the state of c is reset to the default database #0. 

That is because you did not close transaction and connection is not freed. Add `multi.Close()` to your code and you will get expected behaviour. But you can't rely on it when there are multiple goroutines sharing the same client.

>a transaction will eventually mutate the original client for any other subsequent function calls (<- not cool). 

Agreed, and I am going to fix this in v4 with API change:

```
db14 := c.Select(14)
db14.Get("foo")
// code above will execute
// SELECT 14
// GET foo
// and should work reliably
```

**Comment by KtorZ** [comment]
Thanks for the insights :) 
Enough to work correctly though I am looking forward to the V4!
