### ISSUE TITLE
Error upon compiling after go get

### ISSUE THREAD

**Issue by tuxxy** [go-redis/redis#317]
I get this error after doing a `go get gopkg.in/redis.v3`:

\# gopkg.in/redis.v3
../../../go/src/gopkg.in/redis.v3/error.go:70:17: error: reference to undefined identifier ‘strings.LastIndexByte’
  ind := strings.LastIndexByte(s, ' ')

**Comment by tuxxy** [comment]
Ah, disregard.

I fixed the issue by removing and reinstalling go.

**Comment by xh3b4sd** [comment]
I was having the same issue when building the project in `golang:1.4.2-cross` docker container. Using `golang:1.6` worked.

**Comment by vmihailenco** [comment]
The policy for go-redis lib is to support last 2 versions of Go, i.e. 1.5 and 1.6.

**Comment by balajcse** [comment]
I am new to go land . I am trying to cross compile it . how to compile it locally ?
