### ISSUE TITLE
How to add a read replica node with NewClusterClient

### ISSUE THREAD

**Issue by beast** [go-redis/redis#320]
Hi, all. There are probably obvious answer to this but I couldn't really find anything related in the doc. I have a AWS elasticache replication group setup. I can set a NewClusterClient Addrs to a list of nodes but  how do i specify which one is master and which ones are read replicas? Thanks!

**Comment by vmihailenco** [comment]
`ClusterClient` receives information about masters and slaves from Redis Cluster. So you need to configure Redis Cluster and then client will get all info from the Redis Cluster.

**Comment by beast** [comment]
I see. I am still quite new to REDIS so it sounds like the client actually intelligently gets the master/slave config from server and does it automatically. That is awesome. Thanks! @vmihailenco

**Comment by vmihailenco** [comment]
You are welcome
