### ISSUE TITLE
Does cluster HGetAllMap(key).Result() return error if the item doesn't exist?

### ISSUE THREAD

**Issue by ak2344** [go-redis/redis#321]
When I run `_ , err := client.Get("key").Result()` and check if `err== redis.Nil` I can see if the object doesn't exist. However, I when I run `_ , err := client.HGetAllMap("key").Result()` and check if `err== redis.Nil`, I do not seem to get the error even though the hash doesn't exist. Is it possible I'm missing something or is this the expected response?

**Comment by vmihailenco** [comment]
I think this is expected response and is consistent with Redis Server behaviour:

```
127.0.0.1:6379> hgetall foo
(empty list or set)
127.0.0.1:6379> get foo
(nil)
127.0.0.1:6379> 
```

**Comment by ak2344** [comment]
Ah I see. Thanks!
