### ISSUE TITLE
Error: no reachable servers

### ISSUE THREAD

**Issue by oknoorap** [go-redis/redis#322]
How to reconnect again? Any trick?

**Comment by vmihailenco** [comment]
AFAIK `ClusterClient` is supposed to recover/reconnect automatically. I guess it does not work in your case? Can you provide more details?

**Comment by oknoorap** [comment]
so, we must setup client cluster?
[http://redis.io/topics/cluster-tutorial](http://redis.io/topics/cluster-tutorial)

**Comment by vmihailenco** [comment]
Probably. I don't have much info from you - only that you receive `Error: no reachable servers`.
