### ISSUE TITLE
Client Pipelined index out of range

### ISSUE THREAD

**Issue by se77en** [go-redis/redis#335]
Use client pipelined show this error, go version is 1.5.3.

```
Stacktrace (most recent call first):

  File "runtime/panic.go", line 423, in gopanic
    reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
  File "runtime/panic.go", line 12, in panicindex
    panic(indexError)
  File "gopkg.in/redis.v3/parser.go", line 371, in readArrayReply
    switch line[0] {
  File "gopkg.in/redis.v3/command.go", line 605, in readReply
    v, err := readArrayReply(cn, stringStringMapParser)
  File "gopkg.in/redis.v3/pipeline.go", line 124, in execCmds
    err := cmd.readReply(cn)
  File "gopkg.in/redis.v3/pipeline.go", line 102, in Exec
    failedCmds, err = execCmds(cn, failedCmds)
  File "gopkg.in/redis.v3/pipeline.go", line 38, in Pipelined
    cmds, err := pipe.Exec()
  File "github.intra.douban.com/dae/dae-go/api/redis/redis.go", line 252, in Pipelined
    r, err = client.(*redis.Client).Pipelined(fn)
  File "elves/service/process.go", line 1141, in filterAds
    })
  File "elves/service/process.go", line 1013, in GetAdInfo
    p.ads = p.filterAds(cpmList)
```

**Comment by se77en** [comment]
we mount redis.v3 to our own directory but not change any code.

**Comment by vmihailenco** [comment]
I am going to fix the panic, but I need some code to reproduce and fix the underlying issue.

**Comment by se77en** [comment]
@vmihailenco the code is like this:

```
adIDList := []string{"1001", "1002", "1003"}

adInfoCmds := make([]*redisgo.StringStringMapCmd, 0, len(adIDList))

_, err := redis.Pipelined(func(pc *redis.Pipeline) error {
    for _, adID := range adIDList {
        adInfoCmds = append(adInfoCmds, pc.HGetAllMap(fmt.Sprintf("prefix-%s", adID)))
    }
    return nil
})

if err != nil {
    panic(err)
}
```

**Comment by vmihailenco** [comment]
That code does not trigger the panic. I need more details.

I just released v3.6.4 which will return `redis: reply is empty` instead of panicking. But still don't know why Redis reply is empty.

**Comment by se77en** [comment]
Is this issue https://github.com/golang/go/issues/6778 cause the error?

**Comment by vmihailenco** [comment]
Unlikely. Redis Server reply should always contain `\r\n`...

**Comment by MaerF0x0** [comment]
just to add some context that that may help.  I've had intermittent issues in our test package using redis.v4   the errors happen infrequently with redis3.2 and frequently with redis2.8 .  I wonder if there is some kind of incompatibility or difference?

**Comment by vmihailenco** [comment]
I am not aware of any. Do you a backtrace to share?

**Comment by MaerF0x0** [comment]
@vmihailenco  no, after a few more days of debugging I dont think it has anything to do with go-redis . We refactored to redigo and the issues still show up, albeit a little less often, but still my bad code not the library.

**Comment by vmihailenco** [comment]
Okay, thanks for update. Closing.

**Comment by MaerF0x0** [comment]
sorry for all the noise, this has nothing to do with go-redis specifically... 
I'm going to leave the eventual solution to my issue in case it helps others who land here. 

The issue with my test packages was the combination of:
 1.  My code would do a "FLUSH ALL" + fixture setup at the beginning of every tests
 2.  Code was divided into multiple packages that did the above

Those combined with the lesser known feature of go test: 
```
  The 'go test' command may run tests for different packages
	    in parallel as well, according to the setting of the -p flag
	    (see 'go help build').
```

So we had race conditions in testing whereby one package's test  would flush the db whilst another's test would try and access something. 

Solution options, any of: 

1. Have the tests clear/setup their fixtures w/ "DEL"  commands not "FLUSHALL" or "FLUSHDB"
2. Only have 1 package access the data layer and thus only 1 package that could be calling a FLUSHALL on the db
3. use the init() functionality to setup fixtures to cleanup/setup data once and deal with the possibility that tests could have side effects that cause other tests to pass/fail.
