### ISSUE TITLE
Making cmdable an interface

### ISSUE THREAD

**Issue by artushin** [go-redis/redis#341]
Would you be amenable to making cmdable an exported interface? I ask because I'm running a single instance redis docker container in dev and a full cluster in prod, but my code relies on using the global client established in my redis package that wraps go-redis. With the current setup, I can't do that because the ClusterClient and Client are separate types without a shared interface. Since you already use cmdable on both structs, it would be easy to make that an interface that would allow access only to the high level redis interface.

Let me know if that sounds good and I can do a PR.

**Comment by vmihailenco** [comment]
Released in v4.1.0

**Comment by artushin** [comment]
Thanks!
