### ISSUE TITLE
Is there readonly option in gopkg.in/redis.v3?

### ISSUE THREAD

**Issue by umiyosh** [go-redis/redis#346]
I use gopkg.in/redis.v3 and redis-cluster (v3.0.7).  I want to read from the slaves on our redis-cluster since mitigating latency problem. It seems like there is an option to read from the slave in gopkg.in/redis.v4.

[redis/options\.go at v4 · go\-redis/redis](https://github.com/go-redis/redis/blob/v4/options.go#L58)

But there isn't a same option in gopkg.in/redis.v3.

[redis/options\.go at v3 · go\-redis/redis](https://github.com/go-redis/redis/blob/v3/options.go)

How can I read from the slaves on redis-cluster with gopkg.in/redis.v3?
Or should I use gopkg.in/redis.v4?

**Comment by vmihailenco** [comment]
Yes, you should upgrade to redis.v4, because backporting that functionality to redis.v3 is too big task.

**Comment by umiyosh** [comment]
Thank you for the helpful information. 
I'd like to use gopkg.in/redis.v4 for reading the slaves.
