### ISSUE TITLE
How to use it? struct map

### ISSUE THREAD

**Issue by jackluo2012** [go-redis/redis#348]
My program：

```
type UserAppInfo struct {
	//ID         bson.ObjectId `bson:"_id,omitempty"`
	AppId      int64  `bson:"app_id"     json:"appid" redis:"id"`
	UserId     string `bson:"user_id"      json:"user_id" redis:"uid"`
	Udid       string `bson:"udid" json:"udid" redis:"udid"`
	Version    string `bson:"version" json:"version" redis:"v"`
	CreateDate string `bson:"create_date" json:"create_date" redis:"t"`
}
```

I saw all the examples，But I don't know how to map it

**Comment by vmihailenco** [comment]
There is no any specific support for structs. By default struct will be marshaled into bytes using `encoding.BinaryMarshaler` and then those bytes will be stored in Redis. I am not sure it is very useful.

What behavior do you expect?

**Comment by jackluo2012** [comment]
such as：
              github.com/garyburd/redigo/redis
                var uai UserAppInfo
		if err := redis.ScanStruct(v, &uai); err != nil {
			panic(err)
		}
Can give an example ？

**Comment by vmihailenco** [comment]
No, unfortunately this package does not support mapping to structs. The closest match you can get is `HGetAll` is `map[string]string` - https://github.com/go-redis/redis/blob/v4/commands_test.go#L1086-L1095

**Comment by FX-HAO** [comment]
Any solution?

**Comment by vmihailenco** [comment]
I am not sure what you asking for. Please open new issue after looking at existing Scan tests - https://github.com/go-redis/redis/blob/master/commands_test.go#L2863-L2884
