### ISSUE TITLE
Connection Pool timeouts on host failure with Redis Cluster.

### ISSUE THREAD

**Issue by Poogles** [go-redis/redis#360]
I look to have found a bug in this client when migrating hosts in Redis cluster, it seems as though it doesn't refresh the list of hosts and their hash slots when migrating slots from one host to another.

Steps to reproduce.

- Create Redis cluster with data and enough replicas to remove a host.
- Remove a Redis host from the cluster.
- Check to see Redis is still running and available with redis-trib.rb
- Go client still doesn't refresh connections and shows `redis: connection pool timeout` even though I get/set keys through the cli.

Steps to fix.

- Restart app.

**Comment by vmihailenco** [comment]
Does it fix itself with time? Depending on how you configured Redis Cluster it can take some time before node is removed/replaced.

>Remove a Redis host from the cluster.

How do you remove it? Just stop/kill? Or something more graceful?

**Comment by Poogles** [comment]
>Does it fix itself with time? Depending on how you configured Redis Cluster it can take some time before node is removed/replaced.

We've got cluster-node-timeout set to 15 seconds, so I'd expect the cluster to fail over in that time.  Looking at other clients during that time seems to backup that config.

>How do you remove it? Just stop/kill? Or something more graceful?

Standard sigterm, host stops gracefully.

**Comment by vmihailenco** [comment]
How can I reproduce this? I tried https://gist.github.com/vmihailenco/1c790383011ebc388dc469a640a76514 and it properly recovers from node failures.

**Comment by vmihailenco** [comment]
I can't fix this without a way to reproduce the problem. Closing for now.
