### ISSUE TITLE
Connection Pool don't close stale connection obviously

### ISSUE THREAD

**Issue by JackDrogon** [go-redis/redis#362]
Connection Pool don't close stale connection obviously. The stale connection is closed by golang gc. But when the server in big pressure, the connection isn't close immediately and the server has to many unuseful connection. So, should connection pool close connection immediately when the connection is stale?

**Comment by vmihailenco** [comment]
Thanks for the report. I think this fixed by https://github.com/go-redis/redis/pull/364. Please try to upgrade.
