### ISSUE TITLE
Looks like redis.Cmdable interface does not support Pipeline() method.

### ISSUE THREAD

**Issue by didip** [go-redis/redis#372]
Should it?

**Comment by vmihailenco** [comment]
I am not sure. It probably depends on context... so I would not touch without more details ;)

**Comment by didip** [comment]
OK, thanks for thinking about it :)

The nice thing about Cmdable interface is that a user can switch between client implementations:

* redis.Client

* redis.ClusterClient

* redis.Ring

This approach works for all commands but `Pipeline()` which is not a big deal since user can cast to the concrete type to call that method. It's just less convenient, that's all.

**Comment by vmihailenco** [comment]
Okay, I added `Pipeline` in v4.1.11. Hopefully it does not break anything :)
