### ISSUE TITLE
on redis.Ring, when calling Info("all"), do I get aggregated view?

### ISSUE THREAD

**Issue by didip** [go-redis/redis#374]
If not, which machines' Info() is it?

**Comment by vmihailenco** [comment]
All commands without keys such as INFO go to the one node selected by consistent hashing - https://github.com/go-redis/redis/blob/v4/ring.go#L191-L207. But they probably should go to randomly selected node. This behaviour is not well-thought :)

**Comment by didip** [comment]
Thanks! Once you explained it, it makes sense.

I ended up looping every single node and gather the `INFO`, no big deal.
