### ISSUE TITLE
Trouble getting high performance with pipelining

### ISSUE THREAD

**Issue by kellabyte** [go-redis/redis#386]
I'm having difficulty in understanding how to use the library effectively. I'm comparing results from `redis-benchmark` with pipelining and without pipelining with my `go-redis` implementation and the `go-redis` implementation is about `10x` slower with really bad latency and I can't seem to get it any better. Even with pipelining throughput is nowhere near what the server can handle.

I've seen the server handle over `3 million GET/second` but I can't seem to get over `300,000` with [this implementation](https://gist.github.com/kellabyte/2e6e5862600c8587b303dc49873ab529)

I'm trying to combine HTTP pipelining with Redis pipelining. Am I using the library wrong?

**Comment by vmihailenco** [comment]
You are using redigo, not go-redis :)
