### ISSUE TITLE
Ring Keys() command should aggregate results from each shard.

### ISSUE THREAD

**Issue by didip** [go-redis/redis#388]
The current behavior picks one server and runs Keys(), I think that's not correct.

**Comment by vmihailenco** [comment]
It is easy to do it for `Keys` but Redis has so many commands that I don't even want to start going this way. But you can use `ForEachShard`:

```
err := ring.ForEachShard(func(client *redis.Client) error {
    keys, err := client.Keys()
    fmt.Println(keys)
    return err
})
```
