### ISSUE TITLE
Discussion: remove custom import

### ISSUE THREAD

**Issue by dim** [go-redis/redis#395]
How do you feel about removing the custom `// import "gopkg.in/redis.v5"` and allowing people to import the package as `github.com/go-redis/redis`? Two reasons:

1. Most people use some sort of vendor tools these days and they support semver, e.g. https://github.com/Masterminds/glide. You are using tags already!
2. The gopkg.in servers are unfortunately not as stable and robust as I wish they were. We have experienced several failures on builds, CI runs, etc because of non-200 responses.

Thoughts?
dim

**Comment by vmihailenco** [comment]
No problem at all. Can you please send PR with some bold warning in the readme that you are on your own if you import `github.com/go-redis/redis`? Also we probably need to resurrect master branch?

**Comment by dim** [comment]
Closing in favour of #397
