### ISSUE TITLE
cluster.Pipeline doesn't follow the insertion order since redis.v4

### ISSUE THREAD

**Issue by tpiron** [go-redis/redis#399]
I've upgraded my app to use redis.v4 and faced an issue, it looks like when using cluster.Pipeline, the commands are not in the same order as they should be, when they're send to the redis cluster.

Code sample: https://gist.github.com/tpiron/44ad4ad5b3dcec8ca18193237dbe0c65

All the requests are sent to :7000

Using pipe.Set() and pipe.Get() functions seems to be fine (when I was trying earlier today the requests were mixed up, but now it seems to be always consistent.)

Using pipe.Process() is always wrong in my case, the code does '1 del 1 set' three times, but when I monitor on :7000 I don't have the same order:

`1476331574.902508 [0 127.0.0.1:40290] "DEL" "43"`
`1476331574.905712 [0 127.0.0.1:40292] "SET" "43" "34"`
`1476331574.906744 [0 127.0.0.1:40292] "SET" "43" "34"`
`1476331574.906861 [0 127.0.0.1:40292] "DEL" "43"`
`1476331574.906905 [0 127.0.0.1:40292] "SET" "43" "34"`
`1476331574.906943 [0 127.0.0.1:40292] "DEL" "43"`

or sometimes 

`1476332428.987475 [0 127.0.0.1:40382] "SET" "43" "34"`
`1476332428.987899 [0 127.0.0.1:40376] "DEL" "43"`
`1476332428.990138 [0 127.0.0.1:40382] "DEL" "43"`
`1476332428.990167 [0 127.0.0.1:40382] "SET" "43" "34"`
`1476332428.990190 [0 127.0.0.1:40382] "DEL" "43"`
`1476332428.990204 [0 127.0.0.1:40382] "SET" "43" "34"`

but the result should be

`1476332477.488820 [0 127.0.0.1:40418] "DEL" "43"`
`1476332477.488094 [0 127.0.0.1:40422] "SET" "43" "34"`
`1476332477.552378 [0 127.0.0.1:40422] "DEL" "43"`
`1476332477.552310 [0 127.0.0.1:40422] "SET" "43" "34"`
`1476332477.552433 [0 127.0.0.1:40422] "DEL" "43"`
`1476332477.552418 [0 127.0.0.1:40422] "SET" "43" "34"`

**Comment by vmihailenco** [comment]
Looks like those requests are made using different connections, e.g. `127.0.0.1:40290` and `127.0.0.1:40292`. Can it be that you issue those commands from multiple goroutines?

This also can be a side-effect of cluster reconfiguration and/or unreliable connection so go-redis partially retries commands...

I will try to make things more predictable for redis.v5, but so far I don't see anything obviously broken...

**Comment by tpiron** [comment]
I'm definitely not using multiple goroutines, and even with goroutines (using the same pipeline) I would assume that after calling pipe.Exec(), it would do the same has having multiple goroutines.

The difference in my code sample between calling pipe.Set/pipe.Del and pipe.Process was that using process I was sending the commands in uppercase (first character), as pipe.Set/Del are in lowercase

Now when I use process with lowercase command it works, all the requests from the pipeline are being executed in redis in the same order I inserted them in the pipeline.

Question1: Why using lowercase command keeps the same order in redis / using the same connection ? 

`1476370606.538150 [0 127.0.0.1:40958] "del" "43"`
`1476370606.538190 [0 127.0.0.1:40958] "set" "43" "74"`
`1476370606.538522 [0 127.0.0.1:40958] "del" "43"`
`1476370606.538619 [0 127.0.0.1:40958] "set" "43" "74"`

Question 2: am I wrong if I assume that the order the elements are inserted in the pipeline will be the same order redis process them ?

**Comment by vmihailenco** [comment]
>Question1: Why using lowercase command keeps the same order in redis / using the same connection ?

Because go-redis expects commands in lower case. I will fix this.

>am I wrong if I assume that the order the elements are inserted in the pipeline will be the same order redis process them ? 

No, order should be the same. But we have retry mechanism which in some nearly impossible circumstances (network error in the middle of pipeline) can retry only part of the commands.

**Comment by vmihailenco** [comment]
Fixed in v4.2.2. v5 also fixes some corner case in retrying. Closing.

**Comment by tpiron** [comment]
thanks !
