### ISSUE TITLE
how to connect to a new master when using NewFailoverClient?

### ISSUE THREAD

**Issue by JodeZer** [go-redis/redis#408]
Hi,
    We used the redis.NewFailoverClient  to get a client instance as the example said .And this instance is a connection to the master of a 3-node redis sentinel replication.
    When the master is O_DOWN,this client instance can't be used any more.Am l right?
    How to make an automatic switch when the master is changed? Do l have to call 'NewFailoverClient'  again?

**Comment by vmihailenco** [comment]
No, it is supposed to automatically switch to the new master when old master is down. Can you please provide minimal program that reproduces the issue?

**Comment by JodeZer** [comment]
There was a network problem and this client really works.
@vmihailenco Thanks a lot. 
And We decide to use this client to replace redigo.
