### ISSUE TITLE
PubSub keep listening

### ISSUE THREAD

**Issue by Rushmead** [go-redis/redis#410]
Hi all,

So i started using this library and got it all connected, however when i went to use the PubSub features i found that when i call the pubsub.RecieveMessages() function it only listens for a single message not for any further ones. Heres my code:
  http://pastebin.com/59saR2dk

Was wondering if you could help me out?

Thanks
Rushmead

**Comment by vmihailenco** [comment]
Hi,

I think you forgot for loop to receive messages:

```
    func pubSub() {
    	pubsub, err := client.Subscribe("serverFull", "gameState", "updatedYou")
    	if err != nil {
    		panic(err)
    	}
        for {
    			msg, err := pubsub.ReceiveMessage()
    			if err != nil {
    				panic(err)
    			}
    			switch msg.Channel {
    			case "serverFull":
    				serverFull(msg.Payload)
    				break
    			case "gameState":
    				gameState(msg.Payload)
    				break
    			case "updatedYou":
    				updateServer(msg.Payload)
    			}
           }
    }
```

**Comment by Rushmead** [comment]
@vmihailenco i've tried this but the application just exits straight away.

**Comment by Rushmead** [comment]
Oh wow. Just realised, i wasnt even calling the function. Sorry for wasting your time
