### ISSUE TITLE
pubsub+dlock: Getting lots of errors when trying to unlock using redis-lock

### ISSUE THREAD

**Issue by glerchundi** [go-redis/redis#411]
Hi @vmihailenco,

First of all thanks for this gift to the community and your effort for keeping it updated is admirable.

I'm trying to create persistent connections to our cloud using websocket and then use redis pub/sub for intra-cluster communications. An unique identifier for each websocket connection (which tries to acquire a distributed lock to keep just one connection per client) helps us creating a permanent/unique connection to the desired deployment. It's like opening a tunnel to a specific location and then let client redirect to that persistent connections using pub/sub. 

Just to let you known a brief pseudo code of how does actually the code/main loop look like:

```
func WebSocketHandler(id string, redisClient redis.Client, upgrader websocket.Upgrader) error {
	// distributed lock
	ttl := 1 * time.Minute
	dlock, err := acquireDistributedLock(redisClient, id)
	if err != nil {
		return err
	}

	ok, err := dlock.Lock()
	if err != nil {
		return err
	}
	defer func() {
		if err := dlock.Unlock(); err != nil {
			log.Errorf("failed to unlock dlock for '%s': %v", id, err)
		}
	}()

	if !ok {
		return Forbidden
	}

	// pubsub
	psclient := NewPubSubClient(redisClient)
	err = psclient.Run(id)
	if err != nil {
		return err
	}
	defer psclient.Close()

	// websocket
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		return err
	}

	// websocket client
	wsclient := NewWebSocketClient(conn)
	wsclient.Run()
	defer wsclient.Close()

	// lock renewal ticker
	ticker := time.NewTicker((ttl * 9) / 10)
	defer ticker.Stop()

	// main loop
	for {
		select {
		case <-ticker.C:
			if err := dlock.Renew(); err != nil {
				return err
			}
		case wsmsg, ok := <-wsclient.ReadMessage():
			if !ok {
				return nil
			}

			// to something with websocket message
		case psmsg, ok := <-psclient.ReadMessage():
			if !ok {
				return nil
			}

			// do something with redis pubsub message
		}
	}

	return nil

}
```

When trying to create a benchmarking tool to put some numbers on the table I got stuck with a recurring problem. If I open up just a few connections (around hundreds, for ex.: 100) everything works as expected but if I increase the number of connections (to thousands, for ex.: 1000) suddenly I start receiving these kind of messages when trying to freeing up the distributed lock (dlock.Unlock() code):

```
[ERROR]: failed to unlock dlock for 'KQBQzgIrCwwoDcvSXmLXMFBwPDZdsItv': dial tcp 127.0.0.1:6379: getsockopt: connection reset by peer
[ERROR]: failed to unlock dlock for 'QbVmaeAqnvFnOksRgKhBOUdcAfVJBFnB': read tcp 127.0.0.1:60401->127.0.0.1:6379: read: connection reset by peer
[ERROR]: failed to unlock dlock for 'FhdIKbBmmCuDAOoZmwMSXQNXRRrKPtKT': read tcp 127.0.0.1:59867->127.0.0.1:6379: i/o timeout
```

I created the client using these options, so the problem should not reside in the number of pooled connections, i'm right?

```
	client := redis.NewClient(&redis.Options{
		Addr:     "127.0.0.1:6379",
		Password: "haha!",
		DB:       0,
		PoolSize: 5000,
	})
```

And my laptop already has increased maxfiles (macOS Sierra using `launchctl limit maxfiles` & `ulimit`):

```
$> launchctl limit maxfiles
	maxfiles    32768          65536
```

My guess is that as defers are stacked and as Renew() works as expected renewing lock ttl's every 0.9*ttl duration, it must be something with psclient.Close() but the weird thing is that this Close() just Unsubscribe()'s the subscription and nothing else (like closing redis client).

Distributed lock is based on `github.com/bsm/redis-lock` but updated to use the latest client (v5). The interfaced client just use these methods in case is something relevant:

```
// RedisClient is a minimal client interface, supported by gopkg.in/redis.v3
type RedisClient interface {
	SetNX(key string, value interface{}, expiration time.Duration) *redis.BoolCmd
	Eval(script string, keys []string, args ...interface{}) *redis.Cmd
}
```

Any ideas what's happening? I would really apreciate any advice in this regard.

Thanks in advance.

PD.: psclient methods:

```
// NewPubSubClient creates a new pubsub client
func NewPubSubClient(redisClient redis.Client) *PubSubClient {
	return &PubSubClient{
		conn:    conn,
		closing: false,
		recv:    make(chan *pubsub.Message, 256),
		send:    make(chan *sendMessage, 256),
		logger:  logger,
	}
}

// Run executes reader/writer routines without blocking
func (c *PubSubClient) Run(installationID string) error {
	// subscribe to redis channel
	sub, err := c.conn.Subscribe(installationID)
	if err != nil {
		return err
	}

	c.sub = sub
	go func() {
		go c.writePump()
		c.readPump()
	}()

	return nil
}

// Close closes underlying subscription
func (c *PubSubClient) Close() error {
	c.closing = true
	if c.sub != nil {
		return c.sub.Unsubscribe()
	}
	return nil
}
```

**Comment by vmihailenco** [comment]
Looks like your network stack can't maintain enough connections for you. `PoolSize = 5000` means that go-redis will not open more than 5000 connections. If go-redis does not have enough free connections or there is connection leak you will get `pool: timeout` errors not `connection reset`. So I think this is not a go-redis problem :)

On Ubuntu/Linux you usually also need to tweak following params if you want to open a lot of connections:

```
    - {name: net.core.somaxconn, value: 65534}
    - {name: net.core.netdev_max_backlog, value: 65534}
    - {name: net.ipv4.ip_local_port_range, value: "1024 65534"}
    - {name: net.ipv4.tcp_max_syn_backlog, value: 65534}
```

But I can't speak about MacOS...

**Comment by glerchundi** [comment]
> If go-redis does not have enough free connections or there is connection leak you will get pool: timeout errors not connection reset. So I think this is not a go-redis problem :)

So it must be a connection leak or something like that because I can connect to the `listener` by 3333 connections which means 2 x 3333 (two connections per client 1 websocket and another one from the redis pool).

**Comment by vmihailenco** [comment]
I did not have time to run the code, but I recommend you to refactor it so you have only one `PubSubClient` and use that client to subscribe to as many channels as you want. Then you need 1 goroutine that will read all messages and
- deliver them by channel name to appropriate goroutine/webscoket
- broadcast them to every goroutine/websocket and discard messages you don't need

It should be much faster this way.

**Comment by glerchundi** [comment]
Thanks for your approach. Will do as soon as I get to the maximum limit of connections and then start refactoring/optimizing the design.

I'm doing different kinds of implementations right now, trying to test every kernel/proc/user limit. Since last time I get blocked/limited by different ones like:

- `maxfiles` (per process, per system `ulimit -u/-n`, 
- `somaxconn` (max queued conns `net.core.somaxconn`)
- `maxfiles` in redis (`--maxfiles` in `redis-server`
-  your client pool size
- max ephemeral ports (`net.ipv4.ip_local_port_range`)

So as you guessed in your first answer this is not a go-redis problem so closing it now.

Thanks for your support!
