### ISSUE TITLE
compiling takes 2 seconds

### ISSUE THREAD

**Issue by des09** [go-redis/redis#414]
Starting with a completely clean GOPATH, I followed the README, and set up a a glide.yaml pointing to:
- package: github.com/go-redis/redis
  version: ^5.0.0

Copying the pong example takes almost two seconds to build.

Host is ubuntu 16.04 host with a 3GHz dual core AMD proc and 8G ram.
go version go1.7.3 linux/amd64

**Comment by vmihailenco** [comment]
TLDR - not sure what to do here

There is [big 50kb file](https://github.com/go-redis/redis/blob/v5/commands.go) with Redis commands. And that struct is embedded into `Client`, `ClusterClient`, `Ring` and `Pipeline`. I guess that is why compilation is not very fast. But Go should compile package only once and remove all dead/unreachable code. So it should not matter in practise...
