### ISSUE TITLE
Import self internal package with full URL does not allow use of `glide`

### ISSUE THREAD

**Issue by kkpoon** [go-redis/redis#419]
in `README`

> ## Vendoring
> If you are using a vendoring tool with support for semantic versioning e.g. glide, you can import this package via its GitHub URL:
> - package: github.com/go-redis/redis
>   version: ^5.0.0

But in source code, for example: https://github.com/go-redis/redis/blob/v5/cluster.go#L9-L11

`go` does not allow `github.com/go-redis/redis` to use `gopkg.in/go-redis/redis.v5/internal` package

**Comment by vmihailenco** [comment]
Yeah, we either should remove that sentence from the README or stop using gopkg.in. @dim ?

**Comment by dim** [comment]
My preference is not to use gopkg but that would probably break too many
people's code. Let's just remove the note from the README ...

**Comment by vmihailenco** [comment]
I still find gopkg.in useful and unobtrusive, but also a bit abandoned lately... And issues like https://github.com/niemeyer/gopkg/issues/47 don't look good...

Ideally there should be ability to make `gopkg.in` use tag `gopkg-5.1.2` and glide tag `glide-5.1.2`. Then we could have best of the both worlds...

**Comment by vmihailenco** [comment]
I've created master branch without gopkg.in and will tag v6.0.0 soon.
