### ISSUE TITLE
(*redisClient).Scan() method giving different results in different environments

### ISSUE THREAD

**Issue by liteonly** [go-redis/redis#421]
Hey,
I was trying to get all keys which match "cb_*", and was using the (*redisClient).Scan() function(redis.v4)
It is working properly on my local machine(MAC OSX 10.10.5)
But the same code, when run on a linux machine with same redis server installed(3.0.7) is giving empty result

the code used for testing was
```
package main

import (
    "fmt"
    redis "gopkg.in/redis.v4"
)

func main() {
    redisClient := redis.NewClient(&redis.Options{
        Addr:     "localhost:6379",
        Password: "",               // no password set
        DB:       0, // use default DB
    })
    redisErr := redisClient.Ping().Err()
    if redisErr != nil {
        fmt.Println(redisErr)
    }

    var cursor uint64
    keys, cursor, err := redisClient.Scan(cursor, "cb_*",1000).Result()
    if err != nil {
        fmt.Println(err)
    }
    fmt.Println(keys)
}
```
can you verify if there is anything wrong with this code and if so, can you please point it out.
else, can you please suggest the alternate approach to this problem.

**Comment by liteonly** [comment]
@vmihailenco @dim Can you guys take a look whenever you have a little time ?

**Comment by dim** [comment]
@liteonly to consume all keys, you must continue calling `SCAN` until the cursor value reaches 0, but you may encounter empty results along the way. This has nothing to do with the client but is by design and documented in http://redis.io/commands/scan. But, you can use the built-in `Iterator()` [function](https://godoc.org/gopkg.in/redis.v4#Scanner.Iterator) which makes scan commands much more accessible.

**Comment by liteonly** [comment]
@dim Thanks for the quick response. I ended up using the keys() method instead, which served the purpose.
```keys, err := redisClient.Keys("cb_*").Result()```
Thanks again!

**Comment by dim** [comment]
No worries, but please make sure you read the big warning in the docs http://redis.io/commands/KEYS
