### ISSUE TITLE
[Question] Is it possible to query "latency"?

### ISSUE THREAD

**Issue by leandromoreira** [go-redis/redis#422]
I'm able to set up a threshold to latency measurements. 
```go
client.ConfigSet("latency-monitor-threshold", threshold)
```
But I don't see how can I run the command `latency latest`,  do you have any thoughts about how to measure redis-latency using this client?

**Comment by vivace-io** [comment]
Could something like [`Cmd`](https://godoc.org/gopkg.in/redis.v5#Cmd) (or any variant there of like StringCmd) possibly be what you're looking for? 

I believe you would create a new command configured with Redis' [`LATENCY` Command](http://redis.io/topics/latency-monitor) and any subcommands/arguments, then pass it in `client.Process()` to run it against the server. After that, you'd need to parse the result...

I did try to fiddle with it using different command types, but had no luck personally. I was either getting no results after executing, or parsing errors for the response. Although I have no doubt I was going about it the wrong way and I was in a bit of a rush...

Do keep in mind I could be very wrong in my suggested approach, as my use of this package is somewhat limited in scope. So you'll probably want to do some of your own research before giving it a shot.

Hope that helps!

**Comment by leandromoreira** [comment]
Thank you very much, @vivace-io I tried but using the `Result` API results in parser error, I'll keep researching it.

```go
	redisClient := createRedis(config)

	Latency := func() *redis.StringCmd {
		cmd := redis.NewStringCmd("latency", "latest")
		redisClient.Process(cmd)
		return cmd
	}

	v, err := Latency().Result()
	fmt.Printf("%q %s", v, err)

// but then it showed the error
// "" redis: can't parse string reply: "*1"2016/11/18 16:56:40 connected to redis
```

**Comment by vivace-io** [comment]
I think I found a solution for you.

I tried using SliceCmd for `latency history` and got a response. In this case, cmd.Val() returned `[[command 1479498842 1000 1001]]` as an example. If this falls exactly in line with the offical Redis docs...

`command` is the event name (duh)
`1479498842` is the unix time stamp
`1000` is the latestst event's latency in ms
`1001` is the all-time maximum latency

The returned value is of type `[]interface{}` and holds at least one child `[]interface{}`. So with that in mind, you just have to type check the values down to where you want to to grab.

Is this a solution for you?

**Comment by vivace-io** [comment]
As an example, heres a quick and dirty function that I've tested and appears to work:

```func latency(client *redis.Client) (latest, max int64, err error) {
	cmd := redis.NewSliceCmd("latency", "latest")
	if err = client.Process(cmd); err != nil {
		return
	}
	response := cmd.Val()[0].([]interface{})
	latest = response[2].(int64)
	max = response[3].(int64)
	return
}```

Obviously, you'll want a greater degree of safety in error handling and type checking for things like empty/unexpected responses, but that should give you the general idea hopefully!

**Comment by leandromoreira** [comment]
Thank you very much sir! =)

**Comment by leandromoreira** [comment]
@vivace-io I'm trying to do a lib/system that periodically gathers vital info (like connected_clients, rejected_connections, cache_hit from`info` plus latency) from redis and post it to logstash and gaphite.

**Comment by leandromoreira** [comment]
@vivace-io thank you very much 😄  I did the monitoring system https://github.com/globocom/redis-healthy
