### ISSUE TITLE
SetXX Expiration Broken

### ISSUE THREAD

**Issue by jonmchan** [go-redis/redis#425]
SetXX with expiration does not work properly at the moment. When I use Set, the TTL is properly set. However when I use SetXX, the TTL does not get set. Am I doing something wrong or is this a legitimate bug?

```go
import (
	"testing"
	"github.com/stretchr/testify/assert"
	"gopkg.in/redis.v5"
)

func TestSetXXExpiration(t *testing.T) {
	client := redis.NewClient()

	client.Set("test1",0,time.Duration(5*1000000000))
	client.SetXX("test2",0,time.Duration(5*1000000000))

	assert.Equal(t,time.Duration(5)*time.Second,client.TTL("test1").Val())
	assert.Equal(t,time.Duration(5)*time.Second,client.TTL("test2").Val())
}
```

results:
```
	Error Trace:	redis_test.go:14
	Error:		Not equal: 5000000000 (expected)
			        != -2000000000 (actual)
```

**Comment by jonmchan** [comment]
Update: It doesn't even set anything at all:

```go
	client.SetXX("test2","whatever",0)

	assert.Equal(t,"whatever",client.Get("test2").Val())
```

```
	Error:		Not equal: "whatever" (expected)
			        != "" (actual)
```

**Comment by vmihailenco** [comment]
I think this was fixed in https://github.com/go-redis/redis/pull/409

**Comment by jonmchan** [comment]
@vmihailenco I am on the latest version with #409 merged in. SetXX is totally broken at this point. It will not write anything to redis at all.

**Comment by jonmchan** [comment]
I'm sorry. User error. I'm looking for SetNX, not SetXX. Everything works as expected. Thanks.
