### ISSUE TITLE
Export PoolStats with expvar

### ISSUE THREAD

**Issue by tevjef** [go-redis/redis#429]
Requesting a feature to export a client's PoolStats via the [expvar package](https://golang.org/pkg/expvar/)

Here's quick example. 
```go
var stats *PoolStats

func (c *Client) ExpVar(name string)  {
	expvar.Publish(name, expvar.Func(poolstats))
	go func() {
		for { 
			select {
			case <-time.Tick(time.Second * 5):
				stats = c.PoolStats()
			}
		}
	}()
}

func poolstats() interface{} {
	return stats
}

```

This example has no cancellation or removal. The most insidious part is that it seems like `expvar` requires a global.

**Comment by vmihailenco** [comment]
Can you please provide an example of other library outside of stdlib that uses expvar? I personally don't use it so I don't know what are the best practises or even if anyone else does this...

**Comment by tevjef** [comment]
I don't know of any libraries that provide stats about their runtime much less exporting them through expvar. However, I've use one application that utilizes this package, [Influxdb](https://github.com/influxdata/influxdb/blob/933702549da48803df33969a9b7b56476add0cdc/services/httpd/handler.go#L728
). They use it as an interface to provide stats about their internal database engine. This however, is an application not a library. Do you think exposing PoolStats should left up to the library user?

**Comment by tevjef** [comment]
Here's an bit about using expvar in libraries https://youtu.be/5v2fqm_8jYI?t=24m51s

**Comment by vmihailenco** [comment]
I think it is better to leave expvar interaction outside the library for now.
