### ISSUE TITLE
AUTH command does not use Read/Write timeouts

### ISSUE THREAD

**Issue by trilliot** [go-redis/redis#430]
I think I found a small issue.
If I specify a custom ReadTimeout and/or WriteTimeout value, AUTH commands don't use these values.

### Versions
- `go version go1.7.3 darwin/amd64`
- `Redis server v=3.2.5 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=6f9920d2ae584aa0` (a Docker container using redis:latest)
- Redis-go: `^5.1.0`

### What am I expecting ?

Something like that:
```
2016/11/29 12:26:35 redis.Get: read tcp [::1]:63020->[::1]:32779: i/o timeout
```

### How to reproduce ?

- Run redis in a Docker container:
`docker run -ti -d -p 6379:6379 --name 'my-redis-server' redis redis-server --requirepass 'secret'`
- Save this simple Go snippet:
```go
package main

import (
	"flag"
	"log"
	"time"

	redis "gopkg.in/redis.v5"
)

var (
	redisAddr   = flag.String("redis", "localhost:6379", "redis database address")
	redisPasswd = flag.String("redis-password", "", "redis database password")
)

func main() {
	flag.Parse()

	redis := redis.NewClient(
		&redis.Options{
			Addr:         *redisAddr,
			Password:     *redisPasswd,
			ReadTimeout:  250 * time.Millisecond,
			WriteTimeout: 250 * time.Millisecond,
		})

	if err := redis.Info().Err(); err != nil {
		log.Printf("redis.Get: %v", err)
	}
}
```
- Run the snippet once (it should exit correctly): `go run snippet.go -redis='localhost:6379' -redis-password='secret'`
- Pause the Redis container: `docker pause my-redis-server`
- Run the snippet another time: `go run snippet.go -redis='localhost:6379' -redis-password='secret'`
- The snippet stalls and doesn't exit, regardless of the Read/Write timeouts

**Comment by vmihailenco** [comment]
Thanks for the report. I think I just fixed this in v5.1.2.
