### ISSUE TITLE
Ring thread leak when executing large volume of hash commands.

### ISSUE THREAD

**Issue by didip** [go-redis/redis#432]
### Basic Info

1. go-redis version: v4

2. Go version: 1.7.3

3. Server environment: CentOS 7 64bit

### Pseudocode
```
// Client setup
// redisAddrs is large number of Redis in Map.
redisClient := redis.NewRing(&redis.RingOptions{
    Addrs:        redisAddrs,
    WriteTimeout: 3 * time.Minute,
    PoolTimeout:  3 * time.Minute,
    IdleTimeout:  10 * time.Minute,
    ReadTimeout:  2 * time.Minute,
})

// DoWork is run as multiple goroutines (e.g. 200).
// payloads slice is passed in from a channel.
// At high throughput (e.g. 200k TPS), number of runtime goroutines increase rapidly, infinitely (i've seen it go up to 150k goroutines).
func DoWork(redisClient *redis.Ring, payloads []Payload) {
	for _, payload := range payloads {
		redisKey := payload.Key

		// Update sum atomically
		newSum, sumErr := redisClient.HIncrByFloat(redisKey, "sum", payload.Value).Result()

		// Update count atomically
		newCount, countErr := redisClient.HIncrBy(redisKey, "count", 1).Result()

		// Update mean
		if sumErr == nil && newSum >= 0 && countErr == nil && newCount > 0 {
			redisClient.HSet(redisKey, "mean", fmt.Sprintf("%v", newSum/float64(newCount)))
		}
	}
}
```

### Notes

1. The large pool of Redis are not busy at all, this looks like the case of opening too many connections and not closing them.

2. `ss -s` shows ludicrous number of TCP connections, supporting point no. 1. See:

    ```
    ss -s
    Total: 45423 (kernel 45617)
    TCP:   45155 (estab 1954, closed 774, orphaned 19, synrecv 0, timewait 55/0), ports 2205

    Transport Total     IP        IPv6
    *     45617     -         -
    RAW   0         0         0
    UDP   58        44        14
    TCP   44381     1866      42515
    INET      44439     1910      42529
    ``` 

3. I got the number of goroutines from `runtime` package.

What can I do differently here?

**Comment by vmihailenco** [comment]
Can you try to update to v5? Is there any way I can run a program reproducing this?

**Comment by didip** [comment]
ok, I will try to upgrade to v5.

It's difficult to provide the exact code because of confidentiality, but I've reduced the problem to pseudocode above. I can, however, provide you a complete `main.go` to run.

Another problem in testing this is that I don't see this problem when testing locally. If I get further in debugging this, I can probably give you a `Vagrantfile` for testing this with multiple Redis.

**Comment by didip** [comment]
A side question if you don't mind,

Can I run `Script` as part of `Pipeline`? If my problem is too many calls are made to Redis, then maybe I can batch a bunch of stored procedure calls.

**Comment by didip** [comment]
After upgrading to v5 and moving the logic to Pipeline+Eval, I no longer have this problem.

**Comment by didip** [comment]
I spoke too soon, the thread leak is now a lot slower, but still happening.

**Comment by vmihailenco** [comment]
:( I need reproducer, because from you example it is not clear that you were using Script or Pipeline (not that it explains anything). Overall I am using Redis Ring in several projects and it works fine for me. Probably there are some corner cases like timeouts that cause this...

**Comment by didip** [comment]
kk, I am writing a small `main.go` that hopefully can describe the problem better.

**Comment by didip** [comment]
OK, my thread leak problem does not come from the client library.

The goroutine pool was duplicating `*ring.Ring` instances and that causes the explosion of new connections.

Sorry for wasting your time.
