### ISSUE TITLE
Use Redis replica without cluster mode

### ISSUE THREAD

**Issue by pranas** [go-redis/redis#433]
We have Redis master + replica configuration without using cluster mode. We would like to route reads to both based on latency. I see go-redis has this feature but it seems it's only available with cluster mode. Any plans to support it on non cluster client?

**Comment by vmihailenco** [comment]
No, I am not aware of any way to achieve this. And since this is essentially a Redis Cluster with 2 nodes (master+slave) I don't see much value in supporting this in standard client...

**Comment by jpza** [comment]
It's quite common for people to have Redis read-replicas without Redis being in cluster-mode, at least for now since it guarantees strong consistency and is operationally simpler. 

Another issue, [https://github.com/go-redis/redis/issues/673], is also asking for this feature. 

If you don't need master sharding and you just want to scale out reads than this non-cluster mode setup of read-replicas without cluster-mode is more performant. Since the demand for this feature is present and it has been implemented by https://github.com/luin/ioredis I am bumping this.

This difficulty I see here is how to iterate over read-replicas.

**Comment by pranas** [comment]
It would be great if you allow to choose different routing strategies. For our use case we want routing by latency (which you already have in cluster client) while others might want round robin routing.

**Comment by ramonberrutti** [comment]
@Kuqd I have the same problem. I solve now having two connections. redisClient and redisClientRead

**Comment by pranas** [comment]
We also have a similar workaround. Since we have multiple read replicas we initialise multiple go-redis clients, put them in a slice and then randomly pick one for read operations.

**Comment by Kuqd** [comment]
@pranas @ramonberrutti This is good workaround. Thanks.

Though for my use case it requires a bit of refactor since I'm reading and writing a lot. I'll think about it about thanks.

**Comment by vmihailenco** [comment]
See https://godoc.org/github.com/go-redis/redis#example-NewClusterClient--ManualSetup. It uses 2 master nodes, but using single master should work too.

**Comment by FarhanSajid1** [comment]
> We also have a similar workaround. Since we have multiple read replicas we initialise multiple go-redis clients, put them in a slice and then randomly pick one for read operations.

Has go-redis added support, or is this the solution at the moment?

**Comment by michal-mazurkiewicz** [comment]
Up! 

Is there any out of the box solution to use redis with read-replica without cluster mode?

**Comment by Av1shay** [comment]
Any updates on this?
It is really common to use redis with read replica without cluster mode

**Comment by I70l0teN4ik** [comment]
Another bump here. 
Cheapest AWS ElastiCache Redis with 2 read replica in diff zones is more then enough for my app needs to fulfill the redundancy and keep all the data needed.
Cluster mode is definitely an overkill for that scenario. Don't get why that's not supported still :(

**Comment by gaston-haro** [comment]
Is it not this how we are expected to attend this scenario?

```golang
clusterSlots := func(ctx context.Context) ([]redis.ClusterSlot, error) {
		slots := []redis.ClusterSlot{
			// "virtual" cluster node with 1 master and 1 slave.
			{
				Start: 0,
				End:   16383,
				Nodes: []redis.ClusterNode{{
					Addr: ":7000", // master
				}, {
					Addr: ":8000", // 1st slave|read replica
				}},
			},
		}
		return slots, nil
	}

	rdb := redis.NewClusterClient(&redis.ClusterOptions{
		ClusterSlots:  clusterSlots,
		RouteRandomly: true,
	})
	rdb.Ping(ctx)
```

(similar example but with cluster mode enabled from de docs https://github.com/redis/go-redis/blob/2512123b7686dca1f7f0208eaada6cdf3ef0189c/example_test.go#L81-L120)

**Comment by I70l0teN4ik** [comment]
@gaston-haro, thanks that works. 
But retries are some how unpredictable. I have a single master and readonly `addr` defined. So theoretically with `ReadOnly: true` it should try to write only 2 times max. But that's not the case. I some times see like 5 tries or even more to write anything before it selects master endpoint.
So `replication` mode is still not supported normally.

**Comment by gaston-haro** [comment]
> @gaston-haro, thanks that works. But retries are some how unpredictable. I have a single master and readonly `addr` defined. So theoretically with `ReadOnly: true` it should try to write only 2 times max. But that's not the case. I some times see like 5 tries or even more to write anything before it selects master endpoint. So `replication` mode is still not supported normally.

Hi @I70l0teN4ik `ReadOnly` has no effect when creating a Cluster and specifying `ClusterSlots` see:

https://github.com/redis/go-redis/blob/1da50b33ef44c54143b194edcba664d7503b8fc9/osscluster.go#L302-L307

So, if your nodes are not an OSS Redis Cluster just set cluster nodes as in the example and don't set either `ReadOnly` or `RouteRandomly` and I believe it should work as expected.

**Comment by I70l0teN4ik** [comment]
Hi @gaston-haro, thatnks for the response.
I think my problem was that I didn't specify `End:   16383` that's why it acted wired and tried to reconnect all the time.

I guess after all with current code Universal Client could easily support the `replication` mode by just using this `ClusterSlot` with single instance workaround if some specific bool like `Replication: true` would be set along with list of `Addr` obviously with comment that master must be first :wink:

**Comment by maddsua** [comment]
> Is it not this how we are expected to attend this scenario?

I call it good enough 👍 

Having a simple wrapper to get that up from a url or something would be nice tho
