### ISSUE TITLE
EvalSha returning "NOSCRIPT No matching script. Please use EVAL"

### ISSUE THREAD

**Issue by debraj-manna** [go-redis/redis#446]
I am loading a script to redis cluster via `ScriptLoad` as shown below:-

```go
sha1 = client.ScriptLoad("local KEYS = {'JJNbc906fbdc15a11e69fce3c15c2d271f21481650613G'} local ARGV = {30000, 'SSF_lastAccessedDate', 1481627386, 'SSF_expiryDate', 1481657386} if redis.call('EXISTS', KEYS[1]) == 1 then local keyvalues = redis.call('HGETALL', KEYS[1]) local a = {} for i=2, table.getn(ARGV) do a[i-1] = ARGV[i] end local res = redis.call('HMSET', KEYS[1], unpack(a)) redis.call('EXPIRE', KEYS[1], ARGV[1]) return keyvalues else return 2 end").Val()
```

But when I am trying to do `EvalSha` using `sha1` returned from `ScriptLoad` as shown below:-

```go
client.EvalSha(sha1, []string{"0"}, nil).Result()
```

It is throwing the error:-

```
NOSCRIPT No matching script. Please use EVAL.
```

But if I do `evalsha` from `redis-cli` using  `sha1` returned above. It is working fine and returning the value:-

```
127.0.0.1:30001> evalsha f30391cf83780cea3bc9f70c15f3819dea57e0b4 0 
```

The issue can be reproduced using this [gist](https://gist.github.com/debraj-manna/9a73d696ebaad90bb60c29c6611bb48e).

Environment:-

- Go - 1.7.3
- go-redis - v5.3
- Redis - 3.2.5

**Comment by vmihailenco** [comment]
Are you using Redis Cluster?

**Comment by debraj-manna** [comment]
yes

**Comment by vmihailenco** [comment]
@debraj-manna I think you should use https://godoc.org/gopkg.in/redis.v5#example-Script. `ScriptLoad` command does not accept any keys and therefore is routed to the random Cluster Server. Which means that script will be loaded only into 1 random server.

**Comment by debraj-manna** [comment]
When should we use `ScriptLoad` and when `NewScript`.

In my case If I modify my script as follows then `ScriptLoad` is also working. 

```lua
if redis.call("EXISTS", KEYS[1]) == 1 then
    local keyvalues = redis.call("HGETALL", KEYS[1])
    local a = {}
    for i=2, table.getn(ARGV) do
      a[i-1] = ARGV[i]
    end
    local res = redis.call("HMSET", KEYS[1], unpack(a))
    redis.call("EXPIRE", KEYS[1], ARGV[1])  
    return keyvalues
else
    return 2 -- "Key doesn't exists"
end
```
and pass on explicit keys & argv like below:-

```go
keys := []string{"JJNb19ff5e9c1e011e6971b0242ac11009c1481708147G"}
	argv := make([]interface{}, 5)
	argv[0] = 30000
	argv[1] = "SSF_lastAccessedDate"
	argv[2] = 1481627386
	argv[3] = "SSF_expiryDate"
	argv[4] = 1481657386
	res, err := client.EvalSha(sha1, keys, argv...).Result()
```

The complete code can be found in this [gist](https://gist.github.com/debraj-manna/acb1c5420ec001d8e7ab62b49a98ea98). 

`EvalSha` is failing only when the script does not take any keys:-

```
127.0.0.1:30001> evalsha f30391cf83780cea3bc9f70c15f3819dea57e0b4 0 
```
