### ISSUE TITLE
Why HSET(key stirng,failed string,value string) doesn't support "value" as interface{}

### ISSUE THREAD

**Issue by szyhf** [go-redis/redis#453]
Why HSET(key stirng,failed string,value string) doesn't support "value" as interface{} ?

I don't know why HSET doesn't support value as interface{}, I tried make a test function as : 

```
func (c *cmdable) HSet_Interface(key, field, value interface{}) *BoolCmd {
	cmd := NewBoolCmd("hset", key, field, value)
	c.process(cmd)
	return cmd
}

redis.RedisHandler.HSet_Interface("Hello", "World", some_struct)
redis.RedisHandler.HGet("Hello","World")
```

It works well, is it any other reason ?

Thanks .

**Comment by vmihailenco** [comment]
AFAIK it is an overlook. Do you want to sent a PR changing the signature to

```
HSet(key, field string, value interface{})
```

?

**Comment by szyhf** [comment]
Sure, I've already made one, let me try ~

**Comment by szyhf** [comment]
@vmihailenco Should I pull to another branch ?

**Comment by vmihailenco** [comment]
Do you mean v4? No, we don't backport changes to older versions.

**Comment by szyhf** [comment]
Oh, nope, some project has rules that new pull request should not push to the master branch, I was wandering if my PR is push to the right branch yesterday ~ lol

**Comment by vmihailenco** [comment]
There is no master branch - only v5, v4, v3... So all is good - thanks!
