### ISSUE TITLE
what's the different between redis.v4 and redis.v5 in golang package

### ISSUE THREAD

**Issue by Gujarats** [go-redis/redis#458]
Currently I'm doing some project to build cache data using Redis using Go language. I'm using Redis version 4 from gopkg.in/redis.v4. We have the plan to upgrade it to redis version 5.

But I've the following issue before attempt to update version :

- What is the good thing about redis 5 compare to redis 4 

- I tried to find the changelog but I could not, any changelog for this update?

- any changes to make after updating the redis 4 to redis 5 ? like function ?

Hopefully someone could help me regarding this issue. Any help would be appreciate.

link question from [here](http://stackoverflow.com/questions/41254719/whats-the-different-between-redis-v4-and-redis-v5-in-golang-package)

**Comment by vmihailenco** [comment]
Sorry, only list of commits https://github.com/go-redis/redis/compare/v4...v5?expand=1. I think it should be safe to upgrade by fixing compilation errors, but you can never be sure about such things.

The only new feature I remember is TxPipeline, which is a Pipeline that wraps queued commands with `MULTI` + `EXEC`.

**Comment by Gujarats** [comment]
Okay thank you for you answer. I think I will choose to stay in version 4 for a while. Thanks again your library gives such a big help.
