### ISSUE TITLE
Unit testing for set, bitset

### ISSUE THREAD

**Issue by Gujarats** [go-redis/redis#464]
is there any library for unit testing for `set`,`setbit` ? or mocking the database connection?
I was having problem to write a unit test since there are no guidance in the readme.

So I was trying to find a way to it and found it there are another library for unit test for redis but not for this. you can find the link [here](https://godoc.org/github.com/rafaeljusto/redigomock)

**Comment by vmihailenco** [comment]
I am not aware of anything. I am just using real redis-server whenever I have to test code that uses Redis.

**Comment by YahiaSweid** [comment]
In production, sometimes you need to run your tests without spinning a Redis instance. I think it's very useful to have mocks.
