### ISSUE TITLE
client.Eval is not working in v5

### ISSUE THREAD

**Issue by tingliu8** [go-redis/redis#468]
vals, err := client.Eval("return {KEYS[1],ARGV[1]}", []string{"key"}, []string{"hello"}).Result() works fine in V3 but not in v5.

**Comment by vmihailenco** [comment]
It should be `vals, err := client.Eval("return {KEYS[1],ARGV[1]}", []string{"key"}, "hello").Result()`. Function signature was changed...

**Comment by tingliu8** [comment]
what's the statement to pass multiple args? shouldn't the type of args be [] interface{} instead of interface{}?

**Comment by vmihailenco** [comment]
It is `...interface{}`, not `interface{}`. Just pass multiple args - `vals, err := client.Eval("return {KEYS[1],ARGV[1]}", []string{"key"}, "hello", "world").Result()`
