### ISSUE TITLE
ClusterClient does not have WrapProcess method

### ISSUE THREAD

**Issue by rayzyar** [go-redis/redis#477]
As title, could WrapProcess be added to cluster ClusterClient

**Comment by vmihailenco** [comment]
Not sure, but for now you can just use following

```
cluster.ForEachMaster(func(master *redis.Client) error {
    master.WrapProcess()
})
```

or `cluster.ForEachNode` if you want to instrument slaves too.

**Comment by vmihailenco** [comment]
Let's keep this open - it still makes sense to have `cluster.WrapProcess` that will automatically wrap clients when cluster is reconfigured

**Comment by gbbr** [comment]
I also need this. It would help with adding tracing around cluster commands. Wrapping each node’s client doesn’t do the trick. I have very little experience with this library but it seems easy to potentially add this change into a PR - am I wrong?

When wrapping the process, it would also be interesting to know which node has successfully processed the command. Any ideas or suggestions are welcome. 

The same would be great for Ring.

**Comment by vmihailenco** [comment]
Latest version already has [WrapProcess](https://godoc.org/github.com/go-redis/redis#ClusterClient.WrapProcess).

>When wrapping the process, it would also be interesting to know which node has successfully processed the command.

This is not supported, but probably `cluster.ForEachNode` and `node.WrapProcess` can be helpful.

**Comment by gbbr** [comment]
Awesome!!! Thanks @vmihailenco. This can be closed then, I guess :-)
