### ISSUE TITLE
Send array of strings to script.Run

### ISSUE THREAD

**Issue by pxaviad** [go-redis/redis#484]
Is there a way to use `script.Run(c, keys, args)` to have an array as part of the args ?

something like: 

```
    r := redis.NewClient(&redis.Options{
        Addr: "localhost:6379",
    })
    f, e := os.Open("test.lua")
    if e!= nil {
        fmt.Printf("%v", e)
    }
    s, e:= ioutil.ReadAll(f)
    if e!= nil {
        fmt.Printf("%v", e)
    }

    script := redis.NewScript(string(s))
    cmd := script.Run(r , []string{"test1", "test2"}, 1, 2, []string{ "test3" })
```

And if not, Is there a way to work around this if I must?

**Comment by vmihailenco** [comment]
What is the motivation? Should it work the same as `cmd := script.Run(r , []string{"test1", "test2"}, 1, 2, "test3")`?

**Comment by vmihailenco** [comment]
Closing, please reopen if you are still interested.
