### ISSUE TITLE
pubsub: ReceiveMessage fails after 5 seconds if not subscribed to any channel

### ISSUE THREAD

**Issue by glerchundi** [go-redis/redis#485]
After trying to guess what was happening with my application, I added a new test to check if my assumptions were correct:

```
	It("should ReceiveMessage not fail even without subscriptions", func() {
		timeout := 100 * time.Millisecond

		pubsub, err := client.Subscribe()
		Expect(err).NotTo(HaveOccurred())
		defer pubsub.Close()

		done := make(chan bool, 1)
		go func(pubsub *redis.PubSub) {
			defer GinkgoRecover()
			defer func() {
				done <- true
			}()

			time.Sleep(timeout + 100*time.Millisecond)
			err = pubsub.Subscribe("mychannel")
			Expect(err).NotTo(HaveOccurred())

			n, err := client.Publish("mychannel", "hello").Result()
			Expect(err).NotTo(HaveOccurred())
			Expect(n).To(Equal(int64(1)))
		}(pubsub)

		msg, err := pubsub.ReceiveMessageTimeout(timeout)
		Expect(err).NotTo(HaveOccurred())
		Expect(msg.Channel).To(Equal("mychannel"))
		Expect(msg.Payload).To(Equal("hello"))

		Eventually(done).Should(Receive())
	})
``` 

And as I expected, it failed with the following error:

```
------------------------------
• Failure [0.108 seconds]
PubSub
/Users/Gorka/.go/src/gopkg.in/redis.v5/pubsub_test.go:396
  should ReceiveMessage not fail even without subscriptions [It]
  /Users/Gorka/.go/src/gopkg.in/redis.v5/pubsub_test.go:287

  Expected error:
      <*errors.errorString | 0xc420339fb0>: {
          s: "redis: can't parse array reply: \"+PONG\"",
      }
      redis: can't parse array reply: "+PONG"
  not to have occurred

  /Users/Gorka/.go/src/gopkg.in/redis.v5/pubsub_test.go:282
```

The solution or workaround is very easy, just subscribe to an empty channel (`Subscribe("")`) and it works smoothly.

Just in case you want to fix this up, I can send a PR if you want but probably you will do much better and faster than me.

*Version:*
```
- package: gopkg.in/redis.v5
  version: ^5.2.2
```

**Comment by vmihailenco** [comment]
I have a fix for original problem in https://github.com/go-redis/redis/pull/486. It is a new issue, because until recently `Subscribe` required at least 1 channel.

>ERR unknown command 'SCRIBE'

Can it be that you are using `Receive` concurrently? PubSub is not thread safe.

**Comment by glerchundi** [comment]
Thanks for your prompt answer (and fix!)

> Can it be that you are using Receive concurrently? PubSub is not thread safe.

Nope, i'm just using `ReceiveMessage` (as far as I read it is the recommended one) in one place and multiplexing the subscriptions through channel comm:

```
func (rps *RedPubSub) readPump() {
	for {
		rmsg, err := rps.pubsub.ReceiveMessage()
		if err != nil {
			println("kaboooom: " + err.Error())
			continue
		}

		rps.mu.Lock()
		sub, ok := rps.subs[rmsg.Channel]
		rps.mu.Unlock()

		if !ok {
			// loggear que se ha recibido un mensaje de un canal que ya no existe en la subscripción
			// ¡que raro!
			println("no subscription for channel")
		} else {
			select {
			case sub.recv <- rmsg:
			default:
				println("no one is listening!!")
				// loggear que el buffer de recepción está full!
			}

		}
	}
}
```

Will try to do in a reproducible manner but seems to be unrelated to the former issue.

**Comment by vmihailenco** [comment]
Please try v5.2.4 and let me know if you spot any other bugs.

**Comment by glerchundi** [comment]
Fixed, your response time was incredibly fast, glad to see people like you maintaining an awesome library.

Thanks!
