### ISSUE TITLE
Exists should support multiple keys

### ISSUE THREAD

**Issue by eyalpost** [go-redis/redis#489]
The problem is that now Exists returns Bool and when used with multiple parameters it should return int
I'm willing to do PR - let me know how you want it handled?
- Add support for multiple keys but still return bool which indicates if all keys exists
OR
- Add a new ExistsMulti func which returns int

**Comment by vmihailenco** [comment]
Let's add `ExistsMulti` and add todo to replace `Exists` with `ExistsMulti` in v6.

**Comment by eyalpost** [comment]
Done #490
