### ISSUE TITLE
CI Build takes too long?

### ISSUE THREAD

**Issue by eyalpost** [go-redis/redis#494]
The travis logs show that the build under go 1.4 takes 10 minutes and then fails because it gets stuck. Is this something configurable? Can you remove 1.4 from the build altogether?

**Comment by vmihailenco** [comment]
I'd prefer to fix the build rather than to remove it. But anyway Go 1.4 failures are allowed and they don't block anything.

**Comment by eyalpost** [comment]
No problem. So basically if I install go 1.4 on my machine I'm supposed to
reproduce? If yes, will be happy to look at it

Eyal

On 14 Feb 2017, at 10:00, Vladimir Mihailenco <notifications@github.com>
wrote:

I'd prefer to fix the build rather than to remove it. But anyway Go 1.4
failures are allowed and they don't block anything.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/go-redis/redis/issues/494#issuecomment-279633674>, or mute
the thread

**Comment by eyalpost** [comment]
#496
