### ISSUE TITLE
Ping returns "dial tcp: missing address" whereas redis-cli works fine

### ISSUE THREAD

**Issue by Southclaws** [go-redis/redis#495]
I'm writing a Go app that connects a C program to an API via Redis. The C app connects to Redis fine (via Hiredis) and `redis-cli` works fine but the Go app returns `dial tcp: missing address`. Related code: https://github.com/Southclaws/ScavengeSurvive/blob/redis/goss/server.go#L74-L82

It worked fine [yesterday](https://github.com/Southclaws/ScavengeSurvive/commit/b13cd698d29436318606e6038ac14fb0d4a0542a#diff-dbce618591af853252e692b1b55318ceR42), as far as I can tell [the changes I've made](https://github.com/Southclaws/ScavengeSurvive/commits/redis/goss/server.go) shouldn't affect Redis at all, it's still connecting with "localhost:6379" just it's loaded from a .json rather than a flag.

Thoughts? I'm stumped...

**Comment by vmihailenco** [comment]
I can only guess that `api.RedisHost` contains empty or invalid address.

**Comment by Southclaws** [comment]
Yeah I realised on the way to work I forgot to make `api` mutable in `loadConfig`, apologies for the wasted issue!
