### ISSUE TITLE
Go get throws error

### ISSUE THREAD

**Issue by mastertinner** [go-redis/redis#497]
When running `go get gopkg.in/redis.v5`, I get the following error:

```shell
$ go get gopkg.in/redis.v5
# cd .; git clone https://gopkg.in/redis.v5 /Users/taafuto1/go/src/gopkg.in/redis.v5
Cloning into '/Users/taafuto1/go/src/gopkg.in/redis.v5'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/redis.v5: exit status 128
```

I'm using `go1.7.5 darwin/amd64`.

**Comment by eyalpost** [comment]
This helped me when I had this issue:
https://github.com/niemeyer/gopkg/issues/50#issuecomment-273299592

**Comment by mastertinner** [comment]
Thanks for the quick reply, @eyalpost!

**Comment by niemeyer** [comment]
No need to change the configuration anymore. We've changed gopkg.in itself to support the new git quirks.
