### ISSUE TITLE
Leaking goroutines with reaper?

### ISSUE THREAD

**Issue by krk** [go-redis/redis#508]
I am not entirely sure if this is a go-redis bug.

In a heap dump taken with *runtime/debug.WriteHeapDump*, there are thousands (40000+) of *goroutine*s with the following stack trace:

```golang
runtime.gopark 
runtime.goparkunlock 
runtime.chanrecv 
runtime.chanrecv2 
gopkg.in/redis.v5/internal/pool.(*ConnPool).reaper 
runtime.goexit 
```

Is this number of goroutines to be expected in an application that handles around 40000 requests per week?

**Comment by vmihailenco** [comment]
There is exactly 1 reaper per client so it looks like you have 40k clients in the app, which indicates a problem. Usually your app should create 1 client on start and close it on shutdown.

Connection reaper is closed with associated client with some delay (<= IdleCheckFrequency). Did you change IdleCheckFrequency?

PS I assume you are not using Redis Cluster.

**Comment by krk** [comment]
Thank you for the pointers, a new client was being created for every request. Now converted to 1 client per application lifetime.
