### ISSUE TITLE
Stale IPs seen when Redis cluster restart

### ISSUE THREAD

**Issue by safiqueahemad** [go-redis/redis#513]
Hi Guys,

There is deployed Redis cluster with 6 instances.The client interact with redis cluster initially very good. But the problem starts when Redis cluster is restarted.
After restart, all the Redis instance get new IP address.
The client append all new 6 IPs after old IPs.
Actually, the old IPs aren't there anymore. It should be cleared/updated by client.
But it doesn't happen.
When client uses these old IP then request fails.

Kindly, suggest how to update/remove IPs in cluster client.

**Comment by vmihailenco** [comment]
Does it cause any problems? AFAIK it uses those addresses only when "main" servers are down...

@dim what do you think about this? AFAIR you insisted we keep all IP addresses...

**Comment by safiqueahemad** [comment]
There is suspect that it uses old IP addresses after restart.
Some error traces spotted with error (like i/o timeout etc) on old IP addresses.
When the error was seen new IP addresses were alive and reachable.

Please suggest.

**Comment by vmihailenco** [comment]
No ideas - please reopen if you have more details.
