### ISSUE TITLE
Define an interface for redis.Client

### ISSUE THREAD

**Issue by pmenglund** [go-redis/redis#515]
Would consider defining an interface for `redis.Client` so it is possible to drop in a mock during testing?

```go
type Client struct {
  baseClient
  cmdable
}
```

Compare to [InfluxDB](https://godoc.org/github.com/influxdata/influxdb/client/v2#Client) where `client.Client` easily can be replaced with just a couple of lines of code:

```go
type dummyClient struct {
}

func (dc *dummyClient) Ping(timeout time.Duration) (time.Duration, string, error) {
	return nil, "", nil
}

func (dc *dummyClient) Write(bp client.BatchPoints) error {
	return nil
}

func (dc *dummyClient) Query(q client.Query) (*client.Response, error) {
	return nil, nil
}

func (dc *dummyClient) Close() error {
	return nil
}
```

**Comment by vmihailenco** [comment]
We already have https://godoc.org/gopkg.in/redis.v5#Cmdable and [UniversalClient](https://github.com/go-redis/redis/blob/master/universal.go#L116-L120)

**Comment by pmenglund** [comment]
The `Cmdable` interface is **huge** - there are almost 200 calls to mock. Any chance that it can be broken up into a couple of smaller interfaces?

**Comment by dim** [comment]
Simple, just embed the interface and moc/implement the methods you are using:

```
type myMockType struct {
  redis.Cmdable
}

func (c *myMockType) Ping() *redis.StatusCommand {
  ...
}
```

**Comment by pmenglund** [comment]
Ah, didn't think of that! I'll try that, and submit a diff to document how to do it...

**Comment by yashvardhan-kukreja** [comment]
Note: `redis.UniversalClient` can be helpful if you're also willing to also abstract over client-mgmt methods like `Close() error`
