### ISSUE TITLE
Help Needed in Creating Pools of redis connections

### ISSUE THREAD

**Issue by dinilv** [go-redis/redis#517]
Hi,

I am trying to create a pool of redis connections for my frequent use on application in which concurrency is high. 
Could anyone tell whats wrong with my code below? 
Is any better way of creating redis connections not on demand but already created ?

Code:
_"
import (
        pool "gopkg.in/redis.v5/internal/pool"
	"gopkg.in/redis.v5"
)

var RedisClient *redis.Client
var RedisPool *pool.ConnPool

func init() {
	RedisPool = pool.NewConnPool("localhost:6379", 1000, 5, 30, 60)

}"_

Error Message:

_"package main
	imports github.com/adcamie/adserver/listners/v1/tracker
	imports github.com/adcamie/adserver/db/dao
	imports github.com/adcamie/adserver/db/config
	imports gopkg.in/redis.v5/internal/pool: use of internal package not allowed"_

**Comment by vmihailenco** [comment]
go-redis automtically manages connections so you don't need to create pool yourself. Take a look at following example - https://godoc.org/gopkg.in/redis.v5#example-Client.
