### ISSUE TITLE
ClusterClient's "Keys" method only return keys in the first node

### ISSUE THREAD

**Issue by SnowCrumble** [go-redis/redis#518]
client := redis.NewClusterClient(&redis.ClusterOptions{
		Addrs:    strings.Split(ips, ","),
		Password: password,
	})
	if _, err := client.Ping().Result(); err != nil {
		fmt.Println(err)
		panic(err)
	}
	keys, _ := client.Keys("*").Result()
	fmt.Println(keys)

I have six node in my redis cluster, and ten keys in them, but only two keys in first node

**Comment by vmihailenco** [comment]
This is how Redis Cluster works. You probably want:

```
client.ForEachMaster(func(m *redis.Client) error {
    fmt.Println(m.Keys("*").Val())
    return nil
})
```

**Comment by SnowCrumble** [comment]
Thx！
