### ISSUE TITLE
Question: Is there a way to read Options from a v5 Client?

### ISSUE THREAD

**Issue by brunocassol** [go-redis/redis#529]
Hey

First off this is an awesome library 👍

Is there a way to get the Options that was used to create a new redis.Client?

My use case is that I'm implementing a task queue and in the Queue.Start() method I would like to return an error when the user sets Queue.NumWorkers larger than the Options.PoolSize of the redis client that was passed to create the Queue.

I hope I made sense 😃

**Comment by vmihailenco** [comment]
Just added `client.Options()`. You can also check https://github.com/go-msgqueue/msgqueue for SQS based task queue - I plan to release it this week.
