### ISSUE TITLE
AWS Elastichache - problem with setup on cluster mode

### ISSUE THREAD

**Issue by zmagajna** [go-redis/redis#531]
Hi all, I have a problem of setting up client on the cluster mode. When i create the non-cluster mode, i use primary endpoint, and my service can automatically detects primary and replication. Now when i create the redis in cluster mode, i don't get the primary endpoint, i only get the configuration endpoint. When i try to use that, few requests work ok, but on some i'm getting an error: 
**MOVED NUMBER IP:PORT**. 

I check the documentation on the godoc, on the connection client to cluster mode, and it says to do the slice of the addresses in cluster, so my question do i need to input all the endpoints inside the the cluster, or should i use some other value?

**Comment by vmihailenco** [comment]
You need to provide at least one (more is better) `ip:port` of the Redis Cluster server. I can't say more since I did not work with AWS Elastic Cache.
