### ISSUE TITLE
Cluster mode performance seems no stable

### ISSUE THREAD

**Issue by Lwxiang** [go-redis/redis#532]
I have set up a redis cluster in my remote VPS. There are 3 masters and each master has a slave. They all in one VPS and use different TCP ports.

Then I use ClusterClient to make some operations on the remote cluster. I find that each time I run the Set() method on one KEY, it spent different time. Then I make a test-program to compare with Client and ClusterClient. Here is the benchmark:

![image](https://cloud.githubusercontent.com/assets/7104402/24287276/083d1c8c-10b4-11e7-91e5-4fd76b043659.png)

You can see that single Client's performance is stable while the ClusterClient's performance is unstable. It seems that each time the operation make different memeries. I try to dig into the code and find that the differents between Client and ClusterClient are that:
1. ClusterClient contains many Clients which are connecting to different master
2. ClusterClient caculate the slot of a key and use the Client which hold the slot to Process

Is there anything I have misunderstood? Is there anything I can do to find out WHY the Cluster mode performance so unstable?
thank you

**Comment by vmihailenco** [comment]
Can you show the benchmark? Mine does not confirm what you see

```
BenchmarkRedisClusterPing-4        	  200000	      5811 ns/op	     196 B/op	       8 allocs/op
BenchmarkRedisClusterSetString-4   	   50000	     78575 ns/op	     275 B/op	      10 allocs/op
```

**Comment by Lwxiang** [comment]
hi thx for your reply.
I have figured out what happened.
It is connect time out.

I found that "Cluster Slots" will get the slots-server relations.But if I send "Cluster Slots" to Server-A, It returns:
```
1) 1) (integer) 0         
   2) (integer) 5460
   3) 1) "10.135.xx.xx"  //Inner IP
      2) (integer) 7000  // Server-A's port
      3) "xxxxx..."
   4) 1) "139.199.xx.xx" //Global IP
      2) (integer) 7003
      3) "xxxxx..."
2) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "139.199.xx.xx" //Global IP
      2) (integer) 7002
      3) "xxxxx..."
   4) 1) "139.199.xx.xx" //Global IP
      2) (integer) 7005
      3) "xxxxx..."
...
```
It looks like that if I ask Server-A, the info of Server-A is the INNER IP
if I ask Server-B, then Server-B's info is the INNER IP.
SO THAT
when I call NewClusterClient, it random a server to ask. then the clusterState will have ONE INNER IP.
just like:
newClusterClient -> reloadSlots() -> Random and get A -> ClusterSlots() -> serverA returns the info including 5 Global IP and 1 Inner IP which is itself.

when I call a SET, it calculate the KEY and have to connect to A, then it will connect to the Inner IP which it saved just now, then timeout, then reconnect a random one, and then find the Server A.

### So the time out is the reason why the performance unstable.

I dont know if I configured the redis-cluster in a wrong way or other reasons.
I first set up 6 redis-server in port 7000~7005, bind 0.0.0.0
then I use redis-trib.rb create --replicas 1 139.199.xx.xx:7000 139.199.xx.xx:7001 .... to set up a cluster.
is that including its Inner IP normal ? or the package's defect?

best regards.

**Comment by Lwxiang** [comment]
here is the progress
![image](https://cloud.githubusercontent.com/assets/7104402/24296022/4a908b54-10d8-11e7-9732-96776bf0baa7.png)

**Comment by Lwxiang** [comment]
I was to told that redis and its client are usually at the same LAN, so that would be no problem.
I don't know if the case is valuable, but if the redis server and client are at separate network that would be some problem in using ClusterClient

**Comment by vmihailenco** [comment]
I believe this is Redis Cluster configuration issue, but I don't know much about configuring Redis Cluster.

Overall it looks like go-redis works as expected, but is not very smart. E.g. we could remember Redis `redirect` response and use provided working IP address instead of bad one. I can't say for sure this is a good idea in all cases, but it could help you.

**Comment by Lwxiang** [comment]
@vmihailenco thx a lot:)
