### ISSUE TITLE
undefined: atomic.Value

### ISSUE THREAD

**Issue by matveynator** [go-redis/redis#535]
ERROR:

# github.com/go-redis/redis/internal/pool
../go/src/github.com/go-redis/redis/internal/pool/conn.go:20: undefined: atomic.Value

**Comment by vmihailenco** [comment]
I guess you are using old Go version.

**Comment by matveynator** [comment]
Package: golang
Version: 2:1.3.3-1
Installed-Size: 89
Maintainer: Go Compiler Team <pkg-golang-devel@lists.alioth.debian.org>

**Comment by vmihailenco** [comment]
1.3.3 is very old. Please upgrade to latest version or at least Go 1.4.
