### ISSUE TITLE
cluster script cache?

### ISSUE THREAD

**Issue by oldshuren** [go-redis/redis#536]
When doing ScriptLoad(), it seems the ClusterClient does not load the script to every node. Then when I doing EvalSha, I always get NOSCRIPT No matching script. Please use EVAL

**Comment by eyalpost** [comment]
This may help:
https://github.com/go-redis/redis/issues/518

**Comment by oldshuren** [comment]
Thanks,

Yes, I did use ForEachMaster() to load script to every node. It worked.

**Comment by oldshuren** [comment]
By the way, ioredis' defineCommand() is nice, it will automatically load the script if the cache is not there. 

Is it possible to add this feature to go-redis?

**Comment by oldshuren** [comment]
I think redis.Script is the equivalent of ioredis defineCommand. Actually very easy to use!

**Comment by vmihailenco** [comment]
You need to use `script.Run`, not `script.EvalSha`. This way script will be automatically created.

**Comment by antonydeepak** [comment]
How does `script.Run` work in a pipeline?
