### ISSUE TITLE
unexpected fault

### ISSUE THREAD

**Issue by winxxp** [go-redis/redis#539]
version 5.2.9

```text
unexpected fault address 0xc424757500
fatal error: fault
unexpected fault address 0xc424757500
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0xc424757500 pc=0xc424757500]

goroutine 11524497 [running]:
runtime.throw(0xa7dfc5, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc423c3af30 sp=0xc423c3af10
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc423c3af80 sp=0xc423c3af30
vendor/gopkg.in/redis%2ev5.(*ClusterClient).ForEachMaster.func1(0xc42473ad10, 0xc424a36e40, 0xc423e91f20, 0xc4206f6600)
	/home/hl/cache/src/vendor/gopkg.in/redis.v5/cluster.go:558 +0x5d fp=0xc423c3afc0 sp=0xc423c3af80
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc423c3afc8 sp=0xc423c3afc0
created by vendor/gopkg.in/redis%2ev5.(*ClusterClient).ForEachMaster
	/home/hl/cache/src/vendor/gopkg.in/redis.v5/cluster.go:565 +0x2d7
```

**Comment by vmihailenco** [comment]
Closing since there is no enough info to do anything. Please reopen if this happens again with better backtrace.

**Comment by fenggolang** [comment]
when I use go-redis v9 ForEachSlave get redis-cluster all keys,happen panic
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x40702e]

goroutine 917 [running]:
runtime.throw({0x13a1a43?, 0x415f8b?})
	/usr/local/go/src/runtime/panic.go:1077 +0x5c fp=0xc01a6219a0 sp=0xc01a621970 pc=0x43b83c
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:875 +0x285 fp=0xc01a621a00 sp=0xc01a6219a0 pc=0x452665
indexbytebody()
	/usr/local/go/src/internal/bytealg/indexbyte_amd64.s:126 +0xce fp=0xc01a621a08 sp=0xc01a621a00 pc=0x40702e
strings.IndexByte(...)
	/usr/local/go/src/strings/strings.go:118
github.com/redis/go-redis/v9/internal/hashtag.Key({0x646441222c303a22, 0x446c616e6f697469})
	/Users/wangpengcheng/go/pkg/mod/github.com/redis/go-redis/v9@v9.1.0/internal/hashtag/hashtag.go:51 +0x2f fp=0xc01a621a48 sp=0xc01a621a08 pc=0x8611cf
github.com/redis/go-redis/v9/internal/hashtag.Slot({0x646441222c303a22?, 0x1201ea0?})
	/Users/wangpengcheng/go/pkg/mod/github.com/redis/go-redis/v9@v9.1.0/internal/hashtag/hashtag.go:69 +0x1d fp=0xc01a621a68 sp=0xc01a621a48 pc=0x8612fd
github.com/redis/go-redis/v9.cmdSlot({0x1595d38?, 0xc00c3ae540?}, 0xc000658a00?)
	/Users/wangpengcheng/go/pkg/mod/github.com/redis/go-redis/v9@v9.1.0/cluster.go:1789 +0x47 fp=0xc01a621a88 sp=0xc01a621a68 pc=0x873b27
github.com/redis/go-redis/v9.(*ClusterClient).cmdSlot(0x15829a0?, {0x158cb90, 0x1ee2540}, {0x1595d38?, 0xc00c3ae540})
	/Users/wangpengcheng/go/pkg/mod/github.com/redis/go-redis/v9@v9.1.0/cluster.go:1781 +0x145 fp=0xc01a621ae0 sp=0xc01a621a88 pc=0x873a65
github.com/redis/go-redis/v9.(*ClusterClient).process(0xc000262200, {0x158cb90?, 0x1ee2540}, {0x1595d38, 0xc00c3ae540})
	/Users/wangpengcheng/go/pkg/mod/github.com/redis/go-redis/v9@v9.1.0/cluster.go:905 +0xa8 fp=0xc01a621bb8 sp=0xc01a621ae0 pc=0x86f428
github.com/redis/go-redis/v9.(*ClusterClient).process-fm({0x158cb90?, 0x1ee2540?}, {0x1595d38?, 0xc00c3ae540?})
	<autogenerated>:1 +0x45 fp=0xc01a621bf0 sp=0xc01a621bb8 pc=0x98a8c5
github.com/redis/go-redis/v9.(*hooksMixin).processHook(...)
	/Users/wangpengcheng/go/pkg/mod/github.com/redis/go-redis/v9@v9.1.0/redis.go:172
github.com/redis/go-redis/v9.(*ClusterClient).Process(0xc01a621c60?, {0x158cb90?, 0x1ee2540?}, {0x1595d38?, 0xc00c3ae540})
	/Users/wangpengcheng/go/pkg/mod/github.com/redis/go-redis/v9@v9.1.0/cluster.go:898 +0x3d fp=0xc01a621c38 sp=0xc01a621bf0 pc=0x86f2fd
github.com/redis/go-redis/v9.(*ClusterClient).Process-fm({0x158cb90?, 0x1ee2540?}, {0x1595d38?, 0xc00c3ae540?})
	<autogenerated>:1 +0x45 fp=0xc01a621c70 sp=0xc01a621c38 pc=0x98a825
github.com/redis/go-redis/v9.cmdable.Get(0xc000314160, {0x158cb90?, 0x1ee2540}, {0x646441222c303a22, 0x446c616e6f697469})
	/Users/wangpengcheng/go/pkg/mod/github.com/redis/go-redis/v9@v9.1.0/commands.go:982 +0x11e fp=0xc01a621cb8 sp=0xc01a621c70 pc=0x88d37e
m8loc-rtcm/metric.RealtimeStationDOPMetric({0x158cb90, 0x1ee2540})
	/Users/wangpengcheng/Documents/源码/gitee/fenggolang/m8loc-rtcm/metric/realtime_station_dop_metric.go:80 +0x175 fp=0xc01a621fc0 sp=0xc01a621cb8 pc=0xf44cb5
m8loc-rtcm/crontab.StartStationCrontab.func4()
	/Users/wangpengcheng/Documents/源码/gitee/fenggolang/m8loc-rtcm/crontab/realtime_station_crontab.go:44 +0x30 fp=0xc01a621fe0 sp=0xc01a621fc0 pc=0xfbfdf0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc01a621fe8 sp=0xc01a621fe0 pc=0x4716a1
created by m8loc-rtcm/crontab.StartStationCrontab in goroutine 392
	/Users/wangpengcheng/Documents/源码/gitee/fenggolang/m8loc-rtcm/crontab/realtime_station_crontab.go:41 +0x3e
