### ISSUE TITLE
How to add some new commands for redisearch.io ?

### ISSUE THREAD

**Issue by zxl777** [go-redis/redis#542]
I want to do a full text search , So choosed the redisearch.io

redisearch.io is a module.so for REDIS 3.8 beta.

And the redisearch make some commands - FT.SEARCH in redis-cli

I like go-redis/redis ,so I want to add some command for redisearch.

Can you tell me how to do that is the easy way?

**Comment by zxl777** [comment]
I have made some easy command for redisearch.
Now have a question:

How to paste this reply ?  I just found some StringReply

'''
127.0.0.1:6379[1]> FT.SEARCH myIdx hello LIMIT 0 10
1) (integer) 2
2) "doc1"
3) 1) "title"
   2) "hello world"
   3) "body"
   4) "lorem ipsum"
   5) "url"
   6) "http://redis.io"
4) "doc2"
5) 1) "title"
   2) "\xe4\xbd\xa0\xe5\xa5\xbd\xe4\xb8\x96\xe7\x95\x8c"
   3) "body"
   4) "lorem ipsum"
   5) "url"
   6) "http://redis.io"
'''

**Comment by vmihailenco** [comment]
There is an example how to write custom commands - https://godoc.org/github.com/go-redis/redis#ex-package--CustomCommand. I did not try but it looks like you need `SliceCmd`

```
search := func(client *redis.Client) *redis.SliceCmd {
    cmd := redis.NewSliceCmd("ft.search", "myIdx", "hello", "limit", 0, 10)
    client.Process(cmd)
    return cmd
}
```
