### ISSUE TITLE
use of internal package not allowed

### ISSUE THREAD

**Issue by gooops** [go-redis/redis#546]
..\gopkg.in\redis.v6\cluster.go:10:2: use of internal package not allowed
..\gopkg.in\redis.v6\ring.go:13:2: use of internal package not allowed
..\gopkg.in\redis.v6\cluster.go:11:2: use of internal package not allowed
..\gopkg.in\redis.v6\cluster.go:12:2: use of internal package not allowed
..\gopkg.in\redis.v6\cluster.go:13:2: use of internal package not allowed

**Comment by vmihailenco** [comment]
gopkg.in is not supported any more - please import `github.com/go-redis/redis`
