### ISSUE TITLE
Redis Pipeline Interface

### ISSUE THREAD

**Issue by rodrigo-brito** [go-redis/redis#555]
Hello,

I'm having problems with Redis Pipeline for tests. Actually, the Pipeline method from RedisClient is:
```go
type Cmdable interface {
	Pipeline() *Pipeline
```
If exists a Pipeline Interface for this return will help a lot.
To override it in a external Mock will be more easy.
This is possible?

**Comment by felipejfc** [comment]
also suffering with that :/

**Comment by felipejfc** [comment]
we can close that now! @rodrigo-brito see https://github.com/go-redis/redis/pull/557

**Comment by rodrigo-brito** [comment]
Boa! @felipejfc.
