### ISSUE TITLE
ZRevRangeWithScores arguments are String

### ISSUE THREAD

**Issue by lorieri** [go-redis/redis#56]
Not really a problem, but different from ZRangeWithScores

func (c *Client) ZRangeWithScores(key string, start, stop int64) *ZSliceCmd

func (c *Client) ZRevRangeWithScores(key, start, stop string) *ZSliceCmd

**Comment by vmihailenco** [comment]
Looks like correct signature is:

```
func (c *Client) ZRevRangeWithScores(key string, start, stop int64) *ZSliceCmd
```

I will fix it soon.
