### ISSUE TITLE
Backoff Retry During Network Errors

### ISSUE THREAD

**Issue by jonmchan** [go-redis/redis#562]
Would it be possible to have Go-Redis retry connections when maxretries is set with a backoff sleep interval? (https://github.com/jpillora/backoff) 

During intervals when my network is overloaded, it is not using backoff and making the overloaded network connection even worst by retrying immediately and producing other errors.

I'd be happy to submit a PR if this is a feature the community/maintainer wants to see in this library.

**Comment by vmihailenco** [comment]
I am fine with such change, but let's keep it [simple](https://github.com/go-pg/pg/blob/master/internal/internal.go#L8-L18) (no external dependencies) and backoffs should be in range 100-500 ms. I think big backoffs are unacceptable for users relying on Redis to answer within 1ms.
