### ISSUE TITLE
Is it possible to add "key prefix" support?

### ISSUE THREAD

**Issue by yangxikun** [go-redis/redis#563]
such as...
```go
client := redis.NewClient(&redis.Options{
        Addr: "127.0.0.1:6379",
        Prefix: "APP_A_",
    })
```

**Comment by vmihailenco** [comment]
It is possible, but I am not sure it is worth it because Redis supports [database selection](https://redis.io/commands/select)

**Comment by yangxikun** [comment]
Mhm. I will consider use database selection, thanks.

**Comment by githubzhaoqian** [comment]
https://github.com/githubzhaoqian/go-redis-prefix
