### ISSUE TITLE
ERR wrong number of arguments for 'set' command

### ISSUE THREAD

**Issue by prawnsalad** [go-redis/redis#564]
~~~
e := redisClient.Set("key", "test", 0).Err()
// e == nil
~~~

~~~
e := redisClient.Set("key", "test", time.Hour).Err()
// e.Error() == "ERR wrong number of arguments for 'set' command"
~~~

I can't find anything different between what I'm doing and the examples

**Comment by vmihailenco** [comment]
I guess you need to upgrade your Redis Server.

**Comment by prawnsalad** [comment]
That did seem to be the issue. Is there any way to support the older version? I can't change the redis instance I need to send data to.

**Comment by vmihailenco** [comment]
You have to use pipeline of 2 commands with old Redis Server:

```
Set(key, value, 0)
Expire(key, time.Hour)
```

Theoretically it is possible to do that automatically in the client, but it does not look worth it...
