### ISSUE TITLE
Can provide a on event after connect redis?

### ISSUE THREAD

**Issue by xkeyideal** [go-redis/redis#565]
I have a requirement that execute CONFIG SET command after connect redis

**Comment by vmihailenco** [comment]
I wonder why

```
client := redis.NewClient(...)
client.ConfigSet(...)
```

is not an option?

**Comment by xkeyideal** [comment]
It can't meet my requirement， I use redis cluster mode, but when connect a client need exec CLIENT SETNAME command.
This is my code (change you source code in redis.go file)

`func (c *baseClient) initConn(cn *pool.Conn) error {
	cn.Inited = true

	if c.opt.Password == "" && c.opt.DB == 0 && !c.opt.ReadOnly && !c.opt.SetClientName {
		return nil
	}

	// Temp client for Auth and Select.
	client := newClient(c.opt, pool.NewSingleConnPool(cn))
	_, err := client.Pipelined(func(pipe Pipeliner) error {
		if c.opt.Password != "" {
			pipe.Auth(c.opt.Password)
		}

		if c.opt.DB > 0 {
			pipe.Select(c.opt.DB)
		}

		if c.opt.ReadOnly {
			pipe.ReadOnly()
		}

		if c.opt.SetClientName {
			pipe.ClientSetName(c.opt.ClientName)
		}

		return nil
	})
	return err
}`

And add two parameters in ClusterOptions and Options
`	ClientName    string
	SetClientName bool`

**Comment by xkeyideal** [comment]
My company use redis cluster need tell redis administrator who use the redis.

I know nodejs has a on event after connect redis.

**Comment by xkeyideal** [comment]
I see your source code, your redis client pool use net.Conn. The Client SetName command active for every connection. 
My code whether it can solve my problem?

**Comment by vmihailenco** [comment]
I've added `OnConnect` hook in v6.4.0 - https://github.com/go-redis/redis/blob/master/redis_test.go#L347-L349

**Comment by xkeyideal** [comment]
Thanks
