### ISSUE TITLE
pipeline CLIENT SETNAME command result value?

### ISSUE THREAD

**Issue by xkeyideal** [go-redis/redis#567]
CLIENT SETNAME command return result is `false <nil>`

redis docs:
@simple-string-reply: OK if the connection name was successfully set.

**Comment by vmihailenco** [comment]
I can't reproduce. Can you show the code?

**Comment by xkeyideal** [comment]
I see you detail resource code, it my mistake.

I know the reason, code is #565.
 _, err := client.Pipelined(func(pipe Pipeliner) error
this code not exec result.

Please see #565 problem.
