### ISSUE TITLE
Should Timeout Errors Be RetryableError?

### ISSUE THREAD

**Issue by jonmchan** [go-redis/redis#569]
I've started work on the backoff retry timer, but noticed that no retry is made except if the error is ```io.EOF```. Should Timeout errors be also retryable? It would seem that if a connection cannot be made because of a busy network, it would be useful to retry.

**Comment by vmihailenco** [comment]
From what I see all network errors are retryable - https://github.com/go-redis/redis/blob/master/internal/errors.go#L16
