### ISSUE TITLE
Reset commands

### ISSUE THREAD

**Issue by dim** [go-redis/redis#57]
Hi,

I am working a redis-cluster wrapper extension, but I am missing a crucial bit. Because of potential redirects to other servers, I need to be able to reset errors on commands. Could you please add the following:

```diff
diff --git a/command.go b/command.go
index d7c76cf..2a7bca7 100644
--- a/command.go
+++ b/command.go
@@ -35,6 +35,7 @@ type Cmder interface {
 
        Err() error
        String() string
+       Reset()
 }
 
 func setCmdsErr(cmds []Cmder, e error) {
@@ -78,6 +79,10 @@ func (cmd *baseCmd) Err() error {
        return nil
 }
 
+func (cmd *baseCmd) Reset() {
+       cmd.err = nil
+}
+
 func (cmd *baseCmd) args() []string {
        return cmd._args
 }
```

Thanks,
D

**Comment by bsm** [comment]
Oh, forgot link, in case you are interested: https://github.com/bsm/redis-cluster/

**Comment by vmihailenco** [comment]
Please take a look at https://github.com/go-redis/redis/pull/58

>Oh, forgot link, in case you are interested: https://github.com/bsm/redis-cluster/

Looks cool! I will add link to the readme.

**Comment by dim** [comment]
I will try to submit a PR for a direct integration in the next week or two, there is otherwise too much repetition. No reason not to have a `ClusterClient` direcly in your lib, would you agree? I currently (still) have some trouble with your testing framework, but I'll manage.

**Comment by vmihailenco** [comment]
Okay, sounds good. Also I have nothing against ginkgo and gomega for testing. Actually I prefer it when tests become too big and complex.
