### ISSUE TITLE
Options Are Not Exposed For Verifying Settings or Loggin Debug Info

### ISSUE THREAD

**Issue by jonmchan** [go-redis/redis#576]
It would be useful for the ```Client``` to expose a function that returns a read only copy of the ```opt``` object. The purpose I am interested in it for is asserting that the correct client receives the correct options and also for being able to print out all the options set when a error occurs like a timeout in order to give information to fine-tune these values.

**Comment by vmihailenco** [comment]
Did you see https://godoc.org/github.com/go-redis/redis#Client.Options?

**Comment by jonmchan** [comment]
That's exactly what I was thinking about implementing! Missed it! Thanks.
