### ISSUE TITLE
Tests fail on v6 tree

### ISSUE THREAD

**Issue by willroberts** [go-redis/redis#581]
Steps to reproduce:
1. `go get gopkg.in/redis.v6`
2. `cd $GOPATH/src/gopkg.in/redis.v6`
3. `go test -v ./...` (exit code is 1)

Result:
```cluster.go:10:2: use of internal package not allowed
ring.go:13:2: use of internal package not allowed
cluster.go:11:2: use of internal package not allowed
cluster.go:12:2: use of internal package not allowed
cluster.go:13:2: use of internal package not allowed
internal/pool/pool.go:10:2: use of internal package not allowed
internal/pool/conn.go:8:2: use of internal package not allowed
internal/proto/reader.go:9:2: use of internal package not allowed
```

Go version: `go version go1.8.3 darwin/amd64`

**Comment by willroberts** [comment]
Just noticed this commit: https://github.com/go-redis/redis/commit/8040d63c4f268fee385d48d6fdb8db0d32685265

I've moved to using `github.com/go-redis/redis` instead with a pinned commit, which works. Perhaps `gopkg.in/redis.v6` should be removed?

**Comment by vmihailenco** [comment]
It should, but I don't think it is possible... Closing.
