### ISSUE TITLE
Add multiple values in SAdd easily

### ISSUE THREAD

**Issue by frankcash** [go-redis/redis#596]
Hello,  I'm trying to use this package <https://godoc.org/gopkg.in/redis.v3#Client.SAdd> and do a multiple value SAdd but I'm having some troubles trying to figure out how.

my code is along the lines of 
```
	client.SAdd(string, []string).Err()
```

I have a working set of code where I iterate over the values instead of putting them into a `[]string`, but it seems costly to do iterable adds.

**Comment by vmihailenco** [comment]
`client.SAdd("myset", "member1", "member2")`, but I am not sure I understand the question.

**Comment by frankcash** [comment]
Sorry, I was looking for variadic param passing!!

I've changed my code to:

```
	err = client.SAdd(key, []interface...).Err() 

```
