### ISSUE TITLE
cluster.go use of internal package not allowed

### ISSUE THREAD

**Issue by thomasmodeneis** [go-redis/redis#598]
Hi,

I've updated the deps to v6 and golang to 1.8.3 and started experiencing this issue, any ideas ?

```
godep go build -o test main.go;
../gopkg.in/redis.v6/cluster.go:11:2: use of internal package not allowed
../gopkg.in/redis.v6/ring.go:13:2: use of internal package not allowed
../gopkg.in/redis.v6/cluster.go:12:2: use of internal package not allowed
../gopkg.in/redis.v6/cluster.go:13:2: use of internal package not allowed
../gopkg.in/redis.v6/cluster.go:14:2: use of internal package not allowed
godep: go exit status 1

```

**Comment by vmihailenco** [comment]
You should change import to `import "github.com/go-redis/redis"`

**Comment by thomasmodeneis** [comment]
I figure that out after few minutes.. 

Is this documented on the project readme.md or anywhere? or I missed this out ?

**Comment by vmihailenco** [comment]
Readme mentions correct import path, but there should be changelog some day...

**Comment by javier-sanz** [comment]
Sorry to reopen this issue but I am facing the same problem and from your comments is not clear to me what I have to do to fix this issue. In my case I found this problem using `gopkg.in/redis.v6` on my dependencies not `github.com/go-redis/redis `. So I kind had to revert this [commit](https://github.com/go-redis/redis/commit/8040d63c4f268fee385d48d6fdb8db0d32685265) changing all `github.com/go-redis/redis/interna`l for `gopkg.in/redis.v6/internal`. Then it worked. Is it the right thing to do?

**Comment by javier-sanz** [comment]
Ok forget about it. [Here](https://www.bountysource.com/issues/46415615-tests-fail-on-v6-tree) says the solution is not using `gopkg.in/redis.v6` but use github. I wild tag the version on the godeps.json.
