### ISSUE TITLE
seeing this error when installing with glide

### ISSUE THREAD

**Issue by chrislewispac** [go-redis/redis#602]
vendor/gopkg.in/redis.v5/cluster.go:11:2: use of internal package not allowed
vendor/gopkg.in/redis.v5/ring.go:13:2: use of internal package not allowed
vendor/gopkg.in/redis.v5/cluster.go:12:2: use of internal package not allowed
vendor/gopkg.in/redis.v5/cluster.go:13:2: use of internal package not allowed
vendor/gopkg.in/redis.v5/cluster.go:14:2: use of internal package not allowed

**Comment by vmihailenco** [comment]
gopkg.in does not work with slide. That is why in v6 gopkg.in was removed and you should now import "github.com/go-redis/redis".
