### ISSUE TITLE
ReadOnly option should only be used by cluster client.

### ISSUE THREAD

**Issue by v2e4lisp** [go-redis/redis#603]
According to the doc https://redis.io/commands/readonly READONLY is a cluster command so the corresponding `ReadOnly` option should only be used by a cluster client.  However, in the current implementation, `ReadOnly` can be set for single-node client, which leads to a `This instance has cluster support disabled` error when `baseClient.initConn` is called.

It would be a easy fix to just rename `ReadOnly` to `readOnly`.

**Comment by vmihailenco** [comment]
Sounds good. Do you want to send a PR?
