### ISSUE TITLE
Concurrency issue....

### ISSUE THREAD

**Issue by lennycampino** [go-redis/redis#609]
When i access the Get method very often i get that error message: 
2017/08/01 10:48:36 http: panic serving 127.0.0.1:51900: runtime error: invalid memory address or nil pointer dereference
goroutine 186 [running]:
net/http.(*conn).serve.func1(0xc42011c640)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1721 +0xd0
panic(0x14c5c00, 0x17eebd0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
_/Users/Documents/golang-backend/app/core/redis.(*RedisCli).GetValue(0xc420364028, 0xc42073a387, 0x1b8, 0x2, 0x2, 0xc42049e3e0, 0x0)

**Comment by vmihailenco** [comment]
Panic occurred in  `(*RedisCli).GetValue` which is your code, not go-redis.
