### ISSUE TITLE
Deadlock in Pub-Sub

### ISSUE THREAD

**Issue by superkinglabs** [go-redis/redis#610]
```
func (c *PubSub) Subscribe(channels ...string) error {
	c.mu.Lock()
	err := c.subscribe("subscribe", channels...)
	c.channels = appendIfNotExists(c.channels, channels...)
	c.mu.Unlock()
	return err
}

func (c *PubSub) subscribe(redisCmd string, channels ...string) error {
	cn, err := c._conn(channels)
	if err != nil {
		return err
	}

	err = c._subscribe(cn, redisCmd, channels...)
	c.putConn(cn, err)
	return err
}

func (c *PubSub) putConn(cn *pool.Conn, err error) {
	if !internal.IsBadConn(err, true) {
		return
	}

	c.mu.Lock()
	if c.cn == cn {
		_ = c.releaseConn()
	}
	c.mu.Unlock()
}
```

During Subscribe if there is a connection failure. I am getting a deadlock at putConn (c.mu.Lock())

**Comment by vmihailenco** [comment]
Ouch! Fixed in v6.5.5, thanks for the report.

**Comment by superkinglabs** [comment]
Thanks for the quick resolution. I love this library. Great work!!

*Thanks & Regard*
Gameberry
Try our latest game: Word Pirate
Download Links: Android
<https://play.google.com/store/apps/details?id=com.superking.word.pirate>
<https://play.google.com/store/apps/details?id=com.superking.word.pirate>
<https://play.google.com/store/apps/details?id=com.superking.word.pirate>
IOS <https://itunes.apple.com/in/app/word-pirate/id1241917971>

**Comment by superkinglabs** [comment]
Hi,

I have one more question. I see that all operation on pub-sub client is protected by a Mutex, then why is it unsafe to use with multiple go routine?

**Comment by vmihailenco** [comment]
It is protected by mutex so Subscribing and resubscribing (when connection is lost) are not racy. PubSub is not safe for concurrent use because reading from the `net.Conn` buffer is not protected by the mutex.

**Comment by superkinglabs** [comment]
Then how to use the Channel method of the pub-sub client. If subscribing is protected by mutex and the Channel operation is safe for concurrently receiving messages, then will it be safe to use it concurrently?

`
// Channel returns a channel for concurrently receiving messages.
// The channel is closed with PubSub.
func (c *PubSub) Channel() <-chan *Message {
	ch := make(chan *Message, 100)
	go func() {
		for {
			msg, err := c.ReceiveMessage()
			if err != nil {
				if err == pool.ErrClosed {
					break
				}
				continue
			}
			ch <- msg
		}
		close(ch)
	}()
	return ch
}`

**Comment by vmihailenco** [comment]
It is safe because Go channel works like a mutex for ReceiveMessage.
