### ISSUE TITLE
Use cluster client, Some subscription event messages are not received

### ISSUE THREAD

**Issue by MarkLi2011** [go-redis/redis#614]
Sorry, English is not good, the problem may be a little unclear

The debug environment information is as follows:

```
cluster node:
192.168.12.12:8000
192.168.12.12:8001
192.168.12.12:8008

redis server version:
[root@t]# redis-cli -h 192.168.12.12 info |grep 'redis_version'
redis_version:3.2.9

redis client version:
[root@t]# redis-cli -v
redis-cli 4.0.1

[root@t]# redis-cli -h 192.168.12.12 -p 8000 -c config set notify-keyspace-events KEhx
[root@t]# redis-cli -h 192.168.12.12 -p 8001 -c config set notify-keyspace-events KEhx
[root@t]# redis-cli -h 192.168.12.12 -p 8002 -c config set notify-keyspace-events KEhx

ssh windows1
[root@t]# redis-cli -h 192.168.12.12 -p 8000 -c
192.168.12.12:8000> psubscribe __key*__:*
Reading messages... (press Ctrl-C to quit)
1) "psubscribe"
2) "__key*__:*"
3) (integer) 1
1) "pmessage"
2) "__key*__:*"
3) "__keyspace@0__:k3"
4) "hset"
1) "pmessage"
2) "__key*__:*"
3) "__keyevent@0__:hset"
4) "k3"

ssh windows2
[root@t]# redis-cli -h 192.168.12.12 -p 8001 -c
192.168.12.12:8001> hset k3 f3 v3
-> Redirected to slot [4576] located at 192.168.12.12:8000
(integer) 0
192.168.12.12:8000> hset k4 f4 v4
-> Redirected to slot [8455] located at 192.168.12.12:8001
(integer) 0
192.168.12.12:8001> 

ssh windows2 execute hset k4 f4 v4，ssh windows1 No event messages received，Looks like it should have been caused by “-> Redirected to slot [8455] located at 192.168.12.12:8001”

Using go-redis also has the same problem. Is it the wrong place to use it? Part of the code is as follows:
	
clientInst = redis.NewClusterClient(&redis.ClusterOptions{
		Addrs:              urls,
		DialTimeout:        5 * time.Second,
		ReadTimeout:        3 * time.Second,
		WriteTimeout:       3 * time.Second,
		PoolSize:           cfg.RedisPoolSize(),
		PoolTimeout:        3 * time.Second,
		IdleTimeout:        5 * time.Minute,
		IdleCheckFrequency: time.Minute,
		RouteByLatency:     true,
		//Password:           *(cfg.RedisPwd()),
	})

func EventMsgPro() {
	ps := clientInst.PSubscribe("__key*__:*")
	clientInst.ClusterMeet

	for {
		msg, err := ps.ReceiveMessage()
		if msg != nil && err == nil {
			fmt.Printf("Channel[%v] Pattern[%v] Payload[%v]\n", msg.Channel, msg.Pattern, msg.Payload)
		}
	}
}
```

Because of the Markdown format, the original bold text has two underscores at both ends

Thanks for the answer!!!

**Comment by MarkLi2011** [comment]
[__test__](url)

**Comment by vmihailenco** [comment]
Sorry, but I don't really understand what the issue is. Can you write a small program that reproduces the problem?

**Comment by MarkLi2011** [comment]
Sorry, A few days ago sick, did not have time to reply to the message, thank you very much for your reply, the following is my test procedures, I subscribe to the incident, but some cluster node events are not received
package main

import (
	"fmt"
	"syscall"
	"time"

	DEATH "github.com/vrecan/death"
	"gitlab.potato.im/storage_service/glog"
	"gitlab.potato.im/storage_service/redis"
)

// clientInst client
var clientInst *redis.ClusterClient

// newClusterRedisClient cluster connection
func newClusterRedisClient() {
	clientInst = redis.NewClusterClient(&redis.ClusterOptions{
		Addrs:              []string{"192.168.12.12:8000", "192.168.12.12:8001", "192.168.12.12:8002"},
		DialTimeout:        5 * time.Second,
		ReadTimeout:        3 * time.Second,
		WriteTimeout:       3 * time.Second,
		PoolSize:           100,
		PoolTimeout:        3 * time.Second,
		IdleTimeout:        5 * time.Minute,
		IdleCheckFrequency: time.Minute,
		RouteByLatency:     true,
		//Password:           *(cfg.RedisPwd()),
	})

	if clientInst != nil {
		glog.Infoln("RedisClient-newClusterRedisClient: New client instance success.")
	} else {
		glog.Fatalln("RedisClient-newClusterRedisClient: New client instance exception!")
	}
}

func eventPro() {
	EventMsgPro()
}

// EventMsgPro test
func EventMsgPro() {
	time.Sleep(1 * time.Second)
	fmt.Println("EventMsgPro .....")

	ps := clientInst.PSubscribe("__key*__:*")

	for {
		msg, err := ps.ReceiveMessage()
		if msg != nil && err == nil {
			fmt.Printf("Channel[%v] Pattern[%v] Payload[%v]\n", msg.Channel, msg.Pattern, msg.Payload)
		}
	}
}

// run test
func runService() {
	glog.Info("redisclient started success ...")

	go eventPro()

	death := DEATH.NewDeath(syscall.SIGINT, syscall.SIGTERM, syscall.SIGKILL)

	// when you want to block for shutdown signals
	death.WaitForDeathWithFunc(func() {
		if clientInst != nil {
			clientInst.Close()
			glog.Infoln("RedisClient-runService release resources.")
		}
		//do whatever you want on death
	})
}

func main() {
	newClusterRedisClient()
	runService()
}

**Comment by MarkLi2011** [comment]
@vmihailenco

**Comment by JessePreiner** [comment]
> for anyone who pass here. Redis Notification (**key***:*) not distribute across node. Client need to connect to all nodes to get all event.
Related doc: 
https://redis.io/docs/manual/keyspace-notifications/#events-in-a-cluster
