### ISSUE TITLE
Cluster Info is called repeatedly for a Ring client

### ISSUE THREAD

**Issue by arcoraven** [go-redis/redis#617]
I have a go-redis ring client that is successfully making calls to Redislabs. Dashboards and debug logging shows my client is calling `CLUSTER INFO` roughly 2k times per second, which is hurting connection pooling and ultimately latency. Our redislabs instance returns `(error) ERR This instance has cluster support disabled`, so I assume whatever is calling it is retrying on error. Why would a ring client be calling `CLUSTER INFO` at all, much less so frequently?

[This is the line calling `CLUSTER INFO`](https://github.com/go-redis/redis/blob/4e1d2a01db8ebcec6ddeae623050cbaa7df5ffcf/cluster.go#L295)

[And `reloadState()` appears to be calling `Random()`](https://github.com/go-redis/redis/blob/4e1d2a01db8ebcec6ddeae623050cbaa7df5ffcf/cluster.go#L788)

I'm hoping I'm missing something simple like a misconfiguration. Most of the ring options (besides `Addrs` pointed at a single Redislabs endpoint, timeouts, and pool size) are not set and left on default values.

**Comment by vmihailenco** [comment]
Looks like you want to use `redis.NewRing`, but actually using `redis.NewCluster`. `(error) ERR This instance has cluster support disabled` says that you are using cluster client, but Redis does not have cluster support.

**Comment by arcoraven** [comment]
In case people encounter the same issue, my issue was caused by my client first instantiating a clustered client, checking if a `ping` succeeded, and if not, falling back to creating a ring client. After a clustered client ping error, adding a `clusterClient.Close()` forces any pending resources to be freed, stopping the `CLUSTER INFO` calls.
