### ISSUE TITLE
redis cluster can't connect any one address, but the OnConnect method can't return error 

### ISSUE THREAD

**Issue by xkeyideal** [go-redis/redis#620]

**Comment by xkeyideal** [comment]
The Reason is all address can't connection, the `NewClusterClient` method should return two paramters **client & error**

The redis cluster client should provide a method for checking all cluster nodes whether healthy or not.

**Comment by vmihailenco** [comment]
What would you do if `NewClusterClient` returns an error?

**Comment by xkeyideal** [comment]
I see the code, change it‘s complicated
```go
        // Preload cluster slots.
	for i := 0; i < 10; i++ {
		state, err := c.reloadSlots()
		//fmt.Println(state, err)
		if err == nil {
			c._state.Store(state)
			break
		}
	}
```
But the problem is all address can't connect, we can't catch it.

I have not a good idea now.

**Comment by vmihailenco** [comment]
`NewClusterClient` does not return an error, because that is what users want 99% of the time. If you want to check if Redis is up you should use `redis.Ping` and `cluster.ForEachMaster`.
