### ISSUE TITLE
design about the ConnPool

### ISSUE THREAD

**Issue by terry1991** [go-redis/redis#624]
there a member named freeConns in the struct ConnPool. 
from the code , we get conn from the end of the freeConns and put the finished conn to the end of the freeConns.
why get from the and and put from the end?
this design wether make some conns are idle?
if we put some conns from different servers to the pool, wether cause load unbalance phenomena?

**Comment by vmihailenco** [comment]
Each server has its own connection pool. Pool reuses last connection since it is likely to be warmed up, because it was used recently (I doubt it matters in practice). It also helps with idle connections.

**Comment by terry1991** [comment]
@vmihailenco thanks for your answer
so the ConnPool designed for only one server ,not some ?
if we have some proxy instances between the client and the redis server, we should make each server has its own ConnPool?

**Comment by vmihailenco** [comment]
Given that you can't retrieve a connection for specific server from the pool I think you don't have any choice (with go-redis pool).
