### ISSUE TITLE
Connection Pool: How can I keep the pool unclosed?.

### ISSUE THREAD

**Issue by astromahi** [go-redis/redis#627]
This is from `redis.Options`

>// Amount of time after which client closes idle connections.
    // Should be less than server's timeout.
    // Default is 5 minutes.
    IdleTimeout time.Duration

Closing the idle connections in the pool is considered bad idea!. It contradicts the idea of keeping pool of connections where we select on-demand instead of creating one.

Is there any way I can keep an amount of pooled connections?.

Thanks.

**Comment by vmihailenco** [comment]
`IdleCheckFrequency = -1` should disable idle checks.

**Comment by namjitharavind** [comment]
Shall we create connections before actual request comes. Because redis is not allowing very frequent connection creation.

**Comment by vmihailenco** [comment]
Is there a real problem? If not I would not do anything.
