### ISSUE TITLE
Correct way to use BRPopLPush

### ISSUE THREAD

**Issue by gngeorgiev** [go-redis/redis#633]
Using `BRPopLPush` causes the connections to constantly timeout. What's the correct way to block indefinitely?

`reading from redis: read tcp [::1]:39370-\u003e[::1]:6379: i/o timeout`

It seems that the PoolTimeout controls this, but I am not entirely sure that's correct behavior.

**Comment by vmihailenco** [comment]
What did you try so far? `BRPopLPush("a", "b", 0)` should work.

**Comment by gngeorgiev** [comment]
@vmihailenco By default the PoolTimeout is set to *connection timeout + 1 second*, so this will timeout after one second. If we change the PoolTimeout to 5 seconds, it will timeout after 5 seconds.

**Comment by vmihailenco** [comment]
It does not seem to be true - https://github.com/go-redis/redis/blob/master/commands.go#L10-L15

**Comment by gngeorgiev** [comment]
@vmihailenco You are absolutely right. Maybe when I tried it, it I have had too many concurrent **BRPopLPush**, since when the open connections are more than the Pool's max they start dropping.

In any case, I am sorry for bothering you :)
