### ISSUE TITLE
i/o timeout on large DB

### ISSUE THREAD

**Issue by schollz** [go-redis/redis#637]
Hi, love the code. It works great for me in general.

Though, I have a problem: I have a connection which I'm trying to collect all ~3,000,000 keys from a 384MB redis DB. The code I'm using is basically:

```go
c = redis.NewClient(&redis.Options{
		Addr:     c.RedisURL + ":" + c.RedisPort,
		Password: "", // no password set
		DB:       0,  // use default DB
})
keys, err = c.Keys("*").Result()
return keys, err
```

This code works great on all my other DBs (<100 MB). Unfortunately, on this large DB, it always results in an error:

```shell
read tcp 127.0.0.1:48670->127.0.0.1:6377: i/o timeout
```

Is there a way to specify a longer wait before timing out for a large DB?

Interestingly, it seems to work fine when I try to dump with Python:

```python
import redis

r = redis.StrictRedis(host='localhost', port=6377)

with open('keys.txt','wb') as f:
	for key in r.scan_iter('*'):
		f.write(key)
		f.write(b'\n')
```

so I suspect its something to do with Go.

**Comment by vmihailenco** [comment]
See https://godoc.org/github.com/go-redis/redis#example-ScanCmd-Iterator for equivalent Go code. Read/Write timeout can be specified in `redis.Options`:

```
c = redis.NewClient(&redis.Options{
    ReadTimeout: time.Minute,
})
```

But I don't recommend doing that.

**Comment by schollz** [comment]
Thanks, ScanCmd-Iterator worked great!

**Comment by dharmendrasdlt** [comment]
> See https://godoc.org/github.com/go-redis/redis#example-ScanCmd-Iterator for equivalent Go code. Read/Write timeout can be specified in `redis.Options`:
> 
> ```
> c = redis.NewClient(&redis.Options{
>     ReadTimeout: time.Minute,
> })
> ```
> 
> But I don't recommend doing that.

@vmihailenco Why not?
