### ISSUE TITLE
ReceiveMessage buffer full

### ISSUE THREAD

**Issue by xtuc** [go-redis/redis#641]
We are streaming some big JSON objects through the pub/sub mechanism of Redis. Sometimes we hit the internal limit of the ReadLine buffer and the Redis client returns a `bufio: buffer full` error instead of something.

Note that the default size of the buffer is at `4096` bytes.

It would be great to either handle the `isPrefix` returned by ReadLine or allow us to configure the buffer passed to ReadLine at initialization.

See

https://github.com/go-redis/redis/blob/74d5147d860804ea34633071d0c91a7f4b0b5c3a/internal/proto/reader.go#L62-L64

If you agree with that, I'll be happy to make a PR since I've already the code to handle that somewhere.

**Comment by vmihailenco** [comment]
Can we please start with a test that reproduces the issue?

**Comment by xtuc** [comment]
https://github.com/go-redis/redis/pull/642

**Comment by xtuc** [comment]
Any news from this? Can I help you with something? Do we agree on https://github.com/go-redis/redis/pull/642#issuecomment-331711647 now?

**Comment by vmihailenco** [comment]
You can help by writing an app that uses `ReceiveMessage` and reproduces this issue.

**Comment by xtuc** [comment]
As far as I understand, that's what I explained in https://github.com/go-redis/redis/pull/642#issuecomment-331734202. 

`PubSub.ReceiveMessage` uses your ReadLine wrapper under the hood. I was asking if you agree with that. I just followed the function calls with "go to definition".

**Comment by netgusto** [comment]
Seems pretty clear from the golang documentation that `isPrefix` is not an semantically an error, but a flag informing the consumer that there are more bytes to read on the line.

https://golang.org/pkg/bufio/#Reader.ReadLine

This could (should?) be handled in this code as proposed by @xtuc 
https://github.com/go-redis/redis/blob/74d5147d860804ea34633071d0c91a7f4b0b5c3a/internal/proto/reader.go#L57-L72

**Comment by vmihailenco** [comment]
I still did not see a program that reproduces this issue.

**Comment by netgusto** [comment]
Damn, too bad.

**Comment by eelcocramer** [comment]
I get this issue when retrieving large blobs from [redux]() which is API compliant with redis.

I created a test that reproduces that error. It happens when reading from a byte array which length is larger than 4096.

https://github.com/eelcocramer/redis/blob/46c6ac7debcb631c52554a9a990a1f7d6295a71f/internal/proto/reader_test.go#L30-L41

A fix that works for me is:

https://github.com/eelcocramer/redis/blob/46c6ac7debcb631c52554a9a990a1f7d6295a71f/internal/proto/reader.go#L48-L60
