### ISSUE TITLE
How to check redis error type

### ISSUE THREAD

**Issue by mouhong** [go-redis/redis#645]
Hey guys, go-redis will return an error if I `HGet` a hash field which doesn't exist.
But how do i distinguish this error with other errors like network error?
What i want to do is:
```
val, err := redis.HGet("hash", "not_exist_field")
if err.(???) {
   log.Println("ok, the field does not exist, make it default to 0")
} else {
   log.Println("some unknow error occurs, log it and return err to caller")
}
```

**Comment by vmihailenco** [comment]
You are probably looking for `redis.Nil`

**Comment by mouhong** [comment]
@vmihailenco Thanks! This is exactly what I'm looking for. Just wondering why make `nil` response an error instead of a normal return value?

**Comment by vmihailenco** [comment]
Like what?
