### ISSUE TITLE
logger enabled by default

### ISSUE THREAD

**Issue by pierrre** [go-redis/redis#651]
Hello,

I've noticed that since this commit https://github.com/go-redis/redis/commit/5294b5dae18eff1e93fa83164d4f9dcf6f3aebe7
the logger is enabled by default.

Is there a reason ?
I didn't expect this behavior.

Thanks

**Comment by vmihailenco** [comment]
Because otherwise everyone ignores it (including myself). So I reduced log verbosity and enabled it by default.

**Comment by pierrre** [comment]
ok, thanks
