### ISSUE TITLE
redis client connect to Azure redis cluster timeout

### ISSUE THREAD

**Issue by zhangruiskyline** [go-redis/redis#652]
I did a very simple test on Azure redis server but it always get I/o timeout. code is as below. I thought it is some Azure problem but if I create a python client using redis lib it works. so what could be problem

```

package rediscache_test

import (
	"fmt"
	"testing"
	"github.com/go-redis/redis"
)

var client *redis.Client

func CreateNewClient() {
	client = redis.NewClient(&redis.Options{
		Addr: "xxxx.redis.cache.windows.net:6380",
		Password:"xxxxx",
		DB:     0,  // use default
	})
	fmt.Println(client.ClientGetName())
}

func TestCommand(t *testing.T) {
	CreateNewClient()
	val := client.Get("foo")
	fmt.Println(val)

}

```

BTW, attached is working python program

```
import redis
r = redis.StrictRedis(host='xxxx.redis.cache.windows.net',
      port=6380, db=0, password='xxxx', ssl=True)

r.set('foo', 'bar')
print(r.get('foo'))
```

**Comment by zhangruiskyline** [comment]
Golang error msg is like

get foo: read tcp IP:port->IP':6380: i/o timeout

**Comment by zhangruiskyline** [comment]
I found out maybe it is due to that this client dose not support SSL?

**Comment by zhangruiskyline** [comment]
Is there any simple way I can set up SSL=true, like in redigo

redis.DialURL(tt.url, dialTestConn(tt.r, &buf), redis.DialUseTLS(true))

**Comment by vmihailenco** [comment]
Like this:

```
	client = redis.NewClient(&redis.Options{
		Addr: "xxxx.redis.cache.windows.net:6380",
		Password:"xxxxx",
		DB:     0,  // use default
		TLSConfig: &tls.Config{}, // your config here
	})
```

**Comment by zhangruiskyline** [comment]
Thanks, If I just want to enable SSL like SSL=true, how do I put this config?

**Comment by totoyotonet** [comment]
/commands.go

**Comment by vmihailenco** [comment]
Simplest TLS config is `&tls.Config{InsecureSkipVerify: true}`.

**Comment by DeadlySurgeon** [comment]
> Simplest TLS config is `&tls.Config{InsecureSkipVerify: true}`.


I know this issue is closed, however you really shouldn't suggest that people do this, as a lot of people can't seem to understand what the word `Insecure` means and will use it in places they shouldn't.

**Comment by vmihailenco** [comment]
@DeadlySurgeon thanks, I've updated the docs - https://redis.uptrace.dev/#using-ssl
