### ISSUE TITLE
Can't receive message from subscription channel

### ISSUE THREAD

**Issue by lwhile** [go-redis/redis#657]
I subscribe from channel named test, but the code just can receive first one message from the channel.

```go
import rd "github.com/go-redis/redis"
func (r *redis) Subscr() {
	pubsub := r.cli.Subscribe("test")
	defer pubsub.Close()

	for {
		select {
		case msg := <-pubsub.Channel():
			fmt.Println(msg.Payload)
		}

	}
}
```

I can receive message normally from the same channel by redis-cli.

Is my use wrong?

thanks.

**Comment by vmihailenco** [comment]
It should be:

```
func (r *redis) Subscr() {
	pubsub := r.cli.Subscribe("test")
	defer pubsub.Close()

        ch := pubsub.Channel()
	for {
		select {
		case msg := <-ch:
			fmt.Println(msg.Payload)
		}
	}
}
```

But it makes sense to support both variants.

**Comment by Kelvne** [comment]
I'm still having exactly this problem

```golang
	pubsub := appContext.GetRedisClient().Subscribe("test")
	channel := pubsub.Channel()
	defer pubsub.Close()

	go func(channel <-chan *redis.Message) {
		for {
			select {
			case msg := <-channel:
				fmt.Println(msg.Payload)
			default:
			}
		}
	}(channel)

	appContext.GetRedisClient().Publish("test", "lerolero")
```

**Comment by lwhile** [comment]
@Kelvne  Hello, can you add the code to print the error information?
```go
err := appContext.GetRedisClient().Publish("test", "lerolero")
fmt.Println(err)
```

**Comment by vmihailenco** [comment]
Add small delay (100 milliseconds should be enough) before adding message to the channel and try again. Most likely subscription is not created yet when you send first message.

**Comment by Kelvne** [comment]
@lwhile No need too, I'm sorry. The problem was what @vmihailenco said.
I was using it on a goroutine that closed before the subscription wasn't even created! Thanks, guys!
