### ISSUE TITLE
return error when use SPopN function

### ISSUE THREAD

**Issue by ChiefMage** [go-redis/redis#664]
my code：
       `result, err := client.SPopN("testKey",1000).Result()`
return error: `redis: can't parse array reply: +OK`
How should I use this function?

**Comment by vmihailenco** [comment]
Can you provide a small program that reproduces the issue?

**Comment by ChiefMage** [comment]
```
package main

import (
	"fmt"
	"github.com/go-redis/redis"
	"time"
)

func main() {
	var redisClient *redis.Client
	redisClient = redis.NewClient(&redis.Options{
		Addr:         "addr",
		Password:     "pass",           //如果没有密码,默认为空
		DB:           0,            //默认选择0数据库
		MaxRetries:   3,                //连接失败后重试3次
		DialTimeout:  10 * time.Second, //拨号超时
		WriteTimeout: 5 * time.Second,  //写超时
		PoolSize:     100,          //最大连接数
		IdleTimeout:  200 * time.Second,
	})
	result, err := redisClient.SPopN("test_key",1000).Result()
	if err == redis.Nil {
		return
	} else if err != nil {
		fmt.Println(err.Error())
	} else {
		fmt.Println(result)
	}
}

```
please set the addr and password to connetct redis,return` redis: can't parse array reply: "+OK"`when run this program

**Comment by vmihailenco** [comment]
That program works fine for me.

**Comment by sdcuike** [comment]
# Encounter the same mistake

{"error":"redis: can't parse array reply: \"+OK\"","level":"error","msg":"redisCluster.SMembers error:keyForIncludein:{e7857514f201436b9e0fdacf0a060862}","time":"2019-05-22T17:18:44Z","trace_id":"7c7c5279c365461e931d96ae01a01649"}


see https://redis.io/commands/smembers

redis bug？
