### ISSUE TITLE
Problem with get slave via sentinel.

### ISSUE THREAD

**Issue by valentyn-hrynevich** [go-redis/redis#673]
How to get a slave instance via sentinel.
For example https://github.com/andymccurdy/redis-py have method "slave_for" that return client object with slave host.
How to get something same using this library.
I don't found anything about in a documentation.
Thanks for help.

**Comment by vmihailenco** [comment]
`NewFailoverClient` returns plain redis `*Client` so I am not sure where to add `slave_for` method. And now we even don't retrieve/store information about slaves which is another problem.

I guess that you want to use slave(s) for read only commands. If that is the case I would recommend you to use Redis Cluster and enable `ClusterOptions.ReadOnly` and/or `ClusterOptions.RouteByLatency`.

**Comment by valentyn-hrynevich** [comment]
Okay, but I don't want to configure cluster stack. May be will be good to implement parameter for get random slave instead of getting master permanently.
What do you think about it?

**Comment by totoyotonet** [comment]
I do not know how to do it

**Comment by vmihailenco** [comment]
Closing since I don't understand what you are trying to achieve and there is no good place for method like "slave_for".

**Comment by agparadiso** [comment]
Im trying to do the same it was asked here, get a sentinel slave in order to split reads/writes. haven't found a way of doing it with this library. btw the closing reason doesn't seems to be appropriated.

**Comment by vmihailenco** [comment]
https://github.com/go-redis/redis/pull/997 looks promising, but it requires more work.

**Comment by eafzali** [comment]
@vmihailenco I'm happy to work on that if you give it a review and could help me understand your build pipeline

**Comment by yushizhao** [comment]
I have the same need, namely, route all read commands to slaves. 
From what I read here, I think @vmihailenco have suggested to create a go-redis ClusterClient with  `ClusterOptions.ReadOnly`. Would you suggesting then all the read commands passed by ClusterClient::Do will route to a slave while all the write commands go to master? I see there is a work around in clusterState. However, I want to confirm if Sentinel failover a master, how would clusterState get updated? Thank you.

**Comment by landrade** [comment]
Any workaround to resolve it? Write on master and read from slaves is a common approach for applications that don't need sharding data but have a high throughput.
