### ISSUE TITLE
Increase the number of connections per host

### ISSUE THREAD

**Issue by dineshg13** [go-redis/redis#674]
golang default transport has a limit of 2 connections per host unless it is explicitly set. 

From go-documentation: file : transport.go  in net package 
// MaxIdleConnsPerHost, if non-zero, controls the maximum idle
// (keep-alive) connections to keep per-host. If zero,
// DefaultMaxIdleConnsPerHost is used.
	MaxIdleConnsPerHost int

under load , we see the below from net stat command , which is causing unexpected behavior with our latency 
```
tcp        0      0 redis:6379 ESTABLISHED
tcp        0      0 redis:6379 TIME_WAIT
tcp        0      0 redis:6379 TIME_WAIT
tcp        0      0 redis:6379 TIME_WAIT
tcp        0      0 redis:6379 TIME_WAIT
tcp        0      0 redis:6379 TIME_WAIT
tcp        0      0 redis:6379 ESTABLISHED
tcp        0      0 redis:6379 TIME_WAIT
```

go-redis should set the connections per host to same as the pool size before using the underlying http/tcp connection. 

Please let me know if you have any questions in this regard.

**Comment by vmihailenco** [comment]
go-redis uses TCP connections, not HTTP. If you want to increase number of connections you need to tune `Options.PoolSize`.

**Comment by anirudhmendiratta** [comment]
We currently set Options.PoolSize as 800 before initializing the redis client but at any given time, netstat shows only 2 connections to a redis host at any given time

**Comment by vmihailenco** [comment]
And how many requests per seconds do you have? And what is the problem we are solving here?

**Comment by dineshg13** [comment]
We are processing almost 65k req/sec. 

When we see latency from our client side, we see the below 
![screen shot 2017-12-05 at 9 35 05 am](https://user-images.githubusercontent.com/2471669/33613154-db10d228-d9a1-11e7-85b3-3a3ca02de5cc.png)

during the same window, when we see latency from redis perspective (above is in seconds, below is in ms )
![screen shot 2017-12-05 at 9 54 28 am](https://user-images.githubusercontent.com/2471669/33613325-5c89e1b4-d9a2-11e7-9f6e-8060ad50027d.png)

As we see, redis is not loaded and we don't see any spike in CPU in redis. Our code does some get simple Hget operation. In case you need that , we can share the code here . 
We strongly there is some limitation in the go-redis code, that is causing this latency spikes. 

Let me know if you need any further information.

**Comment by vmihailenco** [comment]
Idle Redis is normal if you have more than 1 core and running 1 Redis instance. I would bet that bottleneck is in the network latency/bandwidth.

To prove that go-redis is a problem you should write a program that sends 1 000 000 pings (or Hget in your case) from multiple goroutines and run it with `PoolSize=10/20/30` etc and compare time. Last time I run something like that go-redis was scaling well up until `10 * runtime.NumCPU()` connections. To exclude network issues you also need to run it on the same server where Redis Server is running.

**Comment by vmihailenco** [comment]
Try `IdleCheckFrequency = -1` to disable closing idle connections from go-redis.
