### ISSUE TITLE
How to use client with circuit breaker

### ISSUE THREAD

**Issue by tbarbugli** [go-redis/redis#675]
Is there any example on how to use the redis client with circuit breaker? If not I am more than happy to contribute one (in that case some guidance/tips are very welcome :))

**Comment by vmihailenco** [comment]
go-redis automatically stop opening new connections and starts polling Redis Server when it detects that Redis Server is down. See https://github.com/go-redis/redis/blob/master/internal/pool/pool.go#L106-L113 and https://github.com/go-redis/redis/blob/master/internal/pool/pool.go#L123-L140

**Comment by pareshvpatil** [comment]
Hey there, i have worked with the similar requirement and here's the artifact that you can use already.
See the [artifact] in maven central repo (https://mvnrepository.com/artifact/io.github.pareshvpatil/redis-with-circuitbreaker)
for which the source code could be found [here](https://github.com/pareshvpatil/redis-with-circuitbreaker)
