### ISSUE TITLE
How to “EXPIRE” the “HSET”  key in redis?

### ISSUE THREAD

**Issue by hongxufeng** [go-redis/redis#676]
The think  is here:
First,I SetCacheDuration 
 RedisCache.Expire(key string, expiration time.Duration)
Second,I HSetCache
RedisCache.HSet(key, field string, value interface{})
Thind,I HGetCache
RedisCache.HGetAll(key string)

but the EXPIRE is does't work,and  HGetAll is always exsist ,even though the first and second does't execute and as a result the map is [].

please deal this issues ,   Thank very much;

best wishes！

**Comment by vmihailenco** [comment]
I believe that is how Redis works - `HGetAll` returns empty result even when key does not exist:

```
127.0.0.1:6379> hgetall this-key-does-not-exist
(empty list or set)
```
