### ISSUE TITLE
There's an issues in Hset,How to Expire?

### ISSUE THREAD

**Issue by hongxufeng** [go-redis/redis#677]
First I set the key'expire , RedisCache.Expire(key,duration).  Later,I Hset the data ,  RedisCache.HSet(key,slavekey,value).  But  the data  never expire.  but I want it expire, please tell me how to Implement，   Thank very much;

best wishes!

**Comment by vmihailenco** [comment]
Closing as duplicate of https://github.com/go-redis/redis/issues/676
