### ISSUE TITLE
How to get keys from cluster？

### ISSUE THREAD

**Issue by dsewnr** [go-redis/redis#678]
I tried to get keys but only return keys from one node of cluster.

How to use Keys command in cluster?

Thanks.

**Comment by vmihailenco** [comment]
That is how Redis Cluster works so this is not a go-redis specific. My guess is that you need to iterate over all cluster nodes.

**Comment by dotSlashLu** [comment]
Hi, sorry to bring this closed issue up. 

My question is, If I have to manually iterate over all cluster nodes, what is the purpose of ClusterClient.Keys then? Why not implement it inside this method? 

And how to do that? Do I have to manually connect to each member and issue a Keys command or I can get connections from the ClusterClient? I saw a ClusterNodes method, but it returns strings.

Thanks.

**Comment by vmihailenco** [comment]
`ForEachMaster` should help you to iterate over all master nodes.

>what is the purpose of ClusterClient.Keys then? Why not implement it inside this method?

I believe that using `ForEachMaster` results in better/faster code.

**Comment by dotSlashLu** [comment]
Thanks @vmihailenco 👍
