### ISSUE TITLE
Closing Idle Connections in the pool

### ISSUE THREAD

**Issue by chitrakojha** [go-redis/redis#679]
We're using this lib for over two years now. 

Recently, we increased the pool size to support surge in traffic in our system. 
We're noticing that number of connections to Redis keep growing. Our application receives burst traffic so this number going up intermittently is accepted. However, even at low traffic, we see the number of connections going up. 

We're looking for a way to reduce these connections automagically without restarting our servers. Are we missing something here that's causing this leak? 

Our IdleTimeout is set to 5Minutes.

**Comment by vmihailenco** [comment]
If there is a leak please write a program that reproduces it. Overall this issue has almost no details and description of the problem. My experience that increasing pool size has very little effect and I would not increase it without benchmarks.
