### ISSUE TITLE
The Question of return of  Exec() in Pipeliner

### ISSUE THREAD

**Issue by BrotherGao** [go-redis/redis#689]
Hi,@vmihailenco
First of all, Thank you for your help #687 
As we all know, Exec() api of Pipeliner will return an array of Cmder which is a type of interface.We can get result by calling String() of Cmder. However, what String() returns are not what I want. What I want to get is  value without the command which is preceded by semicolons. I think Cmder should privide a interface which only return value like Val() of StringCmd. I think it is convenient for users to get return values when using Pipeliner.

**Comment by vmihailenco** [comment]
You can cast `Cmder` to concrete type which has `Val` method:

```
cmds, err := pipe.Exec()
if err != nil { panic(err) }
cmds[0].(*StringCmd).Val()
```

or save cmds you need - see https://godoc.org/github.com/go-redis/redis#example-Client-Pipeline and https://godoc.org/github.com/go-redis/redis#example-Client-Pipelined

**Comment by BrotherGao** [comment]
Oh, `cmds[0].(*StringCmd).Val()` is what I want. Thank you for your advice! I think you can close this issue.
Btw, Happy New Year. ^.^

**Comment by vmihailenco** [comment]
Happy New Year!
