### ISSUE TITLE
Pub in PubSub extremely slow

### ISSUE THREAD

**Issue by ericdolson** [go-redis/redis#694]
In setting up the following test

    go func() {
      for {
        msg, _ := pubsub.ReceiveMessage()
        fmt.Println(msg.Channel, msg.Payload)
      }
    }()
    
    go func() {
      for i := 0; i < 1000; i++ {
        redisPubSubClient.Publish("!", strconv.Itoa(i))
      }
      fmt.Println("Pub!")
    }()

it is _very_ slow to publish the 1000 messages. Nearly 40 seconds!

I had this running and published 1000 messages form a NodeJS client and the subscriber in go got them all within 2 seconds. So I know subscribing runs quickly.

I also tried commenting out the subscriber, ran it with publish only, and it wasn't any faster. Pub is the bottleneck.

Is there something going on that I can fix here? Is this redis client requiring a round trip per publish? I would prefer a fire-and-forget model because the events I am publishing are not critical and do not require any ack or anything.

**Comment by vmihailenco** [comment]
The code you provided works fine for me when it is run locally. There is something wrong with your program, network and/or Redis config.
