### ISSUE TITLE
Blocking one second call BLPop will lose data

### ISSUE THREAD

**Issue by wllenyj** [go-redis/redis#697]
I use three machines to test, running three days. 
sum of push is: 175214+87753+125377 = 388344
sum of pop  is:  129654+129246+129388 = 388288
lost 56 

Code:
``` go
func read() {
    for running == 1 {
        result, err := read_client.BLPop(1*time.Second, READ_KEY).Result()
        if err != nil {
            log.Printf("redis BLPop err. %s === %#v", err, err)
            if err == redis.Nil {
                continue
            }
            if neterr, ok := err.(*net.OpError); ok {
                if neterr.Timeout() {
                    continue
                }
            }
            continue
        }
        atomic.AddInt64(&popn, 1)
        //if result[0] != READ_KEY {
        //  continue
        //}
        mproto := &protocol.MProtocolHeader{}
        err = proto.Unmarshal([]byte(result[1]), mproto)
        if err != nil {
            log.Printf("redis unmarshal err. %s", err)
            continue
        }
        //log.Printf("redis rcv: MsgID: %s", mproto.MsgID)
    }
    quit.Done()
}

func main() {
    // .....

    running = 1
    go read()

    for i := 0; i < 2; i++ {

        quit.Add(1)
        go func() {
            var id uint
            for running == 1 {
                mproto := &protocol.MProtocolHeader{
                    MsgID:   fmt.Sprintf("%d", id),
                    To:      "sh",
                    Payload: bytes.Repeat([]byte("a"), 1024),
                }
                id++
                data, _ := proto.Marshal(mproto)
                if err := PushRedis(data); err == nil {
                    atomic.AddInt64(&pushn, 1)
                }
                time.Sleep(time.Duration(rand.Intn(*sleep)) * time.Millisecond)
            }
            quit.Done()
        }()
    }
    // ...
    log.Printf("push: %d  pop: %d", pushn, popn)
}
```
* First machine:
./lost > lost.log 2>&1 &
result:  
2018/01/22 10:48:07 push: 175214  pop: 129654
* Second:
./lost -n 10000 > lost.log 2>&1 & 
result:  
2018/01/22 10:49:16 push: 87753  pop: 129246
* Third:
nohup ./lost -n 7000 > lost.log 2>&1 &
result:
2018/01/22 10:49:52 push: 125377  pop: 129388

version: v5
code: https://github.com/wllenyj/go-redis-test

**Comment by vmihailenco** [comment]
If you are using network or run program locally on busy PC with low read/write timeouts then data can be lost:
1. clients issues BLPop
2. Redis Server receives BLPop
3. client timeouts waiting for Redis Server response, closes connection and returns the error to the user
4. Redis Server sends response which never reaches the client - data is lost

It also can be that there is a bug in go-redis, but we need a way to reproduce it before we can fix it.

**Comment by vmihailenco** [comment]
Also see https://github.com/go-redis/redis/issues/647 - it was improved in master branch by increasing timeout.

**Comment by wllenyj** [comment]
Thanks
Using the master branch, running three days, it is ok.
