### ISSUE TITLE
strconv.Atoi errors

### ISSUE THREAD

**Issue by jlburkhead** [go-redis/redis#704]
Version: 5.2.9 (a16aeec10ff407b1e7be6dd35797ccf5426ef0f0)

I see this error every so often when making 100s-1000s of concurrent requests with a cluster client. I believe it bubbles up from one of the internal methods to read the response. 

```
strconv.Atoi: parsing "34\r": invalid syntax
strconv.Atoi: parsing "": invalid syntax
```

I searched through issues but didn't see anything related. Is/was this a known issue? I can try upgrading to v6 to see if it still happens, but its a tricky one to repro considering I only see it intermittently when making a ton of concurrent requests.

**Comment by vmihailenco** [comment]
It is likely fixed by https://github.com/go-redis/redis/commit/a8340c6b74299c6521176f26583c020aec5f2b93 in master. Please try to upgrade.
