### ISSUE TITLE
Much memory leak

### ISSUE THREAD

**Issue by Neugls** [go-redis/redis#705]
![image](https://user-images.githubusercontent.com/1432749/35787686-ef206cc0-0a6a-11e8-9c86-7e8b9e06c4d6.png)
Like the picture shows,  internal/proto  package have many memory leak, is something I am using the lib wrong?

**Comment by vmihailenco** [comment]
That picture shows that there are some memory allocations. It says nothing about Go version, go-redis version, is it alloc_space/inuse_space, what program you profile and whether those allocations are needed or not.

I quickly tried to profile `go test -run=NONE -bench=BenchmarkRedisSetGetBytes -benchmem -memprofile=mem.prof` and did not spot anything unexpected. If you still think there are memory leaks please open new issue with details about how I can reproduce them.
