### ISSUE TITLE
timeout not working when no route to host

### ISSUE THREAD

**Issue by crodwell** [go-redis/redis#706]
Using a legit DNS host, but no network route does not appear to honour timeout rules and takes forever to finally return "redis: cannot load cluster slots".

```
package main

import (
	"github.com/go-redis/redis"
	"fmt"
	"time"
)

func main(){
	start := time.Now()
	fmt.Println("trying connection:")
	cc := redis.NewClusterClient(&redis.ClusterOptions{
	    Addrs:     []string{
	    	"www.google.com:7000", 
	    	"www.google.com:7001", 
	    	"www.google.com:7002", 
	    	"www.google.com:7003", 
	    	"www.google.com:7004", 
	    	"www.google.com:7005"},
	    MaxRetries: 2,
	   	MaxRedirects: 16,
	   	DialTimeout: time.Duration(5) * time.Second,
 		ReadTimeout: time.Duration(200) * time.Millisecond,
 		WriteTimeout: time.Duration(200) * time.Millisecond,
		PoolSize: 10,
		PoolTimeout: time.Duration(15000) * time.Millisecond,
		IdleTimeout: time.Duration(15000) * time.Millisecond,
		ReadOnly: true,
		RouteByLatency: true,
	})

	pong, err := cc.Ping().Result()
		
	fmt.Println(time.Since(start))
	fmt.Println(pong)
	fmt.Println(err)
}
```

output:

> trying connection:
> 2m35.738056417s
> 
> redis: cannot load cluster slots

**Comment by crodwell** [comment]
@vmihailenco thanks for working on this, but I don't see it working yet. The latest revision just gives this instead:

> trying connection:
> 2m10.839831105s
> 
> dial tcp 172.217.15.100:7001: i/o timeout

**Comment by vmihailenco** [comment]
You have 16 max redirects and 2 max retries which is 32 attempts with 5 seconds dial timeout which is `32 * 5 = 160` seconds. I would remove max retries and lower dial timeout if you want it to work faster.

**Comment by crodwell** [comment]
Thanks for the explanation! I had presumed max redirect was only for MOVED & ASK, not network errors. It might be advisable to distinguish the two? I'd like to error out quickly when the cluster is down but it seems impossible to do that under 10 secs whilst connecting over the internet.

**Comment by vmihailenco** [comment]
>It might be advisable to distinguish the two?

Perhaps, but it is already too complex and I am reluctant to complicate it further.

>to error out quickly when the cluster is down

go-redis should detect that node is down and stop opening new connections and instead return last error - https://github.com/go-redis/redis/blob/master/internal/pool/pool.go#L102-L104.

**Comment by vmihailenco** [comment]
I also think it makes sense to reduce MaxRedirects from 16 to 8.
