### ISSUE TITLE
Intermittent TxPipeline errors

### ISSUE THREAD

**Issue by tbarbugli** [go-redis/redis#713]
Every now and then I get this sort of errors out while r/w keys using MULTI/EXEC:

```redis: expected '*', but got line "+QUEUED"```

I am using v5 and I did a quick scan on the project just to be sure I am not doing something silly like re-using the pipe.

The code error-ing is equivalent to this:

```go
pipe := redisClient.TxPipeline()
defer pipe.Close()

for i := range keysToGet {
    pipe.Get(key)
}

cmds, err := pipe.Exec()
...
```

Is this a known problem or indicator that I am using the client incorrectly?

**Comment by vmihailenco** [comment]
I did not encounter such errors myself, but v5 is ~ 1 year old so who knows. Try to upgrade and if the error persists try to isolate it.
