### ISSUE TITLE
Cluster: keys(*)  just get one node keys

### ISSUE THREAD

**Issue by zhqqqy** [go-redis/redis#720]
I want to get all keys from redis cluster,so i do this:
`keysCmd := redisClusterClient.Keys("*")`
`fmt.Println(len(keysCmd.Val()))`
but I found,this just get one node keys.

**Comment by vmihailenco** [comment]
That is how Redis Cluster works - it returns keys for the node. To get all keys you should use `ForEachMaster` and https://godoc.org/github.com/go-redis/redis#example-ScanIterator to iterate over keys.

**Comment by zhqqqy** [comment]
oh! I get it ,thank you !
