### ISSUE TITLE
i < 10;  why i max was 10? when all the address was io timeout, this reloadSlots() whill try 10*MaxRetries*connect_timeout

### ISSUE THREAD

**Issue by toontong** [go-redis/redis#724]
https://github.com/go-redis/redis/blob/a16aeec10ff407b1e7be6dd35797ccf5426ef0f0/cluster.go#L360

i < 10;  why i max was 10? when all the address was io timeout, this reloadSlots() whill try 10 X MaxRetries X connect_timeout

**Comment by toontong** [comment]
it will take very long time to try all node on the cluster. when the all node was dis-connect.

**Comment by vmihailenco** [comment]
Current version of the code does `MaxRedirects` retries - https://github.com/go-redis/redis/blob/master/cluster.go#L907-L929. It can be slow (but not slower than processing single command), but I am not sure what do you expect from the cluster which has all nodes down.
