### ISSUE TITLE
LoadUint64 panic on 32 bit architecture

### ISSUE THREAD

**Issue by mwhudson** [go-redis/redis#731]
Hi, 1a4d34448d71983c99178509f18ef683762d4584 introduced a call of LoadUint64 on a field that's only aligned to 32 bits ("loading" in 

```go
type clusterNode struct {
	Client *Client

	latency    uint32 // atomic
	generation uint32
	loading    int64 // atomic
}
```

). This causes a failure on 386, as can be seen in https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic/bionic/i386/g/golang-github-go-redis-redis/20180306_063050_acf45@/log.gz (rather messily, I'm sorry).

A very similar problem to #256.

**Comment by vmihailenco** [comment]
Thanks, added 386 build via `env GOOS=linux GOARCH=386 go test ./...` that reliably catches such errors.
