### ISSUE TITLE
Memory leak using write_buffer.go and reader.go in v5

### ISSUE THREAD

**Issue by amitash1109** [go-redis/redis#732]
In short: github.com/gtforge/driver_online_service/vendor/gopkg.in/redis.v5/internal/proto.(*WriteBuffer).AppendString
and
github.com/gtforge/driver_online_service/vendor/gopkg.in/redis.v5/internal/proto.readN /go/src/github.com/gtforge/driver_online_service/vendor/gopkg.in/redis.v5/internal/proto/reader.go

memory consumption has boosted significantly from few 100MB to 1.6G - 2.5G

**Comment by amitash1109** [comment]
network traffic didn't change

**Comment by amitash1109** [comment]
![screen shot 2018-03-07 at 10 02 57 am](https://user-images.githubusercontent.com/31186545/37080447-f3dbc0ac-21ee-11e8-8e69-270460798ab9.png)

**Comment by amitash1109** [comment]
![screen shot 2018-03-07 at 10 05 50 am](https://user-images.githubusercontent.com/31186545/37080504-29dc8b3c-21ef-11e8-8eb3-106260688c90.png)

**Comment by vmihailenco** [comment]
Try to upgrade to latest version. v5 was not changed for a year - even if there is a bug there is no point in fixing it now.
