### ISSUE TITLE
Define Watch Func in UniversalClient

### ISSUE THREAD

**Issue by rylio** [go-redis/redis#733]
Since `Watch(fn func(*Tx) error, keys ...string) error` is defined for both `*ClusterClient` and `*Client` then this could also be added to the interface for `UniversalClient`. Otherwise if one is using a `UniversalClient` they have to cast to a `*ClusterClient` or `*Client` to call `Watch`. I can submit a pull request, just want to make sure this is valid first.

**Comment by vmihailenco** [comment]
Fine with me - please send a PR.
