### ISSUE TITLE
can't marshal []interface {} (consider implementing encoding.BinaryMarshaler)

### ISSUE THREAD

**Issue by songlong** [go-redis/redis#739]
redis.SAdd("words", "1213")
redis: can't marshal []interface {} (consider implementing encoding.BinaryMarshaler)

**Comment by vmihailenco** [comment]
Your code should be more like `redis.SAdd("words", []interface{}{"1213", "12123"})`.

**Comment by Qianlu5110** [comment]
I want do save one object into redis, but also have this problem.
code:

func SetUser(user UserBean) error {
	key := fmt.Sprintf("user:%s", user.Name)
	_, err := Client().Set(key, user, time.Hour).Result()
	return err
}

**Comment by mauleyzaola** [comment]
You can do two things, choose what works better for you:
1. Implement `encoding.BinaryMarshaler` and `encoding.BinaryUnMarshaler` for your type and Redis will do it automatically all operations
2. Manually marshal/unmarshal to `[]byte` as json and store `[]byte` in Redis

**Comment by odiferousmint** [comment]
> You can do two things, choose what works better for you:
> 
> 1. Implement `encoding.BinaryMarshaler` and `encoding.BinaryUnMarshaler` for your type and Redis will do it automatically all operations
> 2. Manually marshal/unmarshal to `[]byte` as json and store `[]byte` in Redis

Could you provide an example or a reference to an example for each cases?

**Comment by mauleyzaola** [comment]
`encoding.BinaryMarshaler` and `encoding.BinaryUnMarshaler` are interfaces methods that you would need to override in your particular struct.
```
type MyStruct struct{}

func(m *MyStruct)UnmarshalBinary(data []byte) error{
  // convert data to yours, let's assume its json data
  return json.Unmarshal(data, m)
}
```
The second case would be to store as `[]byte` in Redis and manually do the same thing. Mind you I just typed by memory the code above, might have errors. Cheers.

**Comment by odiferousmint** [comment]
Oh, I deleted my message to which you replied. I asked him for an example. Thank you a lot @mauleyzaola :)

**Comment by rjjatson** [comment]
i tried to use eval but still have the same error message after implement binary marshaller and unmarshaler. seems like the 1st solution is not working

**Comment by joeke80215** [comment]
that's worked

```
type MyStruct struct{}

func (m *MyStruct) MarshalBinary() ([]byte, error) {
	return json.Marshal(m)
}
```

**Comment by Turing-Chu** [comment]
it passed when use MyStruct instead of *MyStruct.


https://stackoverflow.com/questions/60925203/cant-marshal-implement-encoding-binarymarshaler-go-redis-sdd-with-multiple

**Comment by spade-zd** [comment]
I just want to cache a simple string into SET,  go-redis wont let me do this.  cause all u guys method not worked for me.
