### ISSUE TITLE
Memory Leak Problem

### ISSUE THREAD

**Issue by Neugls** [go-redis/redis#744]
![deepinscrot-2705](https://user-images.githubusercontent.com/1432749/37500471-a3062646-2904-11e8-93be-9a32344fcf78.png)

The program have run for few days, but it is slow and slower, so, I  found out the reason is memory leak, like the picture shows.

the internal package have many leaks,  How can I fix this?

**Comment by vmihailenco** [comment]
Try to google "golang memory profiling". My understanding of the screenshot is that you program stopped at allocating data - it does not mean there is a leak in go-redis.
