### ISSUE TITLE
Info command: question

### ISSUE THREAD

**Issue by franciscocpg** [go-redis/redis#745]
I have a question about client info implementation.

Since [redis info command](https://redis.io/commands/info) supports only one section why [Client.Info](https://godoc.org/github.com/go-redis/redis#Client.Info) was implemented using varags (`Info(section ...string)`)?

**Comment by vmihailenco** [comment]
Looks like a mistake - do you want to send a PR?

**Comment by franciscocpg** [comment]
The problem is that it's going to be a breaking change.

To get all info (without filtering sections) clients of this library may be using `client.Info()`. If I change `Info(section ...string)` to `Info(section string)` the code `client.Info()` is not going to compile anymore.
Clients should start to use `client.Info("")` instead to achieve the same results.

If the breaking change is not a problem for you I would appreciate to send a PR.

**Comment by vmihailenco** [comment]
No, you are right - it is done that way to support `Info()` and `Info(section)`. Closing.

**Comment by mikefaraponov** [comment]
If you are searching for a tool to parse go-redis/redis Info output look for [microredis/tools](https://github.com/microredis/tools)
