### ISSUE TITLE
option to persist object idle times/lru 

### ISSUE THREAD

**Issue by jonathandelanders** [go-redis/redis#749]
Please don't ask me why i need this...     I also need it to replicate to the slaves.     If this was an option in redis.conf it would make me really happy.   I also would like to add that I am very impressed with redis cluster 3.x from an operational perspective.

I realize that the implementation of this is probably wonky,  the idle time would not need to be exactly the same on the slave.   if it were within even 5 seconds of each other it would be ok.

**Comment by vmihailenco** [comment]
I don't understand what you are asking for. What is object idle times/lru? What go-redis is expected to do?

**Comment by jonathandelanders** [comment]
man im such an idiot this is the wrong repository.... closing
