### ISSUE TITLE
Incr() method lost new generated values in high concurrency and high load condition

### ISSUE THREAD

**Issue by Kongoole** [go-redis/redis#751]
Tested with `ab`, use following command
```
ab -c 1000 -n 10000 http://localhost:8080/incr
```
route to following function
```
func incr(w http.ResponseWriter, r *http.Request) {
	val,_ := client.Incr(primaryKey).Result()
	//client.Ping().Result()
	allPrimaryKeys = append(allPrimaryKeys, val)
}
```
I expected there would be 10000 elements in `allPrimaryKeys` slice, but got 9992, 8 lost.
I sorted and printed out all elements in `allPrimaryKeys`, found that
```
...
[39] => 40
[40] => 41    <--- from here 42 lost
[41] => 43
[42] => 44
...
[1280] => 1282
[1281] => 1283 <--- from here 1284 lost
[1282] => 1285
[1283] => 1286
...
[9989] => 9998
[9990] => 9999
[9991] => 10000
```

i am new to Golang using this pkg to test my solution, but failed, looks like `redis` did execute `incr` command, but this pkg didn't return those losted new generated values. Thanks for helping :)

**Comment by vmihailenco** [comment]
You can start with handling error returned by `client.Incr(primaryKey).Result()`.

**Comment by Kongoole** [comment]
Thanks. 
Problem solved, I should have add lock to `allPrimaryKeys` slice, pkg works perfectly.
