### ISSUE TITLE
Disable Sentinel logging

### ISSUE THREAD

**Issue by tboyko** [go-redis/redis#752]
What is the best way to disable the log messages that appear when connecting with Redis Sentinel? It seems strange that the library outputs these messages whereas it doesn't for regular redis connections.

	redis: 2018/04/12 11:13:35 sentinel.go:234: sentinel: new master="mymaster" addr="[REMOVED]:6379"

**Comment by vmihailenco** [comment]
You can use `redis.SetLogger()` to set custom logger.
