### ISSUE TITLE
Random MOVED errors.

### ISSUE THREAD

**Issue by Hamper** [go-redis/redis#753]
I use `MaxRedirects: 1` in cluster client and redis 4.0.2, and sometimes see MOVED errors, but `cluster nodes` output not changes, cluster not resharded.

**Comment by vmihailenco** [comment]
Are you able to isolate the problem and write a program that reproduces the problem?

**Comment by Hamper** [comment]
I will try to isolate, but it's very difficult, with total load of 300000 rps I see about 3-10 errors per second.

**Comment by Hamper** [comment]
I think that I get this error because with `MaxRedirects: 1` if first request is RetryableError than client select random node and that node returns MOVED error to first failed node. In this case MOVED error message looks unclear. You can close issue if you think that this behavior is right.

**Comment by sqaxomonophonen** [comment]
We're seeing this too. Here's a simple program to reproduce it (it simply GETs random keys concurrently):

```golang
package main

import "github.com/go-redis/redis"
import "math/rand"
import "fmt"

func main() {
        client := redis.NewClusterClient(&redis.ClusterOptions{
                Addrs:    []string{":7000"},
                PoolSize: 16,
        })

        const concurrency = 10

        for i := 0; i < concurrency; i++ {
                go func() {
                        for {
                                rnd := ""
                                for i := 0; i < 10; i++ {
                                        rnd += string(rune(int(rune('a')) + rand.Intn(int(rune('z') - rune('a')))))
                                }
                                fmt.Printf("GET %s\n", rnd)
                                err := client.Get(rnd).Err()
                                if err != nil && err != redis.Nil {
                                        panic(err)
                                }
                        }
                }()
        }

        select{} // sleep
}
```

If I set `const concurrency = 1` the error doesn't happen, so it seems to be a bug with multiple goroutines using the same `ClusterClient`.

**Comment by sqaxomonophonen** [comment]
My test program still fails after commit 092971361bcfb3fd8c0cb21d55f959ddd5cecbca

**Comment by vmihailenco** [comment]
I did not try to run your program, because there is nothing special in it and I can't believe that it is broken because of concurrency (who does not use Redis concurrently?). Also it is obvious that you have a different problem so it is better to open new issue.

Are you able to reproduce the problem using test suite? E.g. there are concurrent tests in https://github.com/go-redis/redis/blob/master/race_test.go#L288-L343 and lots of cluster tests https://github.com/go-redis/redis/blob/master/cluster_test.go
