### ISSUE TITLE
Dial redis cluster via Load balancer

### ISSUE THREAD

**Issue by zhangruiskyline** [go-redis/redis#755]
Hi 

I am trying to connect to redis cluster in Azure redis service。 Azure redis uses Load balancer as its external URL, and each nodes have same IP but different ports(basically via NAT way to connect). so in this case, what should be correct dial function. should I dial to "`redisURL:6380`" which is load balancer or directly to nodes like "`redisURL:1500x`" ?

Thanks
Rui

**Comment by vmihailenco** [comment]
There is no any special support for Azure and its load balancer (I have no ideas what it is and how it works). So I guess the only option is to use nodes addresses.
