### ISSUE TITLE
enable TLS dial for redis cluster

### ISSUE THREAD

**Issue by zhangruiskyline** [go-redis/redis#756]
I found out the `redis.ClusterOptions` dose not have TLS dial option, how can we add TLS dial in this case?

Thanks
Rui

**Comment by vmihailenco** [comment]
I think you need to copy `TLSConfig` option to `ClusterOptions` and update https://github.com/go-redis/redis/blob/master/cluster.go#L99-L120. Can you try it and send PR?

**Comment by zhangruiskyline** [comment]
what is minimum default setup I should use for SSL config? if I just want to enable it

**Comment by vmihailenco** [comment]
I would try

```
TLSConfig: &tls.Config{
	InsecureSkipVerify: true,
},
```

**Comment by DeadlySurgeon** [comment]
> I would try
> 
> ```
> TLSConfig: &tls.Config{
> 	InsecureSkipVerify: true,
> },
> ```

To anyone looking to do this, make sure you're aware that in doing so a TLS cert will not be verified, meaning that if the initial connection is not secure, you're going to have a bad day. 

A minimum TLS config should look similar to this:
```go
TLSConfig: &tls.Config{
    MinVersion: tls.VersionTLS12,
},
```

If you're using private certs, then you're going to have to do more to specify them in the `tls.Config` object, but you should not use `InsecureSkipVerify` unless you're running in dev, and even then keeping it out of the codebase is a good idea so it isn't accidentally enabled.
