### ISSUE TITLE
The scan can‘t return all keys

### ISSUE THREAD

**Issue by forthe2008** [go-redis/redis#758]
I use the scan to get all match keys, but lost some key depend on the count parameter.

I have 100000 keys。
1.count:100
&main.Config{InfluxdbAddr:"http://127.0.0.1:8086", InfluxdbUsername:"root", InfluxdbPassword:"root", InfluxdbDatabase:"test", InfluxdbMeasurement:"usage", InfluxdbTimeout:600, RedisAddrs:[]string{"10.0.5.108:4000"}, MasterName:"master00", RedisCount:100}
sum: 99971

2.count:1000
[root@localhost usage_dump]# ./usage_dump 
&main.Config{InfluxdbAddr:"http://127.0.0.1:8086", InfluxdbUsername:"root", InfluxdbPassword:"root", InfluxdbDatabase:"test", InfluxdbMeasurement:"usage", InfluxdbTimeout:600, RedisAddrs:[]string{"10.0.5.108:4000"}, MasterName:"master00", RedisCount:1000}
sum: 99472

3.count:5000
[root@localhost usage_dump]# ./usage_dump 
&main.Config{InfluxdbAddr:"http://127.0.0.1:8086", InfluxdbUsername:"root", InfluxdbPassword:"root", InfluxdbDatabase:"test", InfluxdbMeasurement:"usage", InfluxdbTimeout:600, RedisAddrs:[]string{"10.0.5.108:4000"}, MasterName:"master00", RedisCount:5000}
sum: 98538

4.count:10000
[root@localhost usage_dump]# ./usage_dump 
&main.Config{InfluxdbAddr:"http://127.0.0.1:8086", InfluxdbUsername:"root", InfluxdbPassword:"root", InfluxdbDatabase:"test", InfluxdbMeasurement:"usage", InfluxdbTimeout:600, RedisAddrs:[]string{"10.0.5.108:4000"}, MasterName:"master00", RedisCount:10000}
sum: 98535

With different count parameter , get the different  keys

some code:
```
func ScanF(db *redis.Client, match string, count int64, callBack func(keys []string) error) error {
	var cursor uint64
	for {
		var keys []string
		var err error
		keys, cursor, err = db.Scan(cursor, match, count).Result()
		if err != nil {
			return err
		}
		if cursor == 0 {
			return nil
		}
		if len(keys) == 0 {
			log.Printf("[INFO] empty keys\n")
			continue
		}
		err = callBack(keys)
		if err != nil {
			return err
		}
	}
}
```

**Comment by vmihailenco** [comment]
Please include a program that can be run and that reproduces the problem.
