### ISSUE TITLE
Sentinel - New Failover Client: Get master before performing a set

### ISSUE THREAD

**Issue by sunny-udhani** [go-redis/redis#759]
Can't seem to find a way where after creating a failover client with 5 sentinel addresses, I would be able to connect to master of the sentinels and execute commands on the same. I need to find the master first and then execute the command on it because I'm trying to test the partition tolerance of redis sentinel environment. If you can publish an example for the same, it would be very helpful.

**Comment by vmihailenco** [comment]
If all you need is to execute some commands on specific Redis Server then you should use `NewClient` on that specific server. Failover client does not allow to manually pick the master.

**Comment by sunny-udhani** [comment]
So suppose I have a replicated Cluster of redis servers and sentinels and I create a FailoverClient passing addresses of all the sentinels, then I don't have any way to find the master out of them? If only I can get the address of the master out of this list of sentinels I would be able to create a Client and execute the commands on it. I went through the functionality of sentinel.go which has the potential but had to make many changes and even then couldn't make it work.

**Comment by vmihailenco** [comment]
`FailoverClient` executes commands on the master so I don't understand what the problem is.

**Comment by sunny-udhani** [comment]
I was able to execute the commands on the master everytime with the FailoverClient itself. But would love to see the functionality to get master's address from FailoverClient.
