### ISSUE TITLE
New Release with sentinel TLSOptions

### ISSUE THREAD

**Issue by javier-sanz** [go-redis/redis#770]
First of all sorry for using a Github issue for this but I could not find any other way to make questions to the community. If there is any other way please advice.

We have been recently testing the library using TLS as a transport layer and everything went smoothly. The thing is that in some of our systems we use the sentinel FailOver client and the lib did not support TLSOptions on those clients. But about two weeks ago you added support for that. So my question is: when are you planing to make a release so we can benefit from those changes?

Thanks

**Comment by vmihailenco** [comment]
I've tagged v6.11.0 with all recent changes
