### ISSUE TITLE
Can we introduce an option minIdleConnections ?

### ISSUE THREAD

**Issue by darkpssngr** [go-redis/redis#772]
Issue
I'm using redis-labs. The DNS resolution time for the endpoints they give are very high in regions other than US. Currently my service does not have that much traffic due to which idle connections are getting killed and new connections are spawned everytime a new request comes in. I tried turning off the IdleConnectionFrequencCheck by setting it to zero and using a custom dialer which sends keep-alive. But for some reason these connections get closed after sometime. not sure why? upon inspection of tcp dump we found that the termination is intiated by the client and not the server.

I know this problem needs to be identified and fixed but was also wondering if we could have an option which lets us specify minimum idle connections so that we always have some connections on standby when there are spikes. Or is there any way we can avoid this problem?

**Comment by vmihailenco** [comment]
`IdleCheckFrequency` must be set to -1 to disable it. Zero value is the default value.

Overall I think `minIdleConnections` is a good idea and I'd like to see it supported too.

**Comment by darkpssngr** [comment]
Sorry. I've set the IdleCheckFrequency to -1 only.

**Comment by vmihailenco** [comment]
The code is at https://github.com/go-redis/redis/blob/master/internal/pool/pool.go#L91-L93 if you want to check yourself. Connection is also closed by the client in case of timeout / bad state.

**Comment by vmihailenco** [comment]
See https://github.com/go-redis/redis/pull/778/files - it is WIP, but feel free to try it.

**Comment by darkpssngr** [comment]
So the thing is I'm using my custom dialer which creates connection with keep-alive. I see keep alive msgs being sent and its being ACKed as well by the server. Out of the blue a FIN req is sent by the client and the connection is closed. Its a proper close, not initiated by the server or not something because of a bad state. Not sure whats happening.

**Comment by vmihailenco** [comment]
You should also know that PubSub closes the connection when subscription is closed.

**Comment by ginuerzh** [comment]
does it mean that the `IdleTimeout` option also should be set to `-1` to avoid closing idle connections?

**Comment by darkpssngr** [comment]
Yes. If its not set, it defaults to 5mins. So, even though the reaper does not kill it, the connection will be discarding when asking for a new connection.
https://github.com/go-redis/redis/blob/master/internal/pool/pool.go#L185

**Comment by vmihailenco** [comment]
Master branch has `MinIdleConns` option that should address this problem.

**Comment by xianglinghui** [comment]
@vmihailenco MinIdleConns option will let all redis node have at least MinIdleConns connections on standby even though some node never be visited，like the slave node，then the client will have a lot connections.
I think the MinIdleConns option should just work on "reapStaleConn" step，not the "NewConnPool" and "Get Conn" step.

**Comment by xianglinghui** [comment]
@vmihailenco Our service has a traffic peak every hour，we expected the number of connections in the pool can maintain a stable value，so we set the MinIdleConns a little big，like 50. 

I can set IdleTimeout to solve this problem，but in the morning the total number of connections will continued to decline，and at 6:00 there may be a sudden traffic peak.
