### ISSUE TITLE
Is there a way to interface with sentinelClient?

### ISSUE THREAD

**Issue by jwatroba** [go-redis/redis#777]
I'm attempting to write a redis health check which would utilize info off of the "sentinel master mymaster" command against sentinel, but I can't figure out how to use this library to run commands against the sentinel and not the actual redis master itself. Is there any way to do this with go-redis? I see methods that look like they do this, but they don't seem public and I can't access them. 
Thanks.

**Comment by vmihailenco** [comment]
You can connection to the Sentinel using `NewClient` and execute custom command via https://godoc.org/github.com/go-redis/redis. I also exported https://godoc.org/github.com/go-redis/redis#SentinelClient, but it does not have many commands implemented.
