### ISSUE TITLE
cluster about the newClusterState

### ISSUE THREAD

**Issue by yiippee** [go-redis/redis#783]
Thanks for your go-redis.
When I run redis cluters in different processes on a computer,their ports are different,but ip is the same 127.0.0.1.
In the function newClusterState, you write the code: 		
                      if !isLoopbackOrigin && isLoopbackAddr(addr) {
				addr = origin
			} 
So whe i get a key I can not find the node directly,and need moved. Why you check LoopbackOrigin?Thank you.
I am a Chinese , please forgive my poor English.Thanks.

**Comment by vmihailenco** [comment]
See https://github.com/go-redis/redis/pull/781 - this should be fixed in master.
