### ISSUE TITLE
Sentinel client throws errors during failover. Incorrect usage?

### ISSUE THREAD

**Issue by tboyko** [go-redis/redis#784]
When running `sentinel failover mymaster`, our service which utilizes `NewFailoverClient` returns the following errors:

- use of closed network connection
- EOF
- READONLY You can't write against a read only slave.

Is this typical or an indicator of an issue with our `NewFailoverClient` configuration? What is the proper way to recover from this type of error? I was under the impression that the library automatically handled this but perhaps I'm mistaken.

**Comment by vmihailenco** [comment]
Does it recover with time? It is expected to return errors during short period of Redis failover recovering.

**Comment by tboyko** [comment]
Our current implementation causes the application to crash. How do you suggest recovering? We're using `BRPop` in a loop. Should we just try again or is there client reconnect operations we should perform first?

**Comment by vmihailenco** [comment]
You should retry operation later. `FailoverClient` should start using new master automatically.
