### ISSUE TITLE
Better documentation on performing master failover using NewFailoverClient

### ISSUE THREAD

**Issue by crimsonfaith91** [go-redis/redis#789]
There is no clear documentation on how to perform master failover using `NewFailoverClient`.

A failover client can be set up via:
```
import redisclient "github.com/go-redis/redis"
......

failoverClient := redisclient.NewFailoverClient(&redisclient.FailoverOptions{
    MasterName   : <server-master-name>, //or sentinel name?
    SentinelAddrs: []string{fmt.Sprintf("%s:%d", <sentinel-IP>, <sentinel-port>)},
    Password     : <password-to-access-server>, //or sentinel password?
    DB           : 0,
})
```

After setting up the failover client, I could not find any method to trigger failover using the client. Does `failoverClient.Ping()` automatically trigger the failover?

**Comment by crimsonfaith91** [comment]
@vmihailenco Not sure you can shed some lights on my question. Thanks in advance!

**Comment by vmihailenco** [comment]
Failover is triggered by Redis Sentinel via pub/sub channel. See https://redis.io/topics/sentinel docs for details how sentinel works.
