### ISSUE TITLE
Sentinel connection refused

### ISSUE THREAD

**Issue by herkyl** [go-redis/redis#806]
I am testing out redis sentinel. So I have two redis servers and one sentinel on my local machine. When I shut down the master server and sentinel starts promoting the new master the go program crashes.

`:6380` was the master server and `:6379` was promoted to the new master
```
dial tcp 127.0.0.1:6380: connect: connection refused
```

Besides using `redis.NewFailoverClient`, do I need to do anything else in my app-code to make it resilient to redis server crashes and sentinel failovers? (I got the impression from docs that this was all I needed). Does `go-redis` queue events while the connection is down?

**Comment by vmihailenco** [comment]
`FailoverClient` should automatically re-connect to the master, but that does not happen immediately. Go program should not crash as long as you don't use `panic(err)`.

>Does go-redis queue events while the connection is down?

No, it does not.

**Comment by herkyl** [comment]
Thanks!
