### ISSUE TITLE
how to delete redis with prefix ?

### ISSUE THREAD

**Issue by youcandoit95** [go-redis/redis#807]
can somebody tell me how to delete redis key with prefix ?

example i have redis key :
category:book
category:movie

i want to delete all redis key with prefix category*

thanks

**Comment by jakey766** [comment]
use scan + del

**Comment by youcandoit95** [comment]
@jakey766 can you give me sample golang script ?

please .. thank you

**Comment by vmihailenco** [comment]
Something like:

```
iter := client.Scan(0, "prefix*", 0).Iterator()
for iter.Next() {
    err := client.Del(iter.Val()).Err()
    if err != nil { panic(err) }
}
if err := iter.Err(); err != nil {
    panic(err)
}
```

**Comment by bert82503** [comment]
For Java, use `RedisCacheWriter.clean(cacheName, keyPattern)` in `spring-data-redis-2.7.16`, that using `SCAN(10/20) + DEL(allMatchKeys)` redis commands.

```java
RedisCacheWriter redisCacheWriter = RedisCacheWriter.nonLockingRedisCacheWriter(
                redisConnectionFactory, BatchStrategies.scan(10));
redisCacheWriter.clean(cacheName, keyPattern.getBytes(StandardCharsets.UTF_8));
```
