### ISSUE TITLE
feature request: add OnClose hook to allow writing customized load balance dialer

### ISSUE THREAD

**Issue by EMayej** [go-redis/redis#809]
I have 10 redis slaves mapped to the same dns name.
Right now it is possible to use `Dialer` to ensure that new connections are evenly distributed to slave servers. However, we don't know which connections are get idle and closed. Thus we don't know which server has less connections after a while.

Is it possible to add `OnClose` hook so we know which connection(especially the IP and port) will be closed? So we can write a customized dialer to ensure new connections are connected to less stressed server. Also we could write customized stats to export how many connections are connected to a specific server.

**Comment by vmihailenco** [comment]
Are we talking about cluster client? If so why not to use `RouteRandomly` or `RouteByLatency` that should load balance read-only command to the slaves?

**Comment by EMayej** [comment]
Can't use cluster here because there are too many reads to same keys. Just normal slaves, each holds all keys. 

We decide to assign a dedicated port for each Redis slave, and run `netstat` regularly to capture connections made to each slave. 

Another option is create one client for each slave, but we may sometimes add new slave or destroy old slaves, so that's not working easily here.

Thanks for your reply.

**Comment by vmihailenco** [comment]
I still don't understand why cluster client does not work for you. As I said go-redis should be able to load balance read-only traffic. Is the problem in go-redis client implementation or Redis Cluster itself?

I also don't understand your setup. I guess you have 2 redis client instances:
- first is master which you use to set keys
- second is many slaves which you use to get keys

Am I right? Even without using Redis Cluster you should be able to do something like:

```
	loadClusterSlots := func() ([]redis.ClusterSlot, error) {
		slots := []redis.ClusterSlot{
			// First node with 1 master and 1 slave.
			{
				Start: 0,
				End:   16383,
				Nodes: []redis.ClusterNode{{
					Addr: ":7000", // master
				}, {
					Addr: ":8000", // 1st slave
				}, {
					Addr: ":8001", // 2nd slave
				}, {
					Addr: ":8002", // 3rd slave
				}},
			},
		}
		return slots, nil
	}

	client := redis.NewClusterClient(&redis.ClusterOptions{
		ClusterSlots:  loadClusterSlots,
		RouteRandomly: true,
	})

	client.Set() // automatically routed to master
	client.Get() // automatically routed to random slave
```

See https://godoc.org/github.com/go-redis/redis#example-NewClusterClient--ManualSetup

**Comment by EMayej** [comment]
Thanks for the cluster client usage.

All I have is a dns name `read-only.redis.mycompany.com`.
Behind that dns name are a lot of slave Redis, whose IPs may change occasionally.

`RouterRandomly` randomly chooses a node, but in my case all connections are in the same node (have to use the dns name, can't use IPs directly)

I've tried cluster client but got this err `ERR This instance has cluster support disabled`.
Maybe we need master node here but I don't have that node.

Currently I'm trying to collect more information to see if I really need to build a load balancer in client code.
