### ISSUE TITLE
Is there any plans to supported timeout?

### ISSUE THREAD

**Issue by chzyer** [go-redis/redis#81]
We are working on an bad network now. Any packet can be lost very easy.
So, we need a timeout-kind mechanism to prevent it blocking forever(or very long time).
I know I can wrap the network request into a goroutine and use `select` to specified a timeout, but I think this way is too weird! The simplest way is call the `Conn.SetDeadline()` on `baseClient`.

If you guys would accept that way I suggested, I will pull my request as soon as possible. :)

**Comment by chzyer** [comment]
@vmihailenco

**Comment by vmihailenco** [comment]
Hi,

You can set ReadTimeout on http://godoc.org/gopkg.in/redis.v2#Options and client will call `SetDeadline` for you.
