### ISSUE TITLE
Example using conn to connect to redis server

### ISSUE THREAD

**Issue by palash25** [go-redis/redis#813]
Hi I have been wanting to use this package in a project to create a redis adaptor to transfer data from redis to elasticsearch

Redigo has a [Dial](https://godoc.org/github.com/gomodule/redigo/redis#Conn) func to connect to redis that returns a `Conn` struct

I want a way to connect to redis which returns a `Conn` struct so that I can keep a track of the connection as a property of my struct (like `redisClient.conn = func () Conn`) and close it when I want

Pardon me if this is the wrong place to ask and the question seems stupid but I am new to Go and redis :sweat_smile:

**Comment by palash25** [comment]
I actually found this function [`newConn`](https://github.com/go-redis/redis/blob/master/redis.go#L465) but its not mentioned there in godoc. Why is that?

I think this would satisfy my usecase. Still an example for this would help.

**Comment by vmihailenco** [comment]
Why do you need to keep track of the connection? What that allows you to do that is not possible otherwise?
