### ISSUE TITLE
Cluster Nodes and Cluster Meet Not Functional

### ISSUE THREAD

**Issue by yonatonreid** [go-redis/redis#828]
I have the following code:

     for range of ports {
            address:=net.JoinHostPort("127.0.0.1",port)
		client:=startRedisClient(address,"",0)
		if i==0{
               // first port we use to gossip
	           primaryClient=client
		} else {
                // meet and greet
		    primaryClient.ClusterMeet("127.0.0.1",port)			
            }
      }

where primary client is the first client established out of all cluster nodes.

Here's my `startRedisClient` Code

	func startRedisClient(address string,password string,db int) *redis.Client{
		client:=redis.NewClient(&redis.Options{
			Addr:address,
			Password:password,
			DB:db,
	    })
	    defer client.Close()
	    _,err := client.Ping().Result()
	    CheckErrorf(err,"Redis Ping Pong Issue")
	    return client
	}

The result error is:

    (*redis.StatusCmd)(0xc4200d8240)(cluster meet 127.0.0.1 7002: redis: client is closed)
    (*redis.StatusCmd)(0xc4200d8440)(cluster meet 127.0.0.1 7003: redis: client is closed)

Furthermore, I have : the following code:

    Dump(primaryClient.ClusterNodes())  

The result error is:

    (*redis.StringCmd)(0xc4200de140)(cluster nodes: redis: client is closed)
  
I know my cluster is healthy and functional, as you can see here:

 	localhost:7001> CLUSTER NODES
	7cd5374589e8c4d90628fcd6fbc053f35bd54ca3 127.0.0.1:7002@17002 master - 0 1532545045567 2 connected 5461-10922
	b7ad15d0f840ca6d285ed249b5ebd95ccef5659f 127.0.0.1:7001@17001 myself,master - 0 1532545044000 1 connected 0-5460
	534e867c7e8309f6f9b34de04a5c9b7ec16c9890 127.0.0.1:7003@17003 master - 0 1532545045000 3 connected 10923-16383
	dea5e9c26cefb5f42754f4939ca773ac93bd9db6 127.0.0.1:7004@17004 slave b7ad15d0f840ca6d285ed249b5ebd95ccef5659f 0 1532545044000 4 connected
	2a94929a2ad12eba048c1e01c0bcb2aa96ff8e25 127.0.0.1:7006@17006 slave 534e867c7e8309f6f9b34de04a5c9b7ec16c9890 0 1532545045567 6 connected
	e90ae23889d1de24bf6d8ca1205f804788089244 127.0.0.1:7005@17005 slave 7cd5374589e8c4d90628fcd6fbc053f35bd54ca3 0 1532545044565 5 connected

**Comment by SenZhangAI** [comment]
don't  defer client.Close() in startRedisCluster()
