### ISSUE TITLE
Can WrapProcess support more middlewares like https://github.com/gin-gonic/gin ?

### ISSUE THREAD

**Issue by kaka19ace** [go-redis/redis#831]
Hi, i find WrapProcess is a good instrument way to handle my custom metrics, event collect, authorization.  
But WrapProcess just support only one function, i must wrap many custom logic in one function  and call WrapProcess. 

Maybe there is a better way  with function slice as args to WrapProcess, like gin middleware design :)

**Comment by vmihailenco** [comment]
Hi,

Since you can implement "gin middleware design" yourself in your wrapper I don't think it is worth it to break existing design. You can wrap a wrapper to get some kind of chaining from existing API.
