### ISSUE TITLE
Redis EOF after a period of time - probably due to timeout

### ISSUE THREAD

**Issue by robertmircea** [go-redis/redis#84]
Hello,

While running in production an app which uses go-redis library, we observed that the first request to Redis after a longer period of inactivity fails. It seems that the connection "dies" if unused with err = EOF.

What is the suggested mechanism to re-connect transparently and to prevent failure for the failing initial request? Can the library auto-reconnect in case of failed connection?

The code is super-simple. It does a MGET command for several keys. Redis connection is initialized using:

```go
func InitRedis(host string, db int64) {
    client = redis.NewClient(&redis.Options{
        Network:"tcp4",
        Addr: host,
        DB: db,
    })
}

//request to get
  v, err := client.MGet("cp:"+date, "ob:" + date).Result()
    if(err!=nil || err == redis.Nil){
        log.Println("Error while getting Redis keys: ", err)
        panic(err)
    }

```

Thanks,
Robert

**Comment by vmihailenco** [comment]
Hi,

go-redis detects broken connection, removes it from the pool and replaces it with fresh connection. go-redis currently does not auth-retry failed operation, but this is going to be address in redis.v3. @dim already added auto-retry to the Redis Cluster client and I will port required changes to the plain client too.

**Comment by dmichael** [comment]
I am using redis.v3 and getting the same EOF error from timed out connections on a non-clustered client. Is there a particular syntax I need to use to get this retry behavior?

**Comment by dmichael** [comment]
Just wanted to follow up on the last comment. Looked through the lib and in the Options struct there was the following comment

```go
	// The maximum number of retries before giving up.
	// Default is to not retry failed commands.
	MaxRetries int
```

So it looks like the solution to this is to make sure you are configuring this something like:

```go
        client := redis.NewClient(&redis.Options{
		Addr:     u.Host,
		Password: p,
		DB:       0, // use default DB
		MaxRetries: 2,
	})
```

**Comment by vmihailenco** [comment]
Do you use non-zero `timeout` setting on your redis-server? Then you should use `IdleTimeout` option smaller than `timeout`, e.g.:

```
client := redis.NewClient(&redis.Options{
    IdleTimeout: 5*time.Minute,
})
```

**Comment by dmichael** [comment]
Thanks @vmihailenco - I am also using a timeout on the server and will adjust the client accordingly.

**Comment by vmihailenco** [comment]
Cool, I believe you don't need retries then. E.g. I don't use retries and don't see EOF in production.
