### ISSUE TITLE
EOF erorrs from client 

### ISSUE THREAD

**Issue by mikhailsizov** [go-redis/redis#846]
Hi, guys!

I faced with the fully similar issue with [this topic](https://github.com/go-redis/redis/issues/84) but in my case I'm not using a timeout option on the server (using a default zero value - that mean the server doesn't close a idle connections), and client using a default 5 min timeout. But some times (probably every 20-30 sec) in prod env client returns a EOF error. As I understood EOF appears in case when server has closed a connection, but client is still not OR when connection was closed by network devices between the client and server.
I've tried to set `MaxRetries = 2`, `ReadTimeout = 15 sec` but it was not helpful.

So, my questions is:
- is it safety to store redis client in global variable and simultaneously use it in different request handles? Could it leads to overflow a pool? What would happen then? e.g.
```
var cacheProviderInstance CacheProvider
var cacheProviderInstanceOnce sync.Once

func GetCacheProvider() CacheProvider {
         cacheProviderInstanceOnce.Do(func() {
		cacheProviderInstance, _ = newRedisClient()
	})
        return cacheProviderInstance
}

func newRedisClient() (*redis.Client, error) {
	client := redis.NewClient(&redis.Options{
		Addr:       redisHost,
		Password:   edisPassword,
		DB:         redisDB,
		MaxRetries: 2,
	})

	if _, err := client.Ping().Result(); err != nil {
		client.Close() // is in necessary? could it leads to increasing of memory usage?
		return nil, err
	}
	return client, nil
}
```
- what is the reasons of EOF error could be? 
- what is the suggested way to re-connect and to avoid fails for the initial request? 

Thanks, 
Mike

**Comment by vmihailenco** [comment]
Make sure you are using latest version. Especially v6.13 has KeepAlive enabled by default. Perhaps you need to tweak on Go/OS level. Also check following options:
- CONFIG GET timeout
- Options.IdleTimeout and Options.IdleCheckTimeout
- Options.MaxRetries

But overall I would start with trying to isolate & reproduce this problem using small app. EOF every 30 seconds suggests you are doing something very wrong or network is very unreliable. I wonder what is the latency of PING command?

>is it safety to store redis client in global variable and simultaneously use it in different request handles? 

Yes, that is what you expected to do - create one instance and use it for the app lifetime.

>Could it leads to overflow a pool? What would happen then? e.g.

When there are no connections in the pool app will wait for a free connection and return timeout after Options.PoolTimeout.

>client.Close() // is in necessary? could it leads to increasing of memory usage?

Client is unusable after Close - you will get `client is closed` errors afterwards.

>what is the suggested way to re-connect and to avoid fails for the initial request?

It should happen automatically - you don't need to handle it.

**Comment by arxdsilva** [comment]
EOF sample

tool used: https://github.com/pedrolopesme/call-it
code used: https://github.com/levpay/prest
redis: github.com/go-redis/redis v6.15.1

![eof](https://user-images.githubusercontent.com/9372503/53346498-e31d4500-38f5-11e9-80e3-54cb003f3e76.gif)

**Comment by sneerin** [comment]
were you able to solve that?

**Comment by arxdsilva** [comment]
> were you able to solve that?

https://github.com/levpay/surl/pull/3/files

**Comment by Alfex4936** [comment]
mine was TLS error

`TLSConfig:  &tls.Config{InsecureSkipVerify: true}`

**Comment by mu6m** [comment]
try Alfex4936 answer
