### ISSUE TITLE
Sorted set commands returning empty lists

### ISSUE THREAD

**Issue by palash25** [go-redis/redis#847]
All the sorted set commands are giving me empty lists whereas when I run the same command using redis-cli it works.

I am trying something like `zset, cursor, err := c.conn.ZScan("new", 0, "", 10).Result()` where `c.conn` is a redis client.

```go
type Client struct {
	conn *redis.Client
}
```

Other functions like `Scan` and `SMembers` are working and giving the desired result but the sorted set commands are always returning empty lists. Can someone please check whether this is reproducable or not

**Comment by vmihailenco** [comment]
There is a [test](https://github.com/go-redis/redis/blob/master/commands_test.go#L777-L790) for `ZScan` so this looks like a problem on your side.
