### ISSUE TITLE
what the best way to connect multiple database

### ISSUE THREAD

**Issue by jiangytcn** [go-redis/redis#850]
I'd like to know what's the best way to connect multiple database of a same ~redis cluster~  standalone redis server

Thanks

**Comment by vmihailenco** [comment]
Please elaborate. It sounds like you want to `SELECT` database, but Redis Cluster does not support database selection.

**Comment by jiangytcn** [comment]
thanks @vmihailenco , actually I want to know what the best way to utilize this golang client to use `SELECT` functionality, right now, I maintain a connection map, the element in the map is the different connection to database, don't know whether this a proper way.

**Comment by jiangytcn** [comment]
btw, the redis is a standalone server

**Comment by vmihailenco** [comment]
I believe using multiple databases (SELECT 0/1/2/3) from single app is an anti-pattern and the best way is to not do it. But I may be wrong. Anyway I don't think go-redis has anything to suggest here.
