### ISSUE TITLE
Listening to cluster:slots migrations for pubsub

### ISSUE THREAD

**Issue by andrewarrow** [go-redis/redis#851]
Hello, as I understand pubsub with cluster I need to:

1. Given a channel, find the the node that owns the hash slot.
2. Subscribe to that node and also to `cluster:slots` to detect migrations.
3. Upon slot migration, subscribe to the channel on the new node and keep the old connection open.
4. Forward messages to the application from the old connection until it closes and remember those messages.
5. When migration is complete and the old connection closed, forward messages from the new connection, trimming the remembered messages from the first connection

Does go-redis do this for me already? I was looking through the cluster.go code and I didn’t see this logic specfically. Thanks!

**Comment by vmihailenco** [comment]
No, it does not do that. Where can I find docs on `cluster:slots` channel? I can't google anything related.

**Comment by andrewarrow** [comment]
I was wrong about this, closing and see 
https://stackoverflow.com/questions/52048598/is-there-a-golang-redis-client-that-auto-detects-new-shards-for-pubsub/52054648 for details. Thanks.

**Comment by andrewarrow** [comment]
Also latest info on when/if redis will do this here: 
https://github.com/antirez/redis/issues/2672
