### ISSUE TITLE
GET on bitmaps is returning a value in a different format than the redis-cli

### ISSUE THREAD

**Issue by palash25** [go-redis/redis#854]
How do I get the serialized string value that one gets using the redis-cli when the `GET ` command is called on a bitmap key something like `\x01\x00\x00\x00\x00\x00\x00\x00\x00....` but when I try to do this using the go-redis API I get an empty result 

`redis.Client.Get("key").Val()` gives me an empty string

**Comment by vmihailenco** [comment]
Please provide a small program that reproduces the problem.

**Comment by palash25** [comment]
```go
type Client struct {
	conn *redis.Client
}

func main() {
    c = Client{}

    // code it initialize a new redis client   

    c.conn.SetBit("bm", 2, 1)
    c.conn.SetBit("bm", 9, 0)
    c.conn.SetBit("bm", 4, 1)
    c.conn.SetBit("bm", 13, 0)
    c.conn.SetBit("bm", 1, 1)
    c.conn.SetBit("bm", 14, 1)
    c.conn.SetBit("bm", 23, 0)
 
   result := c.conn.Get("bm").Val()
   fmt.Println(sk)
}
```

When I run the following code I get this result `h`

When I enter the same bitmap using the redis-cli and do a `get bm` I get the following `"i\x1a\x10\x04\x00\x00\x10\x00\x01\x00\x00\x10"` I want to be able to get the value of a bitmap in this very form using the API too. How can I do that?

**Comment by palash25** [comment]
cc @vmihailenco

**Comment by vmihailenco** [comment]
redis-cli automatically encodes the data with hex encoding for you. In Go you can achieve similar result with `fmt.Printf("% x\n", res)` or `hex` package.
