### ISSUE TITLE
Application starts redis cluster object memory is very high

### ISSUE THREAD

**Issue by zhugang123** [go-redis/redis#856]
Simply start the service, not for redis data read and write, use the top command to check the progress of about 800 MB memory (redis. NewClusterClient), stand-alone version of redis object does not exist the phenomenon, use the stand-alone version of redis object, using the top command to check the process of month around 67 MB of memory (redis. NewClient), I feel very confused, hope to get help, thank you!

**Comment by vmihailenco** [comment]
What version are you using?

**Comment by zhugang123** [comment]
Thank you very much, problem solved

**Comment by zhugang123** [comment]
Showing nodes accounting for 53.48MB, 100% of 53.48MB total
Showing top 10 nodes out of 57
      flat  flat%   sum%        cum   cum%
   45.80MB 85.63% 85.63%    45.80MB 85.63%  server/pkg/engine.NewSocketConn
       4MB  7.48% 93.11%        4MB  7.48%  server/vendor/github.com/syndtr/goleveldb/leveldb/memdb.New
    1.50MB  2.80% 95.92%     1.50MB  2.80%  server/vendor/github.com/go-redis/redis.newClusterState
    1.18MB  2.20% 98.12%     1.68MB  3.14%  server/pkg/datacenter.(*UserClientConn).processBizData
    0.50MB  0.94% 99.06%     0.50MB  0.94%  server/vendor/github.com/go-redis/redis.commandInfoSliceParser
    0.50MB  0.94%   100%     0.50MB  0.94%  server/vendor/github.com/go-redis/redis/internal/pool.NewConn
         0     0%   100%     4.51MB  8.42%  main.main
         0     0%   100%     4.51MB  8.42%  runtime.main
         0     0%   100%     4.51MB  8.42%  server/cmd.Execute
         0     0%   100%     4.51MB  8.42%  server/cmd.glob..func3
