### ISSUE TITLE
XRead times out when called with Block 0

### ISSUE THREAD

**Issue by iamwilhelm** [go-redis/redis#863]
XRead times out when I call it with a block of 0.

```
client := redis.NewClient(&redis.Options{
    Addr: "localhost:6379",
    DB: 3,
})

res, err := self.client.XRead(&redis.XReadArgs{
    Streams: []string{"some_topic", "0"},
    Count: 2,
    Block: 0,
}).Result()
```
After a second or two, I get an error:
```
read tcp [::1]:54399->[::1]:6379: i/o timeout
```
Is that suppose to happen? I thought if I put in `0` in the `Block` option, it would block indefinitely until another new message came in.

**Comment by iamwilhelm** [comment]
Wow, thanks for the fix! I had thought it was something I was doing wrong.

**Comment by vmihailenco** [comment]
No, there is net.Conn read timeout set by default which causes the problem in this case.
