### ISSUE TITLE
Error: dial tcp: address http://localhost:6379: too many colons in address

### ISSUE THREAD

**Issue by mollylogue** [go-redis/redis#864]
`client := redis.NewClient(&redis.Options{
		Addr:     "http://localhost:6379,
		Password: "",
		DB:       0,
	})
pong, err := client.Ping().Result()`

err = dial tcp: address http://localhost:6379: too many colons in address

Can anyone explain why this is happening?

**Comment by vmihailenco** [comment]
Replace `http://localhost:6379` with `localhost:6379`. `http://` is meaningless in this context.

**Comment by vmihailenco** [comment]
Use https://godoc.org/github.com/go-redis/redis#ParseURL

**Comment by xacaxulu** [comment]
+1

**Comment by nick0511** [comment]
cluster mode connect error:dial tcp: address 10.129.36.219:30003 10.129.36.220:30003 10.129.36.221:30003: too many colons in address,how to fix?
