### ISSUE TITLE
If redis shutdown pubsub return error and exit

### ISSUE THREAD

**Issue by leeroy561** [go-redis/redis#866]
Is this a problem?
If connect and subscribe to channel everything fine before you restart redis server
`client := redis.NewClient(&redis.Options{...})  
	pubsub := client.Subscribe("channel")  
	msg, err := pubsub.ReceiveMessage()  
if err != nil {  
		fmt.Println(err)  
	}  
`
I got an error and closed app
`redis: discarding bad PubSub connection: EOF`

How can i prevent this? THanks

**Comment by vmihailenco** [comment]
You are supposed to retry `ReceiveMessage` in a loop. `EOF` is returned because you stopped Redis Server and that is expected behavior.

**Comment by vmihailenco** [comment]
It works for me, i.e. when server starts up go-redis automatically re-subscribes to the channel. Make sure you are using latest version and if you the problem is still there try to write detailed instructions describing what is the problem and how to reproduce it.

**Comment by vmihailenco** [comment]
Also until you don't need to do anything special with errors it is better to use `PubSub.Channel` - https://godoc.org/github.com/go-redis/redis#example-PubSub
