### ISSUE TITLE
circuit breaker seems not work very well

### ISSUE THREAD

**Issue by xianglinghui** [go-redis/redis#868]
@vmihailenco We found the circuit breaker didn't work very well when some nodes got stuck, rather than hang up. Now the strategy of circuit breaker is just based on connection detection, not the real invocation state, and the recovery strategy is not gradually. When a node got stuck, it may can connect successful one or two times, then the circuit breaker will recover soon.

We may need a circuit breaker with an elastic window, which can shrink or enlarge based on the invocation state.

**Comment by vmihailenco** [comment]
Okay, that makes sense though connection circuit breaker is created solely for the situation when Redis Server is down and client app uses all available file descriptors creating problems for neighbour apps. 

What you are suggesting sounds interesting but also much more complex so I don't think I will be able to add it any time soon...

**Comment by xianglinghui** [comment]
@vmihailenco Can I try to add this feature and send a PR? Then you can have a reference.

We may need this feature soon，because our service p99 cost has been alarmed many times.

**Comment by vmihailenco** [comment]
Sure, contributions are always welcome. Few random thoughts:
- leave it disabled by default; it should be enabled via option
- try to extract circuit breaker into separate package / sub-package / file. We may vendor it later.
- submit PR early so I can provide some feedback before it is too late

Thanks in advance.

**Comment by xianglinghui** [comment]
@vmihailenco I have sent a pr, https://github.com/go-redis/redis/pull/874.

My english is not very well, the code comment may be not clear.

**Comment by vmihailenco** [comment]
i think this is addresse by adding SetLimiter - https://godoc.org/github.com/go-redis/redis#Client.SetLimiter
