### ISSUE TITLE
memory heap / leak internal proto

### ISSUE THREAD

**Issue by youcandoit95** [go-redis/redis#872]
i'd used go redis in echo labstack .. and i'd installed pprof for memory profiling.

i've found memory leak until 40gb in production environment (K8s) 5 pod

here is result from pprof/heap :
github.com/go-redis/redis/internal/proto.readN
go-redis/redis/internal/proto.NewWriteBuffer (inline)
bufio.NewReaderSize (inline)
go-redis/redis/internal/proto.(*WriteBuffer).AppendBytes

can somebody tell me how to config / fix it ?

thanks

**Comment by vmihailenco** [comment]
First please try latest version. If the issue remains - try to create a program that reproduces the problem.

**Comment by youcandoit95** [comment]
okay solved , i'd upgrade the packages and give some script for deallocate memory ..

thanks
