### ISSUE TITLE
Busy loop on sentinel failure + fix

### ISSUE THREAD

**Issue by leemcloughlin** [go-redis/redis#873]
I'm running a Redis master/slave+slave with 3 sentinels
I'm connecting to it using NewFailoverClient() passing a list of all 3 sentinels.
If the first sentinel in the list fails then my app busy loops reporting:

redis: 2018/09/29 20:29:31 pubsub.go:149: redis: discarding bad PubSub connection: EOF
redis: 2018/09/29 20:29:31 sentinel.go:323: sentinel: ReceiveMessage failed: EOF
redis: 2018/09/29 20:29:31 sentinel.go:323: sentinel: ReceiveMessage failed: dial tcp 192.168.130.101:26379: connect: connection refused
redis: 2018/09/29 20:29:31 sentinel.go:323: sentinel: ReceiveMessage failed: dial tcp 192.168.130.101:26379: connect: connection refused
...

The following fix to sentinel.go fixes the problem:

	diff --git a/sentinel.go b/sentinel.go
	index c5f7149..9d10135 100644
	--- a/sentinel.go
	+++ b/sentinel.go
	@@ -3,6 +3,7 @@ package redis
	 import (
	 	"crypto/tls"
	 	"errors"
	+	"io"
	 	"net"
	 	"strings"
	 	"sync"
	@@ -316,7 +317,7 @@ func (d *sentinelFailover) listen(sentinel *SentinelClient) {
	 	for {
	 		msg, err := pubsub.ReceiveMessage()
	 		if err != nil {
	-			if err == pool.ErrClosed {
	+			if err == pool.ErrClosed || err == io.EOF {
	 				d.resetSentinel()
	 				return
	 			}

**Comment by vmihailenco** [comment]
I am going to improve that code to use Channel, but my understanding is that [this code](https://github.com/go-redis/redis/blob/master/sentinel.go#L196-L206) is responsible for detecting dead sentinel and reconnecting.

**Comment by vmihailenco** [comment]
Closing as stale. Please re-open with more details if you still experience any problems.
