### ISSUE TITLE
Does redis-go caches cluster slots info?

### ISSUE THREAD

**Issue by 15astro** [go-redis/redis#878]
Do go-redis caches cluster slots info at client side or it keeps handling moved and redirections for every request? @vmihailenco @andriikushch

**Comment by vmihailenco** [comment]
Both, it uses cluster slots to route command but also handles moved and redirection errors. Why do you ask?

**Comment by 15astro** [comment]
Based on the docs here: https://redis.io/topics/cluster-spec#clients-first-connection-and-handling-of-redirections

Does go-redis driver fetch the cluster slots info on following two events?
 - At startup in order to populate the initial slots configuration
 - When a MOVED redirection is received
 
and usually, it serves the request by smartly using cache cluster state at client side? Or it handles redirection for every request?

I was trying to understand b/w the efficient and inefficient clients mentioned in above redis-cluster doc w.r.t go-redis.

Thanks!
