### ISSUE TITLE
Howto recover from bad pubsub channel subscription

### ISSUE THREAD

**Issue by riaan53** [go-redis/redis#879]
Hi,

I use a channel subscription and at some stage I got a lot of the following errors without recovery, I had to restart the application for it to recover. Must I add my own ping pong handler to detect errors like this?

`
"redis: 2018/10/09 06:27:02 pubsub.go:149: redis: discarding bad PubSub connection: %!s(<nil>)
`

Im using redis:5.0-rc4.

Thanks!

**Comment by vmihailenco** [comment]
Please try to upgrade go-redis and use `PubSub.Channel` API. If this is still a problem please create a program that reproduces it.

**Comment by riaan53** [comment]
Hi, Im struggling to create a small repo to reproduce it but have changed the way I consume subscriptions to only use one `PubSub.Channel` like you suggested. I also upgraded to the latest master branch now. Will let it run over the weekend and then either close this issue or try again with the small program to recreate to it. Thanks

**Comment by riaan53** [comment]
Hi @vmihailenco ,

It looks like theres a defer missing https://github.com/go-redis/redis/blob/master/pubsub.go#L441 that might cause the issue? It will not send the ping because the timer is stopped immediately. With the latest master branch I get the error that was fixed recently instead of the <nil> like above (ping timeout).

**Comment by riaan53** [comment]
The only way I could reproduce this issue is buy blocking until the message send buffer fills up.
