### ISSUE TITLE
Increased frequency of pool.Put failed: redis: client is closed

### ISSUE THREAD

**Issue by dim** [go-redis/redis#88]
Since last revision of cluster-client was deployed, we see many, many `pool.Put failed: redis: client is closed` in the logs, any idea why this could be?

**Comment by vmihailenco** [comment]
That was a bug in the pool:
1. client is closed
2. operation finishes and connection is returned to the pool
3. pool says that client is closed is logs the message you mentioned

Should be fixed by https://github.com/go-redis/redis/pull/90/files

**Comment by dim** [comment]
Yep, seen it in the patch
