### ISSUE TITLE
Support for Redis version 4.0.11

### ISSUE THREAD

**Issue by 15astro** [go-redis/redis#880]
Does go-redis support redis version 4.0.11? 
Is there any dependency document for go and redis versions to use with redis-go like [this](https://github.com/maodeyi/redis-py-cluster/blob/master/docs/index.rst#dependencies--supported-python-versions)?

@vmihailenco 

Thanks!

**Comment by vmihailenco** [comment]
AFAIK Redis Server is very stable and maintains backwards compatibility at very high level so you can use any Redis Server version you like. But go-redis is only tested against latest Redis Server version.

**Comment by 15astro** [comment]
Thanks, how about the redis-go compatibility with different go versions?

**Comment by vmihailenco** [comment]
The only guarantee go-redis provides is support for last 2 major Go versions - currently it is Go 1.11 and Go 1.10. Other Go versions are likely to work too but you have to verify that yourself.
