### ISSUE TITLE
redis.NewFailoverClient refuses tls connection

### ISSUE THREAD

**Issue by alok-webonise** [go-redis/redis#881]
Hi

I am trying to connect redis Sentinel using tls configuration but it is constantly refusing the connection.
 
my current config looks like 

      `certs := x509.NewCertPool()
	certs.AppendCertsFromPEM([]byte(ext.RedisClusterCert()))
	rdb := redis.NewFailoverClient(&redis.FailoverOptions{
		MasterName :"mymaster",
		SentinelAddrs :address,
		DB:0,
		Password:"hash1234",
		DialTimeout: 1 * time.Minute,
		MaxRetries:10,
		TLSConfig: &tls.Config{
			InsecureSkipVerify: true,
			MinVersion:         tls.VersionTLS12,
			RootCAs:            certs,
		},

	})`

i think  in sentinel.go `func (c *sentinelFailover) masterAddr() (string, error) {}` NewSentinelClient needs  `TLSConfig:c.opt.TLSConfig`

**Comment by vmihailenco** [comment]
Should be fixed in master branch.
