### ISSUE TITLE
FailoverClient uses an already closed connection when switching to new master

### ISSUE THREAD

**Issue by tkliner** [go-redis/redis#889]
I have 3 sentinels and I use the FailoverClient client in the go application, when the first master failure occurs, a new master is found, but if this new master drops out and the other new master is selected FailoverClient uses the old connection and writes the error:

```
 write tcp 172.20.0.5:35766->172.20.0.3:6379: use of closed network connection
```

Do not close (now) inactive connection and establish a new connection to the new master. I would like to ask whether this behavior can be affected by client settings or this behavior is a bug?

**Comment by vmihailenco** [comment]
We need some way to reproduce this problem with latest version of go-redis.

My understanding is that situation you described is possible when 3 conditions are met:
- existing master is dead
- sentinel in use is dead too
- app does not have any activitiy

In all other cases go-redis should detect that master/sentinel are dead and pick new sentinel and get new master from the sentinel.

**Comment by tkliner** [comment]
Hi, I apologize for the late answer, unfortunately I missed the notification of your reply. I have a go app (webserver) with connection to redis. In docker i have 3x sentinel, 1x redis master and 1x redis slave. If I turn off the redis master, the slave switches and the slave becomes the master. If I turn on the original redis master and approx. after 5 sec turn off slave, this problem will occur.

**Comment by vmihailenco** [comment]
Can't fix it without a reproducer - sorry.
