### ISSUE TITLE
Using Store in GeoRadiusQuery results in `can't parse array reply` error

### ISSUE THREAD

**Issue by benjwg** [go-redis/redis#895]
While `Store` is in the `GeoRadiusQuery` struct, including it doesn't seem to work and instead results in an error when `GeoRadius` is called:

`can't parse array reply`

This field is never set to a value in any of the existing tests, but I don't think I'm doing anything fishy myself.

**Comment by vmihailenco** [comment]
Please add a reproducer.

**Comment by lukepighetti** [comment]
@vmihailenco here's your reproducer https://github.com/go-redis/redis/issues/1083
