### ISSUE TITLE
 how to reliably determine when the list is empty?

### ISSUE THREAD

**Issue by gitleet** [go-redis/redis#896]
When calling lpop, how to determine when the list is empty?

In redis-cli an empty list with a lpop call returns nil.

With the go-redis library, should I look for val to be nil or an error or both?

```
val, err := redis.LPop(listKey).Result()
```

**Comment by dkrieger** [comment]
see `redis.Nil`. Values returned aren't pointers, so they have their type's zero val's -- in the case of LPop, it's a string, so `""`. `redis.Nil` error allows one to know that the zero-valued val isn't literal, but a placeholder for nil. That's my understanding of it anyway from reading the code.

**Comment by vmihailenco** [comment]
go-redis returns `redis.Nil` when redis-cli returns `(nil)`.
