### ISSUE TITLE
pipline's bug ?

### ISSUE THREAD

**Issue by katncandix2** [go-redis/redis#902]
pipe := r.Pipeline()
incr := pipe.Incr("pipeline_counter")

//can't get val in this way 
val := pipe.Incr("pipeline_counter").Val()

fmt.Println(incr.Val())
fmt.Println(val)
pipe.Exec() 

what's the diff:
         incr.val()     
          pipe.Incr("pipeline_counter").Val()

**Comment by vmihailenco** [comment]
Value is not available until pipelined commands are executed via `pipe.Exec`

**Comment by katncandix2** [comment]
![image](https://user-images.githubusercontent.com/10647224/48613940-04ea6000-e9c8-11e8-86eb-a2f2ecf8a49f.png)
you can try this
