### ISSUE TITLE
Eval and Evalsha 's   questions

### ISSUE THREAD

**Issue by katncandix2** [go-redis/redis#907]
the same script  
![image](https://user-images.githubusercontent.com/10647224/48758085-cf9c8580-ecd9-11e8-8375-9133e76dccbd.png)

when i use Eval: 403799 ns/op  (local bench mark)
![image](https://user-images.githubusercontent.com/10647224/48758124-ee028100-ecd9-11e8-9995-88eeccccfb67.png)

use EvalSha : 450405 ns/op (local bench mark)
![image](https://user-images.githubusercontent.com/10647224/48758167-1be7c580-ecda-11e8-8ba3-a83558b901fb.png)

**Comment by vmihailenco** [comment]
No explanation here.
