### ISSUE TITLE
redis: discarding bad PubSub connection: EOF

### ISSUE THREAD

**Issue by zhangshp** [go-redis/redis#910]
“redis: discarding bad PubSub connection: EOF ” repeat every 30 seconds

**Comment by vmihailenco** [comment]
Please provide a program that reproduces the problem using latest version of the library

**Comment by zhangshp** [comment]
_package utils

import (
	"fmt"
	"time"

	"github.com/cihub/seelog"

	"github.com/go-redis/redis"
)

type OnSubscribe func(msg *redis.Message) error

type RedisPubSub struct {
	client   *redis.Client
	pubsub   *redis.PubSub
	channels []string
}

func createRedisPubSub(conf *RedisInfo, channels []string) (*RedisPubSub, error) {
	client := redis.NewClient(&redis.Options{
		Addr:         fmt.Sprintf("%v:%v", conf.Server.Host, conf.Server.Port),
		Password:     conf.Server.Passwd,
		DialTimeout:  time.Duration(conf.DialTimeout) * time.Second,
		ReadTimeout:  time.Duration(conf.ReadTimeout) * time.Second,
		WriteTimeout: time.Duration(conf.WriteTimeout) * time.Second,
		DB:           conf.DB,
	})
	if _, err := client.Ping().Result(); nil != err {
		return nil, err
	}
	pubsub := client.Subscribe(channels...)
	if nil == pubsub {
		return nil, fmt.Errorf("subscribe fail")
	}
	return &RedisPubSub{client, pubsub, channels}, nil
}

func (this *RedisPubSub) Close() error {
	this.pubsub.Unsubscribe(this.channels...)
	this.pubsub.Close()
	return this.client.Close()
}

func (this *RedisPubSub) Receive(onSubscribe OnSubscribe) {
	msg, err := this.pubsub.ReceiveMessage()
	if nil == err {
		seelog.Error(err)
	}
	if nil != msg {
		onSubscribe(msg)
	}
}

func (this *RedisPubSub) Publish(channel, data string) error {
	_, err := this.client.Publish(channel, data).Result()
	return err
}

var redisPubSub *RedisPubSub

func InitPubSub(conf *RedisInfo, channels []string) error {
	if rds, err := createRedisPubSub(conf, channels); nil != err {
		return err
	} else {
		redisPubSub = rds
	}
	return nil
}

func ClosePubSub() error {
	return redisPubSub.Close()
}

func WatchPubSub(onSubscribe OnSubscribe) {
	for {
		redisPubSub.Receive(onSubscribe)
	}
}

func Publish(channel, data string) error {
	return redisPubSub.Publish(channel, data)
}
_

**Comment by zhangshp** [comment]
@vmihailenco Could you tell why that happened?

**Comment by vmihailenco** [comment]
No since there is no program that I can run and that reproduces the problem.

**Comment by tegioz** [comment]
I've seen this error message when redis closes a pubsub connection because the output buffer limit in redis is reached (not a problem with the library). You can check your redis logs to verify it as redis notifies you when it happens. Depending on your use case, you may need to tweak `client-output-buffer-limit pubsub` in `redis.conf`.

> https://redis.io/topics/clients
>
> Redis needs to handle a variable-length output buffer for every client, since a command can produce a big amount of data that needs to be transferred to the client.
>
> However it is possible that a client sends more commands producing more output to serve at a faster rate at which Redis can send the existing output to the client. This is especially true with Pub/Sub clients in case a client is not able to process new messages fast enough.
