### ISSUE TITLE
MOVED errors

### ISSUE THREAD

**Issue by apremalal** [go-redis/redis#917]
I am using aws redis cache cluster(2 shards each with 1 master and 1 slave) with following configurations.

```
redis.NewClient(&redis.Options{
			Addr:       []string{"url1:6379","url2:6379","url3:6379","url4:6379"},
			Password:   "",
			DB:         0,
			MaxRetries: 4,
                       MaxRedirects: 8,
		})
```
I'm getting MOVED errors time to time. Do I need to configured the slot details manually?

**Comment by vmihailenco** [comment]
No, slots are configured automatically.

**Comment by sumjha** [comment]
@apremalal : I am also facing this same issue. How did you resolve that?
