### ISSUE TITLE
slowlog support

### ISSUE THREAD

**Issue by winjeg** [go-redis/redis#926]
when ? or never ?

```go
func (c *cmdable) SlowLog() {
	panic("not implemented")
}

func (c *cmdable) Sync() {
	panic("not implemented")
}
```

**Comment by AjithKumar-Raj** [comment]
@vmihailenco any updates??

**Comment by winjeg** [comment]
> @vmihailenco any updates??

I have maintained the `slowlog` command in my own repo. if you are interested you can take a look [here](https://github.com/winjeg/redis)

**Comment by AjithKumar-Raj** [comment]
@vmihailenco Can you create a pull request here?
This repo is a dependency of telegraf, which is one of the open source projects.

**Comment by winjeg** [comment]
The support for `slowlog` command is not so graceful with the original design of the project. if you want to be compatible with redis 3 and redis 4.  I did a little trick to my own project.
