### ISSUE TITLE
cluster client doesn't retry on pipeline read timeouts

### ISSUE THREAD

**Issue by akrylysov** [go-redis/redis#930]
Here is an example:

```go
package main

import (
	"fmt"
	"time"

	"github.com/go-redis/redis"
)

func main() {
	fmt.Println("start")
	options := &redis.ClusterOptions{
		Addrs:              []string{"0.0.0.0:7000"},
		MaxRedirects:       8,
		MaxRetries:         8,
		MinRetryBackoff:    1 * time.Second,
		MaxRetryBackoff:    1 * time.Minute,
		DialTimeout:        100 * time.Millisecond,
		ReadTimeout:        100 * time.Millisecond,
		WriteTimeout:       100 * time.Millisecond,
	}
	c := redis.NewClusterClient(options)
	fmt.Printf("%+v\n", c.Options())
	defer c.Close()
	fmt.Println("ping", c.Ping())
	options.ReadTimeout = time.Millisecond
	pipe := c.Pipeline()
	for i := 0; i < 128; i++ {
		z := redis.Z{
			Score:  float64(0),
			Member: fmt.Sprintf("test%d", i),
		}
		pipe.ZAdd("z", z)
	}
	_, err := pipe.Exec()
	fmt.Println(err)
}
```

- `pipelineReadCmds` doesn't update the `failedCmds` map https://github.com/go-redis/redis/blob/master/cluster.go#L1352.
- `defaultProcessPipeline` doesn't retry because `failedCmds` is empty https://github.com/go-redis/redis/blob/master/cluster.go#L1275.

**Comment by vmihailenco** [comment]
Thanks for the report. The motivation was that we should not try to retry half of the pipeline, because it can be that user relies that all commands in pipeline are executed together once. I am not sure it is still a valid concern after we added TxPipeline.

**Comment by vmihailenco** [comment]
Closed by https://github.com/go-redis/redis/pull/936

**Comment by akrylysov** [comment]
Thank you!
