### ISSUE TITLE
How to gracefully close connections blocked on reading from Redis streams?

### ISSUE THREAD

**Issue by RussellLuo** [go-redis/redis#933]
## Question

Per the documentation of [XREAD](https://redis.io/commands/xread#blocking-for-data):

> In order to avoid polling at a fixed or adaptive interval the command is able to block if it could not return any data, according to the specified streams and IDs, and automatically unblock once one of the requested keys accept data.

In other words, it's recommended to use the blocking mode while reading from Redis streams.

When using go-redis, we may write the following code:

```go
package main

import (
	"log"
	"os"
	"os/signal"
	"sync"

	"github.com/go-redis/redis"
)

func main() {
	client := redis.NewClient(&redis.Options{
		Addr: "localhost:6379",
		// Only need 1 connection for reading.
		PoolSize: 1,
	})

	var waitGroup sync.WaitGroup
	waitGroup.Add(1)
	go func() {
		defer waitGroup.Done()

		lastID := "0-0"

		for {
			streams, err := client.XRead(&redis.XReadArgs{
				Streams: []string{"mystream", lastID},
				Block:   0, // Wait for new messages without a timeout.
			}).Result()
			if err != nil {
				log.Printf("err: %+v\n", err)
				return
			}

			log.Printf("received streams: %+v\n", streams)

			messages := streams[0].Messages
			lastID = messages[len(messages)-1].ID
		}
	}()

	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)

	select {
	case <-c:
		// Question: how to gracefully close the blocking connection here?
		client.Close()

		waitGroup.Wait()
	}
}
```

Then there is a question: **how to gracefully close the blocking connection?**

## The problem of client.Close()

In the example code, If we use `client.Close()` to close the connection, it will cause an error log:

```
err: read tcp 127.0.0.1:55520->127.0.0.1:6379: use of closed network connection
```

What happened behind `client.Close()` is as follows:

1. `client.Close()` will [close the connection pool](https://github.com/go-redis/redis/blob/11cf9400d58a23fe233f2544ed4cd55b7a373f89/redis.go#L244)
2. then the only 1 connection in the pool will be actually [closed](https://github.com/go-redis/redis/blob/11cf9400d58a23fe233f2544ed4cd55b7a373f89/internal/pool/pool.go#L333)
3. then `client.XRead()`, which is blocking on [cn.WithReader()](https://github.com/go-redis/redis/blob/11cf9400d58a23fe233f2544ed4cd55b7a373f89/redis.go#L204), will be unblocked and returns an error "use of closed network connection"
4. then `c.releaseConn()` will be called, and err is judged as [a bad one](https://github.com/go-redis/redis/blob/11cf9400d58a23fe233f2544ed4cd55b7a373f89/redis.go#L104), which will finally **closes the connection again**

The real problem is:

- when the connection is closed at step 2, the file descriptor is also released
- when the connection is closed again at step 4, the original file descriptor may have been used by another valid connection, which will be closed mistakenly.

There was [a discussion about the same issue](https://stackoverflow.com/a/27790293/963379) on StackOverflow.

## Possible solution

Use [TCPConn.CloseRead](https://golang.org/pkg/net/#TCPConn.CloseRead) or [UnixConn.CloseRead](https://golang.org/pkg/net/#UnixConn.CloseRead), which are the Golang's equivalents of Unix's `shutdown()`.

Then we need to add a function`CloseRead()` into [redis.Client](https://github.com/go-redis/redis/blob/11cf9400d58a23fe233f2544ed4cd55b7a373f89/redis.go#L388).

Any other thoughts?

**Comment by vmihailenco** [comment]
Do you suggest we use CloseRead when closing the connection pool?

The alternative is to add some guard against closing the connection twice which should be trivial and conceptually more simpler.

**Comment by RussellLuo** [comment]
> Do you suggest we use CloseRead when closing the connection pool?

In the example scenario I mentioned above, if we can avoid closing the connection twice, I think it's ok to use the existing client.Close().

There is another scenario, in theory, where a connection may be shared by two processes (e.g. both are blocked on reading from the same connection). Then client.CloseRead() can unblock both processes, while client.Close() can only unblock the process where it is called within.

That being said, I have little experience with the latter scenario in Golang, so I don't know if it's a practical problem.

> The alternative is to add some guard against closing the connection twice which should be trivial and conceptually simpler.

Yeah, for the example scenario, I think the alternative solution is good. Maybe we can check the error string "use of closed network connection" (which is an internal error [ErrNetClosing](https://github.com/golang/go/blob/571d93e977862f91bb153f0b98937ca655505fcd/src/internal/poll/fd.go#L18)) before closing the connection?

**Comment by vmihailenco** [comment]
[This](https://github.com/golang/go/issues/20705) issue suggests that closing fd twice is fine in most cases.  We still can add some checks but it looks like there is no real problem here .

**Comment by RussellLuo** [comment]
Yeah, I agree. The problem of Unix's [close](https://linux.die.net/man/2/close):

> It is probably unwise to close file descriptors while they may be in use by system calls in other threads in the same process. Since a file descriptor may be reused, there are some obscure race conditions that may cause unintended side effects.

is due to its manipulation on the **raw fd**.

But in Go, the raw id is wrapped in an implementation of [Conn](https://golang.org/pkg/net/#Conn) (e.g. [TCPConn](https://golang.org/pkg/net/#TCPConn)), which will [do some check](https://github.com/golang/go/blob/571d93e977862f91bb153f0b98937ca655505fcd/src/internal/poll/fd_unix.go#L87) to ensure the safety to be closed twice or more.

@vmihailenco Thanks for your reply. I'm going to close this issue.
