### ISSUE TITLE
redis: discarding bad PubSub connection: redis: ping timeout

### ISSUE THREAD

**Issue by shscy** [go-redis/redis#938]
while I was using  `(c *PubSub) Channel()` function to receive messages , there sometimes occurd the error `"redis: discarding bad PubSub connection: redis: ping timeout"` . I know that `Pubsub.Receive()` method will block the Groutine, so I send messages to the PubSub every 2 seconds,  I tried to expanding `pubsub.ping` buffer capacity, but no effect at all

**Comment by vmihailenco** [comment]
I need a reproducer or you can try to find a problem in the code - https://github.com/go-redis/redis/blob/master/pubsub.go#L397-L469.

>I know that Pubsub.Receive() method will block the Groutine, so I send messages to the PubSub every 2 seconds,

There is no need - go-redis should do this for you automatically.

**Comment by earlonrails** [comment]
I have the same error. I think I am doing something wrong here. I am using echo framework

server.go
```
package main

import (
  "github.com/labstack/echo"
  // mw "github.com/labstack/echo/middleware"
)

func main() {
  // Echo instance
  e := echo.New()

  // Middleware
  // e.Use(mw.Logger())
  // e.Use(mw.Recover())

  e.GET("/", EdgeController)

  // Start server
  e.Logger.Fatal(e.Start(":9001"))
}

```

edge.go
```
package main

import (
  "net/http"
  "github.com/labstack/echo"
  "log"
  "github.com/go-redis/redis"
  "encoding/json"
  "time"
  "fmt"
  "math/rand"
)

const (
  PreFilterChannelName string = "pre-filter"
  RespondChannelName string = "respond"
)

var (
  redisdb   *redis.Client
  preFilter *redis.PubSub
  respond   *redis.PubSub
)

func init() {
  var err error
  rand.Seed(time.Now().UnixNano())
  redisdb = redis.NewClient(&redis.Options{
    Addr:         ":6379",
    DialTimeout:  10 * time.Second,
    ReadTimeout:  30 * time.Second,
    WriteTimeout: 30 * time.Second,
    PoolSize:     10,
    PoolTimeout:  30 * time.Second,
  })
  preFilter = redisdb.Subscribe(PreFilterChannelName)
  respond = redisdb.Subscribe(RespondChannelName)
  // Wait for confirmation that subscription is created before publishing anything.
  _, err = preFilter.Receive()
  if err != nil {
    panic(err)
  }

  // Wait for confirmation that subscription is created before publishing anything.
  _, err = respond.Receive()
  if err != nil {
    panic(err)
  }
}

const letters = "0123456789ABCDEF"

func randomBytes(n int) ([]byte, error) {
  bytes := make([]byte, n)
  _, err := rand.Read(bytes)
  if err != nil {
    return bytes, err
  }

  return bytes, nil
}

func randomString(bytes []byte) string {
  for i, b := range bytes {
    bytes[i] = letters[b%16]
  }

  return string(bytes)
}

func EdgeController(c echo.Context) error {
  var (
    bytes     []byte
    requestID string
    err       error
    val       string
    msgi      interface{}
  )

  log.Printf("context: %v", c)
  // Go channel which receives messages.
  // ch := respond.Channel()
  cJson, err := json.Marshal(c)
  if err != nil {
    return c.String(http.StatusInternalServerError, fmt.Sprintf("error: %v", err))
  }

  bytes, err = randomBytes(32)
  if err != nil {
    return c.String(http.StatusInternalServerError, fmt.Sprintf("error: %v", err))
  }
  requestID = randomString(bytes)
  // Store the request object on key requestID.
  // no ttl
  // err = redisdb.Set(requestID, string(cJson), 0).Err()
  // ttl 300000000 * time.Nanosecond == 300 milliseconds
  err = redisdb.Set(requestID, string(cJson), 300000000 * time.Nanosecond).Err()
  if err != nil {
    return c.String(http.StatusInternalServerError, fmt.Sprintf("error: %v", err))
  }

  // Publish a message.
  log.Printf("Publish Error: %v, %v", PreFilterChannelName, requestID)
  err = redisdb.Publish(PreFilterChannelName, requestID).Err()
  if err != nil {
    return c.String(http.StatusInternalServerError, fmt.Sprintf("error: %v", err))
  }

  for {
    log.Printf("waiting to receive")
    msgi, err = respond.Receive()
    log.Printf("msgi: %v, err: %v", msgi, err)

    switch msg := msgi.(type) {
      case *redis.Message:
        log.Printf("ReceiveMessage: %v, %v", msg, err)
        if requestID == msg.Payload {
          log.Printf("Found matching request: %v, %v", msg.Channel, msg.Payload)
          // Read request object.
          val, err = redisdb.Get(requestID).Result()

        } else {
          log.Printf("Request Not FOUND!!!: looking for: %v, Have: %v", requestID, msg.Payload)
        }
      default:
        log.Printf("default ReceiveMessage: %v, %v", msg)
    }

    log.Printf("val: %v, err: %v", val, err)
    if val != "" || err != nil {
      log.Printf("Breaking!")
      break
    }
  }

  if err != nil {
    log.Printf("Server Error: %v", err)
    return c.String(http.StatusInternalServerError, fmt.Sprintf("error: %v", err))
  }

  log.Printf("StatusOK: %v", val)
  return c.String(http.StatusOK, val)
}
```

A little sloppy, as I have tried a few different ways already.

**Comment by vmihailenco** [comment]
You are using `Receive` and probably do it concurrently. This issue is about `Channel`. Try to use it.

**Comment by shscy** [comment]
my problem is that messages is too much and I did't consume them in time which blocks the `ping` chan。
In your code the `respond` object which binds  a `PubSub Conn` (a tcp connection) is initialized in the init function , `Receive` function reads data from the binded conn , so it  has to  be processed linearly。 if you want to use `Recvice` concurrently, you could call `redisdb.Subscribe(chanName)` in each goroutine, then each goroutine has own `PubSub Conn`。

**Comment by rush24** [comment]
`const timeout = 5 * time.Second

		timer := time.NewTimer(timeout)
		timer.Stop()

		healthy := true
		for {
			timer.Reset(timeout)
			select {
			case <-c.ping:
				healthy = true
				if !timer.Stop() {
					<-timer.C
				}
			case <-timer.C:
				pingErr := c.Ping()
				if healthy {
					healthy = false
				} else {
					if pingErr == nil {
						pingErr = errPingTimeout
					}
					c.mu.Lock()
					c._reconnect(pingErr)
					c.mu.Unlock()
				}
			case <-c.exit:
				return
			}
		}`
this problem also happended in my app and log every 5s，so it must called by `_reconnect` method in   `pubsub.go L461`.  only `pingErr := c.Ping()` pingErr is nil can make it assign with errPingTimeout, so in ping go func we ping redis is work, but why should we reconnect there ? (cuz the conn is fine. whatever, evertimes calling `_reconnect` we may get a new  conn，but the truth is i never get any msg from channel (unless evertimes we get a bad conn, but other pubsub in same redis client is fine).  
hope to get a reply soon, thx
