### ISSUE TITLE
redis i/o time out

### ISSUE THREAD

**Issue by ppmoon** [go-redis/redis#941]
My Code is :
```golang
redisDB = redis.NewClient(&redis.Options{
		Addr:     viper.GetString("redis.addr"),
		Password: viper.GetString("redis.password"), // no password set
		DB:       viper.GetInt("redis.DB"),          // use default DB
		PoolSize: viper.GetInt("redis.poolSize"),
	})
```
Sometimes get key from redis will dial tcp: i/o timeout
I set a Loop task 5s get the same key from redis is ok.But when stop get the key and after 10min or 30 min do a get opt.It will return a error dial tcp: i/o timeout.

Is my code wrong? or other reason?

**Comment by vmihailenco** [comment]
Perhaps you need higher `DialTimeout`. You can also try to set `MinIdleConns` if your connection is not very fast.

**Comment by ppmoon** [comment]
I set MinIdleConns.Now the problem is not reproduce.Thank you very much.

**Comment by jmoreira-netskope-com** [comment]
I'm having the same issue. What is "MinIdleConns.Now " ?? 
Help please!

**Comment by rentiansheng** [comment]
I  set ReadTimeout equal time.Minute
