### ISSUE TITLE
Request list all keys from database

### ISSUE THREAD

**Issue by harryrford** [go-redis/redis#942]
Couldn't find in the documentation how to request a list of all keys from a database. Normally its client.Keys() without any parameters.

**Comment by lalabuy948** [comment]
@harryrford hey, did you find the solution?

**Comment by harryrford** [comment]
Hi @lalabuy948 yes I did. You can use the character "*" to get all keys. Example:

```go
keylist, _ := client.Keys("*").Result()
```

**Comment by lalabuy948** [comment]
@harryrford alright, thanks for sharing
