### ISSUE TITLE
c nil in func (c *PubSub) Channel()

### ISSUE THREAD

**Issue by andrewarrow** [go-redis/redis#944]
From `vendor/github.com/go-redis/redis/pubsub.go`

> panic: runtime error: invalid memory address or nil pointer dereference
> signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x68fd1b
> goroutine 233363978 [running]:
> vendor/github.com/go-redis/redis.(*PubSub).Channel(0x0, 0x13)
> vendor/github.com/go-redis/redis/pubsub.go:391 +0x3b

```
// Channel returns a Go channel for concurrently receiving messages.
// It periodically sends Ping messages to test connection health.
// The channel is closed with PubSub. Receive* APIs can not be used
// after channel is created.
func (c *PubSub) Channel() <-chan *Message {
  c.chOnce.Do(c.initChannel)
  return c.ch
}
```

Any idea why c would be nil? We have this code running for days and days without crash but then sudden got this one nil pointer crash.

**Comment by andrewarrow** [comment]
Sure the version in our go.sum file is `github.com/go-redis/redis v0.0.0-20180817112859-21826c1c21b6`

We have this `Thing` like:

```
type Thing struct {
  pubsub            *redis.PubSub
} 
```

And then this endless for loop:

```
for {
    thing.pubsub = client.Subscribe("key")

    msg, err := thing.pubsub.Receive()

    if thing.pubsub == nil {
      time.Sleep(time.Second * 1)
      continue
    }

    if err != nil {
      time.Sleep(time.Second)
      continue
    }

    ch := thing.pubsub.Channel()

    for {
      msg, ok := <-ch
      if !ok {
        break
      }
      thing.processPayload(msg.Payload)
    }
    time.Sleep(time.Second)
  }
```

**Comment by andrewarrow** [comment]
The outer loop we use for when the aws redis instance just goes away and the tcp connection for that pubsub channel is broken, we need it to try and re-connect over and over until aws redis comes back and the subscribe happens again.

I agree thing.pubsub == nil should never be true, but that came from a real crash when it was!

**Comment by vmihailenco** [comment]
PubSub tries hard to re-connect on connection failures so you don't have to do it yourself. If there is a problem it is better to fix it in go-redis for everyone.

As for the nil pointer - it is very likely you have an initialization race somewhere. Actually that is the only possibility - after all I don't know how `c *PubSub` can become `nil` if it was properly initialized.

**Comment by andrewarrow** [comment]
so any way I tried this this line `ch := thing.pubsub.Channel()` was dangerous. Sometimes, often, it returned a valid thing I could get messages off, but every once in a while amazon's aws redis cluster connection would "go away" and the above error.

To solve I did:

```
type ChannelHolder struct {
  ch  <-chan *redis.Message
  err string
}

func (bd *BirdData) safelyGetChannel(channelHolder *ChannelHolder) {
  defer func() {
    if r := recover(); r != nil {
      logBoth("safelyGetChannel %v", r)
    }
  }()
  channelHolder.err = "init"
  channelHolder.ch = bd.pubsub.Channel()
  channelHolder.err = ""
}
```

And then:

```
channelHolder := ChannelHolder{}
bd.safelyGetChannel(&channelHolder)
if channelHolder.err != "" {
        //ResetClusterClient()
      } 
```
