### ISSUE TITLE
Stop sending requests to the node down in cluster

### ISSUE THREAD

**Issue by 15astro** [go-redis/redis#945]
When one of the master in the redis cluster goes down the client keeps sending requests to the node which is in down state for almost next 20 mins.

The new master was elected within 6 seconds and the old master was in down state.

Error in application : `192.x.x.x:6379 connection refused`

1. Is it required to set any param to avoid such case?

2. Are the requests failing with the above error are retried on the new master since the maxRedirects is set to 8 by default?

Setup: Redis cluster with 6 nodes, version 4.0.11
          Latest version of go-redis
          Readonly is set to true
@vmihailenco 
Thanks!

**Comment by vmihailenco** [comment]
...but if you have "Readonly is set to true" and the node is listed as a part of the cluster go-redis will keep using it.

**Comment by 15astro** [comment]
Thanks, @vmihailenco.

Does the https://github.com/go-redis/redis/pull/948 will solves this issue now?
 
> ...but if you have "Readonly is set to true" and the node is listed as a part of the cluster go-redis will keep using it.

If the cluster state is reloaded on every minute, the driver should identify that the node is down and stop sending requests to that node(readonly ops on slave)? 

Will all such calls be retries itself based on https://github.com/go-redis/redis/commit/d9c8076236ce01c8e172a56c3010cfc3da078685#diff-5012ac478fddb03fa409c41a16a72b0dR963?
