### ISSUE TITLE
No way to retrieve command name for EVALSHA

### ISSUE THREAD

**Issue by gbbr** [go-redis/redis#956]
In commit https://github.com/go-redis/redis/commit/d5fc79d4eedba6c4f81d20756e69b18ccffb521d a change was introduced where `fmt.Stringer` [was removed](https://github.com/go-redis/redis/commit/d5fc79d4eedba6c4f81d20756e69b18ccffb521d#diff-9c42b524cb14ca001c61267826cbefb1R170) from `Cmd`. This breaks our instrumentation code because we can no longer obtain the name of the running command.

Can you suggest a workaround or can we re-introduce a method to access the command name?

This change was introduced in the release of 6.14.0

**Comment by vmihailenco** [comment]
Did you try [cmd.Args](https://github.com/go-redis/redis/blob/master/command.go#L16)?

**Comment by gbbr** [comment]
Yep that worked. Thanks!
