### ISSUE TITLE
Strategy to read data from multiple channels 

### ISSUE THREAD

**Issue by abhit011** [go-redis/redis#961]
I am using go-redis to read data from multiple redis channels. The data at each second is close to 3k-4k per second per channel... 
I am coding like this 
```
func BootUpTheRespectiveHandlers(redisClient *redis.Client,
	, channelList0 []string) {

	serverList := []string{channelList0[0],
		channelList0[1],
		channelList0[2],
		channelList0[3],
		channelList0[4]}

	pubsub := redisClient.Subscribe(serverList...)
	defer pubsub.Close()

	fmt.Println("****** AkGoPubSub Function Start ***** ")
	for {
		for i := 0; i < 2; i++ {
			msgi, err := pubsub.ReceiveTimeout(time.Second)
			if err != nil {
				break
			}

			switch msg := msgi.(type) {
			case *redis.Subscription:
				fmt.Println("subscribed Channel:", msg.Channel)

			case *redis.Message:
				var locData structLocationData
				fmt.Println("<received>", msg.Payload, "from->", msg.Channel)
				ProcessTheJsonIntoDataNode(&msg.Payload, &locData)

			default:
				panic("unreached")
			}
		}
	} // end for
	fmt.Println("PubSubRecv ->> Exit")
}
```
Do I need to take care of anything ? Or this strategy is fine. 

Abhi

**Comment by vmihailenco** [comment]
I recommend to use `PubSub.Channel`.

As for your code:
- What do you achieve with nested loop?
- Using ReceiveTimeout means that you will miss some messages when timeout happens

**Comment by abhit011** [comment]
Its doing some Hashmap and then persisting it in DB ... Yes I am aware of the message timeouts. 
I though did not get PubSub.Channel thing ? Any code snippets for the same 

Abhi

**Comment by abhit011** [comment]
Any further pointers ?

**Comment by abhit011** [comment]
Can i get some code samples for PubSub.Channel
