### ISSUE TITLE
How to write custom commands in pipeline?

### ISSUE THREAD

**Issue by mikefaraponov** [go-redis/redis#962]
P.S. I need to access renamed CONFIG in MULTI EXEC block

**Comment by mikefaraponov** [comment]
Do method still don't available in Pipeliner interface

**Comment by mikefaraponov** [comment]
Nice work!

**Comment by mikefaraponov** [comment]
Maybe Do should be placed to StatefulCmder, what do you think?

**Comment by vmihailenco** [comment]
`StatefulCmder` is an interface - it will not help much.
