### ISSUE TITLE
how can I specified the id parameter in xread or xreadgroup command

### ISSUE THREAD

**Issue by BloodyKnight** [go-redis/redis#966]
from the doc, i see the XReadGroupArgs struct as below:
`type XReadGroupArgs struct {
    Group    string
    Consumer string
    Streams  []string
    Count    int64
    Block    time.Duration
    NoAck    bool
}`
my question is that how can i specified the id parameter?

**Comment by vmihailenco** [comment]
XReadGroupArgs.Streams = []string{"stream1", "id1", "stream2", "id2"}

**Comment by BloodyKnight** [comment]
THANKS very much, I will try it.
