### ISSUE TITLE
Scan to struct

### ISSUE THREAD

**Issue by sharekte** [go-redis/redis#970]
Hi all
Does this package support to scan result to struct?
Thanks

**Comment by mikefaraponov** [comment]
Yes

**Comment by vmihailenco** [comment]
Dup of https://github.com/go-redis/redis/issues/672

**Comment by sharekte** [comment]
@mikefaraponov Hi Mike
Thanks for your suggestion I'll try it

**Comment by knadh** [comment]
Update: This is now supported. https://github.com/go-redis/redis/blob/f8cbf483f4a193d441fac2cf14be3d84783848c6/example_test.go#L281

**Comment by anooshcnayak** [comment]
@knadh I don't think this works for Eval/EvalSha. I have been trying to use Scan for the output of my Lua scripts.

`cmd := r.client.EvalSha(ctx, hash, []string{key}, args...)
`
EvalSha returns Cmd whose `val` is interface{} & it does not contain any Scan function

Could you let me know if I'm missing something?

**Comment by monkey92t** [comment]
> @knadh I don't think this works for Eval/EvalSha. I have been trying to use Scan for the output of my Lua scripts.
> 
> `cmd := rdb.EvalSha(ctx, hash, []string{key}, args...) `
> EvalSha returns Cmd whose `val` is interface{} & it does not contain any Scan function (cmd struct)
> 
> Could you let me know if I'm missing something?

The return value of the `EvalSha` command is unpredictable and depends on the return value of lua, so it does not provide the `Scan` function.

This may be achieved in RESP3 in the future.
