### ISSUE TITLE
Add support for RediSQL Module

### ISSUE THREAD

**Issue by siscia** [go-redis/redis#971]
Hi!

Thanks for your work on the library.

I would be interested in adding support for [RediSQL](https://redisql.com/) with references here: http://redbeardlab.tech/rediSQL/references/

I work on the developing of the module itself, and I can provide a PR myself in quite short time.

However, before to work on it, I would like to know if you will be willing to merge it into the main codebase or if you would prefer a separated library.

Thanks,

**Comment by vmihailenco** [comment]
Hi.

Separate library is preferred since it is more flexible for both of us and does not bloat main library.

**Comment by siscia** [comment]
Perfect!

Thanks!
