### ISSUE TITLE
[Sentinel] Missing manual failover command

### ISSUE THREAD

**Issue by EtienneM** [go-redis/redis#973]
Redis documentation lists the `SENTINEL` commands (https://redis.io/topics/sentinel#sentinel-commands). I would love to be able to run `SENTINEL failover <master name>` using your library. Would you agree if I make a PR which basically adds the following method?

```go
func (c *SentinelClient) Failover(name string) *StatusCmd {
	cmd := NewStatusCmd("sentinel", "failover", name)
	c.Process(cmd)
	return cmd
}
```

**Comment by vmihailenco** [comment]
Yes, sounds good
