### ISSUE TITLE
Retry error - READONLY You can't write against a read only slave.

### ISSUE THREAD

**Issue by afsalparavakkal** [go-redis/redis#977]
I got below error while executing LUA script using evalsha command. 

ERR Error running script (call to f_f67cbd63cdf1434540da47a9f06f9c7d868574c6): @user_script:8: @user_script: 8: -READONLY You can't write against a read only slave

I suspect this error can be reproducible for any write commands. 

My findings is that, driver is able to chose and send commands to right master node for the first time. But if the first transaction fails due to timeout or EOF erros, It will retry on Random node. And one of the retry goes to the Slave of the master which has the key and redis throws this error. 

Please note that, readonly option is true at my client (version : v6.15.1 https://github.com/go-redis/redis/tree/v6.15.1). 

**Redis slave node configuration is given below :** 

```
port 7004
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly yes
requirepass redis
slave-read-only yes
slave-serve-stale-data yes
masterauth redis
```

Quick fix I have done is given below. I request your help for a proper fix. 

package : redis (cluster.go)
method : defaultProcess

```
if internal.IsRetryableError(err, true) {
			// First retry the same node.
			if attempt == 0 {
				continue
			}

                       // newly added block. 
			cmdInfo := c.cmdInfo(cmd.Name())
			// if slave is readonly , redirect all i/o write commands to master
			if c.opt.ReadOnly && cmdInfo != nil && !cmdInfo.ReadOnly {
				node = nil
				continue
			}
                       // end of newly added block

			// Second try random node.
			node, err = c.nodes.Random()
			if err != nil {
				break
			}
			continue
		}
```

Thanks in advance.

**Comment by vmihailenco** [comment]
I think this is only specific to non-readonly Lua scripts executed on slaves. Other write commands are properly `MOVED` to another node.

**Comment by afsalparavakkal** [comment]
Hi ,

This fix is not going to work at least for non-readonly Lua scripts. 

Two reasons : 

1.  Newly added checking wont work for lua scripts 

```
strings.HasPrefix(err.Error(), "READONLY ")
````
Actual error thrown by redis is like (redis-4.0.11)

```
ERR Error running script (call to f_f67cbd63cdf1434540da47a9f06f9c7d868574c6): @user_script:8: @user_script: 8: -READONLY You can't write against a read only slave
```


2. Suppose MaxRedirects = 3 , and the first two transactions are timed out and it will retry on random node. If it is a Slave , Same error can be thrown. 


Again I assure that this can be happen for any non-readonly commands.

**Comment by vmihailenco** [comment]
Did you try it?

**Comment by afsalparavakkal** [comment]
Yes, I tried now and getting the same error.

Error: ERR Error running script (call to f_f67cbd63cdf1434540da47a9f06f9c7d868574c6): @user_script:8: @user_script: 8: -READONLY You can't write against a read only slave
