### ISSUE TITLE
redis cluster:WriteTimeout does not work?

### ISSUE THREAD

**Issue by TanLian** [go-redis/redis#980]
`options := redis.ClusterOptions{
		Addrs:        []string{"127.0.0.1:7000"},
		ReadTimeout:  20 * time.Second,
		WriteTimeout: 10 * time.Second,
	}
	client := redis.NewClusterClient(&options)
	time.Sleep(15 * time.Second)
	now := time.Now().Unix()
	fmt.Println(client.Set("name", "222", 0).Result())
	fmt.Println(time.Now().Unix() - now)`
when sleep 15 seconds, I execute commands **client pause 30000** in each node in the cluster, finally  
**set name 222** failed, and it costs 20 seconds, so WriteTimeout 10 seconds does not work?

**Comment by vmihailenco** [comment]
I think `client pause` does not block writes.
