### ISSUE TITLE
Gorutine Time-consuming increase

### ISSUE THREAD

**Issue by guoyucheng** [go-redis/redis#981]
hi  i do 
```
for i := 0; i < 100; i++ {
		go func() {
			start := time.Now()
			key := fmt.Sprintf("test:%s", string(i))
			redisClient := service_global.NewCache().GetRecommendCache()
			redisClient.Get(key).Result()
			end := time.Now()
			latency := end.Sub(start)
			fmt.Println(fmt.Sprintf(">>>>>times>> %v", latency))
		}()
	}
```
result：
>>>>>times>> 87.723779ms
>>>>>times>> 87.380657ms
>>>>>times>> 87.538872ms
>>>>>times>> 87.691341ms
>>>>>times>> 88.127425ms
>>>>>times>> 90.904647ms
>>>>>times>> 90.507897ms
...
>>>>>times>> 1s

so what happen？

**Comment by guoyucheng** [comment]
??? @vmihailenco

**Comment by vmihailenco** [comment]
Very likely that is a problem in your app. Anyway you need to provide a program that reproduces the problem.
