### ISSUE TITLE
Doc: Broken link https://godoc.org/github.com/go-redis/redis#Multi

### ISSUE THREAD

**Issue by sgon00** [go-redis/redis#983]
Hi, I am new to go-redis. When I read the homepage (README.md) and try to figure out how to use transactions. The link provided is https://godoc.org/github.com/go-redis/redis#Multi which is borken. There is no `#Multi` on the doc. Should I use `TxPipeline`? right? Thanks a lot.

**Comment by vmihailenco** [comment]
Yes, i've fixed the link

**Comment by sgon00** [comment]
@vmihailenco Thanks a lot for your quick fix. Since I don't find a gitter channel for this project, can I ask a question here? I am new to both redis and go-redis. For pipeline (or transaction), can I do something like the following?

```go
pipe := redisdb.Pipeline()

a, _ := pipe.Incr("pipeline_counter").Result()
aStr := strconv.FormatInt(a, 10) + "something"
b, _ := pipe.Incr("pipeline_counter"+aStr).Result()
bStr := strconv.FormatInt(b, 10) + "something"
c, _ := pipe.Incr("pipeline_counter"+bStr).Result()

_, err := pipe.Exec()
```

Because the commands are queued, I don't know if I can trust the order and the result returned and use the result in another command from the same pipeline. 
And is this the same behavior to transaction (TxPipeline) too?
Thanks a lot.

**Comment by vmihailenco** [comment]
You can't call `Result` before `Exec`, but you can save commands and call `Result` later:

```
pipe := redisdb.Pipeline()
a := pipe.Incr("pipeline_counter")
_, err := pipe.Exec()

_, _ := a.Result() // get the result after commands are executed
```

**Comment by sgon00** [comment]
@vmihailenco Thank you very much for the quick answer. OK, I got it. So I can't group/pipeline commands if any of them requires the result from a command inside the same pipeline.
