### ISSUE TITLE
strconv.Atoi errors

### ISSUE THREAD

**Issue by mingrammer** [go-redis/redis#988]
I see very often this error when I make many requests using pipeline.

```
strconv.Atoi: parsing "33\r": invalid syntax
```

How can I resolve it?

p.s. I'm using 6.15.1 version.

**Comment by mingrammer** [comment]
#704 is not helpful.

**Comment by mingrammer** [comment]
I (maybe?) resolved this issue by reducing connection pool size.

Is it related to this issue?

**Comment by vmihailenco** [comment]
Maybe. Feel free to re-open if you have a reproducer.

**Comment by ivanovaleksey** [comment]
@vmihailenco hello!
We seems to reproduce the issue.
We have been using _go-redis/redis_ for some time and lately we decided to decrease read timeouts. Suddenly these errors became to appear.

You can see it on a screenshot below
![image](https://user-images.githubusercontent.com/11523473/62942969-168b5780-bde2-11e9-85a2-aac51425adf0.png)
So, we got just `$` in `line` variable.

There were other cases, just like @mingrammer had.
We got `$14\r` i.e. `36,49,52,13` in bytes.
As I understand in normal case it should be `$14` i.e. `36,49,52,` in bytes.

**Comment by ivanovaleksey** [comment]
@vmihailenco another screenshot with the issue.
This is content of `Reader.rd.buf.`
![image](https://user-images.githubusercontent.com/11523473/62946907-3e7eb900-bdea-11e9-9767-85b4f9a72c56.png)
This time it is also with `$`

**Comment by ivanovaleksey** [comment]
@vmihailenco I was able to reproduce the error in this demo repo https://github.com/ivanovaleksey/redi.
Sometimes it fails with read timeout but sometimes it returns
>strconv.Atoi: parsing "": invalid syntax

Last time I received only read timeouts so I set `ReadTimeout=15000ms` and it return `Atoi` error immediately.
So it may be required to tune timeout on your machine.

**Comment by vmihailenco** [comment]
Thanks for the reproducer. What happens here is that because of read timeout go-redis only has a chance to read portion of the reply. And Go `ReadLine` does not mind that line does not end with `\r\n` of that there is a pending error - it returns data it has without any errors. So later `strconv.Atoi` fails to parse it.

https://github.com/go-redis/redis/pull/1129 should make it always fail with read timeout error.

**Comment by ivanovaleksey** [comment]
@vmihailenco thanks for the reply! 
Yes, that was my guess. I only expect that read timeout error wouldn't be lost. So it was confusing.
