### ISSUE TITLE
Few Queries Regarding GoRedis

### ISSUE THREAD

**Issue by srinidhis94** [go-redis/redis#992]
Hi,
    We are running redis v4.0.10 on elastic cache. Does this matter for redis-client ? Also I would like to know if MSet  has limitation on keys or size ? We are setting approximately 600 keys at once and we observed that last few keys were not set and no errors were thrown. We are using go-redis v6.14.2.

**Comment by vmihailenco** [comment]
go-redis does not limit `MSet`. I don't have any experience with Elastic Cache.
