### ISSUE TITLE
MaxConnAge doesn't seem to work along with MinIdleConns

### ISSUE THREAD

**Issue by mbenford** [go-redis/redis#995]
I was playing with some configuration fields in order to have a better grasp on how go-redis handles connections, and I noticed that if both `MaxConnAge` and `MinIdleConns` are set then all connections become stale immediately and pool misses skyrocket. 

I think the problem lies on the following piece of code within `isStaleConn` in the `ConnPool` type:

```
if p.opt.MaxConnAge > 0 && now.Sub(cn.InitedAt) >= p.opt.MaxConnAge {
    return true
}
```
I don't know whether it is an actual bug or not because I'm not sure it makes sense to use `MaxConnAge` along with `MinIdleConns`.

**Comment by vmihailenco** [comment]
It is a bug - MaxConnAge and MinIdleConns should work well together. It should be fixed by https://github.com/go-redis/redis/pull/996
